### ISSUE TITLE
Add Option to Include Line Numbers in Code Cells

### ISSUE THREAD

**Issue by michael-jarosik** [HappenApps/Quiver#10]
I find this useful for referencing line numbers when explaining what's going on in a code block.

**Comment by bradley-curran** [comment]
Should this be as a per-cell/notebook option or a Quiver global option? 

I think it should be cell based with a default in the global preferences. There's no JSON field for this information in qvnotes currently though.

**Comment by ylian** [comment]
I would vote for a global setting for simplicity. Personally I turn on line numbers in everything: XCode, Sublime Text, etc. Managing each cell separately is a lot of mental overhead.

**Comment by LeonardoGentile** [comment]
+1

**Comment by ylian** [comment]
It's already implemented in Quiver v2.1. Coming out soon.

**Comment by michael-jarosik** [comment]
That's great news. Thanks for continuing to develop and improve Quiver -- I use it almost daily and am finding it indispensable.

**Comment by ylian** [comment]
Implemented in Quiver 2.1. It's turned on by default, but you can turn it off in preferences. There are other options to toggle indent guides, invisibles, etc.
