### ISSUE TITLE
Nested notebook not synchronised using Dropbox

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#1004]
Hello @ylian, 
I've created some new notebooks on device **A**, then I dragged them over other notebooks in order to making them nested. Then in another machine **B** I cold see the change reproduced.
For a while this has worked as it should.

Now I've noticed that the nested notebook created on the machine **A** are not correctly placed on the machine **B**. In details, I can see these new notebooks but they are not nested, they are just added at the bottom of the list.

I don't usually work on both machine at the same time and even quitting/restarting the application won't fix this, so I think it might be related to [this comment](https://github.com/HappenApps/Quiver/issues/2#issuecomment-337884852) but I guess it's not exactly the same problem.

**Comment by ylian** [comment]
I see. This could happen if on the machine B, you opened Quiver before Dropbox finishes syncing. It's possible to fix this. Basically I need to watch this file and reload the sidebar on the file change.

**Comment by LeonardoGentile** [comment]
It seems the wrong nested structure somehow propagated back to the original machine...
In case this would happen again, is there any way to quick fix this before I break the structure also to the original machine?

**Comment by ylian** [comment]
Fixed in 3.2.1. Quiver now watches the library/meta.json file (which contains the nested structure) as well.
