### ISSUE TITLE
Cursor Offset in Code Cells

### ISSUE THREAD

**Issue by justnealpatel** [HappenApps/Quiver#1005]
Ever since I updated to 3.1, in code cells, my cursor has been offsetting by A LOT. A LOT meaning it's pretty much unusable. Were any changes made regarding the ACE editor? It was working fine in version 3.0
The cursor is actually between `]` and `)`
<img width="779" alt="screen shot 2017-11-18 at 6 01 02 pm" src="https://user-images.githubusercontent.com/12269792/32985884-8071d78c-cc8a-11e7-921a-013984ff76b7.png">

**Comment by justnealpatel** [comment]
What are the default styles for the ace editor? I can try to reinstate those and see if the error goes away.

**EDIT:** This is actually an issue of the theme I'm using. I'm using Atom One Dark which is posted on your Wiki for Themes. You may want to contact the author of this theme as I've created an issue on their repo as well.

**Comment by ylian** [comment]
Yes this has been a known issue for a long time. The Ace editor doesn't really support variable-width fonts. The theme you used has set a variable-width font in the code cell.

Will have to switch to CodeMirror soon.

Closing this as duplicate.
