### ISSUE TITLE
Preview CSS for indented blocks doesn't work

### ISSUE THREAD

**Issue by jose-neta** [HappenApps/Quiver#1006]
After reading this https://github.com/HappenApps/Quiver/issues/478 I realised that you managed to make indented blocks behave as code blocks. 

With me they do not, as you can see in the picture I've attached.

<img width="1432" alt="screenshot" src="https://user-images.githubusercontent.com/86932/33046682-e9d44dac-ce49-11e7-9459-cd5d11affc52.png">

I was expecting that code indents would be gaining the same CSS as indent blocks, can you please help me?

I'm using version 3.0.7

**Comment by ylian** [comment]
No, this is the intended behavior. Only fenced code blocks get the syntax highlight. So that you can choose either behavior to fit your use case.

**Comment by jose-neta** [comment]
OK, let me reframe it, I don't need syntax highlight on indented verbatim blocks, I just need to pimp their CSS a bit.

The following CSS is for Editor and when you change it, it will update fenced code blocks and intended blocks
```
/* `code` */
.markdown-cell .ace_support.ace_function {
  color: #cbcbcb;
}
```

I have no problem with editor mode, and if it is supposed to be that way, I'm fine with that. What I really need is a better style for indented block on preview mode. So given that, is there any CSS to pimp indented block only in preview mode?

**Comment by ylian** [comment]
I see. So in the first case (indented code), its preview is simply a `<pre><code>...</code></pre>` block. So style it like:

```
pre > code {
  color: red;
}
```

As for the second case (fenced code block), its preview uses Ace's static syntax highlighter. This is exactly the same preview as a code cell. So the setting is actually in Preferences > Cells > Code Cell > Theme.  If you want to customize it further, turn on the web inspector to see the html tags and style them accordingly. (https://stackoverflow.com/a/16483200)

**Comment by jose-neta** [comment]
thank you so much. That's exactly that! Problem solved. Quiver rocks!

**Comment by sahelsasani** [comment]
### ### ****
