### ISSUE TITLE
UI: Reduce height of a row in note list

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#101]
![napkin 18-04-15 5 59 27 pm](https://cloud.githubusercontent.com/assets/697301/7216142/a8047144-e5f4-11e4-9133-59da6afb64e3.png)

**Comment by ylian** [comment]
How about this? :)

![screen shot 2015-05-03 at 2 11 05 pm](https://cloud.githubusercontent.com/assets/984895/7446176/4b0f3edc-f19e-11e4-8c68-140f4ef810a6.png)

**Comment by Strajk** [comment]
:santa: xmas is early :D yes please :))

**Comment by ylian** [comment]
Implemented in 2.2b30: https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b30.zip

In Preferences, change note list style to "Condensed".

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
