### ISSUE TITLE
Which LaTeX environments does Quiver support?

### ISSUE THREAD

**Issue by omegahh** [HappenApps/Quiver#1018]
每次写Latex都不知道哪些支持，哪些不支持

**Comment by DarthCadeus** [comment]
As an English translation: What is the latex environment (What packages are installed, what aren't, etc.)

**Comment by ylian** [comment]
Quiver doesn't support any LaTeX environment. LaTeX is only used to render math equations. Under the hood, Quiver currently uses MathJax to display equations.
