### ISSUE TITLE
Can't re-open main UI window without exiting if closed after popping open a note in a separate window

### ISSUE THREAD

**Issue by michaelstratman** [HappenApps/Quiver#102]
So if you are in the main UI window you can double click a note to open it in its own window for editing. You can then close the main UI window. So at this point the only active window for Quiver is the new single note editing window you popped open. 

If you want to re-open the main window you have to completely close Quiver and re-launch. There is not way to reshow that window once its been closed and Quiver is still running.

Workaround is minimizing the main window when you open a note in a separate window but it'd be nice if I could just re-open it.

**Comment by ylian** [comment]
Already fixed in the beta builds. Try the latest build here:

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b26.zip

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.
