### ISSUE TITLE
New Libraries

### ISSUE THREAD

**Issue by matthew-hollick** [HappenApps/Quiver#1028]
Hi,

Just started using quiver and I am really liking it so far.
I am intrigued by the "Inbox" library notebook. As far as I can tell it is not dynamic or special in any way.
It occurs to me that a "Doing" and "Done" notebook between "Inbox" and "Trash" would make for a handy (if rather simple) GTD style workflow tool.

Cheers

**Comment by ylian** [comment]
"Inbox" is for notes you haven't organized yet.

You can easily achieve what you want by creating a few notebooks.
