### ISSUE TITLE
Feature Enhancement: Print/PDF export

### ISSUE THREAD

**Issue by ghost** [HappenApps/Quiver#103]
Clicking on the preview button for a note displays a nicely formatted note. However, that view doesn't translate perfectly when a user prints/exports as a PDF from the option at the bottom of the preview window pane. Since the option to style the preview pane with CSS is given to the user, can those styles also be carried through to the actual printing or creation of a PDF? I like to have my code cells/block with a dark background and colored text.

This:
![screen shot 2015-04-29 at 1 00 30 pm](https://cloud.githubusercontent.com/assets/11275324/7398989/d8d705b0-ee6f-11e4-801e-787871a9a236.png)

Not this:
![screen shot 2015-04-29 at 1 00 56 pm](https://cloud.githubusercontent.com/assets/11275324/7398990/d8e90670-ee6f-11e4-9c0f-03a53a5e44ec.png)

**Comment by ylian** [comment]
Thanks. Will fix in the next update.

**Comment by ylian** [comment]
Printing and PDF export have been significantly improved in Quiver 3.0 beta: https://github.com/HappenApps/Quiver/issues/162

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
