### ISSUE TITLE
suggested feature: ability to add new child notebooks directly

### ISSUE THREAD

**Issue by KimMichaelJones** [HappenApps/Quiver#1031]
Adding a new notebook as a child to a n existing notebook requires two steps: create at the root level, move the new notebook to be a child of the other notebook. It would be much more convenient (and intuitive/natural) if one could right click on an existing notebook and select 'Add Notebook' to create a new notebook directly as a child of that selected notebook. Related is a further annoyance that adding the new notebook at root level collapses the previously selected notebook, as a result it takes a bit if searching to find and re-open the selected notebook.

**Comment by ylian** [comment]
Fixed in 3.1.3.
