### ISSUE TITLE
Export Note As Markdown， File Link 的中文字元 變成 亂碼

### ISSUE THREAD

**Issue by jkcoco** [HappenApps/Quiver#1035]
Export Note As Markdown， 檔案連結【File Link】的中文字元 變成 亂碼：
e.g. :
---------------------------------------------
【 in Quiver Text Cell, Link to PDF files 】
[中学生编程.pdf](/Users/Shared/GoogleDrive/Coding/_RedArticles/%E4%B8%AD%E5%AD%A6%E7%94%9F%E7%BC%96%E7%A8%8B.pdf)
==> 【Export Note As Markdown】
[中学生编程.pdf] +  (/Users/Shared/GoogleDrive/Coding/_RedArticles/%E4%B8%AD%E5%AD%A6%E7%94%9F%E7%BC%96%E7%A8%8B.pdf)
----------------------------------------------------------
希望在 匯出 的 Markdown file，Link 可以保留中文字元：
e.g.：
-----------------------------------------------------------
[中学生编程.pdf] + (/Users/Shared/GoogleDrive/Coding/_RedArticles/中学生编程.pdf)
-------------------------------------------------------------
*** 為了不被轉換成 Link，加了“+“ ，請忽略。

Thanks！

**Comment by ylian** [comment]
This is the correct behaviour.

Unicode characters in a URL should be percent-escaped according to RFC. When you open the link in a browser, the browser will automatically decode the characters.

See here (https://stackoverflow.com/questions/2742852/unicode-characters-in-urls) for more details.
