### ISSUE TITLE
empty notebook

### ISSUE THREAD

**Issue by ghost** [HappenApps/Quiver#1037]
all my notebooks are empty.  when i try to restore from a BU they appear to be empty too.

 Version 3.1.2 (126)

**Comment by greenmoon55** [comment]
I had the same problem and it was scary. It was restored after restart.

**Comment by hbx233** [comment]
I had the same problem, all my notes are gone and when I try to import notes from finder, it told me my notebooks are corrupted, how can I get my notes back

**Comment by ylian** [comment]
Check the Quiver.qvlibrary file. If notes are inside the library file, just double click it to open.

If you need further help, email me with more details (library location, screenshots) at ylian@happenapps.com and I will help you from there.

**Comment by ylian** [comment]
Closing this since the issue in the original post was resolved via email (.qvnotebook was zipped and renamed somehow).

For others, feel free to send me more details via email.
