### ISSUE TITLE
Node name placeholder

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#104]
![quiver 2015-05-02 18-19-25](https://cloud.githubusercontent.com/assets/697301/7441792/dce8be8e-f0f7-11e4-9f1f-f80412f1a7eb.png)

Version 2.2b28 (39)

**Comment by ylian** [comment]
Thanks. Appreciate the bug report.

**Comment by ylian** [comment]
Fixed in 2.2b29.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b29.zip

**Comment by Strajk** [comment]
Cool, thanks!

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.
