### ISSUE TITLE
Cut acts as Copy for markdown/code cells

### ISSUE THREAD

**Issue by jaymzcd** [HappenApps/Quiver#1040]
_See #587 for the same error previously_

Not sure when this started happening but I am using 3.1.2 which I think is the latest. If i try to cut anything in a markdown or code cell it does nothing. It loads the cut into the clipboard ok but leaves the content there - as if you had done a copy instead.

![happn-cut](https://user-images.githubusercontent.com/208301/35155456-8dcccb1e-fd25-11e7-89c6-1c86286dc99a.gif)

I tried the main menu, the keyboard shortcut and the popup context menu and all do the same. 

Text cells work as normal.

**Comment by jaymzcd** [comment]
This occurred in #587 back in 2016 - I would try the build posted but it 404s. I see you asked for the Webkit version on that - in Safari (11.0.2) it reports `604.4.7`. It looks like it got resolved in the 3.0.x version that got released and has now reappeared. I see that I've got a MacOS update to apply so will do that and see if it gets fixed. I note that Safari 11.0.2 was [released on the 8th of January](https://support.apple.com/en-gb/HT201222) so perhaps that is where this was introduced.

**Comment by jaymzcd** [comment]
I've installed all system updates and restarted. Now on MacOS 10.13.2. Checking [BrowserSpy](http://browserspy.dk/webkit.php) again it give same the same version info for Safari as above - so Webkit `604.4.7`. Still getting the "cut is copy" issue in Quiver.

**Comment by ylian** [comment]
I noticed that you are using the Emacs keybinding. I don't think the standard copy/cut operations work the same way with the Emacs keybinding.

Cmd+X works fine with the default Ace binding.

**Comment by jaymzcd** [comment]
Hello! Thanks for the reply, much appreciated. I am indeed. I changed to the _Ace_ binding and can cut and paste into markdown cells. I don't remember changing that setting for a long time - is it possible that there is some sort of bug still? Or I could've just confused myself and not noticed over time (extremely likely 😂).

If I have it with emacs bindings and use the context menu or edit menu then cut won't work. If that is expected and/or intentional perhaps worth highlighting to anyone with non-Ace bindings that _cut_ via a menu or **⌘X** won't do what they "expect"? 

Thank you again for the reply and the app itself, I much prefer it over Evernote, Keep and the like ❤️  and it is awesome to see you supporting it all this time.

(Also, how could you tell I was using Emacs bindings? I can't see it anywhere in the issue/screenshot - I'm intrigued)

**Comment by ylian** [comment]
Closing this since the reported issue is resolved.

(I noticed the Emacs bindings because it uses a green cursor.)
