### ISSUE TITLE
Notebooks gone

### ISSUE THREAD

**Issue by ghost** [HappenApps/Quiver#1052]
Not sure what happened but all my notebooks are gone.

app- 3.1.2(126)
OSX 10.13.2

 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Boot ROM Version:	MBP133.0233.B00
  SMC Version (system):	2.38f7
  Serial Number (system):	C02TD1X1GTF1
  Hardware UUID:	43DD3077-7F7E-500E-BF71-24B569C7401C

**Comment by ylian** [comment]
Could you send me more details (how it happened, screenshots for Quiver and its library file)? That will help me figure out what happened. My email is ylian@happenapps.com. Will assist you from there. Thanks.

**Comment by ghost** [comment]
Odd,

The Library claims it has not been modified since November and says it is only 2.7 Meg.

Did the DB reset on me?

Brad Hutchins

**Comment by ylian** [comment]
I can open your library and saw these notes:



Is that about right or should there be more notes?

From your screenshot, it actually looked like the app threw an exception during the app launch (basically it crashed). I just need to know one thing to confirm that: are you using a default theme or a custom theme? You can check in View Menu > Theme.

Also, if you could open Console.app and filter by “Quiver”, you might see the thrown exception. Please take a screenshot of that and send to me as well.

Thanks.

Yaogang

**Comment by ylian** [comment]
I think I found the issue. The app actually crashed during the launch. Will send you a build with the fix tonight.

**Comment by ghost** [comment]
Thank You
Will Make Backups this time.




Brad Hutchins

**Comment by ylian** [comment]
Fixed in 3.1.3.
