### ISSUE TITLE
BUG: Find > Search notes... should be accessible via keyboard shortcut even when writing

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#106]
When I'm writing and wanna search different note, I have to first press esc to quit editing mode and only then I can search.

**Comment by ylian** [comment]
Fixed in 2.2b35:

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b35.zip

**Comment by Strajk** [comment]
Thanks!

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.
