### ISSUE TITLE
Search Notes ⌥ ⌘ F fails to find a note containing the string

### ISSUE THREAD

**Issue by alanfluff** [HappenApps/Quiver#1065]
A note has a `Text cell` with copy such as the following (in the note it's not between code markers):

```
project_log

579cc blagh

578cc blagh blagh

577cc blagh blagh blagh
576cc blagh
575cc blagh blagh
```

yet using `Search Notes` (`⌥ ⌘ F`) to look for `575` or `575cc` fails to find this note that contains this string.

Quiver.app: Version 3.1.2 (126).

**Comment by salmanchan** [comment]
[#121](https://github.com/HappenApps/Quiver/issues/121)
It's a bug that hasn't been fixed yet.

**Comment by alanfluff** [comment]
:'/
