### ISSUE TITLE
Weird behaviour with emoji

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#107]
![quiver 2015-05-07 13-54-16](https://cloud.githubusercontent.com/assets/697301/7514751/a325960a-f4c0-11e4-80fc-458bbfdc320a.png)

**Comment by ylian** [comment]
Ace has issues with unicode and variable character width.

https://github.com/ajaxorg/ace/issues/460

Mark as "Won't Fix" for now, but will update if situations change.

**Comment by Strajk** [comment]
OK, thanks for response :)
