### ISSUE TITLE
can we create a sub notebook easily ?

### ISSUE THREAD

**Issue by MatthewLee123** [HappenApps/Quiver#1075]
Hi, can we create a sub notebook easily ? I mean, just right click a notebook, select create sub-notebook or notebook under current one ? 

right now, I have to right click "notebooks", select new notebook, it was created to the end of the bottom of the whole notebook list ! and I have to drag it into the destination notebook, which, the worst part,  is in deep sub level as well.! it's terrible....

**Comment by ylian** [comment]
Fixed in 3.1.3.
