### ISSUE TITLE
shortcut for "Copy note -> As code only"

### ISSUE THREAD

**Issue by MartinP7r** [HappenApps/Quiver#1079]
I didn't find any option in preferences or documentation on it, but is there a way to assign a shortcut for distinct copy operations on notes?  
for my workflow I'd really like to be able to copy the code content of a note via shortcut.

**Comment by ylian** [comment]
Unfortunately no way to do that at the moment.

**Comment by MartinP7r** [comment]
😢 any chance this gets picked up in an update?  
I'd really like to move to Quiver, but am quite used to my current lookup&copy/paste workflow via keyboard shortcuts.

**Comment by ylian** [comment]
Sure. I will add the "Copy as" options to the main menu. They have been hard to discover as well. Then you could bind your keyboard shortcuts with the menu items as you like.

**Comment by ylian** [comment]
Fixed in 3.1.3. "Copy as" options are now inside the main menu so you can bind keyboard shortcuts to them (https://support.apple.com/kb/PH25377?locale=en_US).
