### ISSUE TITLE
Cursor is not horizontally aligned with typed text!

### ISSUE THREAD

**Issue by msollami** [HappenApps/Quiver#108]
![screen shot 2015-05-08 at 11 19 36 am](https://cloud.githubusercontent.com/assets/1467556/7539313/25cef9da-f574-11e4-937f-32e84fd52095.png)

**Comment by ylian** [comment]
Ace doesn't support variable width fonts. Please use a equal width font such as Menlo.

**Comment by ylian** [comment]
Mark as "Won't Fix" for now, but will update if situations change.

https://github.com/ajaxorg/ace/issues/460
