### ISSUE TITLE
Option to suppress auto capitalization of 1st character after a CR

### ISSUE THREAD

**Issue by alanfluff** [HappenApps/Quiver#1082]
I want to be able to stop Quiver auto capitalizing the first character after a carriage return.

Please can you advise if this is an option I missed in the docs or if not how I may be able to edit Quiver to not do this or can this be added into a new release?

**Comment by ylian** [comment]
This is controlled by the system.

![image](https://user-images.githubusercontent.com/984895/38132795-e85b5302-340c-11e8-942a-9de6c25194e6.png)

**Comment by alanfluff** [comment]
Thanks @ylian and sorry no googling pointed me to this and I didn't know it. Cheers.
