### ISSUE TITLE
What is the inbox for? why can not I clean it ?

### ISSUE THREAD

**Issue by FCh99** [HappenApps/Quiver#1084]

**Comment by justnealpatel** [comment]
I believe the inbox is for notes that don't belong in any previously created notebook, also it could be a temporary note. You can clean it by either deleting notes or moving notes to an actual notebook.

**Comment by AnilRh** [comment]
I've got a similar question. I'm often using Quiver when I want to create a new, unrelated note. There should be a command that always creates a new Inbox note. I'd argue that ⌘N should do this. If I want to create a new note while in a notebook I'd be happy to use a different shortcut for that. 

If a note accidentally gets placed in the Inbox it's not a big deal. I think most people that care about organization will file their inbox. If however a note accidentally gets placed in another notebook, there's a good chance you'll never find it in a timely manner.
