### ISSUE TITLE
Accidentally deleted notes.

### ISSUE THREAD

**Issue by ghost** [HappenApps/Quiver#1099]
Any way to recover a deleted note?
 
I made a subnotebook like it said in the release notes for 3.1.3.
I then grabbed and dragged the note to the subnotebook.
I made sure the note was transferred.
I then deleted the original note in the root of the overall notebook, and it deleted the copy I had in the subnotebook.
Undo is not selectable for this.

Brad

**Comment by ylian** [comment]
It should still be in the Trash (look in the sidebar) if you haven't emptied the trash.

**Comment by ghost** [comment]
Thanks, forgot about that.

**Comment by mweibel** [comment]
@ylian it would be nice to have Undo working for deleting a note, too. I thought now the note is gone because I didn't realize there's a trash and I thought Undo would also Undo a delete action. Should I open a new feature request (issue) for that?
