### ISSUE TITLE
HTML format for inline code

### ISSUE THREAD

**Issue by shyamgupta** [HappenApps/Quiver#1101]
Just like code cells, can we apply themes to inline code and show them in the exported HTML?

**Comment by ylian** [comment]
Inline code can be styled with `code {color: blue}`, though if you want syntax highlighting, use a code cell or a fenced code block in Markdown.

**Comment by shyamgupta** [comment]
1) What is the CSS class of the inline code I should apply this to?
2) Should I change this in Editor CSS or in Exported HTML CSS?

**Comment by shyamgupta** [comment]
Nevermind, I was able to figure it out. Thank you!
