### ISSUE TITLE
Allow Open and Open with...  on images

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#111]
I often need to open the images in Preview or similar app to crop, annotate, adjust... this feature would help me sooo much.

What about context menus on images with Open and Open with (same as in Finder) and opening the image in default editor on double-clicking?

**Comment by ylian** [comment]
Good idea. Seems doable.

**Comment by Strajk** [comment]
You are my hero!

**Comment by Strajk** [comment]
Pretty please, this would help me so much :)

**Comment by ylian** [comment]
Have to wait a bit. I have changed the app UI significantly. Need a stable version first. See #59.

**Comment by ylian** [comment]
@Strajk  You might like this:

![image](https://cloud.githubusercontent.com/assets/984895/8019526/2d3c46be-0c21-11e5-9831-2f319ba4a03e.png)

**Comment by Strajk** [comment]
Yes, I like puppies!! :)) Can you share beta? :)

**Comment by ylian** [comment]
The beta is not quite ready, but here it is: https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b36.zip

PLEASE backup your Quiver library before trying this beta, just in case. Find your .qvlibrary file and simply make a copy.

A few things are still work in progress: tag editor, notebook picker popover, search popover. Probably some serious bugs too.

**Comment by ylian** [comment]
Added the menu items to preview as well. This will come out in the next update.

**Comment by asafge** [comment]
I tried this and it looks good! One issue is that after the file is edited and saved, changes are not shown in Quiver until after a restart to the application.

**Comment by ylian** [comment]
yes I noticed that. Evernote solves this issue by watching for the file change and reload the note on change, as well as sending out a notification to the user.

I will see if I can do something similar.

**Comment by asafge** [comment]
Sounds good.
Also I can no longer add tags to a note, not sure if you've seen it already or not.

**Comment by ylian** [comment]
Yeah I know that. That's what I meant the beta is not quite ready.

**Comment by ylian** [comment]
Implemented in Quiver 3.0, released today. The image reload bug is files as a new ticket #240.
