### ISSUE TITLE
What is the point of "shared notebook" if I need to "reload from disk" for every change?

### ISSUE THREAD

**Issue by notbrain** [HappenApps/Quiver#1115]
Every time I save new content to a shared notebook, then look at it on another computer with the same shared notbook open, the "contents have changed on disk" dialog pops up. This is confusing and can lead to mistakes if you choose the wrong option when this happens. I just chose "reload from disk" and content disappeared from the note that should have remained.

Why is there a distinct option for "shared notebook" if this is still happening? I would hope that the "sharedness" would be assumed and to allow the file to change (in this case on Dropbox) and just always trust the version that is read from the synced dropbox version.

**Comment by MajorGrinch** [comment]
Dude, you are lucky since I couldn't even see this dialog and have the chance to select. I shared a notebook with my friend via icloud where every change I made to the notebook is passed by icloud but my friend could only see the update after restarting the app itself.

**Comment by ylian** [comment]
Fixed in 3.2.1. The dreadful "contents have changed on disk" dialog is history. Quiver now automatically reloads the opened notes to the latest version.
