### ISSUE TITLE
Stacking notebooks together?

### ISSUE THREAD

**Issue by simkimsia** [HappenApps/Quiver#1117]
Paid for this app a couple of days ago, so I'm a happy customer.

Love it that it's really meant for developers. 

I was wondering if there's anyway to group the notebooks together like stacking them in Evernote.

I read #2 so I am not asking for nested notebooks and appreciate the deliberate choice of keeping things simple.

In any case, thank you for developing this app. Much ❤️

**Comment by ylian** [comment]
Nested notebooks have been implemented since v3.1. In the sidebar right click on a notebook and then "New Notebook...", or drag & drop.

![image](https://user-images.githubusercontent.com/984895/39661852-3f0d6434-5059-11e8-81e6-685e81d411a5.png)

**Comment by simkimsia** [comment]
Thanks! Didn't realise this
