### ISSUE TITLE
Active (opened) note is not highlighted in note list

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#112]
I'm using condensed view

**Comment by ylian** [comment]
Details how to reproduce?

**Comment by Strajk** [comment]
Sorry, attaching

![quiver 2015-05-12 14-52-06](https://cloud.githubusercontent.com/assets/697301/7587449/8fea3a2e-f8b6-11e4-94ad-495676e8f717.png)

**Comment by ylian** [comment]
Oh, I see. Will fix.

**Comment by ylian** [comment]
Hmm, I tried search and still not reproducing the issue. Please let me know the particular sequence of actions. Thanks.

**Comment by ylian** [comment]
My bad. I see it happening now. The selection highlight is quite light so I thought it was working.

**Comment by ylian** [comment]
Fixed in Quiver 3.0 beta: https://github.com/HappenApps/Quiver/issues/162

**Comment by ylian** [comment]
Fixed in Quiver 3.0.
