### ISSUE TITLE
export content do not have the style I have changed by setting theme config 

### ISSUE THREAD

**Issue by xieyonn** [HappenApps/Quiver#1122]
I use code theme `github`
this is default preview
![image](https://user-images.githubusercontent.com/7881849/39965507-d06392e0-56cc-11e8-9f9d-e71ec69048eb.png)
I add some css for inline code and code block
my setting
```
"css": {
    "className": "github",
    "editor": ".github .ace-github { background-color: #f6f8fa; padding: 16px; } .github code { padding: 0.2em 0.4em; }",
    "preview": ".github .ace-github { background-color: #f6f8fa; padding: 16px; } .github code { padding: 0.2em 0.4em; }",
    "presentation": ".github .ace-github { background-color: #f6f8fa; padding: 16px; } .github code { padding: 0.2em 0.4em; }"
  }
```
after change
![image](https://user-images.githubusercontent.com/7881849/39965462-8b7555b6-56cb-11e8-8013-6969cdf2efc1.png)

when export as html or pdf
It do not change 
![image](https://user-images.githubusercontent.com/7881849/39965515-ffb3e662-56cc-11e8-9efb-aedcd1d58bbd.png)

**Comment by ylian** [comment]
Indeed you can't set export styles in the theme file at the moment. Although if you just want this for your own use, you could add the css changes to "Preferences > Styles > Export, PDF".

**Comment by xieyonn** [comment]
I did what you said, It works, thanks!
