### ISSUE TITLE
can I open multip Quiver.qvlibrary file simultaneously ?

### ISSUE THREAD

**Issue by MatthewLee123** [HappenApps/Quiver#1149]
hi, can I create multiple .qvlibrary database and open them at the same time? 
for example, I create a private .qvlibrary database and store it in my personal computer for personal use. and I create a public .qvlibarary file in cloud because I need to use it while I am in office.  but when I get home, I have to change the settings to my private database. how can you open them at the same time and just put them in different view/folder ? it must be convenient

**Comment by ylian** [comment]
I am actually redesigning the model layer (persistence, caching, indexing) from the ground up, and the new design will support opening multiple libraries. I am trying to push out this update within a few days.

**Comment by MatthewLee123** [comment]
Hi, Lian

Thanks for reply, happy to hear that.

**Comment by ylian** [comment]
@MatthewLee123 Just a quick update. The 3.2 model redesign/rewrite is still ongoing. I managed to replace all the model classes with the new design, most app functions are working again, but still many issues to fix. I am still focusing on this update and will get it done as soon as I can.

**Comment by MatthewLee123** [comment]
Thanks Ylian.
happy to hear that.
Cheers

**Comment by MatthewLee123** [comment]
Hi Ylian

May I know if any updates on running multiple libraries request? as it's been one month.

thanks.

**Comment by ylian** [comment]
Yes, I am still working on it. The model layer rewrite is much harder than I estimated --- it broke many things. But this rewrite is necessary for finally fixing many data model and syncing bugs. I am very close to the 3.2 release.

**Comment by MatthewLee123** [comment]
Got it. 
Thank you, Ylian, for your quick response.

**Comment by keeprock** [comment]
Thank you for your work and responses, Ylian. Keep up with a good work.

**Comment by ylian** [comment]
Quiver 3.2 is released. Now you can open multiple Quiver libraries at the same time. :)
