### ISSUE TITLE
backup issue

### ISSUE THREAD

**Issue by nicodev3** [HappenApps/Quiver#115]
I tried to make a backup of my library to Dropbox, but as i did this, all my librairy disapeared... Tried to restore the file but all seems desesperatly empty... What a mess ! Has tons of documentation...

**Comment by ylian** [comment]
Sorry to hear that, but I will try to help you recover the notes.

Can you check the file size of "~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/Quiver.qvlibrary"? Maybe notes are still in there.

Also please check the file size of other qvlibrary files you might have.

Please send followups to support@happenapps.com, and I will assist you from there.

**Comment by ylian** [comment]
Could you email yaogang.lian@gmail.com instead? Thanks.

**Comment by r4in** [comment]
Similar issue I had. I had just exported a Notebook into a Shared Notebook. (I wanted to push it to github) Suddenly, all notes are intact but empty. Tried checking out the individual .qvnote files, the "cells" on the json files are empty :/
