### ISSUE TITLE
Nested sub notebook support for shared notebooks

### ISSUE THREAD

**Issue by leventeszmolka** [HappenApps/Quiver#1150]
Hi,

Could you add support for sub notebooks in shared notebooks, please?

Many thanks

**Comment by ylian** [comment]
Shared notebooks are now superseded by a shared Quiver library. Quiver 3.2 brings multi-library support, meaning that you can have multiple Quiver libraries open at the same time. A shared Quiver library supports nested notebooks, and is the recommended way for collaboration going forward.
