### ISSUE TITLE
[Bug] Quiver hangs with pinwheel and must force quit

### ISSUE THREAD

**Issue by lrowang** [HappenApps/Quiver#1159]
In the last 24 hours Quiver keeps hanging and I'm unable to navigate and read/write my library of notes. The pinwheel just keeps spinning and I have to Force Quit the application. I use Quiver extensively for all my client dev notes and would greatly appreciate any help resolving this problem!

Running OSX 10.12.6

Thank you.

**Comment by ylian** [comment]
Possibly one of your notes is causing the problem. Try to reset the last opened note id by running this in the terminal:

```sh
defaults delete com.happenapps.Quiver lastOpenedNoteId
```

**Comment by lrowang** [comment]
I ran the above command and still had to Force Quit, but now after starting Quiver again it's working and no longer hanging. Thank you for the help and appreciate your response!
