### ISSUE TITLE
When I add a resource (image) to Quiver note, then delete it, it stays on disk.

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#116]
It's not critical issue, but Quiver library can grow a lot in size

**Comment by ylian** [comment]
It's actually deleted later on. (When you reopen Quiver and click on that note, it does a cleanup.) But this should be made much simpler.

The reason it isn't simply deleted is the following case: cut some text and images from one note, copy to another. Images are not copied to the clipboard, but copied later. Again, not a good reason for the complexity.

**Comment by ylian** [comment]
This is fixed in Quiver 3.0. Resource management has been completely revamped. With Quiver 3.0, if you delete an image from a note, the image file on disk is deleted right away.
