### ISSUE TITLE
Suggestion: Allow setting image size

### ISSUE THREAD

**Issue by asafge** [HappenApps/Quiver#117]
It would be great if embedded images would have resize options (instead of taking 100% width of the screen). Another great feature would be some basic cropping capabilities.

**Comment by Strajk** [comment]
I would prefer to enable using external image editing tools, which are already great at this - Monosnap, OS X Preview or even Photoshop or Sketch - instead of bloating Quiver, cause this is the reason I hate Evernote :)) Keep it simple!

**Comment by ylian** [comment]
Here are my thoughts:
1. If you want to edit an image, I think it's better to do it in an external editor. Quiver just needs to make it easy to open the image in an external editor, as in #111.
2. If you just want to resize an image in a Markdown cell for display purpose, I think I can enable a Markdown syntax such as 
`![image](quiver-image-url/UUID?s200)`. Mou does something like that, I believe.
3. If it's an image in a text cell and you just want to resize it for display purpose, I haven't figured out a good way to do that. Evernote made each image into a special UI control, which is too complicated in my opinion.

**Comment by unisu** [comment]
> 1. If you just want to resize an image in a Markdown cell for display purpose, I think I can enable a Markdown syntax such as 
>    `![image](quiver-image-url/UUID?s200)`. Mou does something like that, I believe.

Could you share me updated version applied this? I need to resize images in Markdown.

**Comment by ylian** [comment]
Not yet implemented. This should be open.

**Comment by scott-mead** [comment]
It'd be helpful to have a resize option.

**Comment by williamdotyang** [comment]
Definitely want the photo size adjustable, especially in the text box.

**Comment by felixs8696** [comment]
While this is being reviewed you can use html syntax in Markdown: 
`<img src="[quiver-image-...].png" style="width: 300px;"/>`

If you absolutely need the image in a text cell, you can use this workaround even if it can be a pain:
1. Create a new markdown cell (if you do this all in an existing text cell, it can screw with your formatting)
2. Add the desired image
3. Edit the width using the html code above
3. Change the cell into a Text cell
4. Copy and paste the correctly sized image wherever you want it

**Comment by lcrostarosa** [comment]
yes please!!!!

**Comment by shallker** [comment]
Definitely need an image resize in a Markdown cell. Yes please! @ylian

**Comment by junhocho** [comment]
Plz! Can we resize image like deckset app?
`![50%](./image.png)`

**Comment by YanchunHe** [comment]
or resize image using ![alt text](path/image.png =widthxheight).

**Comment by clintharris** [comment]
+1 for the ability to resize embedded images--changing the display size, not actually editing the image--using the GUI (vs. Markdown).

**Comment by KimMichaelJones** [comment]
+1 for this, would be a big time saver

**Comment by 1ce0ear** [comment]
+1 for this, please

**Comment by ylian** [comment]
Image resizing with ![alt text](path/image.png =widthxheight) is coming in 3.0.6. I will push it out tomorrow.

**Comment by ylian** [comment]
A new Markdown syntax is introduced in 3.0.6 for image resizing:

```
![alt text](path/image.png =widthxheight)
```

Width or height can be omitted:
```
![title](image.png =200x)
![title](image.png =x100)
```

**Comment by tflo** [comment]
Thank you very much for all the recent fixes, changes and additions. I’m really glad to see that Quiver is “alive” again!

– Tom

**Comment by ylian** [comment]
@tflo Sure thing. Many more updates are coming. And the iOS beta will see updates shortly as well.
