### ISSUE TITLE
The ability for "shared notebooks" to be nested

### ISSUE THREAD

**Issue by nbrandaleone** [HappenApps/Quiver#1172]
While it is currently possible for local notebooks to be nested (or have sub-folders), this functionality does not seem to work for shared notebooks.  It would be great if this functionality can be extended to shared notebooks.

I use shares notebooks, since I have multiple computers (work, home, laptop), and I need a method to keep them in sync.  I also have many notebooks, so having a way to nest them is also critical to my workflow.

**Comment by ylian** [comment]
"Shared notebooks" are now superseded by a shared Quiver library. Quiver 3.2 brings multi-library support so you can open multiple Quiver libraries at once. A shared Quiver library supports nested notebooks, and is the recommended way for collaboration going forward.
