### ISSUE TITLE
macOS 10.14 dark-mode support?

### ISSUE THREAD

**Issue by tillt** [HappenApps/Quiver#1175]
Can we please have dark-mode support?

**Comment by justnealpatel** [comment]
This can be easily met through themes. Not sure if this is explicitly necessary.

**Comment by koskokos2** [comment]
In the same time it is a common practice to switch dark mode on automatically when OS settings were changed, of course not all apps doing it but it looks like a common sense. It is like you have at least 2 themes and use different one as default basing on OS settings.

**Comment by jdmssmkr** [comment]
> This can be easily met through themes. Not sure if this is explicitly necessary.

Is it possible to theme the window header and scrollbars?

**Comment by justnealpatel** [comment]
Oh, I thought you were referring to general elements on the theme itself. The window header and scrollbars would require a change from the app I believe.

**Comment by baumannn** [comment]
@tillt You can set it yourself for now running `defaults write com.happenapps.Quiver NSRequiresAquaSystemAppearance 0` in your terminal, but unselected icons in the ui element to switch between views disappear when you do this.

![image](https://user-images.githubusercontent.com/5580542/47806404-54aa0580-dcff-11e8-814c-6e18668552c0.png) 
vs 
![image](https://user-images.githubusercontent.com/5580542/47806437-64c1e500-dcff-11e8-8e28-27ff52c556e0.png)

**Comment by tillt** [comment]
@baumannn neat but obviously not a solution.

**Comment by ylian** [comment]
Fixed in 3.2. The title bar and scrollbar are now behaving correctly in the dark mode.

<img width="1552" alt="screen shot 2018-11-25 at 11 16 44 pm" src="https://user-images.githubusercontent.com/984895/48985649-f871b000-f109-11e8-821a-43d1641d9e40.png">

**Comment by mshibanami** [comment]
@ylian 
Thank you for adding the cool feature. Does it also include the feature of changing themes automatically by OS settings? If no, is there any chance that Quiver would support it?
