### ISSUE TITLE
Any Updates???

### ISSUE THREAD

**Issue by rockyzhang24** [HappenApps/Quiver#1179]

**Comment by ylian** [comment]
Doing some final testing for 3.2. This is a major update since the last two years.

**Comment by rockyzhang24** [comment]
@ylian 
1. Will it support TOC or outlines? 
2. Any other new features added?
3. Can I get the expected release date?

Thanks.

**Comment by ylian** [comment]
No TOC. This new version focuses on model layer rewrite, which fixes most bugs related to data models, syncing and searching indexing. The main new user-facing feature is multi-library support (good for personal/work separation, and team collaboration). Expect a release within a week.

**Comment by rockyzhang24** [comment]
@ylian Thank you for your reply. So there are no new features added so far but refine and polish this product, right? After 3.2, do you have a roadmap for the future of this application? Could you please say something about your TODOs? Really appreciate it.

**Comment by ylian** [comment]
After 3.2, here are the tentative plans:
* Quiver for iOS 1.1: add more syncing options
* Quiver for macOS 3.3: focus on UI improvements such as TOC, search UI, etc.
* Markdown editor improvements, Markdown preview improvements...
* Swap out underlying code editor

I am working on Quiver full-time now and picking up speed. I aim to finish the above list in the next two months.

**Comment by rockyzhang24** [comment]
@ylian Really Cool!!!!! I believe everyone will be excited about this roadmap. 

For Quiver iOS version, do you have a plan to add edit mode? Because the notes in Quiver are stored in JSON type, not plain .md file, so I cannot edit my notes on my iPhone or iPad using other markdown applications. Thanks.

**Comment by ylian** [comment]
Yes, I will add editing mode to iOS, right after finishing the list above.

**Comment by kevanchristmas** [comment]
Not trying to join the dogpile but can I please add another vote for some (even very basic) search on iOS on that map?

**Comment by rockyzhang24** [comment]
Okay. Many thanks and we are looking forward to the upcoming release.

You said you are now developing Quiver full-time. So you have totally settled down, right? You will make Quiver alive and won't quit suddenly like your status of the last two years, right?

I think probably you can change the iOS app from free to pay, or even you can make 3.2 "pay to upgrade" so that you can get some motivations or compensation for your hard-working. I believe most Quiver Enthusiasts are happy to support you.

**Comment by kevanchristmas** [comment]
> Okay. Many thanks and we are looking forward to the upcoming release.
> 
> You said you are now developing Quiver full-time. So you have totally settled down, right? You will make Quiver alive and won't quit suddenly like your status of the last two years, right?
> 
> I think probably you can change the iOS app from free to pay, or even you can make 3.2 "pay to update" so that you can get some motivations or compensation for your hard-working.

^^^^^ This 👍 (more than happy to pay for both)

**Comment by koskokos2** [comment]
> Okay. Many thanks and we are looking forward to the upcoming release.
> 
> You said you are now developing Quiver full-time. So you have totally settled down, right? You will make Quiver alive and won't quit suddenly like your status of the last two years, right?
> 
> I think probably you can change the iOS app from free to pay, or even you can make 3.2 "pay to upgrade" so that you can get some motivations or compensation for your hard-working. I believe most Quiver Enthusiasts are happy to support you.

I feel the same. Payed iOS (with more sync options and maybe edit) makes perfect sense. We need stable and motivated dev for this really good app (even if it needs some fixes and couple of improvements at the moment).

**Comment by rockyzhang24** [comment]
@kevanchristmas Yep bro. As long as @ylian could keep polishing and developing this application until it gets great enough, we can pay for both. He is now developing it full-time so I think he needs the payment to support his work.

 @ylian How do you think?

**Comment by kevanchristmas** [comment]
![shutupandtakemymoney](https://user-images.githubusercontent.com/5012041/46794001-33c94280-cd47-11e8-9d27-a22685304a1b.jpg)

**Comment by rockyzhang24** [comment]
I think this post should be reopened so that more friends will see it and leave their advice. :)

**Comment by ylian** [comment]
Yes, iOS version will add in-app purchases for advanced features. I will make sure Quiver development is sustainable.

At the moment I just need to catch up with all the lost development time in the past two years. Bear with me for a bit longer and wait for updates. :)

**Comment by rockyzhang24** [comment]
How is the new release going?

**Comment by ylian** [comment]
Still fixing issues uncovered during testing.

**Comment by rockyzhang24** [comment]
@ylian Cool.  Probably you can release the beta version frequently and I am glad to be a tester. I believe that other users also want to help you out. :)

**Comment by idx3d** [comment]
Hello @ylian. You are working on the app, that's great news for every user. I was looking for an alternative app to Quiver because I need to have consistent workflow being at home, office or on the road. I have a Windows PC, Mac OS Laptop and iOS Device. 

Is it any possibility to open and edit Quiver notes on Windows PC? I'm not asking for app (although it would be wonderful), but maybe you have some library that can parse your database files and provide contents as output? So I can try to build my own UI, for example, using Electron or something like this. 

If you are considering to write app for Windows, I will be the consumer for sure and ready to invest to buy it.

**Comment by ylian** [comment]
@idx3 Quiver uses an open plain-text format, so actually anyone can build a Windows app. https://github.com/HappenApps/Quiver/wiki/Quiver-Data-Format

I do plan to build a Windows version by myself at some point, but I need to get the macOS and iOS versions in better shape first.

**Comment by WLyKan** [comment]
Call for outline function. Even github wiki has an outline.
