### ISSUE TITLE
'Recent Notes' list automatically expands

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#118]
Hello,

ISSUE:
The 'Recent Notes' list will automatically expand once I create a new note or empty the trash.

STEPS:
1. Make sure you have a few 'Recent Notes' listed on the sidebar, then click on 'Hide' next to it, to hide the recent notes list.
2. Click the plus (+) sign at the top of the notes panel to create a new note. Notice the 'Recent Notes' list in the sidebar gets automatically shown, even though I just specified to hide it.
3. So close the 'Recent Notes' list again by clicking on 'Hide'.
4. Select a note and delete it. It will be placed in the trash.
5. Empty the trash.
6. Note that the 'Recent Notes' list will be automatically shown again.

CONCLUSION:
Although this could be personal, I think the 'Recent Notes' list should not be automatically shown just because I create a new note or empty the trash. You can notice similar behavior in OS X in the Finder window where you can list attached devices and tags. When you hide these lists, they won't automatically open just because I create/delete a new tag or attach/remove a device.

Thanks.

OS X 10.9.5 Mavericks
Quiver 2.1.3b17 (28)

**Comment by ylian** [comment]
The sidebar is being redesigned for the next update. See #59 for screenshots. I will make sure the state of each group is properly maintained.

**Comment by ylian** [comment]
This is no longer applicable in Quiver 3.0, since the sidebar has been redesigned.
