### ISSUE TITLE
Markdown and LaTeX Formatting Bug

### ISSUE THREAD

**Issue by justnealpatel** [HappenApps/Quiver#1187]
<img width="486" alt="screen shot 2018-10-23 at 3 55 44 am" src="https://user-images.githubusercontent.com/12269792/47348692-a7d4e600-d677-11e8-8f8b-d01ed224ebaf.png">

As you can see, these two lines are the same. The first one is in a Markdown cell while the second one is in a LaTeX cell. Now lets look at the output.

<img width="344" alt="screen shot 2018-10-23 at 3 55 54 am" src="https://user-images.githubusercontent.com/12269792/47348759-c5a24b00-d677-11e8-86c0-f0a3d8076524.png">

Everything after the `$` gets the formatting bug and becomes peculiarly small and I'm pretty sure it's not supposed to do that.

**Comment by ylian** [comment]
The two lines in the output screenshot look the same to me. Am I missing something here?

**Comment by justnealpatel** [comment]
That's the thing. They're both creating the same error. Don't the question mark and `"` look a bit smaller than usual in both lines?

**Comment by justnealpatel** [comment]
I could be totally wrong and it might be the right size.

**Comment by justnealpatel** [comment]
My apologies. I think just because it's right next to the LaTeX rendered element, it gives the illusion of looking a big smaller, at least from my perspective.

**Comment by ylian** [comment]
No worries. I think it's an illusion. Closing this.

![image](https://user-images.githubusercontent.com/984895/47386755-c2599e80-d70d-11e8-997a-43fd70ac6a63.png)
