### ISSUE TITLE
Deleting multiple selected notes

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#119]
Hello,

ISSUE:
Noticed a few minor issues when deleting notes. When you select multiple notes to delete, only one of them will get deleted when you use the 'Delete Note' command from the context menu.

Similarly, when you have multiple notes in the trash and you select all, and you try to delete them using the 'Delete Note' context menu, none will be deleted from the trash.

STEPS:
1. Create a few notes. They can be just blank ones for this test.
2. Use a lasso selection to select all notes. (E.g. click on the empty area at the bottom of the notes list and drag upwards to select all notes.) They will be hilited in light gray.
3. Right click somewhere on the selected notes. Notice at this point that all selected notes will be outlined as a group, indicating that all notes are selected, hence giving the impression that the command you are going to select from the context menu will apply to all selected notes.
4. Select 'Delete Note' from the context menu.
5. Only the note that you happened to right click on will be deleted, even though other notes are also hilited.
6. So go ahead and delete all notes so they will be in the trash.
7. Click on the trash and select all (or a few notes).
8. Right click on the selected notes in the trash and select 'Delete Note' from the context menu. Notice that no notes will be deleted.

CONCLUSION:
I am aware that there's a menu item 'Delete Notes' under the 'Note' menu in the menubar. However, when you have multiple notes selected and you select 'Delete Note' all selected notes should be deleted.

Similarly, when the notes are in the Trash and I select a few, and delete them via the 'Delete Note' context menu, they should be deleted from the trash.

Thanks.

OS X 10.9.5 Mavericks
Quiver 2.1.3b17 (28)

**Comment by ylian** [comment]
Multi-note operations will be significantly improved in the next update. Working on it.

**Comment by ylian** [comment]
Multi-note actions are significantly improved in Quiver 3.0 beta: https://github.com/HappenApps/Quiver/issues/162

**Comment by ylian** [comment]
Multi-note actions are implemented in Quiver 3.0.

![screen shot 2015-11-17 at 8 50 03 am](https://cloud.githubusercontent.com/assets/984895/11213098/38f5d462-8d08-11e5-9b4f-4e9c10db95a0.png)
