### ISSUE TITLE
Integration with Boostnote

### ISSUE THREAD

**Issue by PatrickF1** [HappenApps/Quiver#1190]
Has anyone tried to migrate their Quiver library to Boostnote? I tried migrating by exporting my Quiver notes to Markdown and then importing them but I ran into 3 huge problems
1. Small Markdown export bugs. I can fix them by hand but multiplied by 1000s of notes, I realized it would be near impossible.
2. No tags exported. I have tagged most of my notes and it'd be difficult to retag everything exactly
3. No images or attachments. Not a big deal but I do have about 100 notes with images or PDF

Has anyone happened to have written a script on this?

Ylian, if you're reading this, I'm sorry if the premises of this question is discouraging. I'm not trying to rub the problems of your wonderful creation that is Quiver in your face, or passive aggressively complain to the community. I just want to try Boostnote for a time as since I uninstalled Evernote a month ago, I've been a note-taking nomad and don't quite know where I want to stay. BUT I do want to say if development picked up on Quiver and the iOS app I would definitely choose Quiver! Right now I think Quiver is in a better state than Boostnote but its trajectory isn't nearly as bright with the lack of recent updates.

**Comment by ylian** [comment]
Quiver 3.2 is just released. It's a full rewrite of many core components including model layer, caching, syncing, and full-text search. I think it shows my commitment to further develop Quiver for years to come. So I am closing this.

**Comment by PatrickF1** [comment]
Thank you Yaolian! I agree that it shows your commitment to Quiver for many years, and am happy to say that I am probably not switching to Boostnote anytime soon :)
