### ISSUE TITLE
can not search in markdown table

### ISSUE THREAD

**Issue by scdeny** [HappenApps/Quiver#1192]
When I push Option+Command+F to search something, which in a mardown cell in table format like this:
-----| ----------
89935 | x | 
90133 | xx
79145 |xxx

I put 89935 into the search box, but nothing show. :(

**Comment by ylian** [comment]
Fixed in 3.2.

<img width="354" alt="screen shot 2018-11-25 at 11 19 36 pm" src="https://user-images.githubusercontent.com/984895/48985521-9d8b8900-f108-11e8-859b-a6064164f779.png">
