### ISSUE TITLE
Theme: scroll bar background color always is white when using dark theme

### ISSUE THREAD

**Issue by matchboxy** [HappenApps/Quiver#1193]
scroll bar background color always is white when using dark theme, while it is over bright in dark theme.   would you fix this ?

**Comment by ylian** [comment]
Fixed in 3.2.

<img width="1552" alt="screen shot 2018-11-25 at 11 16 44 pm" src="https://user-images.githubusercontent.com/984895/48985482-408fd300-f108-11e8-9644-679f2be64bb1.png">
