### ISSUE TITLE
App Store does not allow upgrade to 3.2.

### ISSUE THREAD

**Issue by tillt** [HappenApps/Quiver#1195]
Locally I have Version 3.1.3 (138) running. The App Store shows 3.2 being the current version. However the Quiver page within the App Store does only show an "Open" button and no way to upgrade. What gives?

**Comment by tillt** [comment]
Solved it by removing the app locally and re-installing it via the App Store - now got 3.2 running.

**Comment by ylian** [comment]
Yeah, it's a typical bug with the App Store. Not an app issue.
