### ISSUE TITLE
About window  pretty much unreadable in dark mode.

### ISSUE THREAD

**Issue by tillt** [HappenApps/Quiver#1196]
![screenshot 2018-11-25 at 23 48 24](https://user-images.githubusercontent.com/592445/48985854-efcea900-f10c-11e8-9218-0f61c25f2e87.png)

**Comment by ylian** [comment]
Yep, just realized that myself. Same for release notes. Let me see how to fix.

**Comment by Phill93** [comment]
![bildschirmfoto 2018-11-26 um 09 01 12](https://user-images.githubusercontent.com/1454797/49000437-e0298180-f159-11e8-8cf2-031633d59554.png)

The Release Notes Window is also unread able

**Comment by ylian** [comment]
Fixed in 3.2.1. Both "About Quiver" and "Release Notes".
