### ISSUE TITLE
Backup and restore tabs disappeared from preferences

### ISSUE THREAD

**Issue by FCh99** [HappenApps/Quiver#1198]
Hello, I can not see the Backup / restore tabs in preferences, so I cannot do any of those operations, I don´t know why, even I restored from the Apple Store but the tabs do not appear, please help ¡¡

![image](https://user-images.githubusercontent.com/8345571/48986462-9c148d80-f115-11e8-9746-cb133a7067fe.png)

**Comment by tillt** [comment]
Yup, sync is gone as well.

**Comment by MatthewLee123** [comment]
@FCh99 I think @ylian  is changing the design. means you don't need to sync at all. just open your note from Dropbox separately. after modifying your note, it will be saved automatically to Dropbox. 
ie. you can open your library at anywhere.

**Comment by FCh99** [comment]
I don't want to sync, nor use Dropbox, only to make a regular full backup from time to time, and to restore from my previous backups, anyway if change to NO backup keeps, maybe more frequent Time Machine backup is the best option

**Comment by ylian** [comment]
I removed both tabs.

"Sync" is definitely not needed any more because of multi-library support. You can put your library anywhere. A Quiver library put on a cloud-synced folder will watch file changes, thus "synced".

As for the "Backup" tab I'm not entirely sure. I removed it because it does nothing more than making a copy of the library file, but some users thought it magically keeps the backup up-to-date. For now, if you want to make a backup, simply find the library location (File Menu > Show Library in Finder), and make a copy of the Quiver library. I will gather more feedback and see if I need to add this backup function back in.

**Comment by Odepia** [comment]
That was a useful function in Quiver. Please put it back in a further release.

**Comment by FCh99** [comment]
For me is OK now I don´t think it is needed with File Menu > Show Library in Finder

**Comment by loriculberson** [comment]
@ylian All my team's work from yesterday is GONE! The autosave did not work! NOT a fan of 3.2.1!!! And we stayed late last night to complete it. I've been using this product since 2015 and have raved about it to friends and colleagues. I am very disappointed.

**Comment by Odepia** [comment]
**@loriculberson** Thanks for the info! I'am staying for now with version v3.1.3. Not sure to upgrade to version 3.2.x

**Comment by ylian** [comment]
@loriculberson Sorry to hear that. Can you give me some more details? Autosave didn't change at all in 3.2.x. Was the library shared on iCloud Drive?  Happy to assist more by email (support@happenapps.com).

**Comment by loriculberson** [comment]
@ylian Can I revert to the previous version? I am all for updates and making the product better. I love this product. This has been the first hiccup in 3 years. I appreciate the hard work you do, but I need my documents to persist from one day to the next. Maybe there is something I can check on my end?

**Comment by loriculberson** [comment]
@ylian Yes. I sync with iCloud but the library is not shared. My company doesn't let us use Dropbox. I'll email you.

**Comment by ylian** [comment]
@loriculberson Sure. You can download 3.1.3 from here: https://www.dropbox.com/s/1jzycvppu4s5v45/Quiver%203.1.3.zip?dl=0

Also thanks for emailing me the detailed information. I will follow up by email.

**Comment by aabdullah-bos** [comment]
@ylian Hopefully, this isn't off topic, but is there a way to set the location of the default library? I store my primary Quiver Library in Dropbox so that I have access to it from multiple devices, and it's a bit of a pain to have to open Quiver and then open that library.

**Comment by ylian** [comment]
@aabdullah-bos You just open the library once. Quiver will remember to open that library from then on.

**Comment by ylian** [comment]
Looks like quite a few people want the "Backup" tab back. So I am adding it back in 3.2.2.

**Comment by Odepia** [comment]
@ylian: Thanks you! :)

**Comment by ylian** [comment]
Will do this in 3.2.3 instead, since I really want to submit 3.2.2 tonight with the search fix (#1202).

**Comment by ijoseph** [comment]
I like the idea of multiple libraries. However, I think a UI that makes it more clear that this is what's going on (you open a library once by clicking on it directly, and then it continues to open the last-opened library) would be helpful. I was lost until I found this thread.

**Comment by brandon-fryslie** [comment]
I think the documentation should be updated to describe how the new cloud syncing works.  The tutorial in Quiver and all the docs still refer to the 'Sync' tab.  It is very confusing currently

**Comment by ylian** [comment]
@brandon-fryslie Yep, it's a bit confusing at the moment due to the changes. I am sure multi-library support is the right move, so now comes refinements to simplify these functionalities (sync, open library, backup, restore) for common workflows.

**Comment by itsalitee** [comment]
Please bring back the sync option, people's demand varies and this is the way to address them all, in my view. Thank you!

**Comment by ylian** [comment]
Both tabs are added back in 3.2.3. Just released.
