### ISSUE TITLE
Table cell

### ISSUE THREAD

**Issue by nschneid** [HappenApps/Quiver#12]
I'd like to use Quiver to take notes on experimental results, so being able to enter simple tables would be a huge improvement. Even better would be a mini spreadsheet cell with operations like sums and averages.

(I see that if I paste an HTML table into a Text cell the structure is preserved, but this is not an ideal solution.)

**Comment by nschneid** [comment]
Now I see that GitHub-Flavored Markdown tables are supported in Markdown cells. Is the supported flavor of Markdown documented somewhere? The tutorial merely says "You can use common markdown syntax".

**Comment by ylian** [comment]
Yes GFM tables are supported in Markdown cells, but I didn't add the table styles, so they don't look like tables. I am working on these issues for v2.1.

Quiver uses https://github.com/chjj/marked to render Markdown, with default options. GFM is on by default.

**Comment by ylian** [comment]
GFM tables are now displayed properly in Quiver 2.1.
