### ISSUE TITLE
Newly created notebooks are not being sorted

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#120]
Hello,

ISSUE:
Noticed that newly created notebooks are not being sorted alphabetically until I restart the app.

STEPS:
1. Create a few notebooks and give them some basic names.
2. Notice they will not be sorted alphabetically.
3. Restart Quiver.
4. Now the notebooks are alphabetically sorted.

CONCLUSION:
Would be nice if the notebooks got sorted after changing their names.

Another option could be to have a preference whether the notebooks should be sorted by alpha or not. In which case one could manually drag the notebooks to define their order.

Thanks.

OS X 10.9.5 Mavericks
Quiver 2.1.3b17

**Comment by ylian** [comment]
I think I will disable autosort on notebooks. Users would drag to reorder the notebooks. Autosort won't work with nested notebooks (#2).

**Comment by ghost** [comment]
I think letting the user sort the notebooks is wise. Any eta on nested notebooks and an iOS app?

**Comment by ylian** [comment]
No ETA, but major features have been implemented, so it's close.

**Comment by ylian** [comment]
The original issue in the ticket is fixed in Quiver 3.0, released today.
