### ISSUE TITLE
contents is always empty

### ISSUE THREAD

**Issue by liks144** [HappenApps/Quiver#1203]
Newest version of the app, the contents is always empty.
PLS fix it.
![screen shot 2018-11-26 at 16 47 23](https://user-images.githubusercontent.com/23135511/49002313-38807380-f19a-11e8-8c46-29478c4bf199.png)

**Comment by auxbuss** [comment]
I'm seeing this on a version of Quiver that I upgraded. However, on a fresh install on another machine (installed v3.2), everything works as expected. (Possibly a legacy file that's not being upgraded correctly?)

In my case, if I reopen the Quiver library (File/Open/Library), then the data reappears.

However, I'm not sure I this for note updates. For example, my library is shared via iCloud, and if I delete a note on one machine; close Quiver, then open Quiver on another machine, the note is not deleted, although the note content has been removed. (Possibly a caching issue?)

**Comment by ylian** [comment]
@liks144 Possible to send me this note (as .qvnote, zipped)? Thanks. Looks like the editor failed to load for some reason. My email: ylian@happenapps.com

**Comment by LeonardoGentile** [comment]
For me the notes are not visible at all, not their contents but the list of the notes entirely!!

**Comment by ylian** [comment]
@LeonardoGentile Please see https://github.com/happenapps/Quiver/issues/1201#issuecomment-441604976

**Comment by ylian** [comment]
https://github.com/HappenApps/Quiver/issues/1201#issuecomment-441784275

@rebewnitram mentioned a way to reproduce this bug.

Now I can reproduce this so I will fix this right away and resubmit 3.2.1.

**Comment by ylian** [comment]
3.2.1 is resubmitted with this bug fixed.

**Comment by ylian** [comment]
3.2.1 is just released.

**Comment by Xiao6** [comment]
I am hitting same issue with 3.2.4
