### ISSUE TITLE
Searching by tags is not working in 3.2

### ISSUE THREAD

**Issue by keeprock** [HappenApps/Quiver#1204]
Tags are not respected using Full-text search. Check out image below - note doesn't have tag names in it, but matched using full-text search. Tags functionality no longer works.

![image](https://user-images.githubusercontent.com/5209820/49012915-08ca6f00-f18c-11e8-8a02-b89d74df9891.png)

**Comment by ylian** [comment]
Searching by tags is removed in Quiver 3.2 as I revamped search. I will add it back.

The behavior you are seeing is because:
1. "#origin #php" are stripped of extra symbols, thus become "origin php".
2. Quiver 3.2 searches for substrings by default, so the note is found.

So the behavior is correct, but I need to add tag searching back.

**Comment by keeprock** [comment]
Thanks for quick response! I was relying heavily on tags, so removing tags search ability was a big surprise.

**Comment by keeprock** [comment]
Is there any estimation on which version will contain this update? It would be very helpful. Thanks!

**Comment by ylian** [comment]
It's relatively easy to add it back. The old tag search implementation was too ugly, so I removed it during rewrite. I can add it back in 3.2.2.

**Comment by keeprock** [comment]
Thanks for your quick response!

I kinda understand why you removed tags but for me it was a deal breaker. That way allows me to narrow search to a certain topics more easily, e.g. certain tags comes in a pair which make it as narrow as possible. And its certainly possible to break the whole deal with a new search functionality, if tags were legacy code you wanted to remove. I get it so there is no «FIX IT QUICKLY PLZ» from me.

I'm not even talking about combining tags with search string - I was excited about your search re-write only to later found out that tags were out. 

Anyway, I understand a work volume that complete re-write contain and I only paid once for a life time of upgrades.. But at least I am self-conscious of that and notice and appreciate your hard work :)

**Comment by ylian** [comment]
@keeprock Don't worry. Tag search is not legacy at all. It will be added back in 3.2.2.

**Comment by keeprock** [comment]
Thanks, Ylian!

**Comment by ylian** [comment]
Fixed in 3.2.2.
