### ISSUE TITLE
Quiver disappeared from the Canadian App Store

### ISSUE THREAD

**Issue by Odepia** [HappenApps/Quiver#1205]
I had a notification this morning about an update of Quiver (v3.2) in the MAP, but there is no way to apply the update.

The weird thing is that Quiver seems to have disappeared from the Canadian App Store.

Any idea about that "issue"?

**Comment by jjmean2** [comment]
I'm in the same situation. I cannot find Quiver app in Korean App Store.

**Comment by keeprock** [comment]
May be related to this https://github.com/HappenApps/Quiver/issues/1201#issuecomment-441580306

**Comment by dipech** [comment]
Same things in Russian App Store. Can't find.

**Comment by ylian** [comment]
Temporarily removed from sale due to a bug in Quiver 3.2. I already submitted Quiver 3.2.1, and it probably will be approved in a day or so.

**Comment by Odepia** [comment]
Thank you, Ylian, for the information. I close the current issue.
I am looking forward to work the last Quiver update.
