### ISSUE TITLE
Cannot get code editors to use theme

### ISSUE THREAD

**Issue by smlombardi** [HappenApps/Quiver#1207]
I downloaded the Atom One theme.  Loaded it, made some changes to the UI to make it more Mojave-like.  However, the code cells are not picking up the theme from the downloaded theme (I did not edit those).  It's showing the default code theme.

<img width="540" alt="screen shot 2018-11-26 at 3 05 43 pm" src="https://user-images.githubusercontent.com/835148/49039258-45e33100-f18d-11e8-9f25-7a8ec7e16a95.png">

I followed the instructions and made sure I had this:
```
  "editor": {
    "codeCellTheme": "atom-one-dark",
    "markdownCellTheme": "atom-one-dark"
  },
  "css": {
    "className": "atom-one-dark",
    "editor": ".atom-one-dark{color:#ffffff}.atom-one-dark a{color:#C678DD}...
```

Here's the whole file: https://jmp.sh/5JJtV1g

Am I missing something here?

**Comment by ylian** [comment]
There is no "atom-one-dark" theme for the code editor. Check the list here: https://github.com/HappenApps/Quiver/wiki/Code-Cell-Themes

Same list applies to the Markdown cell theme as well.

**Comment by smlombardi** [comment]
That works, thanks.

So, it that whole "css" block in the json unnecessary? Can I simply delete it, if the code editor is just going to use my chosen ACE theme?

**Comment by ylian** [comment]
The css block applies on top of the ACE theme.
