### ISSUE TITLE
Size limits for notebook

### ISSUE THREAD

**Issue by FCh99** [HappenApps/Quiver#1210]
Hi, I have a 1200 notes Notebook many notes have images, and I started having problems, like when new note creating the note disappeared and other problems, so the question is:  is there any size limit for a Notebook?

**Comment by ylian** [comment]
No size limit. A screen recording of the bug would be very helpful. Thanks.

**Comment by FCh99** [comment]
The issues ( i will try to post you some screen recording too)
Problem 1. When entering the app, I could scroll on the left side notebook names and tags, but the Note to write kept always the same like "frozen", so I quitted the app, reinstalled and OK, but this has happenned several times
Problem 2. Create a new note, write on it, save it, but always lost the body, I could only see the title and tags, this happenned several times
Now I was worried with all the info there, so I split in two notebooks, 650 notes and 450 notes

**Comment by ylian** [comment]
Are you using 3.2 or 3.2.1? There was a bug in 3.2 that might show such symptoms.

**Comment by FCh99** [comment]
Problem 1

![image](https://user-images.githubusercontent.com/8345571/49110447-cf7a2800-f28d-11e8-9551-c1ac1e521191.png)


![image](https://user-images.githubusercontent.com/8345571/49110478-e882d900-f28d-11e8-8d48-a2682deb5381.png)

![image](https://user-images.githubusercontent.com/8345571/49110493-fa647c00-f28d-11e8-8d0a-4e3d07a17147.png)

**Comment by FCh99** [comment]
HI, I updated to 3.2.1 and both problems look like solved, looks good ¡¡

**Comment by ylian** [comment]
@FCh99 Okay, I am relieved. Thanks for letting me know. :)
