### ISSUE TITLE
All notes disappeared after update

### ISSUE THREAD

**Issue by philbayer** [HappenApps/Quiver#1211]
After the recent update (3.2) all of my latest notes have disappeared.  The only notes remaining are very old versions of some of the notes.  Any new notes since February 2018 have simply vanished.  I desperately need those notes restored.

**Comment by ylian** [comment]
If you are not running 3.2.1, please update. If the problem still exists with 3.2.1, let me know.

**Comment by philbayer** [comment]
The app store says I have version 3.2.1, however, the About menu in the app says `Version 3.2 (175)`

**Comment by ylian** [comment]
The latest is 3.2.1 (180). App Store might need to be refreshed.

**Comment by ylian** [comment]
You can delete the application, then install from AppStore.

**Comment by philbayer** [comment]
Ok, I will try it.

**Comment by philbayer** [comment]
Ok, that got me to the latest version, but the notes are still missing.  I have Time Machine backups.  What do I need to do to get them restored?

**Comment by philbayer** [comment]
I was able to locate my notes in time machine and restore from a backup with the latest version.  Thanks for your help.  You can close the issue.

**Comment by csaborio001** [comment]
Where are Quiver files stored? Cannot find anything under /Users/csaborio/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver
