### ISSUE TITLE
can you integrate multi libraries into one window?

### ISSUE THREAD

**Issue by MatthewLee123** [HappenApps/Quiver#1213]
open multi libraries simultanousely is an exciting feature. thanks.

but now,  can you do some improvement to make multi libraries within one quiver window instead of multi windows. it's easy for drag and drop and have a good looking (or need to switch between them when you use them). 

the structure can like
library-name1-> notebooks->sub-notebooks
library-name2-> notebooks->sub-notebooks
.
.
.

thanks

**Comment by ylian** [comment]
I considered that but opted to use the "one library per window" approach. This approach is cleaner, and works seamlessly for users who don't need this feature.

**Comment by MatthewLee123** [comment]
thanks. kindly I think people who don't use this feature, he can just close other libraries simply.
just consider when you do drag and drop within one window is definitely easier than multi windows.
and it then has a good tree-vision. but I can imagine, the key point is,  there should be huge changes on quiver.... as the left pane need to be changed.

**Comment by ylian** [comment]
Yes, it would have big implications to both UI and data models.

**Comment by ylian** [comment]
I am going to close this since I don't want to change the current design. Another implication was that Inbox and Trash are per library, so the whole sidebar would have to be redesigned.

**Comment by wjhdev** [comment]
I just discovered Quiver has multi-library support which is great news! I work in enterprise healthcare and work notes just can't sync. I've been looking for a way to sync work notes against a network drives and personal notes from a cloud. This is going to let me do that!

I agree what I think you're describing is a bad UI and approach. But would it be possible to implement something like Slack's multi-team support skinny sidebar?

![image](https://user-images.githubusercontent.com/3745345/59812880-28b2b300-92d5-11e9-9af3-74e05411dbdd.png)

That would still let notebooks have their own trash, inbox and (hopefully?) data structure.

Why I ask: I'm a big fan of MacOS spaces for core apps, but two for Quiver would be overkill. I'd also like to command+tab to Quiver and have access to all Libraries without sorting through windows.
