### ISSUE TITLE
Tag in shared notebooks does not work in v3.2.x 

### ISSUE THREAD

**Issue by kaix1n** [HappenApps/Quiver#1214]
Platform: OSX 10.14.1

Issues: 
I have several shared notebooks, since I upgraded Quiver to version `3.2`, tag tree became empty. Also when I create a new note, I can not get any history tags any more.

Screenshot:
![image](https://user-images.githubusercontent.com/1772355/49124357-1fd9a000-f2f7-11e8-9abe-43a569b26884.png)

**Comment by ylian** [comment]
Aware of this. Tags from shared notebooks are no longer displayed in this list. Only tags in the library are displayed in this list.

I will try to add it back.

**Comment by kaix1n** [comment]
Thanks!

**Comment by kg4zow** [comment]
I'm having the same problem, commenting so I get notified about this issue.

**Comment by ianthekirkland** [comment]
Uggh. @dev, please fix this!!! This is critical. I'm willing to wait cuz this is a killer app. But, anytime I see a lack of activity on the dev side, it makes me nervous and apt to jump ship to more basic-yet-long-winded solutions (read: cloud-synced plain text). I see some movement 3 months ago, but nothing along the lines of addressing this glaringly obvious oversight. I won't keep investing in a product that seems like it's no longer breathing. I want to know...Quiver, are you breathing?

**Comment by ylian** [comment]
@ianthekirkland I have been working on some huge updates. Thanks for your patience.
