### ISSUE TITLE
Notebook creation '+' should ask for standard vs shared notebook (or better yet, allow setting default to shared)

### ISSUE THREAD

**Issue by satobin** [HappenApps/Quiver#1219]
The creation flow '+' icon should allow selection of shared notebook -- it would also be great if it was possible to change the default notebook creation from standard to shared; as I'm guessing most people want their notes backed up, and accessible across all devices.

Also, it would be helpful if the open space below 'Notebooks' would allow right click for creation of new local or shared notebook:
![image](https://user-images.githubusercontent.com/6655525/49189929-08191080-f325-11e8-9a54-24332931cebc.png)

**Comment by ylian** [comment]
This is intended behaviour. "Shared Notebooks" are superseded by multi-library support.

If you find yourself creating multiple shared notebooks, the recommended workflow now is:
1. File Menu > New Library, and save the new library anywhere you like. If you save the library on a cloud-synced location, then file watching is turned on and the library is "synced".
2. Each library opens in its own window. You can drag and drop notes and notebooks between libraries.

The shared Quiver library can be used in a team collaboration scenario. For example, you can have a personal Quiver library and a work-related Quiver library that's shared with coworkers.
