### ISSUE TITLE
Manual sort not working correctly

### ISSUE THREAD

**Issue by semix2** [HappenApps/Quiver#1221]
I'm using Quiver 3.2.2. This version brake my custom sort order. And when I try to repair order by dragging a note, the note placed incorrect position or the other note moved. (especially trying to move first note)

My notebook has 19 notes, and I'm using Korean language. 

Please fix it.

**Comment by ylian** [comment]
Yep, I can reproduce it. Will fix in 3.2.3.

**Comment by semix2** [comment]
Thank you, I'm waiting fixed version. I like Quiver!

**Comment by Expt-David** [comment]
I'm waiting, too. Thank you very much.

**Comment by darkisa** [comment]
Waiting for the release as well. Awesome app ylian!

**Comment by BenRacicot** [comment]
This app keeps me from changing careers! (jk, jk but seriously) Thanks for fixing this :)

**Comment by ylian** [comment]
Already have a fix. Finishing up two other fixes and plan to submit 3.2.3 tomorrow.

**Comment by leanne63** [comment]
Also awaiting update for this issue. You put a ton of work into this app, ylian - and it shows! I really appreciate your drive to keep this app exceptional!

**Comment by ylian** [comment]
3.2.3 was already submitted. Should be available for download within a day or so.

**Comment by jkryanchou** [comment]
@ylian Has ver 3.2.3 improved filter functionality to improve search?

**Comment by ylian** [comment]
Fixed in 3.2.3. Just released.
