### ISSUE TITLE
Filter in notebook not working correctly

### ISSUE THREAD

**Issue by YuryRadchenko** [HappenApps/Quiver#1227]
The filter takes all items from all notebooks, but not items from a current notebook.
Version 3.2.2 (181)

<img width="490" alt="quiver 2018-12-05 10-16-10" src="https://user-images.githubusercontent.com/2685560/49499757-a2260f00-f877-11e8-85df-00be6983671a.png">

**Comment by jkryanchou** [comment]
+1, I already have a lot notes in my notebook. while it could not ge the correct results when I filter in the textbox on the bottom.

**Comment by jkryanchou** [comment]
@ylian Is there any tips for filter by title or keyword? I have filter many cases while got nothing correct. It confused me a lot. Hope it could be fixed. soon.

**Comment by ylian** [comment]
Yes, this is fixed in 3.2.3 as well. It should be approved for release later today.

**Comment by jkryanchou** [comment]
@ylian Cool.

**Comment by ylian** [comment]
Fixed in 3.2.3. Just released.
