### ISSUE TITLE
Blank second pane when in three pane layout after 3.2.2 update

### ISSUE THREAD

**Issue by mobileben** [HappenApps/Quiver#1228]
I updated to 3.2.2. I use 3 panes layout.  Today is the first day I restarted Quiver after the update. Typically the second pane shows a list of all the notes in a notebook. However after starting. nothing showed up.

Let us say I am on notebook A. I found if I changed the Sort by Title then it would list the notes in notebook A. However if I changed notebook to B, then pane 2 would not change. It would still show the notes for notebook A until I changed the Sort By to Title. I also noticed that Sort By would be set to "(null)".  I realized at the top it was marked as "Inbox". I clicked on the InBox in Library and a few other items and then it magically fixed itself.

Now when I click on the notebook, the notebook name will show up on the top of the 2nd pane. Note that (null) still shows up at times for some of the notebooks where it should say "Sort by". See screenshot as the example.

<img width="503" alt="screen shot 2018-12-06 at 12 39 46 am" src="https://user-images.githubusercontent.com/536780/49572272-45b30600-f8f0-11e8-8be9-2f2de9a58e56.png">

**Comment by mobileben** [comment]
Addition, something seems very broken. If you click on a notebook in the library that contains sub-notebooks and then click on the subnotebooks, the second pane will not update at times. It's spurious but happens at a high frequency.

Steps to create:

1. Have notebook with nested notebooks.
2. Be in 3 panes layout
3. Click on parent notebook
4. start to click down each successive notebook

Note that in second pane, the contents of the pane will not change and be stale. Eventually it will correct itself. Once it does, if you click on previous sub-notebooks that didn't have the notes show up in the 2nd pane, the notes will be listed

<img width="555" alt="screen_shot_2018-12-06_at_12_50_24_am" src="https://user-images.githubusercontent.com/536780/49572677-249ee500-f8f1-11e8-9e60-fac22924ec63.png">

**Comment by ylian** [comment]
This sounds really like a bug in 3.2. Please make sure you are running 3.2.2.

**Comment by ylian** [comment]
Okay, I realized that the fix I did in 3.2.1 didn't cover the initial run (first time after upgrade). All you need to do is to reopen the app. I will fix this edge case with the initial run as well.

**Comment by mobileben** [comment]
@ylian thanks for the reply. It is indeed 3.2.2. And you are correct. I restarted the app and the issue is gone.

**Comment by ylian** [comment]
Fixed in 3.2.3. Just released.
