### ISSUE TITLE
navigation between notes

### ISSUE THREAD

**Issue by FCh99** [HappenApps/Quiver#1229]
I don´t see how to navigate to previously read or even modified note or doing forward wihout having to change to "recents" list which means abandoning your current list and setting it back later which is time consuming, is there any  "back" key  or a "forward" or a shortcut to scroll on a stack of notes quickly?

**Comment by ylian** [comment]
You can use the < > buttons at the bottom of the note.

**Comment by FCh99** [comment]
Great ¡¡
