### ISSUE TITLE
Feature Request: nvALT importer

### ISSUE THREAD

**Issue by lastobelus** [HappenApps/Quiver#123]
The effort of handrolling my own is the only thing that keeps Quiver from being an insta-buy for me.

Perhaps as a quick starting point, having a look at [this gist](https://gist.github.com/anabranch/09c421e3ff13e1245316) and ensuring that it is canonical/complete.

Probably most users of this would not need/want an in app UI, just a shell script with instructions would be fine.

**Comment by ylian** [comment]
You can already import plain Markdown files. File > Import > Markdown. You can choose multiple files.

**Comment by lastobelus** [comment]
Oh, thanks! I will give it a try.
