### ISSUE TITLE
Search commands

### ISSUE THREAD

**Issue by FCh99** [HappenApps/Quiver#1230]
Hello, I have a lot of notes, when I search I select a tag and then go to to the bottom to the search box based on a tag selected. So I enter one word and it returns lots of notes, too many to manage, so how to search by note title only ? is there any shortcut or # or @?, I saw some Alfred extension but no clue how to use it or if it it is what I need, this should be simple and straightforward

**Comment by ylian** [comment]
"Retuning lots of notes" is a bug introduced in 3.2.2. It's fixed in 3.2.3. Just released.

The search field supports a few syntaxes:

Search by tag: #tag 
Search by keywords: blah baz
Prefix search: blah*
Suffix search: *blah
