### ISSUE TITLE
you loose the "name of the note"

### ISSUE THREAD

**Issue by FCh99** [HappenApps/Quiver#1231]
When you scroll down the note you loose the "name of the note", so you loose context when you have many windows opened in your screen (XCode, Quiver, Chrome, etc), and you end up scrolling up and down

**Comment by FCh99** [comment]
So, to clarify, the name of the note should always be seen on top of the note, even if you are scrolling down, further more, you should be able to open some windows simultaneously each with a note and identify their names at a snapshot

**Comment by ylian** [comment]
Thanks. Will consider when I redesign the UI.
