### ISSUE TITLE
Heading highlight disappears

### ISSUE THREAD

**Issue by YanchunHe** [HappenApps/Quiver#1232]
Sometimes, cooler highlights of headings will disappear (as ### WP3 in the attached image), if its previous section has several bullets and there is only one blank line between these two sections.

System: MacOS 10.13.6
Quiver: 3.2.3

![image](https://user-images.githubusercontent.com/1725351/49642450-5c9e4900-fa13-11e8-87d6-f40c659fa067.png)

**Comment by ylian** [comment]
Such issues will be fixed in the editor rewrite, which is the focus of the next major update (3.3).

**Comment by ylian** [comment]
Close this since there are several tickets open for this same issue already.
