### ISSUE TITLE
Search only by note title

### ISSUE THREAD

**Issue by FCh99** [HappenApps/Quiver#1234]
Sorry for insisting but I need an answer for this, if I want to SEARCH ONLY BY NOTE TITLE, is this a possibility? how? The problem is I have 1.200 notes and I want to refine to only titles, not full content, thanks

**Comment by ylian** [comment]
I see. No, there is no separate syntax for searching just the note title. Suggestions are welcome.

**Comment by FCh99** [comment]
I think as Quiver grows to a big information container with lots of notes, all search issues become very  very important, so the points I see are, for a shortcut or similar:
- search by content
- search by title only, returns less notes, speeds searches
