### ISSUE TITLE
Support outline in the markdown

### ISSUE THREAD

**Issue by libratiger** [HappenApps/Quiver#1235]
Is there any plan to support this feature? such as [maxiang](https://maxiang.io/) app does

![image](https://user-images.githubusercontent.com/870144/49681920-92f7c900-fae4-11e8-8c94-63d223f38e22.png)

**Comment by TangHanF** [comment]
My thoughts are the same as you

**Comment by lucical** [comment]
Same here!

**Comment by lhsaq2009** [comment]
Same here!
