### ISSUE TITLE
Error when creating new notes

### ISSUE THREAD

**Issue by FCh99** [HappenApps/Quiver#1240]
Version 3.2.3
- If I go to "+" symbol, then when the "new note" pops up, **I change the notebook**, add some tags plus information, then save it.... that content never appears as a new note, or appears without content, just because I changed the notebook initially

- So, the only work around would is to select the notebook first then to go to "+", never the other way round

Looks like an error as content should be saved whatever changes are done in the process of adding a new note

**Comment by ylian** [comment]
Already fixed in 3.2.4.
