### ISSUE TITLE
All notes is not showing correctly.

### ISSUE THREAD

**Issue by arkilis** [HappenApps/Quiver#1241]
Upgraded to latest version, the `All notes` is not showing correctly:

![image](https://user-images.githubusercontent.com/1528028/49897179-247a8880-fea1-11e8-91dd-700dbb48abae.png)

**Comment by ylian** [comment]
Can you take a screenshot? Thanks.

**Comment by arkilis** [comment]
I am at work now, I will send you the screenshot once I get home. Basically all the shared notebooks are not counted in.

**Comment by ylian** [comment]
I see. This is the same as #1239. Merge with #1239.

**Comment by arkilis** [comment]
Is there any plan for fixing this issue? Thanks

**Comment by ylian** [comment]
Yes, this will be fixed, likely in the next update.

**Comment by arkilis** [comment]
Updated to 3.2.4 190, still not working @ylian 

![image](https://user-images.githubusercontent.com/1528028/51951184-5e1e4780-247f-11e9-879d-2382e081c603.png)

**Comment by mbuchetics** [comment]
Same issue on 3.2.7 (201).
