### ISSUE TITLE
How to search for multi word tags?

### ISSUE THREAD

**Issue by PatrickF1** [HappenApps/Quiver#1244]
I learned from other Quiver issues that you can search for tags using #tag. But what do you do if your tag is two words? I tried #"tag name" and #tag name and neither work.

Also would be nice if this can get documented in the Wiki. (I can do it, too, once I master this feature).
Thanks!

**Comment by ylian** [comment]
Hmm, that's not supported. I am not even sure spaces should be used in tag names.
