### ISSUE TITLE
Request: Don't quit app when closing window

### ISSUE THREAD

**Issue by arthurhammer** [HappenApps/Quiver#125]
Version 2.1.2 (10)

Currently, the app quits when closing the main window. Usually, smaller utility apps behave this way. For apps the size of Quiver I think this is unusual behavior on OS X. I take notes over longer periods of time where I close the window multiple times, and every time I'm surprised the app quits.

I'd suggest adding a preference to quit/not quit on close. (Hiding the app is a workaround but not a great solution.)

**Comment by ylian** [comment]
This is fixed in the coming update.

**Comment by ylian** [comment]
Fixed in Quiver 3.0, released today.
