### ISSUE TITLE
Can't see ace-editor on opening notes

### ISSUE THREAD

**Issue by ghost** [HappenApps/Quiver#1252]
When I open a note in the editor, all `ace-editor` cells are initially invisible. In the following screenshots, there are two invisible cells (one LaTeX, one Markdown):

<img width="513" alt="image" src="https://user-images.githubusercontent.com/6297901/50572509-22c62580-0dba-11e9-8acd-5c5a30ff8095.png">

Clicking the cells makes their content visible:

<img width="515" alt="image" src="https://user-images.githubusercontent.com/6297901/50572521-61f47680-0dba-11e9-9997-4e49d53ae8d8.png">

The same goes for code cells:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/6297901/50572544-d4655680-0dba-11e9-8129-f367f39f5a5f.png">

**Comment by ylian** [comment]
Turned out to be an issue with custom CSS. Resetting to defaults (Preferences > Advanced > Restore Defaults) worked.
