### ISSUE TITLE
3.2.3 blank content on Mojave 10.14.2 

### ISSUE THREAD

**Issue by hzheng** [HappenApps/Quiver#1253]
Just notice that Quiver's content pane is totally blank (except for titles/tags/dates) after recent update. 
I tried changing theme or exporting, no content was shown.

Also I inspected notes' content.json files, which looked normal.

**Comment by ylian** [comment]
Could be an issue with opening the library. Remove the cache file (~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/cache.db), then reopen Quiver.

**Comment by hzheng** [comment]
Now it works. Thanks a lot.
