### ISSUE TITLE
Cannot see typing on anything but text cell. Version 3.2.3

### ISSUE THREAD

**Issue by cgkades** [HappenApps/Quiver#1258]
I'm using version 3.2.3 and after creating a new cell, I cannot see typing if I change it to anything but text. If I type in, for example, a markdown cell and change it back to text, I can see the things I've typed. If I change it back to markdown again, I can see the things I had typed, but I cannot put the curser anywhere or see any new typing.

I'm on macOS 10.13.6

**Comment by ghost** [comment]
Likely the same issue as #1252, so +1

<img width="532" alt="image" src="https://user-images.githubusercontent.com/6297901/50847521-b757f700-1369-11e9-9937-5dcc280f81a6.png">

**Comment by ylian** [comment]
@cgkades That's likely an issue with themes. Try to reset to default settings (Preferences > Advanced > Restore Defaults), then reopen Quiver.

@gclv You issue is with loading the library. I am trying to hunt down this one so it would be great if you could send me (ylian@happenapps.com) these two files (these files only contain some meta data, not your note contents):
```
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/cache.db
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/library.plist
```
Then you can delete the first file, then reopen Quiver. It will likely fix the issue, but those two files will help me debug the issue. Thanks.

**Comment by cgkades** [comment]
That did work, though it is very strange since I did not change the theme.. Thanks for the help

**Comment by ylian** [comment]
@cgkades You might have added some custom css settings. Resetting to the default settings clears the custom css as well.

**Comment by ylian** [comment]
It turned out both are due to custom CSS. Resetting to the default settings (Preferences > Advanced > Restore Defaults) fixed the issues. Close the ticket.
