### ISSUE TITLE
Open Multiple Quiver Notebooks/Instances

### ISSUE THREAD

**Issue by preflight** [HappenApps/Quiver#126]
Is there a way to have multiple notebooks open at a time or multiple instances of Quiver with a different notebook open in each instance?

**Comment by ylian** [comment]
No, you can't have multiple notebooks open at a time. But you can have multiple notes open at a time. Let me know your use case and I will think about it. Thanks.

**Comment by preflight** [comment]
Sure, my use-case is coding something and researching something at the same time. For example, let's say it's a Backbone app and I need to do research for a new feature. In my **Backbone Notebook**, I type out the stuff I learn from reading articles, etc. In a second **Project Notebook**, I type out the specs, notes, details, etc., as they pertain to the feature I'm working on. Both notebooks have multiple notes (for various app features, topics, etc.) and I bounce around a lot from note to note.

Rather than switch back and forth between notebooks in the same app window, I'd like to have multiple notebooks open at a time in different windows (and in my case, on different monitors).

**Comment by ylian** [comment]
I see. It's a good use case. Have to think about this one. I like the simplicity of a single window: having several full-featured windows is useful but it's a big design change.

**Comment by ylian** [comment]
Closing this since I prefer a single window as it's currently implemented. Quiver can't handle all the use cases so there has to be tradeoffs for simplicity.
