### ISSUE TITLE
Give code cells a title

### ISSUE THREAD

**Issue by PatrickF1** [HappenApps/Quiver#1261]
Code cells will be much more useful if they have a title. Often, I have a chunk of code that is part of a bigger note and I want to give a title to it. To give it a title I need to create a text or markdown text positioned above it, but that's inconvenient and brittle if the two cells get separated.

I think if this gets implemented, it would be a superior feature that beats other note taking apps that can store code snippets. For example Boostnote and SnippetsLab both store code and can organize them into tabs. Snippets of code separated into tabs is nice because you can easily organize code that way but then it's hard to view all the code in context of other things. But a feature that allowed code to be easily organized with titles AND be viewed in the context of other information, man that'd be killer. It'd probably convert people from the other products to Quiver.

I understand revamping code cells may break backwards compatibility or it'll be very difficult to write code to migrate to a new format. If that's true, then how about just introducing a new cell type that's code + title. What do you think @ylian ?

**Comment by ylian** [comment]
Quiver is designed for note-taking, not managing code snippets. The ideal usage of Quiver is a user-typed, medium-length note, consisting of dozens of mixed-type cells.

I suggest using a text cell or Markdown cell above the code snippet. And use a note for more than one snippet.

**Comment by PatrickF1** [comment]
But I'm not managing code snippets. I am using it exactly the way Quiver is designed: user-typed, medium-length note, consisting of dozens of mixed-type cells. Going by the use case you said and which is also my use case, occasionally you will need to label a block of code so that it easily fits into the context of the note. That's why I think this feature would fit belongs in Quiver.

**Comment by ylian** [comment]
Then I don't see the point of assigning a title to a code cell. Adding a text cell or Markdown cell on top of the code cell achieves the same thing, and doesn't seem like extra work if you already have multiple cells in the note.

**Comment by PatrickF1** [comment]
Don't you think it's bothersome that you have to create extra cells and
keep the title and code cell together?

**Comment by ylian** [comment]
Creating a cell takes one keyboard shortcut. Thanks for the suggestion but I really don't think this is a hassle.

**Comment by PatrickF1** [comment]
Alright, thanks for listening to my suggestion.
