### ISSUE TITLE
Typing does not work in all cells expect text cells

### ISSUE THREAD

**Issue by ssteiger** [HappenApps/Quiver#1266]
Hello,

I bought Quiver (Version 3.2.3) in the App Store.

When I type in a cell that is not a 'Text Cell' (Code, Markdown, Latex) the cursor does not move and no characters appear. Also I cannot select text or change the place of the cursor (the cursor stays at the beginning of the cell).

But when I switch from editing to the 'View only mode' of a note, the characters that I typed are visible but not when I switch back to the 'Editing mode'.

My System: macOS High Sierra Version 10.13.4

If you need anything else from me, please let me know!
It would be great if that bug get fixed because I would really like to use the other cells as well :-)

cheers

**Comment by ylian** [comment]
This sounds really like https://github.com/HappenApps/Quiver/issues/1258. Can you try to reset the settings? (Preferences > Advanced > Restore defaults)

**Comment by tiff-es** [comment]
I had the same issue, in edit mode, I could **paste** markdown into a markdown cell perfectly fine, *but* I couldn't see as I type. **Resetting the settings to restore default fixed the issue!** Was dreading having to go back to Boostnote, but I'm glad this was a super simple fix. I can now type, format, and edit in **all** cells (MD, code block, etc)! This app is an absolute godsend for taking code notes, wish I found it sooner! 

System: macOS Catalina 10.15 _Beta_
