### ISSUE TITLE
Using tab to indent bullets in markdown

### ISSUE THREAD

**Issue by PatrickF1** [HappenApps/Quiver#1268]
I noticed that in a text cell when editing a bullet point, I can use tab to indent it. But in a markdown cell when editing a bullet point, tab inserts a literal tab. 99% of the time, I bet you, this is not what users want. Could you consider changing the behavior of tab so that it indents the bullet instead? Or maybe add a new shortcut like shift-tab that will do it if you want to preserve the behavior of tab.

**Comment by cocoaaa** [comment]
@ylian is this on your radar? Every time I use Quiver, I hope for this feature:) It would be great if we can configure this behavior in the settings.

**Comment by randyoswald** [comment]
I would love this feature.

**Comment by ssarraju** [comment]
+1. Any workaround for this?

**Comment by ssarraju** [comment]
> I noticed that in a text cell when editing a bullet point, I can use tab to indent it. But in a markdown cell when editing a bullet point, tab inserts a literal tab. 99% of the time, I bet you, this is not what users want. Could you consider changing the behavior of tab so that it indents the bullet instead? Or maybe add a new shortcut like shift-tab that will do it if you want to preserve the behavior of tab.

Patrick, did you find any workaround for this? I dont see a way other than moving cursor to the beginning of the point and hit a tab.

**Comment by PatrickF1** [comment]
No workaround except to move the cursor or tab in vim mode using >>. My real workaround is to switch to http://notable.md/
