### ISSUE TITLE
Move "Note List" style out of Preferences

### ISSUE THREAD

**Issue by robdecker** [HappenApps/Quiver#128]
Moving the "note list" dropdown selector out of preferences and putting it into the View menu would be great. 

It'd be great to not have to go in there every time I want to switch the list styles.

**Comment by ylian** [comment]
Great idea. Seems obvious now you mentioned it.

**Comment by ylian** [comment]
Changed in Quiver 3.0 beta: https://github.com/HappenApps/Quiver/issues/162
