### ISSUE TITLE
Feature to copy all code snippets from a note

### ISSUE THREAD

**Issue by cheics** [HappenApps/Quiver#129]
I tend to use Quiver as more a a Notebook - Think iPython or Mathematica notebooks.

Since code cannot be executed in Quiver, it would be super great if I could copy all code snippets in a particular note to the clipboard.

**Comment by ylian** [comment]
Added an option to "Copy Code Only" in 3.0.1.

![image](https://cloud.githubusercontent.com/assets/984895/12905902/28d79ac4-cea9-11e5-96e2-778986231e4e.png)
