### ISSUE TITLE
Quiver crashed, all data lost.  Unable to restore backup

### ISSUE THREAD

**Issue by cutenarwhal** [HappenApps/Quiver#1293]
I've been a huge Quiver evangelist for over a year now.  But today I opened Quiver and it was extremely slow to load, then when it finally opened (after maybe a minute), there was no data.  Checking the file-system, the library was also so small that it looks like Quiver has basically created a completely new empty notebook :( 

This is with Quiver 3.1.3 running on Mac OS High Sierra 10.13.6.   

If there's any data I can get to help debug, please let me know. 

I made a backup (approx 190 MB) back in December.    However when I try to do File --> Import Notebook,  the backup is shown disabled: 

![image](https://user-images.githubusercontent.com/40391421/55063079-9080a580-50ba-11e9-8187-e8fe895a41a6.png)

I have also tried Quiver -> Preferences -> Backup -> Restore from backup but if I select either of the quiver library files there, it does not import the 190MB of notes I know exist 

![image](https://user-images.githubusercontent.com/40391421/55063234-e2c1c680-50ba-11e9-8c95-0d05b8aa8876.png)

I hope I can at least import the 4-month old backup. I've lost a lot of work since then even.  Is there any other location on the filesystem to find a last cache of the most recent data ?

**Comment by ylian** [comment]
It looks like when you open Quiver, it fails to find or load your Quiver library.

I suggest the following:
1. Check the library at the default location: `~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/Quiver.qvlibrary`. Check the size of this library. If it's quite small (compared to your real library which is over 190MB), then your real library was somewhere else.
2. If you remember where you store your Quiver library, check those locations. You can also use Spotlight to search for "Quiver.qvlibrary".
3. If you find your real Quiver library (over 190MB as you mentioned), double click on it to open.
4. If you can't find your Quiver library, then follow the next steps to restore from the backup.

To restore from the backup:
1. From your screenshots, the backup that is 193.4MB should be renamed to Quiver.qvlibrary.
2. Then open Quiver -> Preferences -> Backup -> Restore from backup, choose the library file.

**Comment by olibclarke** [comment]
Was this resolved @ylian? These reports of data loss are very concerning - I rely on Quiver to store my lab notes and I cannot afford to lose them

**Comment by ylian** [comment]
@olibclarke I am quite certain it's a cache issue, and most users who reported the issue fixed it by resetting the cache. I will fix the cache issue in 3.2.5, pushing out this week.

**Comment by mogita** [comment]
For any future readers, if you found your Quiver contents turned blank, with titles and notebooks remaining, please try the above method. I restored my data this way.

**Comment by ylian** [comment]
Fixed the cache issue in 3.2.5.
