### ISSUE TITLE
Data lost after switching notes

### ISSUE THREAD

**Issue by hollisimo** [HappenApps/Quiver#1295]
Version 3.2.4 
OSX 10.14.4

How to reproduce:

* Edit current note 
* Click on another item on the left panel to show another note
* Switch back to the first note
* Data in the first note will be lost

[Re-Opening an issue that was 'fixed' in 3.2.3] https://github.com/HappenApps/Quiver/issues/709

**Comment by ylian** [comment]
Can you show me a screenshot or screencast? Thanks.

**Comment by hollisimo** [comment]
Screancast of the issue: https://youtu.be/62Z-e2bIS2I

**Comment by ylian** [comment]
@hollisimo Thanks. Are you actually able to view contents of any note at all? If not, it's a cache issue, and please reset the cache by following these steps:

1. Take note of your library location (Preferences > Sync > Library Location).
2. Close Quiver. Delete the cache file and the search index file:
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/cache.db
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/index-v2.dat
3. Double click on your library to open Quiver again.

Also it would be great if you let me know where your library was stored. I am trying to fix this cache issue.

**Comment by hollisimo** [comment]
Resetting the cache as you suggested worked to fix my issue. Thanks! For your reference, my library is  stored in a dropbox folder synced locally.

/Users/hollisimo/Dropbox/Apps/Quiver/Quiver.qvlibrary

**Comment by ylian** [comment]
Thanks for letting me know the library location. It's very helpful. I will close this ticket but will certainly fix the cache issue now that I have a better idea what's causing it.
