### ISSUE TITLE
All Notes Gone

### ISSUE THREAD

**Issue by csaborio001** [HappenApps/Quiver#1297]
Wow, so scary that others have had the problem. All notes are gone, I just edited one about 30 minutes ago...all notes were showing but showed no content, I quit, restated and now all notes are gone. 

I'll try and restore from backup, any pointers greatly appreciated.

**Comment by ylian** [comment]
It's a cache issue. Please do this to reset the cache:

1. Take note of your library location (Preferences > Sync > Library Location).
2. Close Quiver. Delete the cache file and the search index file:
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/cache.db
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/index-v2.dat
3. Double click on your library to open Quiver again.

I will fix the cache issue in v3.2.5.

**Comment by csaborio001** [comment]
Managed to restore from a backup from iCloud which means I lost all notes I took today.  I am baffled and scared of using this app again, never had this happen with any note-taking app.

**Comment by ylian** [comment]
@csaborio001 Where was your library stored? Restoring from backup writes to the default library location (~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/Quiver.qvlibrary). So you might still have all your notes in the original library location.

**Comment by csaborio001** [comment]
It's empty:

https://link.scorpiotek.com/xrgaea

**Comment by ylian** [comment]
@csaborio001 What's your current library location? (Quiver > Preferences > Sync > Library Location)

**Comment by csaborio001** [comment]
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver/Quiver.qvlibrary

The file in there is 282 bytes. The one I found under:

~/Library/Mobile Documents/com~apple~CloudDocs/App Data 

Was 22 MB, which does not have the changes which I did yesterday.

**Comment by csaborio001** [comment]
Don't worry about it...it'd be nice to have an option to automatically backup the library somewhere periodically.
