### ISSUE TITLE
Preview window only remains visible when Quiver is active

### ISSUE THREAD

**Issue by jamesdh** [HappenApps/Quiver#130]
I prefer to take notes in Quiver as I'm developing and occasionally reference them in a more readable view, a la the Preview pane. However as soon as Quiver is deactivated, the preview pane disappears. 

Any chance we can have an option to make the preview pane "stickier"?

**Comment by ylian** [comment]
This is changed in the next update. You will be able to browse notes in the preview mode.

**Comment by jamesdh** [comment]
Not sure what you mean by "browse notes". I just want the preview panel to stay visible even when Quiver is not active. The main editing pane of quiver remains visible when not active, but the preview window disappears.

**Comment by ylian** [comment]
The preview window is integrated into the main window in the next update. You can also open a note and leave it in preview, as well as side-by-side preview.

![image](https://cloud.githubusercontent.com/assets/984895/8254246/c95500e8-1664-11e5-9a4f-608b6b9b5333.png)

![image](https://cloud.githubusercontent.com/assets/984895/8254184/699917ac-1664-11e5-8033-372dc75cb5a6.png)

**Comment by jamesdh** [comment]
So you're saying preview and edit can't be open simultaneously?  :(

**Comment by jamesdh** [comment]
Oh, you could open a note and set it to preview, while leaving the main window for the same note in edit mode?

**Comment by ylian** [comment]
Yep you could open a note and set it to preview, while leaving the main window in edit.

Or you can use side-by-side preview:

![image](https://cloud.githubusercontent.com/assets/984895/8265289/6e2f2b84-16c4-11e5-860d-3cc9ab600997.png)

**Comment by jamesdh** [comment]
Awesome!!!

**Comment by ylian** [comment]
The new side-by-side preview is implemented in Quiver 3.0, released today.
