### ISSUE TITLE
Notes are lost on Mac OS with only the labels to be seen.

### ISSUE THREAD

**Issue by vinodMS** [HappenApps/Quiver#1300]
I didn't do anything special. No Mac OS update nor did I update the application. I use the application every day and found it completely empty when I opened it this morning.
<img width="477" alt="Screenshot 2019-04-15 at 20 56 48" src="https://user-images.githubusercontent.com/2227036/56158029-3db35300-5fc1-11e9-975b-5c026418897b.png">

Mac OS: 10.14.3
Quiver: 2.3.4

**Comment by ylian** [comment]
Please reset the cache files: 

1. Take note of your library location (Preferences > Sync > Library Location).
2. Close Quiver. Delete the cache file and the search index file:
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/cache.db
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/index-v2.dat
3. Double click on your library to open Quiver again.

I am fixing this issue right now.

**Comment by vinodMS** [comment]
Oh man, thanks a lot. I got them back, was afraid I lost them forever.
