### ISSUE TITLE
Screenshots on clipboard taken on retina screen are not retina aware in text field

### ISSUE THREAD

**Issue by cheics** [HappenApps/Quiver#132]
When taking a screenshot and bringing the image into Quiver, if you're on a Retina MBP, the image ends up HUGE since the application is not aware that the screenshot was taken on a retina screen.

Some apps, like Bohemian Sketch - are retina aware on screenshots and will size them appropriately when pasted into the canvas. The below example is two partial screenshots taken with Cmd-Cntrl-Shift-4 to the clipboard of the menu bar, one on a retina screen and the other on my non-retina second screen. These screenshots were pasted into Bohemian Sketch from the clipboard and the size was maintained.

![image](https://cloud.githubusercontent.com/assets/904633/8235839/5cc55034-15b2-11e5-902b-5a9f617bf271.png)

**Comment by ylian** [comment]
Good find. Will look for a fix.

**Comment by ekinsenturk** [comment]
I had the same issue today, while copy pasting a screenshot of a window (running on Retina MBP). Looking forward to a fix.

**Comment by danielcompton** [comment]
This happens to me too.

**Comment by ylian** [comment]
Fixed in 3.0.6.
