### ISSUE TITLE
[Feature Request] Refrencing / Hyperlinking to other notes

### ISSUE THREAD

**Issue by adamk22** [HappenApps/Quiver#1331]
Big fan of Quiver here, love the app! I'm not sure if this is a feature that's already on the to-do list, but I would love to see the ability to reference / hyperlink to other notes or specific cells inside a note. As a workaround I make use of specific tags to organize notes about a certain subject, but sometimes I just want to reference or hyperlink a piece of text inside another note rather than copy-pasting it. 

Cheers!

**Comment by olibclarke** [comment]
The first part already exists if I understand your question correctly. If you right click on a note there is an item "Copy Note Link" - you can use this to copy a hyperlink to that note that can be pasted in another note. I agree that the capacity to link to specific positions in a note would be useful - for example, to allow users to create a "table of contents" at the top of a long note.

**Comment by adamk22** [comment]
@olibclarke Totally overlooked this feature, thank you so much! But indeed, the possibility to link to specific cells within the same or other documents would be an awesome additional powerfeature.
