### ISSUE TITLE
Text not appearing in code cell

### ISSUE THREAD

**Issue by WelshWizzard** [HappenApps/Quiver#1342]
Can edit in text cell OK, but not code cell. 

When attempting to type into code cell what is typed does not appear in editor window, but does in preview window.  For text to appear in code cell have to select a different snippet and then select original.

**Comment by ylian** [comment]
Likely an issue with custom css or theme. Please reset the settings (Preferences > Advanced > Restore Defaults).

**Comment by WelshWizzard** [comment]
Restarted app and it started working.
