### ISSUE TITLE
Cannot open library from Dropbox; Open Another Library button missing

### ISSUE THREAD

**Issue by sixcupsofcoffee** [HappenApps/Quiver#1343]
I just got a new machine, and wanted to sync my library, which already exists on Dropbox. However, on the new machine, with a new download of Quiver, there is no button to Open Another Library.

**Comment by ylian** [comment]
File Menu > Open Library

**Comment by sixcupsofcoffee** [comment]
Great. Thanks. You might consider updating the documentation.
