### ISSUE TITLE
cursor is n spaces right of actual cursor

### ISSUE THREAD

**Issue by samuko** [HappenApps/Quiver#1351]
Mac OS Mojave 10.14.5 .  When I edit a code cell the edits take place the number of characters that exist (n) n spaces to the left of my flashing cursor symbol. It has been doing it for a while and I've had to stop using Quiver. 

i.e. If there are 10 characters on a line, my flashing cursor is 10 spaces to the right of the last character typed. The more I type the greater the gap. If I start deleting on a line that has 10 characters, the deletes take place 10 characters to the left of my flashing cursor.  

This only happens in a Code Cell. Any type Code Cell. C#, Python, C++ etc.

**Comment by ylian** [comment]
This happens when you use a variable-width font in the code cell. Switching back to a fixed-width font in your custom css will fix the issue.

A new editor (for code cells and Markdown cells) is currently in development (80% complete as of now). The new editor will support variable-width fonts.

**Comment by samuko** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Thanks for the quick reply!                                                                                                                                               Sent from my BlackBerry - the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: August 24, 2019 5:05 PMTo: Quiver@noreply.github.comReply-to: reply@reply.github.comCc: sam.kohler@cru.org; author@noreply.github.comSubject: Re: [HappenApps/Quiver] cursor is n spaces right of actual cursor (#1351)  This happens when you use a variable-width font in the code cell. Switching back to a fixed-width font in your custom css will fix the issue.
A new editor (for code cells and Markdown cells) is currently in development (80% complete as of now).

**Comment by samuko** [comment]
Since this is to be addressed in future release I'll close this. 
The workaround you gave above worked. 
Thanks.
