### ISSUE TITLE
Scrolling in side-by-side view in Quiver 2.2b36

### ISSUE THREAD

**Issue by cheics** [HappenApps/Quiver#136]
It would be super handy if there was a switch or something to approximately synchronize the scrolling of the editing and preview panels. Something like keeping cell at the top of the window similar among both panels.

**Comment by ylian** [comment]
Absolutely. That's a major piece before I can release the next update.

**Comment by ylian** [comment]
Implemented in Quiver 3.0 beta 3: https://github.com/HappenApps/Quiver/issues/162
