### ISSUE TITLE
[bug]3.2.6 scroll sync does not work on MacOS 10.15 Catalina

### ISSUE THREAD

**Issue by hemisu** [HappenApps/Quiver#1362]
scroll sync does not work rightly :D

**Comment by ylian** [comment]
Please check if you have turned it on: View Menu > Note View > Scroll Sync.

**Comment by hemisu** [comment]
I checked but it doest

**Comment by ylian** [comment]
Okay, I will install Catalina and try.

**Comment by hemisu** [comment]
thank you

**Comment by ylian** [comment]
Confirmed. Thanks for the report. I will make sure it's fixed before the official release.

**Comment by pralayb007** [comment]
Thanks ylian. Well, when is the next official release?! It has been a while that we last heard that the new UI is 80% complete - do you have an ETA in sight?

**Comment by ylian** [comment]
@pralayb007 The UI redesign/rewrite project is going on well. The current timeline is a huge release (Quiver 4.0) by the end of October.

@hemisu I already have a fix for this scroll sync bug on Catalina. I will push out a small update (3.2.7) tomorrow.

**Comment by hemisu** [comment]
excited!

**Comment by ylian** [comment]
Fixed in 3.2.7.
