### ISSUE TITLE
Unable to type in any cell except Text cell

### ISSUE THREAD

**Issue by jlcalbre** [HappenApps/Quiver#1365]
When I try to use any cell except the text cell, I am unable to type anything, select any text, copy/paste, or do anything else.  The cursor just goes to the beginning of the cell and flashes.

**Comment by ylian** [comment]
Likely an issue with theme or custom css. Please reset to the default settings (Preferences > Advanced > Restore Defaults).

**Comment by scottparish** [comment]
Same issue here...I just installed the app and have not made any changes to it. What is happening is any cell, but text cells, does not show what is being typed. if you create a markdown cell, for example, it will not show you typing in it...but if you convert to a text cell it shows everything you have typed.

**Comment by jlcalbre** [comment]
I did what ylian suggested and it works fine now.

**Comment by scottparish** [comment]
Ah...thanks...really strange, because I just installed the app and it didn't work. But once I restarted the app after doing the Restore defaults it works now. Thanks!
