### ISSUE TITLE
在 inbox 里无法创建新文档

### ISSUE THREAD

**Issue by ghostzhang** [HappenApps/Quiver#1369]
![2019-10-08 20 08 23](https://user-images.githubusercontent.com/194242/66394319-6c0d6a80-ea07-11e9-8cd9-fa21306fbcff.gif)
![image](https://user-images.githubusercontent.com/194242/66394359-821b2b00-ea07-11e9-9236-f55a9e424307.png)

**Comment by ylian** [comment]
Can you check your library file? (Preferences > Sync > Current library location). Right click on the library file, "Show Package Content", and see if Inbox.qvnotebook is there.

**Comment by ghostzhang** [comment]
没有找到 Inbox.qvnotebook 这个文件

**Comment by ghostzhang** [comment]
我新建了quiver文件后把library里的 Inbox.qvnotebook 和 Trash.qvnotebook 复制到原先的library里，重新打开，一切正常。
