### ISSUE TITLE
Anyway to include Link?

### ISSUE THREAD

**Issue by PuffedRiceCrackers** [HappenApps/Quiver#1371]
Hello, 

Is there any way to include a link with custom text like [this](https://www.google.com/search?q=cat+photo&rlz=1C5CHFA_enKR841KR841&oq=cat+photo&aqs=chrome..69i57j0l5.1337j0j7&sourceid=chrome&ie=UTF-8) in a text cell?

Thank you.

**Comment by ylian** [comment]
Yeah, highlight the text and hit "Cmd+K".

**Comment by PuffedRiceCrackers** [comment]
Brilliant!

**Comment by PuffedRiceCrackers** [comment]
> Yeah, highlight the text and hit "Cmd+K".

Brilliant!
