### ISSUE TITLE
Recents contains only the default Quiver tutorial notes

### ISSUE THREAD

**Issue by dkp** [HappenApps/Quiver#1376]
I swear "Recents" used to display my recent notes....but the functionality has been broken for a long time.  Should it work? Or is this a known issue.  If the latter, will you be fixing it any time soon?

Thanks,

Dianne

**Comment by ylian** [comment]
Something is not right with your library. You might want to reset the cache files.

1. Take note of your library location: Preferences > Sync > Library Location.
2. Remove these two files:
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/cache.db
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/index-v2.dat
3. Reopen Quiver. You might be prompted to open your library again. If not, use File Menu > Open Library and select your library file.

This will reset the cache files and fix the issues you described.

**Comment by dkp** [comment]
Aha, Recents and Tags both don't work with "Shared Notebooks", only with Notebooks...

**Comment by dkp** [comment]
How can I store my notebooks in dropbox and have recents and tags?

**Comment by ylian** [comment]
I see. I am aware that recents and tags don't include notes from "share notebooks". It was a design change in 3.2 but a lot of users didn't like it. I will revert the behavior in the next update.

**Comment by dkp** [comment]
Thanks,  I didn't know what was going on. I'm just sharing with myself through dropbox.

**Comment by ylian** [comment]
You could create a library (File Menu > New Library), put the library on Dropbox. Then create notebooks in your library, and drag notes  over from shared notebooks.

**Comment by dkp** [comment]
Okay, thanks, I'll try that!

**Comment by ylian** [comment]
Quiver introduced multi-library support in 3.2. That's why the shift away from shared notebooks. Basically you can create multiple libraries (File Menu > New Library) and have them open at the same time.

For your case, it's easiest just to create a library and put it in Dropbox as I mentioned above. That's the recommended way to sync notes. A synced library has way more organizational abilities (nested notebooks for example) than a shared notebook.

**Comment by dkp** [comment]
It seems to be working on both machines now!  Thank you, thank you!  I should not have suffered so long in silence!

**Comment by ylian** [comment]
@dkp No worries. I have been using the past year to work on rewriting most of Quiver to bring it to the next level (Quiver 4.0). It's almost there so stay tuned.

**Comment by dkp** [comment]
Cool! I've looked at competing tools, but I always come back to quiver.  I'd be happy to do a paid update.  You desrve it.

-Dianne
________________________________
