### ISSUE TITLE
Help on using quiver2html

### ISSUE THREAD

**Issue by PuffedRiceCrackers** [HappenApps/Quiver#1379]
Trying to use the [quiver2html package](https://github.com/HappenApps/quiver2html). Installed version is 0.2.1.

The instruction was as below,
```
quiver2html test.qvnotebook -o output_dir
```
I'd like to know how to set the target quivernotebook file's path.
I've tried to give an absolute path of the target file as below

```
quiver2html /Users/puffedricecracker/Downloads/test.qvnotebook -o /Users/puffedricecracker/Downloads
```
Or run the command on the path that has the target notebook in it

```
pwd
>> /Users/puffedricecracker/Downloads
ls
>> test.qvnotebook

quiver2html test.qvnotebook -o /Users/puffedricecracker/Downloads
```
And yes this doesn't seem like how I use it. I'll really appreciate any help!

**Comment by ylian** [comment]
I haven't touched that package for a while. I just gave it a try and it failed as well. Give me a few minutes and I will get it fixed.

**Comment by ylian** [comment]
@PuffedRiceCrackers Just published v0.3.0 on NPM. Update the package and it should work.

**Comment by PuffedRiceCrackers** [comment]
@ylian Works perfectly now, thank you! 👍🏻👍🏻

**Comment by ghost** [comment]
@ylian Can you update the package so that it works like current export to html feature? There is no ace highlight or indexing in the current package.

**Comment by ylian** [comment]
@Kumgyul These are not trivial tasks. I filed a ticket in the quiver2html repo (https://github.com/HappenApps/quiver2html/issues/4) and will do it later.
