### ISSUE TITLE
Cursor alignment issues when changing the font-family

### ISSUE THREAD

**Issue by escobara** [HappenApps/Quiver#138]
When I change the font-family of in my markdown editor, the text cursor moves out of alignment. 
![screen shot 2015-07-01 at 10 56 00 am](https://cloud.githubusercontent.com/assets/3768562/8457510/c9c568fe-1fdf-11e5-9098-bea7e63d37dd.png)

**Comment by ylian** [comment]
This is a limitation of the Ace editor that Quiver uses for code cells and Markdown cells. Please use equal-width fonts such as Menlo.

**Comment by lastobelus** [comment]
@ylian This also happens with fixed-width fonts if the font-size for headers is different than the body font-size. Is there any chance this could ever work? Using TextMate & Macdown, I've gotten really used to using larger font for headers.

**Comment by ylian** [comment]
I wouldn't say it will never work. But to fix this, someone needs to seriously spend some time on Ace. I will try when my hands are not as full.
