### ISSUE TITLE
Notes GONE

### ISSUE THREAD

**Issue by minhnguyen2013** [HappenApps/Quiver#1387]
Im pretty sure I saved the file. I added a lot of notes to my existing notes  and saved it. I switched to a different notebook. I came back a few days later and everything that I added to my existing note is completely gone. This is the second time I think this happened to me. It is very frustrating to see my notes gone and then I would have to spend so much time trying to remember what I wrote in my notes and rewrite it. Please help me restore my notes.

**Comment by ylian** [comment]
Is your Quiver library on a cloud-synced folder? If yes, which cloud service?

**Comment by minhnguyen2013** [comment]
I have it on OneDrive I believe

**Comment by ylian** [comment]
I think OneDrive syncs note files individually. If you happen to edit the same note on two machines, there could be a conflicted copy generated by OneDrive. You could check that by right clicking on the note in the note list, "Show in Finder", then right click on the .qvnote and "Show Package Contents". There might be a conflicted copy in there.

**Comment by minhnguyen2013** [comment]
I found the content.json on there which contains all the things I added (that does not belong to the old version). Why don't I see this in my quiver notebook but only see the old version in my notebook. And why don't I see the old part of that note on OneDrive but only on my quiver notebook? Also, how do I get this into my quiver notebook and prevent this from happening in the future?

**Comment by ylian** [comment]
Is the "content.json" file named differently? For example, "content (conflicted copy).json"?

If not, please show me screenshots of the directory content of the note . That will help me figure out what's going on.

**Comment by minhnguyen2013** [comment]
No the content.json is named normally.
<img width="1260" alt="Screen Shot 2019-11-03 at 2 37 41 PM" src="https://user-images.githubusercontent.com/56754867/68093156-83454980-fe47-11e9-93c0-14cc47cb6ead.png">

**Comment by minhnguyen2013** [comment]
I figured it out. I moved the library to a repository folder thinking that it would move, but it simply copied the library instead. I edited on the original library but was looking at the library in the repository. Therefore, two different versions. I deleted the original library and now am using only the repository one. Thanks for the help.
