### ISSUE TITLE
Frustrations and concerns

### ISSUE THREAD

**Issue by pralayb007** [HappenApps/Quiver#1391]
Yilan, 

Fellow developer here and fully cognizant of the fact that estimating software is super hard. Also, a big fan and a loyal follower of your app over the years who cannot help but vent out some concerns that I have. This is not meant to discourage you but I think you "really" should be aware of a few things.

1. **Writing experience**  Writing experience on Quiver is dismal to say the least. Are you cognizant of the fact that note taking has come a long way since you first launched the app. Have you used other apps such as Bear, Typora, iA Writer, Ulysses and the likes? If not, I recommend you do so. Taking notes on them is aesthetically pleasing and it is a joy to write and read notes on them. Can Quiver meet the bar, if not exceed? Using Quiver feels as if I am writing into a prehistoric windows-based app and it does not need to be that way. I am looking forward to your new release - which according to you is on-track for Nov end and I am hoping that there are significant revamps on the look and feel of the app. 
2. **Lack of essentials** An exhaustive list of what is lacking would be endless but let me talk about a few basics - looking up a search keyword does not highlight the text itself - I mean really? There is no way to select multiple cells in a note, selection of discontinuous cells is virtually impossible, there seems to be no way to merge cells, let aside merge multiple notes, no support for TOC, no way to quickly organize things (see Bear) etc etc etc. Do you not see such features as basic necessities of an app that you are offering? Have you ever consulted a product manager to obtain some feedback on your app? Heck, have you atleast consulted a UX/UI someone to assess the usability of your app? It feels wrong holding your customer base at ransom saying that these features are "coming soon". This concerns me because it almost feels like there is a lack of foresight into doing things and am not sure how would you really scale overtime. How does it feel to see guys asking for progress on issues that are opened since 2016? How do you sleep at night with such gory misses in a product that you are offering with such a large customer base? 
3. **A companion iOS/mobile app** Yet again, it takes you multiple years to hash out one. I am sympathetic towards you because I presume that you probably are the only developer on this and you probably have a full time job. But do you reckon the fact that **there is just massive delay** is pushing things out. Goddamn every app out there has a companion mobile app but Quiver's remains a read-only piece of crap for years together now. Please understand that while this may be a side-gig for you, we - your customers trust your app for taking and retaining our notes. Do you want us to maintain that trust or if not, can you please be explicit in letting us know  if this software is pretty much going to see improvements at this snail-pace forever even in the future? 

This list of deficiencies , I can bet, can go 20X the size it is now if someone were to jot down all of the pain points but I will stop with my rant here now. I am sorry for all this Yilang - but I couldn't help but post this. 

Best of luck to you. I am out.

**Comment by ylian** [comment]
I fully understand your frustration. I have certainly underestimated the scope of work and oftentimes took on too many things at once. I am still working on this at this very moment, and I hope to finish all the big pieces I have been working on in the past year. Afterwards, small improvements would be easier for me to handle and the progress will be faster.

**Comment by ijoseph** [comment]
While I somewhat agree with the content of OP’s criticism, the level of rudeness and personal attacks (“How do you sleep at night?”) is such that I’d at least personally find it difficult to extract anything constructive from it.

**Comment by ylian** [comment]
I will close and lock this conversation since I am fully aware that frustration among Quiver users will only grow until I push out some significant update. The first such update will be Quiver for iOS 2.0. I need to focus and get it done.
