### ISSUE TITLE
Dragging image from Safari into Quiver inserts broken image

### ISSUE THREAD

**Issue by lilyball** [HappenApps/Quiver#140]
If I drag an image from Safari into a Quiver cell, it tries to insert an image, but shows the little broken image indicator instead of the image I dragged in. I need to drag the image to my desktop first, and then drag it into Quiver, to make it work.

**Comment by ylian** [comment]
Supposed to work. Will investigate.

**Comment by ylian** [comment]
Pretty sure this is fixed in Quiver 3.0. In the previous version of Quiver, certain image types were not handled properly, causing the little broken image indicator to show. I am sure this is fixed now.
