### ISSUE TITLE
Cmd-click on notebook deselects it but doesn't update the UI

### ISSUE THREAD

**Issue by lilyball** [HappenApps/Quiver#141]
If I cmd-click on the active notebook, it deselects the notebook, but it doesn't update the rest of the UI. The second table still shows all the notes from that notebook, and the editor pane still shows the selected note. I would have expected it to replace the notes table with a placeholder saying "No Notebook Selected" and to replace the note editor UI with the "No Note Selected" placeholder you see if you select an empty notebook.

![screen shot 2015-07-08 at 12 27 40 pm](https://cloud.githubusercontent.com/assets/714/8579977/bbcc4a82-256c-11e5-80cb-64e2bc77d881.png)

**Comment by ylian** [comment]
Will fix.

**Comment by ylian** [comment]
Fixed in 3.0 beta 4: https://github.com/HappenApps/Quiver/issues/162#issuecomment-142169924

**Comment by lilyball** [comment]
It's buggy. If I cmd-click it deselects properly, but if I then select the same notebook (or Library item) the UI doesn't update. I have to select something different for it to update correctly.

**Comment by ylian** [comment]
Good catch. Fixed again in beta 6: https://github.com/HappenApps/Quiver/issues/162#issuecomment-143357959

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.
