### ISSUE TITLE
[Fixed] Stopped working with macOS 10.15.4 (19E287)

### ISSUE THREAD

**Issue by Schneppi** [HappenApps/Quiver#1427]
Quiver stopped working with macOS 10.15.4 (19E287). All my Code is not visible anymore. Even after a restore. But the JSON Content is still in the qvlibrary File.

<img width="1112" alt="Bildschirmfoto 2020-04-19 um 16 42 01" src="https://user-images.githubusercontent.com/46476806/79690816-b5fbc680-825c-11ea-9fc9-2b5c29f1dfbf.png">

**Comment by ijoseph** [comment]
To clarify, is it just code cells that fail to render, or all types of cells and all content?

**Comment by Schneppi** [comment]
Happened with every Cell Type. I had to remove every trace of your App from my Mac and then reinstalled it. Now it seems to work again.

**Comment by ijoseph** [comment]
I wish it were my app, but I’m just another user that was holding off on upgrading to 10.15.4 in light of this. Glad it’s working again - just kicked off an upgrade to my OS. Will report back whether I also have issues.

**Comment by ijoseph** [comment]
No hiccups here, FWIW. Notes loaded and rendered as usual after upgrading.

**Comment by ijoseph** [comment]
One hypothesis: I noticed that I had my Documents folder symlinked into my Dropbox folder:
```
Documents -> /Users/ijoseph/Dropbox/Documents
```

prior to updating to 10.15.4, but when I updated, it killed that symlink and replaced it with an empty Documents folder. I had some issues with other apps before I realized what had happened.
