### ISSUE TITLE
Free Trial banner overlaps note text, requires Scroll past end

### ISSUE THREAD

**Issue by lilyball** [HappenApps/Quiver#144]
When using the Free Trial, the banner covers up the bottom of the note (assuming the note is not smaller than the window). The only way to read that text is to enable the "Scroll past end" setting. Similarly, the scroll bar actually goes underneath the banner. Instead Quiver should just shrink the editor area so it doesn't go under the banner.

You can easily reproduce with the 2nd tutorial note ("02 - Cell Types"). This is a relatively long note, and with the default settings, in the Free Trial it looks like it ends with

![screen shot 2015-07-08 at 12 33 55 pm](https://cloud.githubusercontent.com/assets/714/8580125/a3c1fef4-256d-11e5-909c-f2d1908d9d09.png)

It's only after enabling "Scroll past end" that you see there's some more text:

![screen shot 2015-07-08 at 12 34 21 pm](https://cloud.githubusercontent.com/assets/714/8580166/e5942cf8-256d-11e5-91d9-db967f2ab86b.png)

Incidentally, I don't think you should simply add padding for the banner. Because the banner overlaps the scroll bar, it's also a usability issue for anyone that wants to be able to drag the scrollbar around. Alternatively, you could add the padding, but shrink the banner so it doesn't overlap the scrollbar (assuming the scrollbar is set to be permanently visible, such as on machines using a mouse).

**Comment by ylian** [comment]
Thanks. The banner will be changed.

**Comment by pentool** [comment]
I thought that was intentional. After all, that's a free version and that is the "limitation" of it... :-)

**Comment by ylian** [comment]
It's kind of intentional. But it seems that most people would be willing to pay, so probably will make it less intrusive.

**Comment by lilyball** [comment]
It did occur to me that it could be somewhat intentional, but it's literally preventing users from reading all of the tutorial (and they may not even know they're missing out). I didn't realize what was going on until I hit one of the later tutorials where it was more obvious (I think "05 - Preview and Presentation", since that ends with a large image).

**Comment by lilyball** [comment]
For the record, I think the banner's size and appearance is quite reasonable. Having it always be there at the bottom of the editor pane is a nice reminder to pay. It just needs to not prevent you from actually reading the entire note.

**Comment by ylian** [comment]
Yep, good point. Absolutely will make it less intrusive.

**Comment by ylian** [comment]
The free trial banner in Quiver 3.0 is much less annoying now:

![screen shot 2015-11-17 at 8 37 41 am](https://cloud.githubusercontent.com/assets/984895/11212858/7e5ea13e-8d06-11e5-8b29-c39d52033eae.png)
