### ISSUE TITLE
Contextual menu on notebooks causes 2 rendering issues

### ISSUE THREAD

**Issue by lilyball** [HappenApps/Quiver#145]
When right-clicking a notebook, there's 2 separate rendering issues it causes.

![screen shot 2015-07-08 at 12 37 22 pm](https://cloud.githubusercontent.com/assets/714/8580227/55d7c72c-256e-11e5-896d-0896aa42dfd3.png) ![screen shot 2015-07-08 at 12 37 33 pm](https://cloud.githubusercontent.com/assets/714/8580231/571576b6-256e-11e5-9596-f01895831d69.png)

The first is fairly obvious. When right-clicking the selected notebook, it causes some weird glitches with the selection highlight. If you right-click a different notebook you can see it's drawing a blue ring around that notebook. The weird glitches with the selected notebook background look like it's trying to do something again with the same path used for the blue ring but screwing it up.

The second is pretty subtle. It's a lot easier to see when actually trying yourself, or if you flip between the two images (instead of viewing them side-by-side). The issue is that when right-clicking, all of the text in the notebooks list becomes slightly thinner. After looking at it closely, I actually suspect that what's going on is that normally it draws the text _twice_, which causes the antialiasing to draw on top of itself and end up darker. But when right-clicking, it only draws the text once. I'm suggesting this because none of the font metrics have changed (indicating there's no actual change in font weight), and because, after playing with this, the text rendering seen when right-clicking actually looks better, as if that's the correct rendering for that font, and the rendering the rest of the time feels too dark.

**Comment by ylian** [comment]
Thanks. This is fixed in the coming update.

**Comment by ylian** [comment]
Fixed in Quiver 3.0 beta 3: https://github.com/HappenApps/Quiver/issues/162
