### ISSUE TITLE
Change css style of only certain cells?

### ISSUE THREAD

**Issue by JRChapman1** [HappenApps/Quiver#1464]
I almost exclusively use LaTeX cells. I'd like to be able to give some of my LaTeX cells a border, but not all of them.

Is this possible?

It would be great if I could define my own cell type, say 'LaTeX2', which had slightly different css associated with it.

**Comment by GastroGeek** [comment]
@JRChapman1

Fire up the 'styles' options for the 'preview' and customize the latex css.

<img width="980" alt="Screenshot 2021-02-07 at 14 42 05" src="https://user-images.githubusercontent.com/16214942/107149824-d2cfca80-6952-11eb-8ddc-47da1a97990d.png">

**Comment by JRChapman1** [comment]
> @JRChapman1
> 
> Fire up the 'styles' options for the 'preview' and customize the latex css.
> 
> <img alt="Screenshot 2021-02-07 at 14 42 05" width="980" src="https://user-images.githubusercontent.com/16214942/107149824-d2cfca80-6952-11eb-8ddc-47da1a97990d.png">

Thanks for the response. However, I was hoping to add a border to only some latex cells, not all latex cells.

**Comment by GastroGeek** [comment]
@JRChapman1

Seems you can just wrap your latex in markdown with HTML? and then style the preview css as desired...


```
<div class="awesome">

$\LARGE\sum_{i=0}^n i^2 = \frac{(n^2+n)(2n+1)}{6}$

</div>
```

**Comment by JRChapman1** [comment]
> @JRChapman1
> 
> Seems you can just wrap your latex in markdown with HTML? and then style the preview css as desired...
> 
> ```
> <div class="awesome">
> 
> $\LARGE\sum_{i=0}^n i^2 = \frac{(n^2+n)(2n+1)}{6}$
> 
> </div>
> ```

Ahh, thanks so much! I never looked at the markdown cells so was unaware that this was an option.
