### ISSUE TITLE
Text cell - cannot change css

### ISSUE THREAD

**Issue by smlombardi** [HappenApps/Quiver#147]
I tried to change text cells to 14px Arial.  No dice.  Code cell formatted as I requested, though.

![screen shot 2015-07-12 at 5 20 47 pm](https://cloud.githubusercontent.com/assets/835148/8640108/980711f8-28ba-11e5-8500-b339b0e222bc.png)

**Comment by ylian** [comment]
Hmm, it looks right. Are you changing the preview or editor? If nothing works, you may reset the settings (Preferences > Advanced > Restore Defaults) and start over again.

**Comment by smlombardi** [comment]
No, the text cell appears to be in Time Roman;

![screen shot 2015-07-12 at 5 20 47 pm](https://cloud.githubusercontent.com/assets/835148/8640312/cf3d31dc-28c1-11e5-8359-d825bf7ed129.png)

**Comment by ylian** [comment]
Yep, I see you still have "Time Roman". Is this text copied in? If that's the case, it might have inline styles. You can select the text and choose "Format > Clear Formatting".

Also, I checked the default font family. It is set as `font-family: Arial, Helvetica, sans-serif;`

This is what I have, by the way.

![image](https://cloud.githubusercontent.com/assets/984895/8640567/366a35e0-28cb-11e5-9e5e-de35caa5a58c.png)

**Comment by smlombardi** [comment]
I did paste it in. But I also tried paste as unformatted and new text block

**Comment by smlombardi** [comment]
Only way I could get it to work was to change the text cell to something else and back

**Comment by ylian** [comment]
I see. Seems that the text had inline styles. "Paste as plain text" is really "Paste and Match Style". I probably will change it so it's not as misleading.

**Comment by ylian** [comment]
Changed to "Paste and Match Style" in Quiver 3.0 beta 3: https://github.com/HappenApps/Quiver/issues/162
