### ISSUE TITLE
Library would not move, now data is misplaced

### ISSUE THREAD

**Issue by smlombardi** [HappenApps/Quiver#148]
I installed the Trial, thought it looked awesome so bought it right away.

I tried "move library" to move it to the "apps" folder I have in dropbox.  Quiver reported there was already a library there -- no idea why, but there was.  I clicked ok, figuring it would overwrite it.

Later on, I installed Quiver on my other MBP and to opened the one on Dropbox.  None of my code was there!  So I returned to MBP#1 to check prefs and no, it had not moved.  So I tried manually opening the one on Dropbox.  It opened.

Of course, my code (I hope) is still in the original library, or I've lost a lot of work.  Where is this library?

**Comment by smlombardi** [comment]
Found the default library:

`'/Users/stevel/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver/Quiver.qvlibrary'`

**Comment by ylian** [comment]
I see. It seems that "move library" didn't go through because a library was in the destination. I will check the code logic for the overwrite. It probably simply bailed out instead of overwriting.
