### ISSUE TITLE
Add Fortran syntax highlighting

### ISSUE THREAD

**Issue by helgee** [HappenApps/Quiver#149]
Fortran is alive and well in scientific computing. Therefore support would be much appreciated.

**Comment by ylian** [comment]
I had some trouble converting the sublime package for Fortran into Ace, but will try again.

**Comment by ylian** [comment]
Coming in 3.0.2.

**Comment by helgee** [comment]
Great! 👍🏼

**Comment by ylian** [comment]
Added in 3.0.2. Released today.
