### ISSUE TITLE
CSS for Markdown preview/export

### ISSUE THREAD

**Issue by nschneid** [HappenApps/Quiver#15]
The current CSS adds a line break but no vertical space between paragraphs, which makes it difficult to read the rendered form of Markdown cells with large amounts of text.

Ideally, it would be nice to be able to edit the CSS of the generated HTML (as is already possible for the cell itself).

**Comment by ylian** [comment]
This will be fixed in the coming update.

**Comment by ylian** [comment]
Implemented in Quiver 2.1. Open preferences. Now you can add custom CSS for the editor, preview, presentation or exported HTML.
