### ISSUE TITLE
parenthesis problem & url in markdown

### ISSUE THREAD

**Issue by tomibennett** [HappenApps/Quiver#155]
First Thanks a lot for this tool which became my only one taking-note tool pretty quickly!

I noticed, often wikipedia's url ended with a right parenthesis: `)`
This parenthesis is interpreted as the end of the markdown's link which is a problem, like showed below
### edition mode

<img width="449" alt="screenshot 2015-08-17 12 55 49" src="https://cloud.githubusercontent.com/assets/3235855/9303577/67dada3c-44df-11e5-817e-f5de903eebc2.png">
### result in preview mode

<img width="114" alt="screenshot 2015-08-17 12 55 56" src="https://cloud.githubusercontent.com/assets/3235855/9303583/700f60d8-44df-11e5-8996-7dc6e81cd0b8.png">
### when link it clicked

<img width="415" alt="screenshot 2015-08-17 12 56 12" src="https://cloud.githubusercontent.com/assets/3235855/9303589/7501ab64-44df-11e5-8349-a98b25aedf95.png">
### what it should have produced

<img width="420" alt="screenshot 2015-08-17 12 56 22" src="https://cloud.githubusercontent.com/assets/3235855/9303590/751942ba-44df-11e5-8648-59a98372c528.png">

I fixed this by replacing my parenthesis by `%29` code, but maybe there's better solution that can be found.
### Also

It would be great to add the anchor system.
### Finally

Would be great to add reference-style links as described [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) to improve much more the reading of our note in edition mode and the link management too.

**Comment by medifle** [comment]
Have the same problem, too.

https://stackedit.io
https://hackmd.io
may be a decent solution for this

**Comment by ylian** [comment]
Fixed in 3.0.4.
