### ISSUE TITLE
Shared notebook data loss when stored on iCloud Drive

### ISSUE THREAD

**Issue by Bouke** [HappenApps/Quiver#156]
My shared notebook stored on iCloud Drive has disappeared. I've run into data corruption before with a shared notebook stored on iCloud Drive before.

**Comment by ylian** [comment]
Send details to my email: support@happenapps.com, including screenshots of whatever you still have. I think iCloud Drive just added the capability to restore files from the web interface, but I haven't tried.

**Comment by ylian** [comment]
Please see https://github.com/HappenApps/Quiver/issues/98 for fixes.
