### ISSUE TITLE
Free trial banner breaks scrolling to bottom of view

### ISSUE THREAD

**Issue by mkhorton** [HappenApps/Quiver#157]
Hi,

I've just been trying out this app but couldn't evaluate it properly because I couldn't actually figure out how to add/edit a new cell because of the free trial banner covering up the bottom part of the view. Decided to get the app anyway, because it seems useful, but it was frustrating I couldn't evaluate it properly first!

**Comment by ylian** [comment]
Yep the banner will be less intrusive in the future.

**Comment by ylian** [comment]
The free trial banner is much less annoying in Quiver 3.0.

![screen shot 2015-11-17 at 8 37 41 am](https://cloud.githubusercontent.com/assets/984895/11221354/b2c3f57e-8d32-11e5-900e-122644a75042.png)
