### ISSUE TITLE
Disclosure arrows pixelated on retina screens

### ISSUE THREAD

**Issue by mkhorton** [HappenApps/Quiver#158]
Disclosure arrows in code cells appear pixelated on retina screens.

**Comment by ylian** [comment]
The little triangle in the gutter? 

![screen shot 2015-08-19 at 1 50 02 pm](https://cloud.githubusercontent.com/assets/984895/9364232/4db8ddfc-4679-11e5-9d55-702c254b392e.png)

**Comment by mkhorton** [comment]
That's exactly it.

**Comment by ylian** [comment]
That came from the Ace editor, but I can fix. Thanks.
