### ISSUE TITLE
Sync with GitHub Gist

### ISSUE THREAD

**Issue by robdecker** [HappenApps/Quiver#159]
Not sure if this is on your radar or not, but the ability to sync with GitHub's [Gist](https://gist.github.com/) service would be awesome. [GistBox](http://www.gistboxapp.com/) is okay, but incorporating Gist syncing to a native desktop app would be so much better.

**Comment by ylian** [comment]
I thought about that, but gist really isn't a good format for mixing content. A note in Quiver is saved as a single JSON file, but when mapped to a gist, it becomes several small files (one file per Quiver cell). And the presentation of these files are not great either. They look like separate files instead a coherent note.

Ideally there should be a way to present a Quiver note on the web the same as how it's presented in the app. This isn't hard but my hands are full at the moment.

**Comment by tuxracer** [comment]
It looks like Github gists can now contain multiple sections similar to the way sections are presented in Quiver https://gist.github.com/tuxracer/8659217

**Comment by ylian** [comment]
@tuxracer GitHub gists have been able to contain multiple files for a long time. But it's geared towards files. The presentation is quite terrible if you mix text with code snippets, IMHO.

**Comment by freemo** [comment]
@ylian  Lack of this feature is the only thing keeping me from using quiver btw. Downloaded it and uninstalled after a few minutes when I learned gist support didnt exist. You almost won me over with the latex support though :(
