### ISSUE TITLE
Syntax highlight not working properly

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#16]
I've created a code cell and pasted some javascript code there.
As you can see from the screenshot the comments colours are kind of confused and can also influence the other lines if there is any quote or tag inside them

![image](https://cloud.githubusercontent.com/assets/412061/5774268/527dbabc-9d6c-11e4-8ff7-754b46b94e32.png)

**Comment by ylian** [comment]
This is working for me. Please double check if you have selected the right language.

**Comment by LeonardoGentile** [comment]
ah! I tough  that syntax was automatically recognised. Ok, by manually setting the language works better!
Any toughs on automatic syntax recognition? 

Thanks for your help

**Comment by ylian** [comment]
I think manual setting is fine for most use cases. Automatic syntax detection doesn't always work, esp. when you support over 120 languages. :)

**Comment by ylian** [comment]
Manual syntax highlighting is fine.
