### ISSUE TITLE
Edition mode: problem writing at the end of the window

### ISSUE THREAD

**Issue by tomibennett** [HappenApps/Quiver#160]
I found myself many times anoying by this thing (I don't know if it a bug or not), that I'll try to explain.

When writing and reaching the end of the window like in the first screenshot. The document is not scrolled down completly. Thus it's hard to see if we're reach the end of the note or if we writing above a paragraph (see below)
<img width="521" alt="screenshot 2015-08-25 20 14 22" src="https://cloud.githubusercontent.com/assets/3235855/9475343/6be34e92-4b66-11e5-9129-ecdce8aa7f5c.png">

Could you manage to always show a view like the screenshot 2 without having to scroll down manually?

<img width="514" alt="screenshot 2015-08-25 20 14 46" src="https://cloud.githubusercontent.com/assets/3235855/9475363/83d63f32-4b66-11e5-91da-4b0e5ba34aa9.png">

Don't hesitate to ask me for more/better explanation
AND THANKS for this amazing tool!

**Comment by ylian** [comment]
Oh I see.  The webview thinks the last line being edited should be at the bottom of the screen.

I don't know a way to change this default behavior, but I suggest you turn on "Scroll past end while editing" in the preferences. It's implemented specifically to solve this issue, although it may not be exactly what you had in mind.

**Comment by tomibennett** [comment]
Yeah it's not completly what I was in mind but much thanks.
Meanwhile, I found a better explanation.
Actually, the problem is not related to line in cells but to cells themselves.

I found out that creating new cells at the end of document will provoke this problem. One of two new created cells will not be displayed completly.

See screenshots:

#### I reach the end of the windows and I'm creating a new cell

## <img width="470" alt="screenshot 2015-08-26 11 13 54" src="https://cloud.githubusercontent.com/assets/3235855/9489767/c43357ea-4be3-11e5-8c55-2cff5daff259.png">

#### I don't touch to the scroll bar and create a new cell

## <img width="465" alt="screenshot 2015-08-26 11 14 15" src="https://cloud.githubusercontent.com/assets/3235855/9489779/ccb073e4-4be3-11e5-8df7-c76263d429ff.png">

### I do it one more time

<img width="463" alt="screenshot 2015-08-26 11 14 38" src="https://cloud.githubusercontent.com/assets/3235855/9489789/d13e028c-4be3-11e5-9a0b-af2e2d1e2402.png">

It's what I couldn't explain earlier. Would you me to edit my original post then?

**Comment by ylian** [comment]
It's the line. It doesn't matter whether you are entering more text in a cell or create a new cell. The webview always scrolls the last line right above the bottom of screen. I don't know how to change this default behavior. The best alternative is to use "scroll past end".

**Comment by tomibennett** [comment]
Ok thanks a lot for quick answer and enlightenments.
