### ISSUE TITLE
Search Notes Keybinding is not working

### ISSUE THREAD

**Issue by marionava** [HappenApps/Quiver#161]
The keybinding cmd+alt+F is not working. Could you fix this please.
<img width="717" alt="captura de pantalla 2015-09-07 a las 15 57 30" src="https://cloud.githubusercontent.com/assets/478018/9722762/675cc6d8-5579-11e5-93db-5f5dd736c07f.png">

**Comment by ylian** [comment]
Works for me. Maybe there is a conflict with keyboard shortcuts in other apps?

**Comment by ylian** [comment]
Seems not to work if the cursor is in a code cell or Markdown cell. Will fix.

**Comment by marionava** [comment]
Thank you ylian. I appreciate it!

**Comment by ylian** [comment]
Fixed in Quiver 3.0 beta: https://github.com/HappenApps/Quiver/issues/162

**Comment by marionava** [comment]
Excellent, I will try the new beta

**Comment by ylian** [comment]
Fixed in Quiver 3.0, released today.
