### ISSUE TITLE
Shortcut: Switch between Notebooks and Tags

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#165]
1) Is there a quick way to focus on the Notebook Sidebar?
2) Related to 1, does it exist a shortcut to change view between Notebooks and Tags? It seems I have to use the mouse in Quiver `3.0b1 (48)`

**Comment by ylian** [comment]
There isn't a shortcut to switch between notebooks and tags. I was contemplating `cmd+7`, `cmd+8`, but wasn't sure. Would that solve 1 as well?

**Comment by LeonardoGentile** [comment]
`7` and `8` seems so far from the cmd on the left that wouldn't be very useful with one hand :)
I think that activating one of those would also focus on the sidebar. If we hit the shortcut for, say, notebook and they are already visible we just focus on them.

Maybe `ctrl+1` and `ctrl+2` if they are not already used. 
Would be nice some feedback from others about what shortcuts to use.

Also I think that having the possibility to customize the shortcut as in #31 via a configuration file would solve this dilemma for everyone, also for #76

**Comment by ylian** [comment]
Added `ctrl+1` and `ctrl+2` shortcuts. Also focus on the sidebar.

**Comment by LeonardoGentile** [comment]
:+1:

**Comment by ylian** [comment]
Implemented in Quiver 3.0, released today.
