### ISSUE TITLE
Tags not highlighted

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#166]
- I hit `cmd-j` and I select a tag 
- the sidebar will show the tag list and focus on the selected tag

PROBLEM1: at the top of the note list there is the title of the tag, example `html`. But it's not specified what I looking at, a list of notes by tag called `html` or a list of notes within the `html` notebook. 
I guess a simple title `tag: html` or `Notebook: html` would be enough.

PROBLEM1a: if the tag is at the bottom of the list, the sidebar won't scroll hence we don't see that it is actually highlighted.

PROBLEM2: If I switch the view from Tags to Notebooks and back, then the tag is not highlighted anymore so (related to 1) I don't know if the list of notes showed is by tag or notebook.

**Comment by ylian** [comment]
All fixed in beta 4: https://github.com/HappenApps/Quiver/issues/162#issuecomment-142169924

**Comment by ylian** [comment]
Fixed in Quiver 3.0, released today.
