### ISSUE TITLE
Dark Theme Tags Field - Occasional Black Font

### ISSUE THREAD

**Issue by jeffkimbrel** [HappenApps/Quiver#167]
In Quiver 3.0 beta, typing in the tags field in dark mode normally works correctly, and has a light colored font that is readable.

However, if you backspace and remove a tag, then start typing in a new tag, the font is black (or very dark), and isn't readable. 

Text is still be entered, and hitting the 'enter' key will add the text as a tag.

Jeff

**Comment by ylian** [comment]
Thanks. Will fix.

**Comment by ylian** [comment]
Fixed in 3.0b3: https://github.com/HappenApps/Quiver/issues/162#issuecomment-141668442
