### ISSUE TITLE
CSS Class for Active Text Cell

### ISSUE THREAD

**Issue by preflight** [HappenApps/Quiver#168]
What class(es) are added to text cells when they become active? I'd like to target them with CSS.

**Comment by ylian** [comment]
Use `.text-cell.inEditMode`.

BTW, You can turn on the web inspector and inspect all the elements and their styles. http://stackoverflow.com/questions/695038/is-there-a-way-to-use-the-webkit-web-inspector-from-a-cocoa-webview-object

**Comment by preflight** [comment]
Excellent - thank you
