### ISSUE TITLE
Preview window triggers Safari to look for "othersite.com"

### ISSUE THREAD

**Issue by ianthekirkland** [HappenApps/Quiver#169]
### Trigger(s)
- Action / Menu Item: Note  >  Show Preview Window  
- Wait: Roughly 5 seconds of having the preview window showing  
### Result(s)
- Safari activates  
- Safari opens a "Failed to open page" tab with the following message:  
  - 'Safari can't open the page "othersite.com" because Safari can't find the server "othersite.com"'  
  - Screenshot: [http://bit.ly/1Q1Ykhy](http://bit.ly/1Q1Ykhy) (see image below)  

![](http://bit.ly/1Q1Ykhy)  
### Notes
- I use customized styles  
- None of my files, styles, or referenced @import CSS files contain "othersite.com"

**Comment by ylian** [comment]
Please send me the note (.qvnote file). Something in the note is sending a request to "othersite.com". My email is support@happenapps.com

**Comment by ylian** [comment]
Closing this since I didn't receive further details. I'm pretty sure there is a hidden link in the note.
