### ISSUE TITLE
Custom css guidelines

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#17]
Hello, nice work with quiver!

I've been trying to customise the css (mostly the colors) for the syntax highlight of a block code but I don't  know which rules to override, is there a guide I missed or overlooked?

thanks

**Comment by ylian** [comment]
That would be difficult to do. There are tons of CSS rules in a code cell, and it's better just to change the theme. If you really want to do this, there are two ways:
(1) The editor is a WebView, so if you turn on the web inspector (http://stackoverflow.com/questions/695038/is-there-a-way-to-use-the-webkit-web-inspector-from-a-cocoa-webview-object), you can see the HTML and play with CSS.  Then you add those customizations to the code cell CSS in preferences.
(2) Create a custom theme for the Ace editor (http://ace.c9.io/), then I may include it in the next version of Quiver.

**Comment by LeonardoGentile** [comment]
Ok thanks, wouldn't be better to let the user 'insert' their own created themes instead?
Of course this is not a priority I guess so I will try with the solution 1

Thanks

**Comment by ylian** [comment]
The problem is the complexity of such an undertaking. There are tons of CSS rules in syntax highlighting. Go to http://ace.c9.io/build/kitchen-sink.html and turn on the web inspector. You'll see what I mean.

**Comment by ylian** [comment]
Close since editing code cell CSS is already possible, but probably not the right thing to do for a user. Changing themes is more practical.
