### ISSUE TITLE
Note List state doesn't track Preview navigation

### ISSUE THREAD

**Issue by lastobelus** [HappenApps/Quiver#171]
(Beta 3.0) #162
## Steps to reproduce:
1. select a note that has a link to another note in the Note List
2. open preview
3. click on link to other link in preview
4. open editor
## Result

The first note will still be selected but not highlighted in the Note List, while the editor shows the second note. If you click on the first note name in the Note List, it will highlight, but the editor still shows the second note. If you click on any other note name in the Note List, the Note List and editor will get back in sync.

**Comment by LeonardoGentile** [comment]
@lastobelus what do you mean by a `link to another note`? You mean a link that you put inside a text cell for example? I'm not aware if we can put a link in the note metadata, is it possible?

**Comment by ylian** [comment]
He meant wiki-style "note links". You can create those in text cells or Markdown cells.

**Comment by lastobelus** [comment]
@LeonardoGentile There are three ways to create a note to a link that I am aware of:
1. With the note active in the editor, the menu `Note > Copy Note Link` with shortcut `ctrl-opt-cmd-C`
2. With the note active in the editor, the shortcut menu on the bottom right has the same menu command
3. Context click on a note in the Note List also has the `Copy Note Link` menu command

Then you have to paste it into the note you are editing. In the preview mode these links navigate between notes as you would expect.

**Comment by lastobelus** [comment]
Actually it seems that after previewing a note, I can also no longer edit it until I navigate away from it and back.

**Comment by ylian** [comment]
The issue with editor not responding to keyboard input is fixed in beta 3: https://github.com/HappenApps/Quiver/issues/162#issuecomment-141668442.

Still working on the main issue so leave this open.

**Comment by ylian** [comment]
Fixed in Quiver 3.0, released today.
