### ISSUE TITLE
Markdown convert line to header bug

### ISSUE THREAD

**Issue by dkarter** [HappenApps/Quiver#177]
Cannot change markdown line to a header using the Ctrl-Shift-1 (Format->Headings->Heading 1).
- When in the middle of the line, Quiver deletes few characters and inserts the pound sign a few characters before the caret. 
- When on the beginning of the line, it erases some of the text and inserts it in the right position.

I'm using vim mode, Quiver 3 beta 2.
Cannot use the header menu items/keyboard mapping in version 2. For some reason they are disabled there.

Image:
![Markdown Bug](http://g.recordit.co/YvxJ3u5HfM.gif)

Suggestion:
I really like how headers are done in the Ulysses app:
![Ulysses Header Inc/Dec](http://g.recordit.co/dVPZTMbKfW.gif)
What do you think?

**Comment by ylian** [comment]
Great idea. That's how headings should be done in Markdown. I will change this in the next beta.

**Comment by ylian** [comment]
Fixed in beta 3: https://github.com/HappenApps/Quiver/issues/162#issuecomment-141668442

**Comment by dkarter** [comment]
Works great! Thanks! :+1:
