### ISSUE TITLE
Code Cell Theme bug when switch between Light and Dark mode

### ISSUE THREAD

**Issue by floq-design** [HappenApps/Quiver#178]
Running Quiver Version 3.0b2 (49) - as the subject says - when you switch from Light to Dark mode (or Dark to Light) the code cell theme is not preserved.
In fact the code cell theme seems to revert to Monokai theme.

**Comment by ylian** [comment]
It's intentional. Some code cell themes don't look great with the dark theme, which may give the user a bad first impression. You can always switch the code cell theme afterwards.

**Comment by floq-design** [comment]
OK if it's automatic, but the theme setting doesn't get updated to reflect the change...

**Comment by ylian** [comment]
@floq-design Thanks. The code theme setting is now correctly updated in beta 3: https://github.com/HappenApps/Quiver/issues/162#issuecomment-141668442
