### ISSUE TITLE
Bug in markdown cell after preview

### ISSUE THREAD

**Issue by binderclip** [HappenApps/Quiver#180]
Steps:
1. ~~In a markdown cell, click **image button** and select an image from local~~
2. **Preview** the note
3. Back to **edit** mode ==> :bug: : can't move the cursor by up, down, left and right key, also can't use some other things. (need input something to get it right) 

PS: If there are someway that I can insert image from clipboard will be better :laughing:

**Comment by ylian** [comment]
Fixed in beta 3: https://github.com/HappenApps/Quiver/issues/162#issuecomment-141668442
