### ISSUE TITLE
Not clear how/what LaTeX should work.

### ISSUE THREAD

**Issue by ghost** [HappenApps/Quiver#185]
Why doesn't this simple code work? See image
<img width="1280" alt="screen shot 2015-09-18 at 14 59 09" src="https://cloud.githubusercontent.com/assets/67455/9961033/2ffdcb6a-5e16-11e5-8cfd-e9473a1b1c3f.png">

I get that it might be difficult for you to know when LaTeX code should be parsed... but this is within a LaTeX cell! Shouldn't it be assumed to be... well... LaTeX?

Why doesn't \begin{enumerate} \end{enumerate} work? What _does_ work? Forgive my rage, but I paid for this app because it clearly said I could write LaTeX in it. Apparently not.

**Comment by ylian** [comment]
There is an example in the tutorial "02 - Cell Types":

```
LaTeX cells make it easy to typeset math equations. For example,

\begin{align}
  \nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} & = \frac{4\pi}{c}\vec{\mathbf{j}} \\
  \nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\
  \nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\
  \nabla \cdot \vec{\mathbf{B}} & = 0
\end{align}

Inline LaTeX is also supported, for example, $x^2$.
```

The reason that you need to use delimiters is that LaTeX is only used to typeset equations. Quiver uses MathJax in LaTeX cells, which doesn't support text-related macros.
