### ISSUE TITLE
Small UI bug

### ISSUE THREAD

**Issue by binderclip** [HappenApps/Quiver#188]
![1.png](http://7ktslh.com1.z0.glb.clouddn.com/imgs/2015-09-21/1.png)

![2.png](http://7ktslh.com1.z0.glb.clouddn.com/imgs/2015-09-21/2.png)

![3.png](http://7ktslh.com1.z0.glb.clouddn.com/imgs/2015-09-21/3.png)

bug:

![4.png](http://7ktslh.com1.z0.glb.clouddn.com/imgs/2015-09-21/4.png)

should be:

![5.png](http://7ktslh.com1.z0.glb.clouddn.com/imgs/2015-09-21/5.png)

**Comment by ylian** [comment]
I can't reproduce. Are you running beta 3? on El Capitan? Please send me the exact sequence of actions to reproduce this issue.

**Comment by ylian** [comment]
You must be running beta 2, :)

Please try beta 3: https://github.com/HappenApps/Quiver/issues/162#issuecomment-141668442

**Comment by binderclip** [comment]
OK! Go to download beta 3 now :D

**Comment by binderclip** [comment]
Beta 3 is OK!
