### ISSUE TITLE
Search InputView on search popup can't input after click 'Full-Text Search in All Notes' label

### ISSUE THREAD

**Issue by binderclip** [HappenApps/Quiver#189]
![search-pop-up](https://cloud.githubusercontent.com/assets/8187479/10010810/32ef27dc-6123-11e5-8b42-94c118fa1e30.png)
1. click the magnifying glass to let the search view popup
2. can input things to inputview
3. click the 'Full-Text Search in All Notes' label
4. try to click input view to go on input but no response

**Comment by binderclip** [comment]
Beta 3 & EI Capitan

**Comment by binderclip** [comment]
PS. Where is the 'Search within a notebook'? Don't know how to do that.

![screen shot 2015-09-22 at 12 20 38](https://cloud.githubusercontent.com/assets/8187479/10010895/848c4808-6124-11e5-8504-e7ba8afc8862.png)

**Comment by binderclip** [comment]
10.11.1 is OK, maybe the EI Capitan 10.11's bug.

**Comment by ylian** [comment]
I see. That's good to know.

Search within a notebook:

![image](https://cloud.githubusercontent.com/assets/984895/10016407/bdfcb8f0-60f4-11e5-9c39-b25583c9e6b7.png)

**Comment by ylian** [comment]
It's the same full-text search, just filtered to the current note list. This is better and more flexible than choosing notebook in the search view. In the future you may be able to select multiple notebooks, and search within several notebooks this way.

**Comment by ylian** [comment]
BTW, beta 4 is out: https://github.com/HappenApps/Quiver/issues/162#issuecomment-142169924
