### ISSUE TITLE
maybe an issue with Dropbox sync

### ISSUE THREAD

**Issue by binderclip** [HappenApps/Quiver#193]
![](http://7ktslh.com1.z0.glb.clouddn.com/imgs/2015-09-23/quiver-issue.png)

When using Dropbox, it is easy to appear this when Duplicate note. Don't appear when pause syncing.

Don't know if an issue.

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.

**Comment by binderclip** [comment]
Haaaaaappy!
