### ISSUE TITLE
Tag duplication issue (Quiver 3 beta 6)

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#194]
Hi,

There's an issue with tags being duplicated after they get renamed. Also, once you delete the duplicated tag, and create another tag, then rename that tag as well, the previously deleted tag reappears.

STEPS:
1. Make sure all three panes are being displayed (this is probably not a requirement, but I'm going to list everything the way I have it: View > Main Layout > Three Panes). Also make sure the 'Notebooks' pane is showing.
2. Create a new note by pressing the plus (+) icon.
3. Create a new code cell for this note an write something into the cell.
4. Assign a new tag to the note. For the sake of this example, I call it 'TagA' so I can reference this back later. Press ENTER to make sure the tag gets assigned.
5. Switch to the 'Tags' pane to show the list of tags.
6. Rename this new tag (TagA) to something else, say 'junkTag'
7. Switch back to the 'Notebooks' pane and wait a second or two until everything updates.
8. Switch back to the 'Tags' pane again. Now there are two sets of 'junkTag' appeared. One of them has 0 occurrence, the other one has 1 occurrence.
9. Delete the 'junkTag' that has 0 occurrence by right clicking on the tag in the 'Tags' pane and selecting 'Delete Tag'. The other 'junkTag' is still assigned to the note you have created in step 2.
10. Create and assign another new tag for the same note (let's call it 'TagB') and press ENTER to make sure the tag gets assigned.
11. Switch to the 'Notebooks' pane, wait a second or two, then switch back to the 'Tags' pane.
12. Notice the previously deleted 'junkTag' (with 0 occurrences) reappeared!
13. Now repeat from steps 6 but for the new 'TagB'. Notice that now not only 'TagB' will be duplicated and will reappear even if you delete the one with 0 occurrence, but also the previous 'junkTag' will reappear as well.

OS X 10.10.5
Quiver 3 beta 6 (53)

**Comment by ylian** [comment]
Fixed in Quiver 3.0, released today.
