### ISSUE TITLE
Hiding Title in Preview and export.

### ISSUE THREAD

**Issue by unisu** [HappenApps/Quiver#197]
I don't want to show **Note title and under-line** on Markdown preview, Printing and export document such as PDF, etc.
Actually this issue was solved with your TIP as below on Quiver 2.

> # titlearea .title {
> 
>  font-size: 0px;
> }

But above CSS does not work well on Quiver 3.0b6.
- Note title is hided on Preview but, title under line is still showed.
  ![2015-10-02 10 50 11 am](https://cloud.githubusercontent.com/assets/8086686/10238151/5dea70ec-68f6-11e5-9250-502cd6d0373e.jpg)
  <br>
- Note title and under line is showed when print or export.
  ![2015-10-02 10 51 08 am](https://cloud.githubusercontent.com/assets/8086686/10238155/6596f928-68f6-11e5-9626-0012962586f2.jpg)
- This is the result on **Quiver 2**.
  ![2015-10-02 11 03 13 am](https://cloud.githubusercontent.com/assets/8086686/10238157/6c3172d6-68f6-11e5-86e5-587b3d7e111d.jpg)

Please fix this. Thanks.

**Comment by ylian** [comment]
The underline is the bottom border of `#titlearea`. So you should hide the whole title area like this:

``` css
#titlearea {
  display: none;
}
```

Note that Quiver 3 adds another CSS file for print and export. So you need to add the above snippet to that CSS file as well.
