### ISSUE TITLE
[REQUEST] Option to resize images once inserted

### ISSUE THREAD

**Issue by zachkirsch** [HappenApps/Quiver#199]

**Comment by Strajk** [comment]
Resize just the representation of the image or the image itself?

IMHO it should be just representation, something like this maybe would be helpful 
http://stackoverflow.com/questions/14675913/how-to-change-image-size-markdown

**Comment by zachkirsch** [comment]
Basically sometimes I'll take a screenshot that copies directly to my keyboard, and then paste in Quiver - after which there's no way to resize the image.

**Comment by af7777** [comment]
Same issue

**Comment by MauriceZ** [comment]
This would be very useful

**Comment by ylian** [comment]
I am aware of this issue. For resizing images in a Markdown cell (as in @Strajk 's comment), it should be fairly easy to implement. For resizing images in a text cell (just for display), it would require some UI. Most JavaScript image resizing tools are too complicated. Evernote's image resizing is also too complicated, IMHO. If someone already knows a simple JavaScript-based image resizing tool, let me know.

**Comment by tyyyang** [comment]
Really appreciate it if it could be implemented in future. Resizing snapshot outside the Quiver is so unhandy.

**Comment by hongbo-miao** [comment]
Same here. If add a basic resizing image function like Evernote provided right now, that will be perfect!

**Comment by gratain** [comment]
I can open the image with external app and modify the size of the picture. However, I need to restart Quiver for the picture to appear with new size. Is there anyway to "refresh" the notebook so that the picture will be shown in the new size?

**Comment by YanchunHe** [comment]
sth like this: ![ImageName.png](path-to-image.png =123x123)

**Comment by jkryanchou** [comment]
+1 I am looking forward to the feature very much. Any plan to add the feature?

**Comment by CYCTina** [comment]
+1 happy that I bought Quiver and hope this useful feature can be added soon!

**Comment by ylian** [comment]
Markdown image resizing is implemented in 3.0.6.

Use the following syntax:
```
![alt text](path/image.png =widthxheight)
```

Will track text cell image resizing in another ticket.
