### ISSUE TITLE
Provide nested notebooks functionality

### ISSUE THREAD

**Issue by ecoment** [HappenApps/Quiver#2]
Hi there,

I've just downloaded the trial and well, awesome work! I really like it and I really would like to purchase a full version.

But there is one thing, that currently prevents me from buying quiver: I need nested Notebooks, which seems not possibly within the current version.

So please provide this functionality and I will buy the full version! 

Regards,
Martin

**Comment by ylian** [comment]
I would like to gather some thoughts on this issue.

Should nested notebooks be nested on the file system as well? Or just a visual hierarchy, like groups in Xcode?

**Comment by ylian** [comment]
I guess the current persistence format of notebooks and notes (https://github.com/HappenApps/Quiver/wiki/Quiver-Data-Format) could support nested notebooks. There are still dangling issues like how to display a notebook with both notes and sub-notebooks. If displayed in the sidebar like Finder, the note list column would not make sense. If displayed in the note list column, that column becomes far more complicated.

**Comment by preflight** [comment]
I think nested on the file system would be better because it seems like it would be easier to extract a sub-notebook in an export script. I haven't worked with export scripts myself yet though, so others may be able to weigh in on their experience.

Regarding how to display the nesting structure, I definitely think the way to go is to display Notebooks as a row of tabs near the top of the application window. That means Sub-Notebooks would take over the far left column (where Notebooks are now) and Notes would stay where they are.

Thanks for considering adding nesting -- I think it will add a lot of value.

**Comment by ylian** [comment]
Having nested notebooks on the filesystem seems to be a logical expansion of the current scheme.

If we are going to support nested notebooks, I think we should allow arbitrary depth of nesting. It doesn't make sense to add arbitrary restrictions: if we allow one level of nesting, why not two or three?

In that case, tabs on top won't work. A typical Finder style sidebar will work just fine, and users are familiar with that. So subnotebooks will be listed under the notebook, while notes are in the note list column. This works.

**Comment by preflight** [comment]
Oh that's great - didn't realize that multiple levels of nesting was a possibility. The Finder-style sidebar seems perfect.

**Comment by LeonardoGentile** [comment]
:+1:

**Comment by preflight** [comment]
Just checking to see if the nested notebooks feature is expected in the next release. Quiver is really great - thanks for continuing to work on improvements.

**Comment by ylian** [comment]
Maybe. I just finished redesigning the sidebar, paving the way for implementing nested notebooks. I certainly hope to put nested notebooks in the next release.

![screen shot 2015-05-14 at 10 19 38 am](https://cloud.githubusercontent.com/assets/984895/7633555/cf19fcda-fa22-11e4-9ea2-93a8ee739004.png)

**Comment by preflight** [comment]
Looking great - thanks for the update

**Comment by asafge** [comment]
+1

**Comment by deini** [comment]
+1 <3

**Comment by yaodong** [comment]
:+1:

**Comment by hlissner** [comment]
+1 It's the only thing holding me back from getting Quiver too!

**Comment by yaodong** [comment]
Any updates on this?

**Comment by ylian** [comment]
@yaodong Yes, I think I figured out a good implementation. Come in the next release (3.1, since 3.0.1 is waiting for review).

**Comment by visini** [comment]
Looking forward to the release of 3.1 - this feature would definitely improve my current notebook structure and make the product more suitable for a lot of applications.

**Comment by LeonardoGentile** [comment]
@ylian any news on the date of the release of this feature?
I think it's the most awaited one :)

**Comment by visini** [comment]
I agree, I'm checking almost every week or so if there is an update, the mess from my dozens of notebooks is very annoying - I know of several competing products which offer this feature. Extremely looking forward to this one!

**Comment by pfordyce** [comment]
I would also be very interested in this functionality!  Thank you.

**Comment by zachkirsch** [comment]
Any update on this?

**Comment by visini** [comment]
Can we open a kickstarter campaign for this feature? I'd gladly pay more money for this. On a more serious note, any plans for this feature @ylian ? You'd make us all in here so happy!

**Comment by preflight** [comment]
Agreed - $10 for this app feels like robbery. Perhaps nested notebook functionality could be part of a paid upgrade or premium version.

**Comment by LeonardoGentile** [comment]
@ylian has always been extremely fast in responding to questions and request  except fo this one, I'm not really sure why.. 
If this is not feasible or you are not willing to do it could you please at least tell us? So we will stop bothering you about this topic :) 

The original question was asked on Dec 5, 2014, if you don't answer us we could start worrying that quiver is not being actively developed anymore, and that would be an enormous loss for people like me that really appreciate your product and effort 👍

**Comment by ylian** [comment]
@LeonardoGentile No, I have nothing against this feature request. I need this feature myself.

What happened was that I have made some big changes to my life this year. These changes are important for me personally and also crucial for the long-term development of all my projects.

I would like to ask for everyone's continued support and trust. Quiver still has a long way to go and I won't stop until all is done.

**Comment by LeonardoGentile** [comment]
Thanks for your answer, my full support here 👍

**Comment by xnxky** [comment]
Yeah, please keep us posted on the status :)

Very looking forward to this. Maybe you can have a cap on how many levels are supported, if too many levels is an issue. Ideally, it could be like this:

![image](https://cloud.githubusercontent.com/assets/1526944/17757029/d9cb5c6e-6498-11e6-8fc6-b0cb5732f543.png)

**Comment by zachkirsch** [comment]
The [comment above](https://github.com/HappenApps/Quiver/issues/2#issuecomment-74015355) by @ylian addresses that and says that there is no reason for an arbitrary limit on the depth of nested notebooks. I would bet that the difficulty of implementing this would not be much (if any) easier by setting a cap on the depth.

**Comment by trentjones21** [comment]
Just wanted to throw in my support for this feature.  Absolutely love the way Ulysses handles nested folders.

**Comment by xnxky** [comment]
@ylian Hi, Yaogang, as this is one of most wanted features in quiver, how is the progress on this one? Thanks.

**Comment by ntoombs19** [comment]
I came here to see if this was already a feature request. I'm glad to see that it is and I look forward to when it is released.

**Comment by kimaldis** [comment]
I, and my massive list of disorganised notebooks, would like to add a +1 to the call for nested notebooks to multiple levels.

In the meantime, I'm using link pages to index and keep things slightly less untidy but I wondered if anyone had any better ideas.

**Comment by c-minton** [comment]
I'd like to add my +1 for the nested notes feature as well. This feature is the only thing keeping other note-taking systems competitive and keeping me from committing the $10. I love everything else about this app!

**Comment by Kwadz** [comment]
If there is a controversy about "simple hierarchy" vs "nested notebooks", you can simply offer to enable the latter as an option in the preferences:

[x] Nested notebooks

**Comment by KimMichaelJones** [comment]
adding my +1

**Comment by hsdwayne** [comment]
+1 here too. Great work so far! This is a great app and does everything I wanted OneNote to do.

**Comment by ell46and2** [comment]
+1 Great app. Nesting would make it perfect and is very much needed as I create more notebooks.

**Comment by karstengresch** [comment]
+1 the more I use Quiver (love it a lot!), the more I need more levels of organization beside tags. Would be great if you could make it!

**Comment by jsbeckr** [comment]
+1 Quiver is exactly what I need/want (and actually planned to build). The only necessary thing it lacks is nesting of notebooks.

**Comment by mgkim-woowahan** [comment]
+1 I wanna this feature~!~!

**Comment by mogita** [comment]
I think I need this feature too.

I have several company projects going on, currently each takes a folder, so the folder list just for my company projects is growing large, yet I can't put them into a single "company" folder and use tags to separate them, because there are so many notes for each project, putting all notes together will make the note list meaningless without searching everytime. 

So +1 for the nested folder feature

**Comment by arivogel** [comment]
+1

**Comment by op1490** [comment]
+1 - this is the only thing currently preventing Quiver from being perfect for me

**Comment by evmin** [comment]
+1

**Comment by justnealpatel** [comment]
+1 @ylian do you have an approximate date on when version 3.1 will be released?

**Comment by ylian** [comment]
I have got UI and drag&drop working. Still working on the persistence of the nested structure. Aim to finish this weekend.

**Comment by e1782753** [comment]
Any news on this?

**Comment by ylian** [comment]
@e1782753 Yes almost done.

**Comment by ylian** [comment]
Mostly there. Here is a build you can try:
https://dl.dropboxusercontent.com/u/3445731/Quiver%203.1%20Build%20105.zip

![image](https://user-images.githubusercontent.com/984895/29067156-d7f59c4a-7c31-11e7-87bf-c79e050c90d5.png)


Some final touches and testing then submit.

**Comment by waterdr0p** [comment]
So +1 for the nested folder feature

**Comment by tobiwollender** [comment]
Thanks for the test build! I tried it and found a few missing pieces I think. I can't create a nested notebook via context menu. I always have to create a normal notebook and after that move it into an existing one (but that works without problem). I also  can't move a local notebook into a shared notebook, which I think might be very useful. So in this test build it's not possible to create nested notebooks in a shared notebook. But it already looks very promising!

**Comment by ylian** [comment]
@twllndr Thanks for testing. I am fixing the context menu. Unfortunately this won't work for a shared notebook, because the nested structure is only an illusion backed by a json file inside the library file. The illusion will be broken for a shared notebook.

**Comment by tobiwollender** [comment]
Don't know if I understand this correctly. But does this mean, no nested notebooks at all when using shared notebooks? (I only use shared notebooks at the moment ;) )

**Comment by ylian** [comment]
@twllndr Yes. It's a limitation of this approach.

**Comment by tobiwollender** [comment]
@ylian Ok. Any chance, that this will be added in the future? Would be really helpful for working in teams. Otherwise it's a pita to share dozens of notebooks with coworkers. With "real" nested notebook support you would just have to share the parent notebook, and the rest is automatically synced.

**Comment by justnealpatel** [comment]
Thanks for the test build! @ylian Not sure if you've fixed this yet from the build posted on this issue, but I have to restart in order to delete a nested notebook. I can delete un-nested notebooks with no issue, however. Also, it would be nice to see notebooks with no nested notebooks to have the notebook icon to the left of them. Not sure if it would look weird, but that's just my opinion.

**Comment by cminton-utk** [comment]
@ylian @justnealpatel I've observed this too. I did a little digging, and it seems like the nested notebook is deleted from the file system immediately, but it takes a restart to observe the change in the UI.

**Comment by ylian** [comment]
@justnealpatel @connor-minton Yeah, already fixed this in my local build.

**Comment by justnealpatel** [comment]
@ylian Are you just waiting for Apple to approve the update or are changes still being made to it?

**Comment by ylian** [comment]
@justnealpatel Still have a couple issues found during testing.

**Comment by justnealpatel** [comment]
@ylian What issues are left in your local build pertaining to this feature?

**Comment by ylian** [comment]
@justnealpatel Some issue with syncing the nested structure on two devices.

**Comment by zachkirsch** [comment]
@ylian the dropbox link you posted on 8/7 is no longer valid - is that intentional? Can I download a beta with nested notebook functionality?

**Comment by justnealpatel** [comment]
@ylian any update on this feature?

**Comment by juststevede** [comment]
I also can't wait for this feature. Any update or is it possible to provide another test version? I really would love to have this feature for some current projects. :)

Thanks for your continued efforts!

**Comment by ylian** [comment]
I have a 3.1.0 build that seems to work quite well. Have been testing for a week and if no new bugs are found today, I will submit it tonight.

**Comment by juststevede** [comment]
This is awesome news! Thank you so much!

**Comment by xnxky** [comment]
Amazing !!!!

**Comment by justnealpatel** [comment]
Looks like it's already up on the App Store. Thanks so much!

**Comment by juststevede** [comment]
Awesome, this is a game changer for Quiver! Thanks!

**Comment by LeonardoGentile** [comment]
@ylian 
> Some issue with syncing the nested structure on two devices.

Can you confirm this is fixed? Do we risk to mess up/destroy our valuable notes db?

What happens if a nested structure is created in one device but the other device still uses an old version of quiver that do not provide such functionality? Ka-boom?

**Comment by ylian** [comment]
@LeonardoGentile The nested structure is saved in a single "meta.json" file under the library folder. When you reorder the notebooks, only this "meta.json" file is updated. So your notes and notebooks are safe.

If a nested structure is created on one device, but the other device still uses an old version of Quiver, the second device will see notebooks in a plain list, exactly like in previous versions.

The only thing that doesn't work at the moment is: If you have two devices both running 3.1.0, and synced up using Dropbox, and you are reordering notebooks on both devices *at the same time*, the nested structure may get out of sync (in UI only). You would need to reopen Quiver to see the updated nested structure.

**Comment by xnxky** [comment]
@yilan thanks a lot for adding this feature. That's what I have waiting for for a long time. However, it seems that the only way to add a nested notebook is to create a new one, and drag it to another notebook; Is there any other way to do it like right click, context menu, or things like that?

**Comment by ylian** [comment]
@xnxky I surely can add an option in the context menu, so right clicking on a notebook -> "Create a new Notebook", and it creates a notebook inside. The result is, of course, exactly the same as creating a new notebook, then drag it to another.

**Comment by LeonardoGentile** [comment]
@ylian testing this.
I've notices new Notebooks wether nested or not are not automatically re-ordered alphabetically

**Comment by ylian** [comment]
@LeonardoGentile That's intended. Now it's all manual sorting.

**Comment by LeonardoGentile** [comment]
Eh, don't like it that much :)
Especially when you have almost 100 notebooks. 
This should an option inside the setting, not the only and forced choice.

**Comment by ylian** [comment]
@LeonardoGentile Maybe an option in the context menu (when right clicking on a parent notebook) to "Sort alphabetically".

**Comment by LeonardoGentile** [comment]
@ylian yes, that would good.
Not all the notebooks will be nested so besides on the specific Notebook this should be an option on the main Notebook menu (see pic)

![image](https://user-images.githubusercontent.com/412061/31787628-9e22ed9c-b50c-11e7-8ad8-d05c4ac90d95.png)

When we right click on this there should be an option to sort either cyclically all the notebooks (so first level and nested ones). Or or just the first level notebooks.

In any case this option should be remembered, meaning that new notebooks will automatically be sorted following that option. Specify for each new notebook how it or its children should be sorted is not optimal. 

What do you think?

**Comment by ylian** [comment]
@LeonardoGentile I agree that there should be options to sort alphabetically (either the first level, or recursively) in the context menu when clicking on the Notebooks group.

But I don't think this should be remembered. You create nested notebooks by drag & drop, while drag & drop implicitly implies manual sorting. Imagine drag & drop to reorder some items, only to see them being moved back to alphabetical order because of rule override.

I think having an option in the context menu to sort alphabetically is enough. I can't imagine users creating tons of notebooks all the time.

**Comment by xnxky** [comment]
@ylian Thanks for the reply; The right click does not have the "Create a new Notebook" option for me? Am I missing something? Thanks.

![screen shot 2017-10-19 at 12 03 42 pm](https://user-images.githubusercontent.com/1526944/31789094-ce44463e-b4c5-11e7-8eee-d6bf4337516d.png)

**Comment by ylian** [comment]
@xnxky My bad. I meant that I could add such an option.

**Comment by xnxky** [comment]
Thanks for clarifying. That would be nice !!!

**Comment by op1490** [comment]
I'm unsubscribing from this thread now the functionality has been added. Thank you so much - this is genuinely life changing ! Now I can fully migrate to quiver!

Kind regards,
Oliver

**Comment by ylian** [comment]
I am closing this thread as well. Please open new issues for further improvements of this functionality.

**Comment by KimMichaelJones** [comment]
Thanks for adding this @ylian. I updated my copy and saw this in the release notes. Unfortunately I can't seem to see how/where I do this. I've searched here and the documentation as well and can't seem to find anything that explains how one creates nested notes/notebooks. Help?!

**Comment by ylian** [comment]
@kimaldis In the sidebar, just drag one notebook into another. You probably want to create a few new notebooks as parent notebooks.

**Comment by KimMichaelJones** [comment]
Got it, thanks!
