### ISSUE TITLE
missing syntax highlight for bash

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#20]
Not sure if this was by design or a limitation of `ace` but I can't find the bash language for the code cell

**Comment by ylian** [comment]
Try "Shell".

**Comment by LeonardoGentile** [comment]
:+1:  :D

**Comment by ylian** [comment]
This is renamed to "Bash" in Quiver 2.1. Coming out soon.

**Comment by LeonardoGentile** [comment]
yes, that makes more sense, thanks again!
