### ISSUE TITLE
New update wipes off everything in Quiver library

### ISSUE THREAD

**Issue by muyiibidun** [HappenApps/Quiver#200]
I noticed the latest updates wiped off all my notebooks, tags etc on Quiver. It basically restored the app to default state when I first got it. I moved the library to Google Drive some months ago and it is been fine since. Until today that I tried to use it and everything is gone with no trace of the library file......the Drive app is in good shape all other files and folders are intact, just Quiver is missing.

**Comment by ylian** [comment]
Replied your email. I will help you from there.

**Comment by ylian** [comment]
Just for anyone who might read this thread, the Quiver library file (along with some other deleted files) has been restored with the instructions here: https://support.google.com/a/answer/6052340?hl=en

It might be a Google Drive bug since other files were deleted as well.
