### ISSUE TITLE
Add Syntax Support for JSX

### ISSUE THREAD

**Issue by preflight** [HappenApps/Quiver#201]
Feature request: add code-cell language support for JSX (React): https://facebook.github.io/jsx/

**Comment by preflight** [comment]
Already added :-)

**Comment by ylian** [comment]
Fancy fancy. I would love to play with React soon. Once I push out Quiver 3, I guess.

**Comment by preflight** [comment]
Quiver is amazing, thanks for putting so much time into it. Hard to believe it's the work of one person; I'm routinely impressed by the attention to detail.
