### ISSUE TITLE
Markdown Inline Code Formatting Incorrect (Quiver 3 Beta 8)

### ISSUE THREAD

**Issue by jjanusch** [HappenApps/Quiver#202]
Beta 8 has some formatting issues within inline code blocks.

Here is `$newTag->post_id = $post->id` in Beta 7:

![screen shot 2015-10-16 at 8 20 42 am](https://cloud.githubusercontent.com/assets/3516836/10545701/e5ed4cf6-73de-11e5-96f5-cdaf4a9fae20.png)

And here it is in Beta 8:

![screen shot 2015-10-16 at 8 20 05 am](https://cloud.githubusercontent.com/assets/3516836/10545725/0513558a-73df-11e5-9cfa-768e0ddf8bbb.png)

**Comment by ylian** [comment]
Good find. Will fix.

**Comment by ylian** [comment]
Fixed in beta 9: https://github.com/HappenApps/Quiver/issues/162#issuecomment-149857673
