### ISSUE TITLE
Spacegray Theme

### ISSUE THREAD

**Issue by ylian** [HappenApps/Quiver#205]
From @floq-design: (https://github.com/HappenApps/Quiver/issues/162#issuecomment-149865663)

I've had a go at theming Quiver and found a few areas where I didn't have control. Here's a PDF file indicating the areas:
https://cl.ly/0z3y1z0g2m27

Here's the theme json file for review so you can see for yourself. It's based on the Spacegray theme that comes with Snippetslab app.
https://cl.ly/code/3P3d1h1b192w

**Comment by ylian** [comment]
The checkmark in the notebook picker can be changed now. I fixed in the latest beta.

``` json
  "notebookPicker": {
    "table": {
      "textColor": "#444",
      "selectedTextColor": "#000",
      "iconColor": "#444",
      "selectedIconColor": "#252525",
      "selectedRowBgColor": "#d4d4d4",
      "emphasizedRowBgColor": "#1F6FEB",
      "emptyTextColor": "#7f7f7f"
    }
  }
```

Note the addition of "iconColor" and "selectedIconColor".

**Comment by ylian** [comment]
To change the selected cell outline, add this to the editor css:

``` css
.cell.inEditMode {
  border-color: red;
}
```

**Comment by ylian** [comment]
I will fix the other issues in the next beta.

**Comment by floq-design** [comment]
Awesome. Updated theme file with above solutions integrated:
https://cl.ly/code/290X1V403S2N

**Comment by ylian** [comment]
Awesome. Would you mind publishing the theme file in a GitHub repo and add a commercial-friendly license? Like MIT or BSD. I would like to include it in Quiver if it's okay with you. (once the other issues are fixed, of course).

**Comment by floq-design** [comment]
@ylian

I just tracked down the original author of the Spacegray theme and the license is open:
https://github.com/kkga/spacegray/blob/master/LICENSE

So here's the repo for the Quiver variant:
https://github.com/floq-design/quiver-spacegray-theme

Awaiting for the next beta to push theme updates.

**Comment by ylian** [comment]
Awesome. Appreciate it.

**Comment by ylian** [comment]
I addressed other issues:
- Added `emphasizedTextColor`, `emphasizedTextColor`, `emphasizedIconColor` to all the tables.
- The blue highlight can’t be changed in Yosemite, but it works in all other OS X versions now (including El Capitan). I hard-coded the text colors for Yosemite so they work with the blue highlight regardless of the theme settings.
- I turned off the sidebar translucency for the Light theme. Switching between translucent  and non-translucent sidebars caused weird visual artifacts. Thus the “translucent” field was removed from the theme file.
- Renamed “tokenField” to “tagField” and added a few more keys:

``` json
"tagField": {
  "textColor": "#999",
  "placeholderColor": "#aaa",
  "tag": {
    "textColor": "#000",
    "selectedTextColor": "#fff",
    "backgroundColor": "#cadff3",
    "selectedBackgroundColor": "#6caff1",
    "borderRadius": 4
  }
}
```
- Added “tagField” to the multi-note view as well

``` css
"multiNote": {
  "tagField": {
    "textColor": "#444",
    "placeholderColor": "#b8b8b8",
    "backgroundColor": "#fff",
    "borderColor": "#fff",
    "borderRadius": 4,
    "tag": {
      "textColor": "#000",
      "selectedTextColor": "#fff",
      "backgroundColor": "#cadff3",
      "selectedBackgroundColor": "#6caff1",
      "borderRadius": 4
    }
  }
}
```
- In preview, you can style the tags with CSS. The default CSS styles are:

``` css
#tag-field {
  margin: 8px 2px 10px;
}

#tag-field .tag {
  display: inline-block;
  background: #cadff3;
  border-radius: 4px;
  padding: 1px 8px;
  color: black;
  font-size: 12px;
  margin-right: 10px;
  line-height: 1.4;
}
```

**Comment by ylian** [comment]
I have added the new fields to the theme file and created a pull request in your repo: https://github.com/floq-design/quiver-spacegray-theme/pull/1

**Comment by floq-design** [comment]
Nice work. I've merged, tweaked and pushed!

**Comment by ylian** [comment]
Love it. Those tags look much better now. I will remove a couple unnecessary CSS (since they are in the default already) and change the Markdown cell background color. I think that should wrap it up.

**Comment by floq-design** [comment]
Cool. Thanks very much for including it in the app.. well chuffed!

**Comment by ylian** [comment]
Just sent another pull request with the final cleanup. https://github.com/floq-design/quiver-spacegray-theme/pull/2

Thanks a lot for the gorgeous theme. Lots of people rave about it.
