### ISSUE TITLE
doubleclick in ”Move to Notebook” does not work

### ISSUE THREAD

**Issue by gruenheit** [HappenApps/Quiver#206]
in version 3.0b9 (57) the doubleclick on an item does not trigger the default button in ”Move to Notebook” like in ”Jump to Notebook”

**Comment by ylian** [comment]
Thanks. Will fix.

**Comment by ylian** [comment]
Fixed in beta 10: https://github.com/HappenApps/Quiver/issues/162#issuecomment-150564507
