### ISSUE TITLE
Different notes opening when double clicking empty note list area (3.0b10)

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#211]
When I double click in the empty area in the note list pane, I get a popup window whose contents are randomly different. In some cases the contents of this popup window seems to be the last note I had open, but in some cases I get a brand new, empty note window. Yet other times nothing happens when I double click the notes field.

Here are a few steps you can try in no specific order.
- Select "Inbox" in the sidebar (I have 0 items) then double click in the empty notes list area. You get a new window showing "1 - Getting started." Close the window.
- Look at a couple of tutorial items. Eg select Quiver Tutorial in the sidebar, and select a few lessons. Now go back and select the Inbox, double click again in the notes list. This time, the tutorial item you viewed/selected the list time will open in a new window.
- Create a new notebook. By default it has 0 items. Double click the notes list. You get a new window with the first tutorial item (not the last one you viewed).
- Create a new note in the notebook section you just created, but don't enter anything. Double click the notes list. This time nothing happens. Eg no new window opens up.
- Go back to the tutorial list, select a tutorial, now go back to your newly created notebook. Should have a single item there you created. Do not select it, just double click in the notes list. Now you get a blank, empty note in the new popup window. Close it.
- Select the Trash (zero items). Double click notes list. Nothing happens.
- Go back to your newly created notebook, double click notes list. Nothing. A moment ago I got a new, blank note popped up. Now nothing.

Close Quiver. Re-open it. Go through these steps again in random order.

You can repeat the above list in any order you wish. The point is that double clicking the blank area of the notes list (middle pane) will result in a seemingly random events. Sometimes you get a new window with a blank note; other times you get a window with the previously viewed note; sometimes nothing happens.

Quiver 3.0b10
OS X 10.11.1

**Comment by ylian** [comment]
Great find. Thanks. Fix right away.

**Comment by ylian** [comment]
Fixed in beta 11: https://github.com/HappenApps/Quiver/issues/162#issuecomment-150998697
