### ISSUE TITLE
BUG: Keyboard shortcut "comment" in markdown mode override system wide "Show help" shortcut

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#214]
I'm heavy user of system wide keyboard shortcut to invoke help (and searching + launching commands with just keyboard when I don't remember exact keyboard shortcut), but when I'm in markdown mode, this keyboard shortcut triggers "commenting of selected text"

`cmd` + `shift` + `/` 

<img width="350" alt="screen shot 2015-10-25 at 18 48 29" src="https://cloud.githubusercontent.com/assets/697301/10716967/85c5e302-7b49-11e5-8a04-401d9c763b23.png">

**Comment by ylian** [comment]
I can fix this right away for Markdown cells. How about code cells? Do you think I should keep the current behavior ("commenting of selected text") for code cells?

**Comment by ylian** [comment]
`cmd+shift+/` in code cells creates a comment block. `cmd+/` creates line comments. I think probably it's okay to disable `cmd+shift+/` for all the cell types.

**Comment by Strajk** [comment]
TextMate uses `cmd`+`alt` (instead of shift) + `/` for block comments

<img width="237" alt="screen shot 2015-10-25 at 20 43 07" src="https://cloud.githubusercontent.com/assets/697301/10717473/07889e48-7b59-11e5-8837-ee85810c9b39.png">

Thanks for quick reply!

**Comment by ylian** [comment]
Fixed in beta 11: https://github.com/HappenApps/Quiver/issues/162#issuecomment-150998697

**Comment by Strajk** [comment]
Great! Thanks!
