### ISSUE TITLE
Width of presentation view

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#217]
I was wondering what governs the width of the presentation window? I have attached a screenshot off of my retina MacBook Pro. Some of the lines with the </script> tag wraps around to a new line, even though seemingly there would be enough space if I could just widen the presentation window (or the padding/margin) would be less.

v3.0b11
OS X 10.10.5

<img width="1280" alt="screen shot 2015-10-26 at 2 30 24 pm" src="https://cloud.githubusercontent.com/assets/1972916/10743290/641d0bbc-7bef-11e5-8a3c-4a1c7757673c.png">

**Comment by ylian** [comment]
It's controlled by css. Go to Preferences > Styles > Presentation Edit CSS, add:

``` css
body {
  width: 80%;
}
```

The default width is set to 70% of screen.

**Comment by pentool** [comment]
GREAT! Thanks!

**Comment by die4live** [comment]
@ylian 

hi, I'm adjusting presentation CSS, and wonder is there more info about it or some default template. For example I want to decrease margin from title to top, but the `margin-top` seems not work. And not sure if the title of note belongs to `h2` class, as I tried some modification but nothing works.
