### ISSUE TITLE
Replacing with a space in Vim mode inserts the word 'space'

### ISSUE THREAD

**Issue by dhda** [HappenApps/Quiver#219]
When Vim mode is enabled, when you attempt to replace the character under the cursor with a space ('r '), the next five characters are instead replaced by the character 'space'. This happens in both Markdown cells and Code cells.

I'm running beta 12.

**Comment by ylian** [comment]
That's a hilarious bug. Thanks.

It seems that the latest Ace editor has fixed the bug. I will update Ace included in Quiver sometime soon, but certainly after Quiver 3. (Updating Ace breaks a lot of things.)

**Comment by ylian** [comment]
Fixed in 3.0.2.
