### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#222]
I'm using iCloud Drive for syncing. I noticed that on the iCloud drive it is indicated that my library is 572KB. When I export all my notes (Select All > Export Notes > As Plain Text), they are only 21KB total. So not sure where the other 501 KB is coming from. Does the library store other settings besides the notes?

**Comment by ylian** [comment]
You might have images in your notes. Those are saved inside the note file package, under the `resources` folder. If you are using the latest beta, you might have file attachments saved in that folder as well.

Also, text cells save content as HTML, which can be significantly bigger than exported plain text.

You can right click the Quiver library file and choose "Show Package Contents". Check the size of the notebooks. Then right click on a notebook and "Show Package Contents" to see the size of the notes. Right click on the note again and "Show Package Contents" and you'll see the content files and maybe a `resources` folder. (The resource folder is only created if you have included images in the note.)

An easier way to navigate is to use the Terminal. In the Terminal, the Quiver library, notebook and notes are just folders.

**Comment by pentool** [comment]
Got it. Thank you. This solved the issue. I don't have images and attachments, but the Quiver Tutorial is included in my 32 notes, and that took up the 500+ size since the tutorial does have a few images.
