### ISSUE TITLE
Adopt a more standard shortcut for paste without formatting

### ISSUE THREAD

**Issue by skypanther** [HappenApps/Quiver#223]
A lot of Mac apps use Command + Shift + Option + V to paste and match formatting. Google's web apps (Gmail, Docs, etc.) use Command + Shift + V (maybe that's a webapp standard?). Quiver uses Command + Option + V. I have to remember & try three paste key combinations to get unformatted text. Could you adopt one of the more common key combinations?

**Comment by ylian** [comment]
Good point. I will change to Cmd+Shift+Option+V.

**Comment by ylian** [comment]
Fixed in beta 13: https://github.com/HappenApps/Quiver/issues/162#issuecomment-152359388
