### ISSUE TITLE
Finder Links in Markdown Cells

### ISSUE THREAD

**Issue by jeffkimbrel** [HappenApps/Quiver#224]
Hello,

Quiver 3 (not sure which beta version) changed the copy/paste behavior for links in markdown cells.

What used to happen:
In finder, find the file you want to link to, and hit command-C.
In Quiver, type `[filename]( 'command-V' )`, and the full path would paste along with the file name, creating the full link.

What happens now:
Upon typing `[filename]( 'command-V' )`, whether selecting "link" or "copy" form the dialog box, only the filename is pasted, without the full path. This effectively doesn't create a link.

Can we have the old behavior back for markdown cells, or perhaps a third option in the dialog for pasting the full path?

Thanks,

Jeff

**Comment by ylian** [comment]
Great find. It's broken when I implemented file attachments. Will fix right away.

**Comment by jeffkimbrel** [comment]
You're the best! Thanks!

I suppose the dialog box isn't needed at all for markdown cells, since it isn't capable of actually storing any file attachments, correct? Pasting can really only add text.

**Comment by ylian** [comment]
Actually it does copy the file. Give it a try and then right click on the note, "Show in Finder", then right click, "Show Package Contents". You will see the file copied to the resource folder.

**Comment by ylian** [comment]
The reason it works is that `NSPasteboard` stores several data types, the filename as text, file URL as URL, etc. Quiver finds the file URL and copies it to the resources folder.

**Comment by ylian** [comment]
This does create a problem with removing resources. I need to rename the file path to `quiver-file-url/...` if it's copied. So if you delete the file path from the note, Quiver will be able to delete the corresponding file. I will fix that.

**Comment by jeffkimbrel** [comment]
It feels like in the past it doesn't copy to the resources folder. For example, if I link to an image with the `![]()` syntax, due to sandboxing, I can't see the file until I give Quiver permissions to see inside the folder.

**Comment by jeffkimbrel** [comment]
But I see, you are right, it does copy to the resources. So why does it still show up as a broken image until I give quiver access to the folder the original file was in?

**Comment by ylian** [comment]
Images are treated differently from other file types. Now that file attachment is implemented, I may need to rethink images as well. Stay tuned. I will sort this out in the next beta.

**Comment by ylian** [comment]
Fixed in beta 14: https://github.com/HappenApps/Quiver/issues/162#issuecomment-152673670

You no longer need to type `[filename]( 'command-V' )`. Just copy the file, and paste into the Markdown cell. It will automatically create the Markdown file link.

Files can be either copied or linked. Images are always copied.

**Comment by jeffkimbrel** [comment]
Thanks for the fix... I like the way this works now!

**Comment by ylian** [comment]
This is now implemented in Quiver 3.0, released today.

**Comment by jeffkimbrel** [comment]
Starting in 3.0.7, this behavior has changed in that PDFs now are being moved to the Quiver library, instead of being treated as files and having links generated. 

If in Finder and copying a .pdf, pasting in a markdown cell used to add a link as in [name](name.pdf). Now, it moves it to the library as ![name](quiver-image-url/5409EF7DC95F6171857AAA1033C15120 =612x792). 

The old method is still preferable, as in not having anything copied to the Quiver library, or to be given the option to copy or link, which is the dialog box that pops up with other files.

**Comment by ylian** [comment]
Aware of the issue. Will fix.
