### ISSUE TITLE
Assigning existing tags: bug or by design?

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#225]
I've noticed that I am not able to assign already existing tags to notes, unless I re-type the whole tag.
1. Let's say I have 2 notes, A and B. Note A has a tag assigned to it, called "WordPress".
2. I select note B and want to assign the tag "WordPress" to it (just like note A has).
3. When I start typing "W..." into the tag field, I was anticipating to get maybe a popup list of some sort listing the already existing tags I can just select from. But regardless, I will have to type in the whole tag name again because the field doesn't recognize that I already have a "WordPress" tag.
4. In addition, if I mis-spell "WordPress" (while adding it to note B) to, say "wordpress", now I have two wordpress tags. One with camel case, the other is lower case.

Would be nice to get a popup selection of the already existing tags when I start typing in the tag field, or, another option, to simply be able to drag-and-drop tags onto notes.

Or is there something I may have missed regarding this issue? Maybe a workaround? Don't know if this is a bug, or this issue has not been address yet.

v3.0b14
OS X 10.10.5

**Comment by pentool** [comment]
Wait! Now it's doing it. I had to quit and restart Quiver and now I am getting the popups for the tags as I type them in.

I was playing with the tags, adding, deleting, renaming, etc them, and as I was doing it, at one point the popup just stopped showing up as I was trying to add already existing tags to a note. Restarting Quiver seems to solve it. But maybe there's some issue lurking in the background why the tag popup stopped working. Will play around with it some more.

**Comment by ylian** [comment]
Right, it should work, but you might have triggered an exception.

Can you check your console log? (Open the Console app, search for "Quiver") Check if there is an exception or crash in the log.

**Comment by pentool** [comment]
Well, it seems it must've been a hiccup. I was not able to reproduce it so far. I don't have anything in the Console either that would point to this issue. The only thing shows up for Quiver is:

"10/30/15 8:09:21.148 AM Quiver[752]: CoreText CopyFontsForRequest received mig IPC error (FFFFFFFFFFFFFECC) from font server"

But that's for a completely different timeframe.

**Comment by ylian** [comment]
Thanks. The font warning is harmless. I will close this but feel free to reopen if you run into it again.
