### ISSUE TITLE
Help! Quiver crashed soon after a save, but all my work seems to be gone!

### ISSUE THREAD

**Issue by CandaceSoVan** [HappenApps/Quiver#227]
I spent several hours transferring notes into Quiver (I really enjoyed using it). I had done several Saves and one backup. I was looking at the tags I created and saw that I had one tag that was "collection" (used in two places) and one that was "collections" (used in one place). So I changed the one tag from "collections" to "collection." Boom, the application locked up tighter than a drum. I did a Force Quit, and when I tried reopening the app, it seemed to contain zero data. Didn't even have the tutorial notebook. Empty. I see that my Quiver.qvlibrary is 792 bytes in size. I had placed it in my Dropbox, and when I went to the Dropbox site, it was represented as a folder. But it's not like Dropbox renamed it or anything. Is my work just gone? BTW, the Preferences I set are still there -- just not the data. I really cannot use the app if it's going to eat my work like that. The whole idea of a notebook is that it's a place to store information. Do I have any recourse or have I lost all my work?

**Comment by CandaceSoVan** [comment]
Update: I was able to get the material deleted in the crash back by using the Dropbox Event timeline. Still, a crash should not have deleted all those notes. This is a pretty serious bug in the program.

**Comment by ylian** [comment]
That's quite strange. It should not delete any files even if it crashed.

A few things that can help me debug:
1. Which version of Quiver are you using?
2. You mentioned that you did a backup. Did you backup after you have moved your library to Dropbox? There was a bug in Quiver 2.1.2 that might erase your library, if the backup destination is the same as your current library location.

Appreciate your help.

**Comment by CandaceSoVan** [comment]
Running latest version for of Mac App store. I think what I did exactly matches your case #2. Won't do  that again! <Grin>

---Sent from Boxer | http://getboxer.com

On November 4, 2015 at 6:59:23 AM EST, Yaogang Lian notifications@github.com wrote:That's quite strange. It should not delete any files even if it crashed.  A few things that can help me debug: 1. Which version of Quiver are you using? 2. You mentioned that you did a backup. Did you backup after you have moved your library to Dropbox? There was a bug in Quiver 2.1.2 that might erase your library, if the backup destination is the same as your current library location.  Appreciate your help.  —Reply to this email directly or view it on GitHub.

**Comment by ylian** [comment]
Yep, that's the culprit. It was a silly programming mistake I made in Quiver 2.1.2. Quiver 3.0 is waiting for review and should come out in a few days.
