### ISSUE TITLE
Feature request: Implement Vim-Surround

### ISSUE THREAD

**Issue by dkarter** [HappenApps/Quiver#229]
Vim-Surround allows surrounding text-objects in vim with a closure (parens, quotes, etc..)
Although it is technically a vim plugin, it is considered to be essential in vim. 
It is sorely missed in Quiver. 

I often find myself wanting to surround a word or a sentence with italics or bold (markdown), sometimes parens and quotes when writing code, and currently cannot do it without some inefficient acrobatics.

Not sure how easy/hard it would be to implement this in Quiver. Would love to hear your thoughts.

**Comment by ylian** [comment]
It needs to be implemented in the Ace editor. I will check if someone is working on this for the Ace editor, but if not, it's unlikely I can implement this myself.

**Comment by dkarter** [comment]
Thanks for the quick response @ylian! That's cool, I can create a pull request on their repo. Are you using Electron? how are you able to use this javascript library in an OSX native app?

**Comment by ylian** [comment]
@dkarter No, I'm not using Electron. The editor is a WebView.
