### ISSUE TITLE
Feature request: Implement Visual Block Mode in Vim

### ISSUE THREAD

**Issue by dkarter** [HappenApps/Quiver#230]
This a very powerful built in functionality in vim that is currently missing in Quiver's Vim implementation.
It is illustrated here:
http://vimcasts.org/episodes/selecting-columns-with-visual-block-mode/

The gist of it is that it lets you select text vertically by columns. I can see it being extremely useful for editing tables in markdown, turning lines into bulleted lists, commenting paragraphs of code, and many more.

Would love to hear your thoughts on this one.

**Comment by dkarter** [comment]
This feature exists in the Ace editor:
![Visual Block](http://g.recordit.co/vmMNdiQ9V3.gif)

**Comment by ylian** [comment]
Cool. Then I can support it in Quiver.

**Comment by ylian** [comment]
Coming in 3.0.2.

**Comment by dkarter** [comment]
Works great in Version 3.0.2 (82) beta! Thank you!

**Comment by ylian** [comment]
Fixed in 3.0.2.
