### ISSUE TITLE
Spontaneous Loss of Entire Library

### ISSUE THREAD

**Issue by cassidyclawson** [HappenApps/Quiver#234]
Hello,

Love Quiver!

I am using dropbox to sync my library between two computers. For some reason, Quiver deleted the contents of my library. Luckily I was able to restore the folders via Dropbox. This was a close call.

Perhaps it tried to create a new library on top of the original? Perhaps I had something to do with it? In any case - this was a very close call and I suggest you implement better protections against data loss. This would have been catastrophic had I not been able to recover the files.

**Comment by ylian** [comment]
@cassidyclawson Thanks for the report. There was one known bug that could cause this in v2.1.2. If you have made a backup and selected the backup destination the same as your library location, it wipes your library. Is that what might have happened?

**Comment by cassidyclawson** [comment]
I do not believe that I made a backup. Though it's possible. I'm sorry I can't provide more concrete information to help isolate the bug. Hopefully this anecdote will be helpful if more users come forward with a similar issue.

**Comment by ylian** [comment]
@cassidyclawson Thanks.

**Comment by ylian** [comment]
Closing this for now. Reopen if this happens again. I am quite confident this no longer happens in Quiver 3.0, released today.

**Comment by jamesmgg** [comment]
I got the same error... It happened when I logged into my computer after ~3 weeks of not using it and maybe a month of not using Quiver... What seemed to happen was the moment I opened Quiver, whatever data I had was wiped. Luckily, I was able to use TimeMachine to recover the file I had before opening Quiver.
