### ISSUE TITLE
Editing in Code View

### ISSUE THREAD

**Issue by arbitrarily** [HappenApps/Quiver#237]
Having trouble editing notes in code view; can't line return. Resorting to pasting in code. Is this the intended functionality?

**Comment by ylian** [comment]
Same as in #238. Probably the app had an exception or crash. Restart the app and try again.

**Comment by arbitrarily** [comment]
Luckily restart correct each issue!

**Comment by ylian** [comment]
@arbitrarily Appreciate it if you could open Console.app, search for "Quiver", and send me any exceptions or crash logs.

**Comment by ylian** [comment]
Thanks. Closing for now. Reopen if it happens again.
