### ISSUE TITLE
Toggling Presentation Mode Visual Bugs

### ISSUE THREAD

**Issue by arbitrarily** [HappenApps/Quiver#238]
Having trouble editing notes in code view; can't line return. Resorting to pasting in code. Is this the intended functionality?
![screen shot 2015-11-15 at 3 57 00 pm](https://cloud.githubusercontent.com/assets/899183/11170982/a2f90e40-8bb1-11e5-9492-224ecaed0616.png)

**Comment by ylian** [comment]
No, that doesn't look right at all. The app might have crashed. Restart the app and try to edit the note again.

If you could, check your logs (open the Console app and search for Quiver) and let me know if you see exceptions or crashes.

**Comment by arbitrarily** [comment]
![screen shot 2015-11-16 at 10 30 04 pm](https://cloud.githubusercontent.com/assets/899183/11202008/9ac51664-8cb1-11e5-983c-7f1c9b4dcf99.png)

Interestingly enough: nothing.

**Comment by ylian** [comment]
Hmm, that's weird. Then keep an eye on this and let me know if it ever happens again. Thanks.

**Comment by arbitrarily** [comment]
You got it, otherwise, keep up the great work!
