### ISSUE TITLE
Lost all data after update to 3.0

### ISSUE THREAD

**Issue by ad-lebedev** [HappenApps/Quiver#241]
Mac OS X 10.11.
After update to 3.0 I lost all saved notes. It looks like application has been installed first time.
What kind of information I can provide you for investigation?
BTW: do I have any options to restore data? May be from time capsule backup? If so, what kind of files and from where do I need to restore?

**Comment by ylian** [comment]
That's strange. I can jump onto a Google Hangout with you if it's convenient. Please contact me directly via email (ylian@happenapps.com).

Yes, you can restore data from time capsule backup. Find Quiver.qvlibrary file, and open Quiver > Preferences > Backup > Restore from Backup.

**Comment by ylian** [comment]
Emailed instructions but no reply. Closing this, but feel free to contact me again if you still need help.

**Comment by jamesmgg** [comment]
I got the same error... It happened when I logged into my computer after ~3 weeks of not using it and maybe a month of not using Quiver... What seemed to happen was the moment I opened Quiver, whatever data I had was wiped. Luckily, I was able to use TimeMachine to recover the file I had before opening Quiver. I'm on version: 3.0 (66)
