### ISSUE TITLE
Unable to Open File via File URL Link -- Add Cancel Button

### ISSUE THREAD

**Issue by JMichaelTX** [HappenApps/Quiver#244]
#### Quiver 3.0 on Yosemite 10.10.5

When I click on a link in Quiver to a file on my Mac, I get this error:

> The application “Quiver.app” does not have permission to open “How to Use Error Handler.scpt.”

This same link works fine in Evernote.

I have given Quiver.app permission to control my Mac in **Mac Preferences > Security & Privacy > Privacy > Accessibility**

Is this a BUG, or it there some setting I need to change?

**Comment by ylian** [comment]
How did you create the file link?

All the apps from Mac AppStore need to be sandboxed, so is Quiver. The sandbox limitation means that you can't open an arbitrary file on the file system from Quiver, without explicitly giving Quiver the permission first. This is different from the permission settings in Accessibility.

For a sandboxed app, there are two ways permissions can be granted to the app:
1. The user uses the "Open File" panel to select a file.
2. The user drags the file into the app.

So if you manually typed in the file link, it won't work. If you use the "Attach file" button on the toolbar or dragged the file into the note, Quiver will be able to open the file afterwards.

**Comment by ylian** [comment]
If you are tired of dragging in one file at a time, simply drag in a top folder, for example, your Desktop folder, or your Dropbox folder, etc. That gives Quiver permission to open any file inside that folder.

**Comment by JMichaelTX** [comment]
> For a sandboxed app, there are two ways permissions can be granted to the app:
> 1. The user uses the "Open File" panel to select a file.
> 2. The user drags the file into the app.

OK, thanks.  That works great!

BTW, on the popup window to select Link or Copy, it would be great to also have a "Cancel" button.

**Comment by ylian** [comment]
Yeah, that makes sense. I will add a "cancel" button. Leave this ticket open for that.

**Comment by ylian** [comment]
The "Cancel" button is added in 3.0.1.
