### ISSUE TITLE
Overwide rendered LaTeX in Preview and Presentation views

### ISSUE THREAD

**Issue by nschneid** [HappenApps/Quiver#25]
Rendered LaTeX (particularly math formulas) can exceed the normal content width. While it is possible to resize the width of the Preview window, neither the Preview nor Presentation views allow horizontal scrolling. I think an appropriate solution would be to allow horizontal scrolling if the note contains any overwide LaTeX content.

**Comment by ylian** [comment]
Would it make sense to allow horizontal scrolling in the cell instead?

**Comment by ylian** [comment]
I tried it out. Horizontal scrolling in the cell feels quite good. Coming out in v2.1. Submitting tonight.

**Comment by ylian** [comment]
Fixed in Quiver 2.1.
