### ISSUE TITLE
[Request] Copy note as markdown

### ISSUE THREAD

**Issue by dkarter** [HappenApps/Quiver#251]
I know it's possible to export a note as markdown, but when I want to create a simple blog post out of a note the process currently looks like this:
1. Open note
2. Export note to markdown
3. Browse to folder where exported
4. Open markdown file in text editor
5. Copy markdown
6. Paste in blog and post
7. Delete markdown file

Alternatively, I would have to go to each cell individually and copy / paste into the blog program while switching windows multiple times.

The "copy note as markdown" feature will simplify this workflow by skipping the file creation and deletion and putting the markdown version directly into the clipboard.

Thanks so much for your continued support!!! 
Quiver 3.0 rocks!🤘

**Comment by ylian** [comment]
Absolutely. This is easy to add. Stay tuned.

**Comment by JMichaelTX** [comment]
:+1:  :sunglasses:

**Comment by kikyous** [comment]
:+1:

**Comment by dkarter** [comment]
Many thumbs way up! Works great, thank you @ylian!

**Comment by ylian** [comment]
Fixed in 3.0.1.
