### ISSUE TITLE
[How To]  Keyboard Shortcuts for Cursor Movement

### ISSUE THREAD

**Issue by JMichaelTX** [HappenApps/Quiver#254]
Hi.  This is not an issue, but a question of how to.
If there is a better place to post questions like these, please advise.

Is there a list of all keyboard shortcuts for Quiver?
Specifically, I'll looking for movement to:
- Top of Note
- Bottom of Note
- Next Cell (down) 
- Previous Cell (up)
- Note Title
- Note List
- Sidebar

Until we get full AppleScript support, I can use these type of shortcuts with AppleScript and Keyboard Maestro to do some useful stuff.
Thanks.

**Comment by ylian** [comment]
It's fine to post questions here.

I need to write a doc for these. But here is the gist:
- Top of Note: N/A
- Bottom of Note: N/A
- Next Cell (down): cmd+down arrow, twice
- Previous Cell (up): cmd+up arrow, twice
- Note Title: N/A (except that you can use cmd+up to move from the first cell to the note title)
- Note List: esc from the editor, tab or right arrow from sidebar
- Sidebar: ctrl+1, ctrl+2 selects Notebooks or Tags in the sidebar and moves focus to the sidebar. Shift+tab or left arrow from the note list.

**Comment by ylian** [comment]
Wrote a doc for keyboard shortcuts: https://github.com/HappenApps/Quiver/wiki/Keyboard-Shortcuts

**Comment by JMichaelTX** [comment]
Thanks.  This is terrific!  :+1:
