### ISSUE TITLE
Paste Image works in Text Cell, but not work in Markdown Cell

### ISSUE THREAD

**Issue by Gohan** [HappenApps/Quiver#258]
Cool Apps, find that Paste Image not works in markdown cell, happy to wait for it fix. 

For my case: I had to switch to plain cell, and paste image, then switch to markdown cell, to make it show simple in editor area

**Comment by ylian** [comment]
If you copy an image file then paste into a Markdown cell, it should work.

Right now it doesn't work if you copy an image to the clipboard directly (e.g. take a screenshot), then paste in a Markdown cell. I will try to fix it.

**Comment by urmyfaith** [comment]
+1

hope to see it fixed in next version.

**Comment by prurph** [comment]
+1 this would be very useful.

**Comment by ylian** [comment]
Fixed in 3.0.6. Now you can paste an image from the clipboard into a Markdown cell.
