### ISSUE TITLE
Hide the line below the note title.

### ISSUE THREAD

**Issue by janodev** [HappenApps/Quiver#26]
This line shows the date of the note creation (which I have no use for) and the tags (which are already duplicated in the pane to the right). 

I’m a heavy use of Codebox and I find it useful to scan vertically the column with the note titles without any other information in the way. I’m attaching a screenshot:

![screen shot 2015-02-09 at 15 50 27](https://cloud.githubusercontent.com/assets/627538/6108448/96f692f8-b073-11e4-989e-8f0878a218d0.png)

**Comment by ylian** [comment]
Great idea. A condensed note list will be very helpful for the iOS version as well. Will implement in 2.2.

**Comment by preflight** [comment]
Thanks for implementing this, it's been on my wishlist as well

**Comment by ylian** [comment]
Implemented in 2.2b30: https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b30.zip

In Preferences, change note list style to "Condensed".

![screen shot 2015-05-03 at 2 11 05 pm](https://cloud.githubusercontent.com/assets/984895/7446497/83c09df2-f1a8-11e4-8461-9b3c1f5e113a.png)

**Comment by ylian** [comment]
Implemented in 2.2b30: https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b30.zip

In Preferences, change note list style to "Condensed".

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
