### ISSUE TITLE
Fuck you!!!!!

### ISSUE THREAD

**Issue by lintaoSuper** [HappenApps/Quiver#265]
English only, Fuck you. dog b.

**Comment by thomasxu1991** [comment]
Sau đó, làm thế nào để sử dụng tiếng Việt, Sao năm

**Comment by Johnhacker** [comment]
丢人又丢到国外去了  唉

**Comment by FrankFang** [comment]
Poor guy.
扑街。

**Comment by imWildCat** [comment]
@lintaoSuper 

https://github.com/HappenApps/Quiver/wiki/Quiver%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8

Are u BILND? Such a loser!
