### ISSUE TITLE
Swift Syntax Highlighting: quote escape

### ISSUE THREAD

**Issue by ghost** [HappenApps/Quiver#270]
Hi,

In code cell, quotation mark is not escaped properly.

Subsequently, codes following the quotation mark are recognized as String.

![2015-12-03_13-42-13](https://cloud.githubusercontent.com/assets/12084861/11552082/acb9db92-99c3-11e5-9cd5-5648965e646e.png)

**Comment by ylian** [comment]
Fix coming in 3.0.2.

**Comment by ylian** [comment]
Fixed in 3.0.2.

**Comment by ghost** [comment]
Thank you!
