### ISSUE TITLE
icons go missing after going to Presentation mode

### ISSUE THREAD

**Issue by Kiresorg** [HappenApps/Quiver#271]
While doing the tutorial, I went to Presentation mode on Note 6. When I exited Presentation mode, several icons were no longer visible. Among them: The Presentation icon in the bottom right, the three dots icon in the bottom right, and the search icon in the top right.

To restore some of the icons, I went to the INbox and returned to the Tutorial Notebook. This restored most icons; the search icon remains invisible but active (meaning I can get to it by keyboard shortcut or by clicking where I know it is).

I am using a MacBook Air mid 2013, on OS X Yosemite 10.10.5.

**Comment by ylian** [comment]
Just to clarify, when the icons are "missing", do they look something like this? (I photoshopped this, a screenshot would be helpful)

![screen shot 2015-12-03 at 8 27 32 am](https://cloud.githubusercontent.com/assets/984895/11561825/eaa9cfba-9997-11e5-8138-9d9e2ece6eec.png)

Or is the window cut off like this? (again photoshopped)
![screen shot 2015-12-03 at 8 27 32 am](https://cloud.githubusercontent.com/assets/984895/11561866/2bb952a0-9998-11e5-8a9c-8298c0cf7a0a.png)

**Comment by ylian** [comment]
Closing for the lack of details.

**Comment by jboxman** [comment]
In Version 3.2.4 (190), if the Inbox is selected and there are 0 notes, the search icon is not displayed in the upper right corner.

Also, **Edit > Find > Search** Notes doesn't work.

If I pick a folder with notes and select any note from the list, the search icon appears and **Edit > Find > Search Notes** opens a modal for searching.
