### ISSUE TITLE
[feature request] automatic backups

### ISSUE THREAD

**Issue by yaodong** [HappenApps/Quiver#275]
It's inconvenience for me to choose filename very time when I creating a backup. I think automatic backups will be better. User choose a backup dir name, then Quiver generate backup zip files with in format of "xxx-201512130945.zip".

**Comment by ylian** [comment]
That would be better. Or even better with Git integration. I am aware of this but there are higher priorities at the moment.

A good solution right now is to move your library to Dropbox, or Google Drive, or use a Time Machine backup. Both Dropbox and Google Drive keep 30 days of file history, and let you revert to previous versions easily. Time Machine of course can revert files to previous versions as well.

**Comment by ylian** [comment]
Beware that iCloud Drive doesn't have a way to revert to previous file versions. At least not at the moment.

**Comment by yaodong** [comment]
@ylian but dropbox can't revert a folder.

**Comment by ylian** [comment]
It can. Check out this app: https://itunes.apple.com/us/app/revisions-for-dropbox/id819348619?mt=12

**Comment by yaodong** [comment]
@ylian now using Dropbox is more reasonable solution, however it more complicated for end-users.

**Comment by ylian** [comment]
Yeah, I agree, a built-in solution would be better.
