### ISSUE TITLE
"inline code" text style is simply Helvetica

### ISSUE THREAD

**Issue by smlombardi** [HappenApps/Quiver#276]
Shouldn't it be the code font and style, with the syntax background similar to `how github does it`?

**Comment by ylian** [comment]
No it's not Helvetica, it's Menlo, unless you have custom CSS that overrides the default.

![screen shot 2015-12-03 at 2 40 53 pm](https://cloud.githubusercontent.com/assets/984895/11571759/f4fdbede-99cb-11e5-9a07-448d9065865d.png)

The easiest way to check is to turn on the web inspector (http://stackoverflow.com/questions/695038/is-there-a-way-to-use-the-webkit-web-inspector-from-a-cocoa-webview-object)

**Comment by smlombardi** [comment]
You are correct.  it might be nice to change the background color behind inline code to make it stand out.
![screen shot 2015-12-17 at 9 38 41 am](https://cloud.githubusercontent.com/assets/835148/11872215/190c08f4-a4a2-11e5-87e5-c973a1ca8800.png)

**Comment by ylian** [comment]
You can customize it in Preferences > Styles > Preview - Edit CSS. For example,

``` css
code {
  background: red;
}
```

**Comment by jiamingz42** [comment]
I have a difficult time open the Web Inspector:

I ran this command in the Terminal

``` bash
defaults write 'com.happenapps.quiver" WebKitDeveloperExtras -bool true
```

And then I quit and restart the Quiver, go the preview and then right-click the panel. I expected to see a dropdown with a item called "Web Inspector" but there is no dropdown shown up. Did I do something wrong here?

**Comment by ylian** [comment]
Try:

```
defaults write com.happenapps.Quiver WebKitDeveloperExtras -bool true
```

Right click in the preview and you should see "Inspect Element". That brings up the web inspector.

**Comment by jiamingz42** [comment]
It works! Thanks!
