### ISSUE TITLE
[Suggestion] - Mobile app

### ISSUE THREAD

**Issue by bborysenko** [HappenApps/Quiver#280]
Quiver has almost all functions that I need to move from Evernote, but what I really missing - is a mobile app.

**Comment by ylian** [comment]
Duplicate of https://github.com/HappenApps/Quiver/issues/207.

iOS beta testing starts early January. You can sign up here: http://eepurl.com/bItzIv

**Comment by ghost** [comment]
Hi, I was wondering if maybe the iOS beta testing would start this month?

**Comment by ylian** [comment]
@liweijian Getting close. Please be patient. :)

**Comment by pelted** [comment]
Five months have passed, are customers any closer to having and iOS app?

**Comment by ylian** [comment]
@pelted The iOS beta has been out for a few months.
