### ISSUE TITLE
Markdown cell lost footnote in preview

### ISSUE THREAD

**Issue by yaodong** [HappenApps/Quiver#289]
Cause Quiver can't fold long links in markdown, so I put reference link as footnote. But preview has no footnote.

Footnote example:

``` markdown
Clicking this number[^fn-sample_footnote] will lead you to a footnote.

[^fn-sample_footnote]: Handy! Now click the return link to go back.
```

**Comment by ylian** [comment]
Currently footnotes are not supported. But I plan to add the footnote support.

**Comment by dkarter** [comment]
+1 for that feature

**Comment by laupiFrpar** [comment]
:+1: for that feature

**Comment by timesking** [comment]
+1 for that feature

**Comment by dotinspace** [comment]
+1

**Comment by man-ito-ba** [comment]
+1.

Bear app does it well.

**Comment by DelightRun** [comment]
+1.
Thanks for ylian's great contribution.

**Comment by Geekinus** [comment]
And I also want
⒈ to sync my note on Evernote and 印象笔记( in China),
⒉ to add more LaTeX package to draw more graphic,
⒊ enhanced markdown labels and HTML cell.

**Comment by will-rowe** [comment]
+1 for this feature!

**Comment by phyjswang** [comment]
PLZ add this very useful feature!
