### ISSUE TITLE
store cell content in a diff-friendly format

### ISSUE THREAD

**Issue by oliverlangan** [HappenApps/Quiver#291]
Per the notes on this page: https://github.com/HappenApps/Quiver/wiki/Quiver-Data-Format
cell content is stored directly in the content.json file. Newlines are represented as \n in this format.

Elsewhere in the documentation, git-backed notebooks are mentioned as a way to have some control over merge situations, but this storage format means that individual cells will still be quite difficult to merge.

Instead, please consider storing the content in separate files ('cell resources' or some such), where newlines are stored in their native format. These files are inherently diff-able.

Instead of:

```
  ...
  "cells": [
    {
      "type": "code",
      "language": "javascript",
      "data": "void hello()\n{\n    console.log(\"Hello World!\");\n}"
    },
    ...
```

perhaps:

```
  ...
  "cells": [
    {
      "type": "code",
      "language": "javascript",
      "href": "938E0373-8493-43B8-B7B5-AD873D368091.js"
    },
    ...
```

where the href is a generated uuid and (optionally) an extension specifying syntax.

There is additional cost in loading these separate files when displaying the note, but probably not when searching (assuming the index is generated separately from the content).

**Comment by ylian** [comment]
Good point. Indeed `git merge` doesn't do word-level merge.

I will think about this but I don't think I want to change the file format any time soon.

**Comment by oliverlangan** [comment]
I understand it is not a minor change, but a diff-friendly format would help a lot in our ability to use Quiver to share information across a team. I would also recommend it with html which sometimes loses insignificant whitespace when transformed (are you using NSXML?)... however adding line breaks to html can have subtle effects.

**Comment by ylian** [comment]
Unfortunately this is too big a change to make at this point. It will affect how the note is loaded, as well as search indexing. Backward compatibility would be a big headache since not all users may upgrade at once, and shared notebooks in the new format would break older versions of Quiver.

Quiver was not designed to handle note-level conflicts. The mention of using git to merge changes is more of an extra bonus, instead of a major supported feature. Sorry for the confusion.

**Comment by ylian** [comment]
Mark as WONT FIX for now.
