### ISSUE TITLE
If the note has been moved, view area will resets/scrolled to up

### ISSUE THREAD

**Issue by facetheheat** [HappenApps/Quiver#293]
If the note has been moved, view area will resets/scrolled to up. 
It's inconvenient when I have a lot of notes. I should scroll down after each move/delete.
Thanks

**Comment by ylian** [comment]
Thanks. I noticed this, too. It's quite annoying. Will definitely fix in 3.0.1.

**Comment by facetheheat** [comment]
Sounds great! 
I will be waiting for update :)

**Comment by ylian** [comment]
Fixed in 3.0.1.
