### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by ajgon** [HappenApps/Quiver#294]
Hey,

I plan to develop a simple Alfred Extension, which implements Full Text Search in Quiver. However, to do this I need a way, to open the exact note in quiver (either via params of command line, or apple-script). Is it possible at the moment?

**Comment by ylian** [comment]
Not at the moment, but this scheme will be added shortly: https://github.com/HappenApps/Quiver/issues/97

I wonder how you are going to implement full text search? There is no scripting support in Quiver yet.

**Comment by ajgon** [comment]
Thanks for quick reply :)

I was thinking about using some Ruby/Python script, to parse Quiver JSON-data files. Even basic string matching, would be sufficient for my needs (at least at the beginning).

**Comment by ylian** [comment]
I see. That would be okay if the library isn't too big. You can switch over once I add scripting support for that.

**Comment by ajgon** [comment]
Awesome!

One last thing, just to confirm - even the `quiver:///notes/{noteId}` scheme is still not available? I tried both `open "quiver:///notes/B59AC519-2A2C-4EC8-B701-E69F54F40A85"` and `open "quiver://notes/B59AC519-2A2C-4EC8-B701-E69F54F40A85"` with no luck...

**Comment by ylian** [comment]
@ajgon That's correct. But go ahead with your implementation. I will send you a special build within a day or two.

**Comment by ajgon** [comment]
Great! Thank you!

**Comment by ajgon** [comment]
Ok, so here is the initial draft of the extension - if anybody is interested :)
https://github.com/ajgon/alfred2-quiver-search

**Comment by ylian** [comment]
@ajgon Thanks. Here is a special build with the URL scheme (`quiver:///notes/{noteId}`) enabled:

https://dl.dropboxusercontent.com/u/3445731/Quiver-scripting-b1.zip

This will be included in 3.0.1.

**Comment by ajgon** [comment]
Works perfectly, thanks!

**Comment by ylian** [comment]
Merged this with https://github.com/HappenApps/Quiver/issues/92.

I also added a entry here: https://github.com/HappenApps/Quiver/wiki/Alfred-LaunchBar-Integration

**Comment by ylian** [comment]
The URL scheme is implemented in 3.0.1.
