### ISSUE TITLE
Import notes from Evernote format enex

### ISSUE THREAD

**Issue by x-y-z** [HappenApps/Quiver#3]
I have bought the full version and want to use it all the time.

But I have a fair amount of notes in Evernote. Is there any plan for adding import notes from evernotes?

Thanks.

**Comment by Strajk** [comment]
Anybody worked on importer from Evernote yet? I'm looking for Evernote alternative for years and this might be it :))

**Comment by ylian** [comment]
I did some work on this in 2.1 but not yet finished. Just need to handle images and files, etc. You could try to write a script or wait for me to implement this in a future update (prob. 2.2).

**Comment by Strajk** [comment]
@ylian hey, any update here?

**Comment by ylian** [comment]
I will post a beta build here shortly.

**Comment by ylian** [comment]
@Strajk Apologize for the delay. Have been working on Quiver for iOS.

Attached is a test build with the Evernote importer implemented. It can properly import text and images. Give it a try and let me know.
https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b1.zip

BTW, if you would like to see a really early build of Quiver for iOS, email me.

**Comment by ylian** [comment]
@Strajk Fixed a few more issues with the importer. Now it imports tags, attachments (files) and todo items as well. It seems quite stable now. Let me know if you find issues. Thanks.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b2.zip

**Comment by ylian** [comment]
Fixed an issue that sometimes the creation date and modified date are not imported correctly.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b34.zip

**Comment by Strajk** [comment]
@ylian sorry for not responding, I've tried it just now and it's working perfectly!

**Comment by ylian** [comment]
No problem at all. I still need to fix #2 and #59 so it's easier to manage all the notebooks.

**Comment by ylian** [comment]
@Strajk Note that if you have attachments in your Evernote notes, currently they are imported as file links, but this will change as I fix #83. So don't import notes with attachments just yet. Images are fine.

**Comment by ylian** [comment]
This is now implemented in Quiver 3.0, released today.

**Comment by overture8** [comment]
I have all my notes organised in notebooks in Evernote - it'd be cool if the import created notebooks in Quiver for each notebook in Evernote (rather than putting all the notes in a general "Imported..." notebook).

**Comment by bensethbell** [comment]
@ylian the link no longer works.

**Comment by FCh99** [comment]
Hello, I am testing the trial version for a definitive migration but, making an import of 1001 notes from Evernote all of them tagged sometimes two or more tags per note. Quiver imports all the notes, but when listing tags in the tag view, there are many tags missing, I repeated the importing several times and it brought in other lists of tags but never complete, always tags missing from the list, please let me know, thanks in advance,

**Comment by FCh99** [comment]
I had an issue with importing tags from Evernote, but now everything looks ok. I just deleted my app, installed again, and imported the notes, now good, thanks ¡¡
