### ISSUE TITLE
Cmd+Backspace doesn't work in the search field

### ISSUE THREAD

**Issue by ylian** [HappenApps/Quiver#303]
From Alexandr Kirsanov:

I am constantly experiencing an annoying bug.
A cursor is within the note, in a text cell for example. Press cmd+alt+f (“Search notes”). A search input is shown and becomes focused. Start typing something in search field. Then try to clear the search input field: press Cmd+Backspace.
Expected: a search input field is cleared.
Actual: a note is deleted to Trash (like Cmd+Backspace was pressed when the note in note panel was focused, but focus was in input search field).

Same bug is for regular search (cmd+F): Cmd+F, Cmd+Backspace => note deleted.

**Comment by ylian** [comment]
That's an annoying bug. Will fix in 3.0.1.

**Comment by JMichaelTX** [comment]
> Then try to clear the search input field: press Cmd+Backspace.
> Expected: a search input field is cleared.

That is a bad bug that needs to be fixed.
But I never would have thought of using ⌘⌫ to clear a search field.
ESC works fine, and seems to be commonly used in the other Mac apps that I use.

**Comment by ylian** [comment]
Fixed in 3.0.1.
