### ISSUE TITLE
Add GraphViz as one of the diagram sources

### ISSUE THREAD

**Issue by acrodrig** [HappenApps/Quiver#304]
GraphViz has a javascript implementation that can be embedded:

https://github.com/mdaines/viz.js/

This would make the diagrams all the more powerful.

**Comment by ylian** [comment]
It's probably going to be too slow. The demo already takes a few seconds to load on my laptop. Embedding in Quiver and doing live reload every few keystrokes would kill the performance.

**Comment by acrodrig** [comment]
Got it. Then other generic diagramming solutions should be added. The two offered are very nice, but not general enough in my (limited) experience so far.

**Comment by ylian** [comment]
Closing this but I will work on a more generic diagram library soon.

**Comment by acrodrig** [comment]
Take a look at:

http://jburrow.github.io/canviz/

It's an alternative library that is pure JS. DOT is a vert well know language for diagrams and it would be awesome to have it supported in Quiver.

**Comment by ylian** [comment]
@acrodrig Thanks. This is helpful.

**Comment by nkgm** [comment]
@ylian have you given this any more thought? Would be really useful to be able to use DOT in a diagram cell.
