### ISSUE TITLE
[Help Needed] App opens with all notes missing

### ISSUE THREAD

**Issue by ylian** [HappenApps/Quiver#309]
A user reported in an AppStore review that:

> ...after the most recent update, there will be times when the app opens up and show that it’s empty (no notes whatsoever), and after I Cmd+Q to kill and restart the app, my notes will then show up. I’m using Dropbox for the sync, please fix this!

Does anyone else experience this issue? I would like to get to the bottom of this nasty bug.

A couple of things that can help me:
1. When this happens, take note of the library location (Preferences > Sync > Library location). Is it empty or different from where your library really is?
2. A screenshot would be helpful.

Thanks!

**Comment by rcrooks** [comment]
I saw this just once after a system restart, but not again. I just relaunched Quiver and all was well. 
Unfortunately don't have much info for you. At the time, my library was stored in a Github working copy - I've since moved it to Dropbox.

**Comment by TheTweak** [comment]
I just experienced the same bug after installing system update with restart, I've checked preferences and library location is neither empty nor different from real one. Relaunch didn't help. I am afraid I've lost all my data.
What else can I try to restore? I thought it has auto save.

**Comment by TheTweak** [comment]
It also had default theme enabled (I use dark) after restart.

**Comment by TheTweak** [comment]
FYI: I was running Quiver outside of "Applications" folder.

**Comment by ylian** [comment]
@TheTweak  Can we use Google Hangout to share screen? It would help me greatly to figure out what's going on, and I'm confident your data are still there.

**Comment by TheTweak** [comment]
@ylian Yes, we sure can!

**Comment by ylian** [comment]
You can call me now: yaogang.lian@gmail.com

**Comment by ylian** [comment]
@rcrooks @TheTweak Appreciate your help.

It seems that sometimes, after system restart, Quiver can't resolve the library path, thus you won't see your notes.

If anyone runs into this issue, do the following:
1. Restarting the app usually fixes the issue.
2. If not, find your Quiver.qvlibrary, double click to open it.

If you need more help, feel free to email me at ylian@happenapps.com.

In the meantime, I will figure out why this is happening and push out a fix ASAP.

**Comment by ylian** [comment]
Finally figured it out. It's because security-scoped bookmarks were not cleaned up. Quiver 3 uses security-scoped bookmarks in more places, such as file attachments. That's why this issue is greatly amplified. Fix coming in 3.0.1 (submitting this weekend).

References for myself:
- http://stackoverflow.com/questions/24258462/reusing-apple-sandbox-security-scoped-bookmarks
- https://discussions.agilebits.com/discussion/19639/1password-losing-sync-permissions-after-system-restart-mas

**Comment by ylian** [comment]
Fixed in 3.0.1.

**Comment by martinfua** [comment]
Hi, I'm on 3.0.1 and I've just lost all of my data. Restarted the app didn't work and neither did clicking on Quiver.qvlibrary (it's now 84 bytes in size). Any idea what else I can do to get my data back?

**Comment by ylian** [comment]
@martinfua Please contact me via email with details. Happy to help you from there. My email is ylian@happenapps.com.

**Comment by smking** [comment]
I have the same issue in Quiver Version 3.1.1 (123) - from the app store (latest version as of 22 Oct 2017).  Every other time I open Quiver the notebooks are all empty.  Quit with CMD-Q and start again, and the notes are all there.

I'm storing my Quiver.qvlibrary in an Amazon WorkDocs folder.

**Comment by ash0080** [comment]
@ylian same issue as above, lost all my notes about 2 years!  3.1.2 (126)
Got it
The old path ~/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver
new path ~/Library/Application Support/Quiver

**Comment by good2best123** [comment]
I am experiencing this issue with 3.1.2 (126). Restarted my mac and quiver opens with empty default notebooks. The /Users/<xxxx>/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver/Quiver.qvlibrary. If I click on Open Existing and locate my library, it is still empty. This happened the last time I restarted my machine as well, but I was able to restore using Sync -> Open an existing library option in prefs. Unable to do so now.

**Comment by neurosaurus** [comment]
I'm having the same issue as @good2best123. Help!

**Comment by thiyagu-7** [comment]
This doesn't seem to be fixed. I still face this issue. 

Quiver is empty after restarting my mac.
Opening quiver by clicking Quiver.qvlibrary brings the notes back and this is annoying.

P.S: I using 3.2.4 version and google drive for sync.

**Comment by piccoloportfolios** [comment]
> Hey, I will e-mail you as well as I have the same problem now.

**Comment by jerickson-yipit** [comment]
Also having similar issues. Will email as well.

**Comment by tashmays** [comment]
I'm having an issue with all my notes not showing, I will send email too.
