### ISSUE TITLE
[request] Subscript and superscript

### ISSUE THREAD

**Issue by middledash** [HappenApps/Quiver#310]
I would like to suppose to include subscropt and superscript. Predominantely for Markdown:

It would be very beneficial to enable the following syntax for subscript:

H_2O ==> Formula for H2O
Speed_(max) ==> Speed in normal and "max" in subscript // e.g. abc_(12)def

Syntax for superscript:

x^2 for x2
normal^(superscript)normal

When this is implemented your program would be very useful for most scientiest :-)

Thank you very much in advance!

**Comment by ylian** [comment]
Markdown cells support inline LaTeX, and that's exactly for this use case (as well as more complex math symbols and equations).

For example, 

``` md
Markdown supports inline LaTeX, such as $H_{2}O$, $x^2$.
```

It's rendered as:

![screen shot 2015-12-12 at 1 51 14 pm](https://cloud.githubusercontent.com/assets/984895/11763413/7818ccac-a0d7-11e5-80d1-0cda975e05f8.png)

**Comment by middledash** [comment]
Thank you for your answer. That's right - inline LaTeX is very powerful. But as it is know by most other Markup-Editors (e.g. MacDown or Haroopad) sometimes it is much easier to write x^2. Furthermore it would be very beneficial if it remains the same font-type. As you can see the rendered output is written in italics what can be irritating.

**Comment by melgu** [comment]
You can use HTML code in a markup cell so `2<sup>8</sup>` becomes 2<sup>8</sup>
and `H<sub>2</sub>O` becomes H<sub>2</sub>O .

Inside the normal text cell you can just choose sub- or superscript from the menu (Format -> Style -> Baseline)

**Comment by keenguy** [comment]
You can extend the markdown syntax by hacking `Quiver.app/Contents/Resources/dist/js/preview.js`
Just find the snippet 
```
i=f.a("vendor/markdown-it-task-lists.js","module");n.use(i)
```
and add snippets like this
```
i=f.a("vendor/markdown-it-sup","module");n.use(i);
i=f.a("vendor/markdown-it-sub.js","module");n.use(i)
```
Then add the corresponding JS files to the folder `Quiver.app/Contents/Resources/dist/vendor/`. Just use the `index.js` file in the corresponding githhub repo, rather than that in the folder `dist`.

It also works for other extensions like mark, footnote, ins, etc.

Hope the author could update more markdown features. I currently rate [hackmd](https://hackmd.io/features) the best.

**Comment by gandalfsaxe** [comment]
I would indeed be nice to have better syntax for subscription and superscript that doesn't require writing it as LaTeX. The emerging standard syntax for this in markdown seems to be:

`32^nd^`
`H~2~O`

as shown here:
https://beegit.com/markdown-cheat-sheet

Beegit, Typora, MacDown are just some of the others also supporting this.
