### ISSUE TITLE
Markdown cell with dollar sign ($) not rendering properly

### ISSUE THREAD

**Issue by ApeWare** [HappenApps/Quiver#318]
If I write the following markdown:

``` markdown
**Cost $1788 yr @ 149per month**
```

It is rendering like this:
**Cost** 1788_yr @_**149per month**

See photo
![screen shot 2015-12-17 at 12 24 03 pm](https://cloud.githubusercontent.com/assets/389759/11876730/251f1dcc-a4b9-11e5-8731-f163a70b4a91.png)

**Comment by ylian** [comment]
This is because `$...$` is processed as inline LaTeX. A configuration option will be added in 3.0.1.

**Comment by ApeWare** [comment]
Thanks! That would be great.

**Comment by ylian** [comment]
Added an option to configure LaTeX delimiters in 3.0.1. There is also an option to turn off LaTeX in Markdown cells completely.

**Comment by ApeWare** [comment]
Thank you! Did the trick!
