### ISSUE TITLE
LaTex inside a markdown cell is not rendered properly when using _

### ISSUE THREAD

**Issue by alanzchen** [HappenApps/Quiver#319]
Try this inside a markdown cell. On the source side, the `1=p(y)y` is italic. Markdown syntax should be disabled inside an inline LaTex.

```
$\pi_1=p(y)y_1-c(y_1)$
```

You can take a look at how another app, Archimedes, handles this. It has a LaTex highlighting mixed with Markdown syntax highlighting.

**Comment by ylian** [comment]
Yes, this is an issue inside the editor. Duplicate of #209.

**Comment by alanzchen** [comment]
Sorry about that. I searched LaTex but no result so I suspect nobody talked about this.
