### ISSUE TITLE
How to Generate UUID

### ISSUE THREAD

**Issue by mAAdhaTTah** [HappenApps/Quiver#321]
I'm writing a script that will convert a couple markdown note files I have into Quiver notes. However, I'm not sure how to generate the UUID for the note format. Is there a particular method for doing so? Does it actually matter that much?

**Comment by ylian** [comment]
It doesn't matter much. A random string with a low probability of collision would work fine.

**Comment by mAAdhaTTah** [comment]
Easy enough.

**Comment by JMichaelTX** [comment]
> It doesn't matter much. A random string with a low probability of collision would work fine.

Here's an idea using date/time down to milliseconds to generate a unique ID.
This was done using AppleScript, but the meat is using shell scripts.
If you know Perl, you can probably combine this all in a perl shell script.

``` applescript
--- REPEAT TO VERIFY UNIQUE ID IS GENERATED ---
repeat 5 times
    set strDate to (do shell script "date '+%Y%m%d%H%M%S'")
    set strMS to (do shell script "perl -e 'use Time::HiRes qw(time); print time'")
    set strID to strDate & "-" & strMS
    log strID
end repeat

-- Results:
(*20151222002734-1450765654.06041*)
(*20151222002734-1450765654.13195*)
(*20151222002734-1450765654.20351*)
(*20151222002734-1450765654.27757*)
(*20151222002734-1450765654.35196*)
```
