### ISSUE TITLE
Cursor Position - Markdown Custom Styles

### ISSUE THREAD

**Issue by tmattacchione** [HappenApps/Quiver#323]
I changed my font sizes for the markdown cell's headings and I noticed that when the fonts are too big the cursor position is incorrect.  My code looks like this:

```
/* # Heading 1 */
.markdown-cell .ace_heading.ace_1, 
.markdown-cell .ace_heading.ace_1 ~ .ace_heading {
     color: #311b92;    /* t-custom - purple */
     font-size: 30px;
     font-weight: bold; /* t-custom */
     line-height: 1.1;; /* t-custom */
}
```

and the cursors seems to think the font-size is still set to `12px`.  See image below:

<img width="384" alt="screen shot 2015-12-22 at 12 15 18 pm" src="https://cloud.githubusercontent.com/assets/8523922/11961303/b36191f6-a8a5-11e5-9b6e-2a1656e0c351.png">

I know it appears like I am only highlighting the hash tag, but that is what happens when you try to highlight the `# h1`

**Comment by ylian** [comment]
Yeah, it's a known issue with the Ace editor. Ace doesn't support variable character width (https://github.com/ajaxorg/ace/issues/460).

At the moment I am not able to fix Ace bugs, but eventually I will fix them.

**Comment by tmattacchione** [comment]
Is there anything we can do in the meantime / help with this fetaure?

**Comment by ylian** [comment]
The best course of action is to contribute to Ace development. Ace is a great open-source editor, and it's clear that they can use some help.

**Comment by ylian** [comment]
Merge into #432.
