### ISSUE TITLE
Change default font to -apple-system

### ISSUE THREAD

**Issue by lilyball** [HappenApps/Quiver#327]
The default body font for a note seems to be `Arial, Helvetica, sans-serif`. Arial is a kind of odd choice here, since that's generally associated with Windows and usually considered to be Helvetica's uglier cousin.

In recent versions of the OS you can actually use the font family `-apple-system` to get San Francisco. I'd recommend changing the default body font to being

``` css
body {
    font-family: -apple-system, Helvetica, Arial, sans-serif;
}
```

While we're at it, the style for `<code>` in text cells is to use `font-size: 85%`, but with the default `13px` body text, this produces an `11px` code span, which is just a bit small. Note that the default font size for Code/Markdown/LaTeX cells is `12px`. I'd recommend bumping that up to `90%` instead, which should produce a `12px` font given a base of `13px`.

**Comment by ylian** [comment]
Fixed in 3.0.4.
