### ISSUE TITLE
Clojure syntax not complete

### ISSUE THREAD

**Issue by clojj** [HappenApps/Quiver#33]
keyword 'def' is correctly highlighted,
but 'defn' is not

Also, indenting seems broken (first line '(def ...)')
![screen shot 2015-02-10 at 21 47 21](https://cloud.githubusercontent.com/assets/4367963/6136124/6ff675fa-b16e-11e4-9732-e1dbd2e2de68.png)

light grey comments would be nice too !
(btw: the wrong indenting is gone in this case)
![screen shot 2015-02-10 at 21 50 17](https://cloud.githubusercontent.com/assets/4367963/6136179/d5306a20-b16e-11e4-84d7-2897f711a02e.png)

Is there any way to define the language highlightings/settings somewhere ?

**Comment by ylian** [comment]
Quiver uses Ace for the code editor, as well as syntax highlighting. So this is a limitation of Ace's Clojure syntax highlighter. It would be better if we can make the changes upstream.

I am not very good with regex or familiar with many languages' syntaxes, so it would be greatly appreciated if someone can contribute to Ace's syntax highlighters. It will help many other apps/projects as well.

http://ace.c9.io/#nav=higlighter

**Comment by ylian** [comment]
Close since this should be fixed upstream.
