### ISSUE TITLE
Backing up to iCloud driver in 10.11.3 Beta

### ISSUE THREAD

**Issue by oxoocoffee** [HappenApps/Quiver#330]
I noticed that there is a problem in Backup where ui locked up everytime

Here is what I do
1. Select Preferences
2. Select Backup 
3. Select Back up now (This opens dialog window)
4. Navigate to iCloud driver and I have Mac folder in it where I already have previous backup file)
5. Press Save
6. Nothing happens. The Dialog box stays and Cancel and Save button you can't click.

Checking iCloud/Mac folder I do not see the file updated

**Comment by ylian** [comment]
How big is your Quiver.qvibary? This happens if the library is quite large. Certainly this should be made non-blocking.

**Comment by oxoocoffee** [comment]
It is 4.4 Mb. Also when I removed old backup file through Finder/iCloud/Mac (4.4 MB file since I added very small item before backup) It did not block at all. So I did try to repeat it and back up again (no content change just backup) and this time no problem. So it had to be something with old backup on iCloud that was not backed up for a while. Not sure what to make out of this :)

**Comment by ylian** [comment]
That's interesting. 4.4Mb is small, and shouldn't block at all. But either way, I will improve this functionality.
