### ISSUE TITLE
Checkboxes do not render in preview when there is one new-line between them.

### ISSUE THREAD

**Issue by davidskeck** [HappenApps/Quiver#333]
When checkboxes are formatted as shown below, Quiver will not render them properly in preview.
- [ ] [test1]()
- [ ] [test2]() 

Quiver shows these as a bulleted list. 

<img width="1001" alt="screen shot 2015-12-31 at 1 50 03 pm" src="https://cloud.githubusercontent.com/assets/1740630/12067779/6e8508a2-afc5-11e5-9eef-579cbef518d4.png">

**Comment by davidskeck** [comment]
any status on this? this is still an issue.

**Comment by ylian** [comment]
Fixed in 3.0.4.
