### ISSUE TITLE
Inline LaTex bug

### ISSUE THREAD

**Issue by lihuanglx** [HappenApps/Quiver#337]
In a markdown cell, if I have content as below.

![image](https://cloud.githubusercontent.com/assets/7406791/12073972/aff152d0-b175-11e5-975a-e26d9bba76a0.png)

The LaTex code in the middle will not be rendered properly.

However if I remove either code block, it works fine.

**Comment by ylian** [comment]
Great find. This helps. I am fixing a few related issues.

**Comment by ylian** [comment]
Fixed in 3.0.1.
