### ISSUE TITLE
Wishlist: Copy all and only code from a note

### ISSUE THREAD

**Issue by elbie-x** [HappenApps/Quiver#338]
As a psychologist who works in R & as a new Quiver user, one of the things I was pleased about with this app is the ability to write longer, readable comments about the R code I'm writing, in separate Markdown cells. But then I find myself copying-and-pasting a few lines at a time back into R (RStudio, actually) to run them, whereas it would be incredibly nice to be able to extract _all_ the code from a note and paste it directly in R to run it. That would let me preserve my commentary, be able to read through my code, and streamline the analysis process.

Is there any way to do this already? If not, is it something you might consider implementing?

Thanks so much for this new tool!

**Comment by ylian** [comment]
So an option to "Copy as: Code Only"?

**Comment by elbie-x** [comment]
Yes, precisely - in fact, that's where I'd gone looking before I'd come to the conclusion it wasn't implemented yet!

**Comment by ylian** [comment]
Cool. This is trivial to implement. I will make sure it's in 3.0.1.

**Comment by elbie-x** [comment]
Fabulous. Thank you!

**Comment by JMichaelTX** [comment]
> Cool. This is trivial to implement. I will make sure it's in 3.0.1.

@ylian:  Awesome!  I can really use this also.  :+1:

**Comment by JonathanPerkins** [comment]
This is great, but I wonder if you could also include GFM code blocks in addition to code cells? Otherwise if you are preview mode its a bit confusing if some notes with code get copied but others don't.

Thanks!

**Comment by ylian** [comment]
Fixed in 3.0.1. Current behavior is to copy code cells only. I will let people try it out first and see if the behavior needs to be changed.
