### ISSUE TITLE
Wishlist: Merge two cells of the same type

### ISSUE THREAD

**Issue by elbie-x** [HappenApps/Quiver#339]
Just dropping things in here as I come up with use cases... 

The idea is that if someone has, say, md // code // md, and then decides to delete the code and wants to chunk the two md blocks together, it would make sense to be able to Merge Cells, rather than cutting, pasting, and deleting, as I think has to be done at present.

I've noticed that one can't select multiple cells at once, and I guess there's probably some good reason for this -- in which case perhaps 'Merge with Adjacent Cell' (of the same type) might be the way to go?

**Comment by ylian** [comment]
Oh you can merge adjacent cells of the same type. Just place the cursor at the beginning of the second cell, hit backspace.

**Comment by elbie-x** [comment]
Nice! Thanks again.
