### ISSUE TITLE
Preview layout borked?

### ISSUE THREAD

**Issue by evaneykelen** [HappenApps/Quiver#34]
The layout of the Markdown preview looks odd:

![2015-02-11 at 19 50](https://cloud.githubusercontent.com/assets/11846/6153765/4d705b9a-b227-11e4-9139-d4bfcd89c47d.png)

**Comment by ylian** [comment]
That's odd. Did you add any CSS customization to the preview?

**Comment by ylian** [comment]
Mine looks like this.
![screen shot 2015-02-11 at 1 54 03 pm](https://cloud.githubusercontent.com/assets/984895/6153847/799ffa22-b1f5-11e4-974b-497a53c65219.png)

**Comment by evaneykelen** [comment]
Another screenshot, just taken:

![2015-02-11 at 20 22](https://cloud.githubusercontent.com/assets/11846/6154410/cef6f56c-b22b-11e4-8ee5-4cf45608ad3b.png)

**Comment by ylian** [comment]
Can you send your settings file to support@happenapps.com? Thanks.
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/settings.json

**Comment by nschneid** [comment]
Those look like they might be extra scrollbar tracks.

**Comment by ylian** [comment]
Thanks. That seems to be the case. I will check the default CSS. Maybe some versions of WebKit has different default settings for scrollbars.

**Comment by ylian** [comment]
Yep I am pretty sure this is a side effect of fixing #25. I should have used .cell {overflow: auto}. It didn't happen to me so it slipped through.

Anyway, you can fix it now by adding the following to the preview CSS:

``` css
.cell {
  overflow: auto;
}
```

Give it a try and let me know. Thanks.

**Comment by evaneykelen** [comment]
See https://gist.github.com/evaneykelen/ac6f665c9ca964544c67 voor settings.json

**Comment by evaneykelen** [comment]
Ref `.cell { overflow: auto; }` => that fixes it!

**Comment by ylian** [comment]
Thanks for testing. I will fix this in 2.1.1.

**Comment by ylian** [comment]
Fixed in 2.1.1.

**Comment by ylian** [comment]
Note that I had to retract 2.1.1 due to a separate issue. Please wait for 2.1.2 to verify this fix.
