### ISSUE TITLE
Enable Delete keyboard shortcut

### ISSUE THREAD

**Issue by danielecook** [HappenApps/Quiver#343]
Any chance a keyboard shortcut could be added for deleting notes? The <kbd>delete</kbd> key would be good.

**Comment by dkarter** [comment]
![image](https://cloud.githubusercontent.com/assets/551858/12121672/2226f92c-b39c-11e5-88de-330df8a4db82.png)
You can also change it through the Keyboard preferences on your Mac settings to whatever you like.

**Comment by danielecook** [comment]
Ah thanks - I was looking in the 'edit' menu where the shortcut is not present!
