### ISSUE TITLE
Draw charts and diagrams

### ISSUE THREAD

**Issue by jerald-acacus** [HappenApps/Quiver#344]
Feature request here.
It would be nice if we can have the ability to draw shapes and lines in Quiver for flowcharts, data flows, etc.

**Comment by fomotoshi** [comment]
+1

**Comment by nonatomiclabs** [comment]
:+1:

**Comment by paulelms** [comment]
++++++++ 👍🏼

**Comment by jeffkimbrel** [comment]
Isn't there already an existing cell type to do this?

**Comment by arougthopher** [comment]
Yes, there is a Diagram Cell Type for doing flowcharts and sequence diagrams:

### Diagram Cell

Diagram cells let you create sequence diagrams and flowcharts from text.

Please check the syntax here:
- Sequence diagram: http://bramp.github.io/js-sequence-diagrams/
- Flowchart: http://flowchart.js.org/
