### ISSUE TITLE
increase font size by hotlkey

### ISSUE THREAD

**Issue by fomotoshi** [HappenApps/Quiver#345]
I use the 4k and rMBP 13" external display. During the day, I often leave my office. I take my laptop and go to another place. I need to change CSS settings every time because when I work in the office I use only the external display and a very small font.

I would like to have the possibility to change the font size (in the editor mode and preview) in the app by the hotkey (for example, CMD + scroll).

Good luck!

**Comment by ylian** [comment]
Good idea. Will implement in the future.

**Comment by jayceekay** [comment]
`cmd + -` and `cmd + =` are standard on osx. just came looking to see if this existed as well, as sometimes i have an external monitor which sits a bit farther away and would like to zoom in or increase the font size ala google chrome.

**Comment by dkarter** [comment]
+1 for `cmd + +` and `cmd + -`

**Comment by ghost** [comment]
Is there a way to change the font size manually? I can't find where. When I go to format >> Show Fonts. The window about changing font sizes and type appear but never update.
![2016-01-08_1653](https://cloud.githubusercontent.com/assets/4752947/12210484/5a112202-b628-11e5-9cd1-c61d22f3f9c5.png)

I assume that is to make the size of notebook note bigger?

**Comment by ylian** [comment]
@jonathanbello Right now, the only way to change font size is in CSS: Preferences > Styles > Editor or Preview CSS. If you want to set a default font for the whole note, you can set it on the `<body>` element:

``` css
body {
  font-family: Georgia;
  font-size: 17px;
}
```

**Comment by hSATAC** [comment]
Really need this. Changing font-size css manually over and over again is too overwhelming when switching between 4k & other monitors.

**Comment by johnnylai** [comment]
+1

**Comment by ofstudio** [comment]
+1

**Comment by rimblas** [comment]
+1 for `cmd +` and `cmd -`

**Comment by n3bulous** [comment]
+1 Actually, we should be allowing zooming, so that the fonts are not intrinsically changed, but the view is made larger/smaller.

**Comment by nasht** [comment]
👍 for cmd +/- zoom

**Comment by derickfay** [comment]
+1

**Comment by ssteinerx** [comment]
+1

**Comment by bartimez** [comment]
+1

**Comment by ssteinerx** [comment]
New version soon?

**Comment by AnthonyShipman** [comment]
Would also love to see this.

**Comment by trevorzhou** [comment]
Love the app but it was too small in full resolution on 15 macbook. I love more space really need full resolution.

**Comment by bensethbell** [comment]
+1 on zooming especially without changing font size

**Comment by ghost** [comment]
+1-- w/o actually changing the actual font size.

**Comment by JMichaelTX** [comment]
> +1 on zooming especially without changing font size

> +1-- w/o actually changing the actual font size.

### We Need two different sets of shortcuts
1. _Zoom_ -- **Increase/Decrease the font sizes of all text in the window as they appear without actually changing the underlying font size**
    * Much like how a Browser zoom works.
2. _Font Size_ -- **Increase/Decrease the actual font size of text as stored in the Note cell.**
    * If it is a (rich) Text Cell, then it should apply only to selected text
    * If it is a code cell, it should apply to all text in the cell for that language, effectively increasing/decreasing the CSS point size.  It would apply to all code cells of that language, the same as making a change to the CSS settings.
    * I'm not sure about the other cell types, as I rarely use them.  Someone else will need to suggest a rational approach.

**Comment by BeyondTheProof** [comment]
+1

**Comment by rehmanzile** [comment]
👍

**Comment by aldanor** [comment]
👍 👍 👍

**Comment by thromera** [comment]
👍

**Comment by dcdanko** [comment]
+1

**Comment by pf22099** [comment]
+++

**Comment by santouras** [comment]
please please, this is one thing that kills me when I'm using quiver
