### ISSUE TITLE
[Feature request] Add shortcut to jump to tags in a note

### ISSUE THREAD

**Issue by dkarter** [HappenApps/Quiver#348]
Probably the only feature that's missing right now in my workflow to make Quiver completely mouse free is jumping to the tag list when creating a note. It would be cool to have a keyboard shortcut that allows editing the tags by focusing on the tag field.

Here's Evernote's implementation:
![image](https://cloud.githubusercontent.com/assets/551858/12218093/b56936dc-b6da-11e5-88bb-1ea460600ca8.png)

As long as it is in the menu it would be easy for users to customize what that shortcut is.

Thanks!

**Comment by ylian** [comment]
Yep will do. I should have a build with this by Monday.

**Comment by thenet** [comment]
+1

**Comment by ylian** [comment]
This is implemented in Quiver 3.0.1 beta (#361).

**Comment by dkarter** [comment]
Thanks much @ylian works perfectly!!

**Comment by ylian** [comment]
3.0.1 is released.
