### ISSUE TITLE
Typing right or down arrow at end of line before empty bullet point

### ISSUE THREAD

**Issue by nschneid** [HappenApps/Quiver#35]
In Quiver 2.1, with the following note in text mode:

<ul><li>asdf</li><li>ghjk</li><li></li></ul> 

Expected behavior: Positioning the cursor after the "k" and arrowing right or down should move the cursor to the third bullet line.

Observed behavior: The last non-empty bullet is treated as the end of the note, so the cursor will only move to the next note if there is one, skipping the last bullet.

**Comment by ylian** [comment]
Yep that's a real bug. Will fix shortly. I will wait a few days to gather little bugs like this before sending in v2.1.1.

**Comment by ylian** [comment]
Fixed in 2.1.1.

**Comment by ylian** [comment]
Note that I had to retract 2.1.1 due to a separate issue. Please wait for 2.1.2 to verify this fix.
