### ISSUE TITLE
Export Markdown incl image

### ISSUE THREAD

**Issue by jkjelsbak** [HappenApps/Quiver#351]
Version 3.9 (66)

When notes including images are exported as Markdown the images will be filed in a **resources** subdirectory, but the markdown text files still have **quiver-image-url** as part of the image reference for some images.

**Comment by ylian** [comment]
Good find. Just fixed in my dev build, a beta build soon.

**Comment by ylian** [comment]
Fixed in 3.0.1.

**Comment by zachmaurer** [comment]
Was this fixed completely? I'm running 3.0.6 and the .md documents I upload to Github do not properly display the images in the resources folder. Do I have to modify the image markdown elements to get them to render?
