### ISSUE TITLE
When opening a .qvnote package belonging to the current library, Quiver suggests to import it

### ISSUE THREAD

**Issue by ffdumont** [HappenApps/Quiver#355]
I need to manage links to Quiver pages in other tools. I use shortcuts to .qvnote packages, but when I open this package, Quiver suggest to import it. I would rather prefer Quiver to raise the corresponding page in the library.

**Comment by ylian** [comment]
This should be fixed. Thanks.

**Comment by ylian** [comment]
Fixed in 3.0.2.
