### ISSUE TITLE
code cell is invisible in preview mode

### ISSUE THREAD

**Issue by sapjax** [HappenApps/Quiver#359]
![screen shot 2016-01-15 at 12 26 44 pm](https://cloud.githubusercontent.com/assets/990255/12345399/4d04b0a0-bb83-11e5-99d1-3fbef9d1cae5.png)

Version 3.0 (66)

**Comment by ylian** [comment]
I can't reproduce this. Does this happen to other notes? If you switch to the default theme (light), restart the app, does it work?

**Comment by sapjax** [comment]
@ylian   you're right.   default theme works well, only "Reddish Theme" has such problem.

**Comment by ylian** [comment]
@sapjax Yep, I just sent a pull request to the theme's creator. You can also just open the theme, scroll to near the bottom, and change "Crimson Editor" to "crimson_editor". Then restart the app.

**Comment by sapjax** [comment]
@ylian thanks! :+1:
