### ISSUE TITLE
Save Notebooks to Local Filesystem vs. Library Location

### ISSUE THREAD

**Issue by preflight** [HappenApps/Quiver#36]
If the app could support it, I'd like to be able to save individual Quiver notebooks to my local filesystem in the folders of my choice rather than to the Library Location set in Sync preferences. For instance, my notebook(s) on Clojure would go in my Clojure folder, Haskell in Haskell, etc.

The benefit to doing it this way is that Quiver notes would be saved in the same place where I have my other documents on that subject. I suspect most users also have a folder structure set up for their non-Quiver documents (Word docs, PDFs, text files, etc.) for the subjects they track/study, and it would be ideal to treat Quiver notebooks like a file that can be opened from that location, edited in Quiver, and saved back to the same location.

I've tried exporting a notebook to a local folder, closing the existing one in Quiver, and then opening the one I saved, but it always saves back to the Library Location.

**Comment by ylian** [comment]
I think you can already do this. First export the notebook to a local folder, remove the existing one in Quiver (clear the trash as well), then open the saved notebook as shared.

**Comment by ylian** [comment]
If a "shared notebook" is not in a cloud-synced folder, it's just a local file.

**Comment by ylian** [comment]
Close this since this is already supported.

**Comment by preflight** [comment]
Thanks for explaining, I didn't understand how shared notebooks work
