### ISSUE TITLE
[Request] Copy and paste of images from clipboard while in non 'Text Formatting'

### ISSUE THREAD

**Issue by aeroechelon** [HappenApps/Quiver#360]
A common part of my note taking workflow is to take a screenshot of something and then paste it into a note. However, to avoid polluting my desktop with tons of screenshots, I simply take a screenshot to copy to clipboard.

Would be useful to copy and paste images from clipboard into Quiver while using another format than 'Text Formatting'.

**Comment by dkarter** [comment]
You can do that with the text cell. But I agree it would be cool to be able to paste into markdown cell and get the file copied to the quiver directory and embedded with markdown markup.

**Comment by ylian** [comment]
Implemented in 3.0.6. Now you can paste an image from the clipboard into a Markdown cell.
