### ISSUE TITLE
evernote too much can't import

### ISSUE THREAD

**Issue by imkratos** [HappenApps/Quiver#369]
my evernote note all 333 item,export to *.enex , can't import quiver, not response,nothing 

info:
os  :  mac os 10.11.2
evernote : 6.3
quiver: 3.0

**Comment by ylian** [comment]
Can you try the build 3.0.1 in #361?

If it still doesn't work, send me the .enex file and I will fix.

**Comment by ylian** [comment]
Close this. 3.0.1 fixed a bug in the Evernote importer.
