### ISSUE TITLE
quiver 3 markdown mode comment problem

### ISSUE THREAD

**Issue by skymoney** [HappenApps/Quiver#370]
i'm using quiver 3, and in markdown mode, I want to use comment(or code style?) like this

```
comment with tab
```

but in quiver, it always show line num before like this,

```
 1, comment with tab, line num before
```

 so is there another way to do this or am i wrong?

**Comment by ylian** [comment]
One tab or four spaces generate a code block, not a comment.

You can turn off line numbers for the code block if you like, in Preferences > Cells > Code Cell > uncheck line number.

**Comment by skymoney** [comment]
ok, I see, A little different from macdown or mou setting.

**Comment by jhalter** [comment]
I ran into this as well.  My expectation is that code blocks in GFM should render in the same way that Github renders them, so I was a bit confused by this.

Thanks for the solution.
