### ISSUE TITLE
[Feature Request] Export Group of Notes as one PDF

### ISSUE THREAD

**Issue by fbrubacher** [HappenApps/Quiver#372]
Hi Thanks for the great app. I would love to have the ability to group notes (maybe merge into one and then) export into a pdf all of them together instead of different PDFs.

**Comment by ylian** [comment]
You can already do that. Select multiple notes from the list, then choose "Export Notes" from the right pane. You have an option to export as "a single PDF". You can right click on a notebook and export all the notes inside into a single PDF as well.
