### ISSUE TITLE
[Feature Request] If adding a link to an existing text in Markdown, the selected text should be inserted in the 'Title' field

### ISSUE THREAD

**Issue by aeroechelon** [HappenApps/Quiver#373]
While using Markdown, when you click `CMD + K` (Add/Edit Link) the selected text should automatically be placed in the title field. Currently this is the behaviour while using 'Text Cell'.

<img width="508" alt="screen shot 2016-01-24 at 4 21 48 pm" src="https://cloud.githubusercontent.com/assets/2360095/12539004/976cd084-c2b6-11e5-8417-5c20c0d86eb7.png">

**Comment by ylian** [comment]
Great find. Will fix.

**Comment by ylian** [comment]
Fixed in 3.0.2.
