### ISSUE TITLE
Width of the editor?

### ISSUE THREAD

**Issue by akaman** [HappenApps/Quiver#376]
Is is possible to have a max width of the text area of the editor? When taking notes in a meeting, I like working in a single note in full screen (cmd-1, cmd-4). This means that the text in the entire width of the screen, which isn't comfortable (for eyes) for writing.  It would be nice if there is a max width, like nvAlt and other apps. 

I feel this should be a CSS setting, but I tried a couple of attributes and it didn't seem to work.

TIA,
aka

**Comment by ylian** [comment]
You can set like this:

``` css
body {
  max-width: 800px;
  margin: 0 auto;
}
```

**Comment by akaman** [comment]
Works great.  Thanks.  I knew it would be easy.
