### ISSUE TITLE
Does Markdown cell support `table of content` feature?

### ISSUE THREAD

**Issue by hanks** [HappenApps/Quiver#377]
And click link will jump to the specified place

Like:  
**Table of Contents**  
- [a](#a)
- [b](#b)
- [c](#c)
- [d](#d)
## a

demo
## b

demo
## c

demo
## d

demo

**Comment by aeroechelon** [comment]
+1 for this feature

**Comment by ylian** [comment]
TOC support is planned, not just for Markdown cells.

**Comment by acrodrig** [comment]
+1

**Comment by hanks** [comment]
+1

**Comment by lezh** [comment]
+1

**Comment by YujiShen** [comment]
+1 for "not just for Markdown cells". So I can create really long notes like a Wiki!

**Comment by scott-mead** [comment]
+1 for TOC.  This is how I ditch all of my other editors completely!

**Comment by bnsblue** [comment]
@ylian May I ask if there's any plan to release this feature in near future? Thanks!

**Comment by liweijian** [comment]
+1

It has been more than 6 months

**Comment by junhocho** [comment]
+ 1

**Comment by acrodrig** [comment]
If it is useful for anyone in this thread, while waiting for this feature I wrote a small script that builds the TOC (see this [blog post](https://medium.com/@acrodriguez/one-liner-to-generate-a-markdown-toc-f5292112fd14)). I usually have to copy my Quiver note into a separate file to run it.

**Comment by adison** [comment]
+1

**Comment by ChristianClassen** [comment]
+1 , really needed feature to work with large markdown files

**Comment by quietin** [comment]
+1

**Comment by m-jacobi** [comment]
+1

**Comment by cameronwlewis** [comment]
+1

**Comment by asdfgeoff** [comment]
+10

**Comment by HappyBangs** [comment]
+11

**Comment by 1ce0ear** [comment]
+1

**Comment by op1490** [comment]
+1

**Comment by qiaokang92** [comment]
+1 a year passed, any progress?

**Comment by dnng** [comment]
+1

**Comment by coolgoose85** [comment]
+1

**Comment by rayaman** [comment]
+2

**Comment by skyfire417** [comment]
+1

**Comment by rafaelsuguiura** [comment]
+1

**Comment by m-jacobi** [comment]
+1

**Comment by zfanswer** [comment]
+1 really need this feature, even only shows on preview panel

**Comment by zfanswer** [comment]
oops, this issue is closed, but why?

**Comment by andreilupe** [comment]
'+ 1

**Comment by czlhs** [comment]
`+2`

**Comment by ahlixinjie** [comment]
+1

**Comment by nblopes** [comment]
It looks like development has stopped.

**Comment by likaiguo** [comment]
It looks like development has stopped.

**Comment by likaiguo** [comment]
+1

**Comment by fbruch** [comment]
+1

**Comment by RadioHeadach** [comment]
+1

**Comment by codycodes** [comment]
+1

**Comment by euii** [comment]
+1

**Comment by mengfeimu** [comment]
+1. seems this feature is not added yet. Hope to see it in the near future.

**Comment by enovid** [comment]
+1

**Comment by backwind1233** [comment]
+1000000000000000000000000000000000000000000000

**Comment by rockyzhang24** [comment]
+1

**Comment by xealgo** [comment]
++i

**Comment by xianlinglu** [comment]
+1

**Comment by alexdetrano** [comment]
+1

**Comment by jmontroy90** [comment]
+1

**Comment by denkensk** [comment]
+1

**Comment by chuckleong21** [comment]
For those want to add a TOC manually, please refer to [How to add footnotes to GitHub-flavoured Markdown?](https://stackoverflow.com/a/29384216)
This is also how you direct the footnotes in markdown to footnotes' content.

**Comment by 0x67cq** [comment]
+1， very very need toc, looking forward v3.3.0

**Comment by moderato** [comment]
+1, can't believe it has been four years and 'table of content' is still not supported

**Comment by ijoseph** [comment]
This project is in the regime of abandonware nowadays, unfortunately. Quite a shame, as it is an incredible piece of software.

**Comment by secyp** [comment]
+1
