### ISSUE TITLE
[Feature Request]: Add a "Show in Finder" for media

### ISSUE THREAD

**Issue by acrodrig** [HappenApps/Quiver#378]
It would be nice to to have a "Show in Finder" context menu like some Apple apps (Photos and iTunes come to mind). Something like:

![screen shot 2016-01-27 at 10 52 28 am](https://cloud.githubusercontent.com/assets/959336/12624493/41606784-c4e4-11e5-9e47-916e8f7c4fdb.png)

**Comment by ylian** [comment]
Coming in 3.0.2.

**Comment by ylian** [comment]
Fixed in 3.0.2.
