### ISSUE TITLE
[Feature Request] - Change Diagram Library to Mermaid

### ISSUE THREAD

**Issue by arougthopher** [HappenApps/Quiver#382]
https://github.com/knsv/mermaid

The mermaid library is being actively developed, provides 3 diagram types (flow, sequence, gantt), and appears to be much more feature rich.
Though flowchart.js was updated recently, I don't see any significant changes, and sequence.js has not been updated since last year.

**Comment by drumanagh** [comment]
It looks like #422 is another request like this.

**Comment by ylian** [comment]
Merge into #433.
