### ISSUE TITLE
Most wanted features and other ideas

### ISSUE THREAD

**Issue by tomibennett** [HappenApps/Quiver#384]
I've recently been through issues here, and something appears to me. Here what it is.

It seems that lot of those issues _treat of wanted features_ and among them, the same feature are asked multiple times. See for the TOC example:
#377, #368 and #30 (more or less for the last one).

AND I'm very interested by the TOC too.

What it came to me is that rather than flooding you more. I propose you a new way to manage these request features.

It would be to redirect people into a webpage where they can vote for the requested feature or propose a new one.
- Thus, **as user**, we can now what it's most likely to be develop next
- and you **as developer**, you can:
  - have a better view of what user want
  - stop beeing flooded by new issues whose subject is most likely already treated somewhere else
  - get rid of these `+1` thing since Github didn't plan to support them [see for yourself](https://github.com/isaacs/github/issues/9). (Since 2013, last updated two days ago)

You've got a more popular tool everyday and you appear  to be alone on it.
Saying "planned" or "under development" is maybe not what you like to say the mose.

I'm not necessarily speaking of some nerdy/complicated/expensive tool. It can be a simple and free like a Trello board. It's what been used by [devdocs](https://trello.com/b/6BmTulfx/devdocs-documentation

**Comment by dkarter** [comment]
I think the key is creating a plugin system that will allow developers do what they do best. It could be that all you'll need to do is expose an api for people to write ruby scripts. This will create a flourishing ecosystem around quiver and will alleviate a lot of pressure off you. 

It will also keep quiver performant for those who elect to keep the feature base to a minimum and not install a lot of plugins.

**Comment by tomibennett** [comment]
@dkarter I'm not sure it's the Quiver's ambition. It's just a point of view, because, of course, I can't answer for it's creator.

I think, the plugin way doesn't fit here, it's not flashlight or ubersicht or whatever. Quiver was not designed to this.
Don't make me wrong I like tools like flashlight (RIP), übersicht, or configure my vim and my system itself.

But For me, the problem with plugins is that, users spend half-time using them and half-time review them because there are most likely fast developed and buggy.

Also, Quiver's features are secure, complete and, not buggy, neither halfway developed. And it's the reason we like to use this app.
We're not spending our time to looking for new plugins because the one recently installed is full of crap or not doing exactly what we wanted it to do but instead, we're using the app itself, requesting for features time to time because we can.

**Comment by ylian** [comment]
Thanks guys. But no worries. I have been mostly working on the iOS app for the last two months, so progress on the Mac app has been slow. But lots of things will be completed in the next couple months.

**Comment by cswarth** [comment]
I don't understand this common development trajectory.  What is the fascination with porting these types of note-taking apps to the IOS and android platforms?  Does anyone really sit down and tap out some notes with their thumb on a crappy screen keyboard with a 4-inch display?    I presume that's where the money is but I really don't understand what the appeal is.

**Comment by ylian** [comment]
@cswarth Quiver for iOS is the most requested "feature" since Quiver 3 was released two months ago. I have close to a thousand users signed up for beta testing as of today.

Most people just want to read their notes on the go. So a good syncing implementation is a must.

**Comment by skypanther** [comment]
I'd love to have access to my notes when away from my desktop. Unfortunately, I'm an Android user.

**Comment by ylian** [comment]
Closing this. More updates are coming.

**Comment by jcrben** [comment]
Where can we look for future updates on mobile functionality? Android user here.

**Comment by ylian** [comment]
@jcrben There is a Android app built by someone in the community: https://play.google.com/store/apps/details?id=net.andrewt.quaver&hl=en

**Comment by ChristophBoget** [comment]
Closed because there is no plan to implement this?  Super sadness...
