### ISSUE TITLE
How can I rename a Notebook

### ISSUE THREAD

**Issue by cursorzz** [HappenApps/Quiver#385]
is there any way to rename an newly created notebook or I missed something?

**Comment by ylian** [comment]
Just click on the notebook name, or right click and select "Rename Notebook".

![image](https://cloud.githubusercontent.com/assets/984895/12707647/e5b33c2a-c864-11e5-8778-08c9d8ee38ea.png)

**Comment by cursorzz** [comment]
oh thx for the quick reply, I was confused because I accidently choose the two panel view before but forget there's an extra panel to edit those things.

**Comment by eddyg** [comment]
FWIW, I came here with the same question.

This behavior is not obvious _unless_ you are in the "Three Panes" view.

**Comment by ryandeussing** [comment]
Holy mackerel this took me ages to figure out. I think there could be a more intuitive way to see how to edit while in other views ;)

**Comment by ddh** [comment]
Google search landed me here. Couldn't find it at first!

**Comment by craigp** [comment]
Google search as well, very non-obvious.

**Comment by sorrisobloc** [comment]
Doesn't seem to work for me. When I click I follow the instruction it just takes me to the notebook and right clicking does not give the "Rename Notebook" option. What am I doing wrong?

**Comment by sorrisobloc** [comment]
Never mind, I found it. It's a little unintuitive. Complete agree with @eddyg

**Comment by Kadrian** [comment]
To give some counter-argument here: I found it right away. Always working with the notebook sidebar as well :-)

**Comment by jianhaiqing** [comment]
oh, my god. It's really hard to figure out how to performance rename operation, as well as the three panes.

**Comment by emptymalei** [comment]
same two-panel problem. 😭

**Comment by humblefeet** [comment]
SO simple! haha Thank you. I was stuck on 2 panels the whole time

**Comment by themoenen** [comment]
Unacceptable UX fail, this ticket should never have been closed.
