### ISSUE TITLE
Emacs-like keybindings in Markdown Cell

### ISSUE THREAD

**Issue by anisiomqs** [HappenApps/Quiver#387]
Hey, some emacs keybindings, which you can use by default in other apps are not working in a markdown cell, although they work properly in a text cell. C-p, for instance, does nothing (it should go to the previous line). Others are working fine, like C-a and C-e.
Other thing I would like to suggest is for you to consider the custom kebindings that the user puts in `~/Library/KeyBindings`. They are supported in the text cell but not in the markdown cell.

**Comment by ylian** [comment]
Markdown cells use the Ace editor, so keybinding works differently. To use Emacs keybinding in a Markdown cell, go to Preferences > Cells > Markdown Cell, and change the keybinding to Emacs:

![image](https://cloud.githubusercontent.com/assets/984895/12717668/47d70dda-c8b7-11e5-99a2-ec259072c565.png)

**Comment by anisiomqs** [comment]
Hello. Sorry for that. I didn't know about these options. Thanks for the help.
