### ISSUE TITLE
Issues with vi keybindings in markdown blocks

### ISSUE THREAD

**Issue by jess-sol** [HappenApps/Quiver#389]
Two issues I've noticed while playing around with quiver: 1) zz, zb, and zt shortcuts don't work.  They should put the cursor at the center/bottom/top of the screen (by scrolling).  And 2) typing "r " should replace the character under the cursor with a space, but instead it replaces the character under the cursor with the word "space".

It'd also be nice if you guys picked up my ~/.vimrc, but I'd understand if that isn't possible.  Being able to pick an alternative key-sequence to exit would be nice (I like mapping "kj" to go to command mode).

**Comment by ylian** [comment]
I'm aware of these issues. These are limitations of the Ace editor. And I will get to these after the iOS release.

**Comment by benjamincharity** [comment]
I've also noticed that I can't seem to get into visual block mode with `ctrl+e` but get sent to the end of the cell.

**Comment by dkarter** [comment]
see issue #230

Visual block mode is ctrl-v. it's supported on Ace but somehow not turned on in quiver. I really miss it. @ylian said he will fix it in the issue referenced above.

**Comment by benjamincharity** [comment]
@dkarter Good find. Figured someone else had hit that one.

**Comment by ylian** [comment]
My apologies. Here is a build with the visual block mode enabled. I have updated Ace to the latest version (1.2.3). Please help me test Ace-related functionalities (code cell, Markdown cell) to make sure this new version is stable. Thanks.

https://dl.dropboxusercontent.com/u/3445731/Quiver%203.0.2%20Build%2082.zip

**Comment by ylian** [comment]
@ioben Issue 2 is fixed with the latest Ace version. Issue 1 is unlikely to be fixed, since those commands apply to the cell, not the whole editor. Custom keybinding is possible, but needs some UI for that.

**Comment by ylian** [comment]
Visual blocks are now supported in 3.0.2.
