### ISSUE TITLE
Shortcuts don't work with numpad numbers

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#39]
Shortcuts involving numbers (example `ctrl-shift-3` for Headings 3) don't work if the button `3` is pushed in the numpad

**Comment by ylian** [comment]
This is a bug in HTML contenteditable. I created a test project with just an HTML contenteditable, and shortcuts like `ctrl-shift-3` don't work there either, if using the numpad.

Mark as "Won't Fix".
