### ISSUE TITLE
[Feature Request]: shift-right and shift-left

### ISSUE THREAD

**Issue by cswarth** [HappenApps/Quiver#393]
Microsoft OneNote, but not Evernote, has the ability to shift a paragraph or image left or right.
I really miss that functionality.

![screen shot 2016-02-02 at 2 55 32 pm](https://cloud.githubusercontent.com/assets/295428/12767395/c52da77e-c9bd-11e5-83a9-d1ee8302648c.png)

_You have made an awesome tool - one I was happy to pay for!_

**Comment by cswarth** [comment]
This is likely a duplicates of #316
Sorry I didn't notice that before submitting.

**Comment by ylian** [comment]
Closed as a duplicate of #316.
