### ISSUE TITLE
Function to open linked notes in a new window

### ISSUE THREAD

**Issue by rasbt** [HappenApps/Quiver#397]
Hi, 
I just gave Quiver a try and really love it so far! I have a little suggestion for the feature list. It would be really nice to add an "open link in a new window" feature to the context menu for linked notes (I attached a screenshot below to illustrate what I mean). This would be an extremely handy feature ... For example, let's say your main note is an outline of some sort, and you have several resources linked to it; it would be nice to be able to continue editing this outline while opening these "linked contents" for skimming. 

Cheers,
Sebastian

![screen shot 2016-02-03 at 1 32 47 am](https://cloud.githubusercontent.com/assets/5618407/12774775/12f505e4-ca16-11e5-887f-0d092d49abb0.png)

**Comment by dkarter** [comment]
Command + clicking the link will do it. :)

**Comment by rasbt** [comment]
Thanks for the tip. I tried it on 2 separate machines (both running Version 3.0 (66) from the Appstore) and it doesn't seem to work :(. Somehow, it's ignoring the command button.

**Comment by ylian** [comment]
@rasbt Oh, cmd+click is added in 3.0.1. You can try the build here: https://github.com/HappenApps/Quiver/issues/361

3.0.1 is currently waiting for review.

**Comment by rasbt** [comment]
Cool, thanks!

**Comment by ylian** [comment]
3.0.1 is released. Cmd+click is supported.
