### ISSUE TITLE
Memory use and scalability

### ISSUE THREAD

**Issue by rasbt** [HappenApps/Quiver#398]
Hi, 
I just got started with Quiver and just important some note files from text and markdown files, plus, I attached a few PDFs.
When I started with an "empty" Quiver application (Version 3.0 (66)), I saw that it was using about ~60 Mb of RAM. Now, after I added these 32 notes, I am at ~135 Mb RAM usage. Now, I am a bit concerned about scalability and wanted to ask you if this is normal? What can I expect in terms of Ram usage if I've let's say > 200 - 500 notes? I don't mean to criticize here, but I am just wondering what other users, who have used Quiver for a while, have experienced so far in terms of RAM use.

![screen shot 2016-02-03 at 1 41 30 am](https://cloud.githubusercontent.com/assets/5618407/12774920/91595ace-ca17-11e5-8d56-69a5912739e0.png)

**Comment by dkarter** [comment]
I have 250 notes and mem usage is at 125MB
![image](https://cloud.githubusercontent.com/assets/551858/12774986/f2239854-ca0f-11e5-80c4-b066d793a8e7.png)

**Comment by rasbt** [comment]
Thanks for the info. Sounds like 120 - 140 Mb is probably the normal range regardless of the number of notes?

**Comment by dkarter** [comment]
I am not in a position to know but I did notice a correlation to type of note you have open. Notes reach with graphics take more memory:
![image](https://cloud.githubusercontent.com/assets/551858/12775156/65153740-ca11-11e5-99d3-d4fe54f783bd.png)

**Comment by ylian** [comment]
@rasbt The editor and preview use webviews. As you switch notes, memory used by previous notes are garbage collected. But since webviews use garbage collection instead of ARC like in Cocoa, the system controls when to release the memory. So you would see memory usage climb up, but it will go down once the system kicks off garbage collection (the exact timing depends on memory pressure and other system resources).

**Comment by rasbt** [comment]
Thanks for the insights @ylian . So, even having > 10,000 notes wouldn't really impact the memory use -- unless I do a search or so?

**Comment by ylian** [comment]
@rasbt That's right, the number of notes isn't a concern here. Only note metadata are loaded into the memory. Note contents are only loaded when you open the note, and released when the note is no longer open in any window. 10,000 notes' metadata are only about 10,000 \* 100 bytes = 1MB.

Most memory usage comes from the webviews: images, diagrams, LaTeX equations can use quite a bit memory, but the memory will be released by the system when switching away from the note (again, exact timing of garbage collection depends on memory pressure, etc.)

Also, search doesn't incur much more memory usage. Quiver uses Spotlight search, not searching notes one by one. So it's an indexed search, and should incur little memory cost.

**Comment by rasbt** [comment]
Oh nice; honestly, I was a bit concerned about scalability, but that's sounds great! I guess I found me a new favorite note taking app then :)

**Comment by ylian** [comment]
@rasbt I have tested with 8000 notes myself, and app startup, usage and search are all quite fast. I will keep improving app performance regardless.

**Comment by rasbt** [comment]
I think if it stays around the 100-200 Mb that's just fine! If I remember correctly (has been a while) comparable apps like Evernote used about half of it. However, I think the markdown rendering/preview is quite expensive itself. Haven't seen a markdown editor that was significantly under 100Mb; so, really good job here with Quiver!
