### ISSUE TITLE
ACE Editor - Activate Vim or Emacs keybindings

### ISSUE THREAD

**Issue by avendael** [HappenApps/Quiver#4]
I've read somewhere that the editor is based on the ACE editor. In their [about](http://ace.c9.io/#nav=about) page, they listed that it's possible to have Vim and Emacs keybindings. Can this be turned on in Quiver?

**Comment by ylian** [comment]
Implemented in Quiver 2.1. Go to "Preferences", then change keybindings for the code cell. You can change keybindings for the Markdown cell and LaTeX cell as well.

**Comment by LosMyke** [comment]
Are there plans to extend Vi & Emacs key bindings to text cell?

**Comment by ylian** [comment]
@LosMyke No, that's not feasible. Text cells use HTML contenteditable, while other cells use the Ace editor. Reimplementing all the contenteditable behavior (text and image wrapping, drag and drop, etc.) plus Vi/Emacs key binding would be an impossible task.
