### ISSUE TITLE
Right arrow at the end of a text cell

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#40]
Steps:
- In a text cell I select a word (for example to apply the style bold) 
- the word is the last word of the cell (no new lines after it)
- there isn't any new cell after the one I'm working on
- I try to deselect the word by pressing the right arrow key  

Result:
Nothing happens. I have to press the left arrow key to deselect the word, then press `alt+right arrow` to position the cursor at the end of the last word.

Most probably this is due to the shortcut of the right arrow positioning the cursor to the next cell if we are at the end of a cell.

**Comment by ylian** [comment]
Thanks. Will fix in 2.1.1.

**Comment by LeonardoGentile** [comment]
Thanks :+1:

**Comment by ylian** [comment]
Fixed it in my dev branch last night. Going to submit v2.1.1. today.

**Comment by ylian** [comment]
Fixed in 2.1.1.

**Comment by ylian** [comment]
Note that I had to retract 2.1.1 due to a separate issue. Please wait for 2.1.2 to verify this fix.
