### ISSUE TITLE
Markdown cell formatting issues

### ISSUE THREAD

**Issue by kevnm67** [HappenApps/Quiver#401]
Recently markdown cells are acting strangely:
- Selecting text highlights a different area (see image at the following link) http://snpy.in/j2aL5c
- Editing text moves the cursor to a random spot in the cell but editing resumes where the cursor originated.  Similar to the first bullet point.   http://snpy.in/znLRov

Basically, I can't tell what I'm editing because the cursor is consistently in the wrong part of the cell.

**Comment by ylian** [comment]
Markdown cells use the Ace editor, which doesn't support variable-width fonts. Please use a equal-width font for now. Ace bugs will be fixed sometime later.

Merged into #432.
