### ISSUE TITLE
Changing the label of the "Open Another Library..." button

### ISSUE THREAD

**Issue by rasbt** [HappenApps/Quiver#404]
Not a big deal but a little suggestion: I find the label "Open Another Library..." a tad confusing. It seems to me to be saying that an _additional_ library will be opened, rather than opening a _different_ library. I'd suggest changing it to "Open an existing library..." or so.

**Comment by ylian** [comment]
Good point. Will change.

**Comment by ylian** [comment]
Fixed in 3.0.1.

**Comment by rasbt** [comment]
Thanks a lot, I really appreciate it!
