### ISSUE TITLE
Suggestion: custom note order

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#41]
Besides ordering notes by date and name would be nice to have a custom order. 

For example if we are taking notes about a new languages and we are writing the arguments as they are presented in a book would nice to follow the chapter organization so to have a custom order

**Comment by nschneid** [comment]
Do you mean it should be possible to manually order the notes in a particular notebook? (I think this would be useful.) Or specify custom sort criteria (e.g., using regular expressions)? (Not sure how useful that would be.)

**Comment by ylian** [comment]
Yeah I meant manual sorting. Will get to it in 2.2 or later. Some small UI redesign is required.

**Comment by ylian** [comment]
I think manual sorting is useful. Prob. get to it in 2.2 or later. Some small UI redesign is required.

**Comment by LeonardoGentile** [comment]
@nschneid I mean manual sorting within a notebook. And..if feasible apply this also to notebook ( and when ready) to nested notebook. 
So I imagine this to be the fourth sorting option: title, date created, date updated and `manual`

**Comment by ylian** [comment]
That's what I thought too.

**Comment by ghost** [comment]
+1

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
