### ISSUE TITLE
Markdown preview not rendering

### ISSUE THREAD

**Issue by cblanc** [HappenApps/Quiver#410]
Markdown cells will preview when Quiver app first loads. However when I start writing Markdown, it stops rendering altogether

![http://i.imgur.com/3qOKYNy.png](http://i.imgur.com/3qOKYNy.png) 
![http://imgur.com/EaNAo72.png](http://imgur.com/EaNAo72.png)

**Comment by ylian** [comment]
That's weird. Restarting the app should fix it. I think a certain note trigged a JavaScript error that breaks the preview. If you find a way to reproduce this (like open the app, click on a particular note), let me know. That will help a lot.

**Comment by cblanc** [comment]
You're right, there was some embedded javascript which broke the preview.
