### ISSUE TITLE
With Vim binding, code cells can sometimes not access last character

### ISSUE THREAD

**Issue by kandangath** [HappenApps/Quiver#411]
1. Use vim keybinding
2. Create a text cell and type 'Hello'
3. Switch cell to a code cell
4. Attempt to move the cursor to the end of the word. 

Results:
Cursor only moves till 'l' and cannot go past 'o'.

Workaround:
Click outside the cell and click back. Now the cursor can go to the end of the sentence.

**Comment by ylian** [comment]
Fixed in 3.0.2.
