### ISSUE TITLE
Markdown number list returns alphabet list

### ISSUE THREAD

**Issue by emson** [HappenApps/Quiver#413]
When creating a number sublist in markdown, the output (preview) returns it as an alphabetic list. e.g.

```
* Create 2 new buckets
  1. `www.somedomain.com`
  2. `somedomain.com`
```

Will output:
- Create 2 new buckets  
  a. `www.somedomain.com`  
  b. `somedomain.com`

Rather than outputting:
- Create 2 new buckets  
  1. `www.somedomain.com`  
  2. `somedomain.com`

**Comment by ylian** [comment]
This can be set in CSS:

``` css
ol ol, ul ol {
  list-style-type: decimal;
}
```

If you want `i, ii`, use `list-style-type: lower-roman`.
