### ISSUE TITLE
Moving text cursor with mouse

### ISSUE THREAD

**Issue by cblanc** [HappenApps/Quiver#421]
I'm experiencing an odd issue where when I move my text cursor by clicking within a text cell, the text cursor immediately jumps to a different location in the cell when I begin typing. However when I navigate with arrow keys to the location where I want to insert text, the text cursor works as expected.

I'm afraid the document I'm editing can't be shared, however it uses just plain text (alphanumeric + punctuation) broken out into paragraph blocks. Please let me know if there are any other details I could supply

**Comment by ylian** [comment]
If this is in a Markdown cell, and you have changed the font to a variable-width font, see #432.

I can't reproduce this for a text cell.
