### ISSUE TITLE
Feature request : use viz.js instead of flowchart.js for diagram cells

### ISSUE THREAD

**Issue by MaximeArnstamm** [HappenApps/Quiver#422]
viz.js (https://github.com/mdaines/viz.js/) is as simple as flowchart to write but is more powerful and not limited in termes of number of branches or directions

samples of what can be done with it : http://www.webgraphviz.com/

**Comment by drumanagh** [comment]
It looks like #382 is another request like this.

**Comment by arougthopher** [comment]
I would not use webgraphiz if you go that route, but graphiz directly. However, it is eclipse public license. Make sure you read it, as i think there are some copy-left provisions in it.

**Comment by ylian** [comment]
Merge into #433.
