### ISSUE TITLE
Display Mathematics Spacing

### ISSUE THREAD

**Issue by pizzimathy** [HappenApps/Quiver#423]
In LaTeX cells, the spacing of display mathematics (anything in `$$ ... $$` delimiters) is too large.
![screen shot 2016-02-05 at 9 00 58 am](https://cloud.githubusercontent.com/assets/9503402/12849870/7cfcdd54-cbe7-11e5-9377-42de4e9c0fab.png)

The line spacing between display math is a too great, and I don't believe there's an option to change this. Can this be fixed?

**Comment by ylian** [comment]
Yeah, that vertical spacing is quite large. I'm using MathJax's default settings. Not sure if they have a reason to set such a large vertical margin, but you can change it in Preferences > Styles > Preview CSS:

``` css
.MathJax_Display {
  margin: 0;
}
```

**Comment by pizzimathy** [comment]
Thank you.
