### ISSUE TITLE
Cannot delete first checkbox in text cell

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#43]
SYMPTOM 1:
1. Create a text cell.
2. Insert a checkbox as the very first character (by clicking on the checkbox control).
3. You can't delete it.

SYMPTOM 2:
1. Create a text cell.
2. Insert a checkbox.
3. Press 'delete' (aka backspace) to try to delete the checkbx. The cursor will move in front of the checkbox.
4. Press return/enter to add a new line. You can press enter/return as many times as you want to add x number of blank lines.
5. Now press delete/backspace. You can't move back. If you pressed enter five times, now you have a checkbox in the first line and five blank lines and you can't backspace.

SYMPTOM 3:
1. Create a text cell.
2. Insert a checkbox.
3. Edit > Select All
4. Press delete. Now you can delete the checkbox.
5. Now type something. Notice the text become really tiny.

OS X 10.9.5
Quiver 2.1 (8) free trial

**Comment by ylian** [comment]
Appreciate the bug report. Will fix in 2.1.1, submitting today.

**Comment by ylian** [comment]
Fixed in 2.1.1.

**Comment by ylian** [comment]
Note that I had to retract 2.1.1 due to a separate issue. Please wait for 2.1.2 to verify this fix.
