### ISSUE TITLE
Feature request: make tab indent bullet in Markdown mode

### ISSUE THREAD

**Issue by segphault** [HappenApps/Quiver#430]
When writing a bulleted list in markdown, I often want to be able to easily change the indentation depth of the current line. When I hit tab immediately after an asterisk, the current bullet doesn't indent—I just get a tab after the asterisk. If possible, I'd like hitting tab in a line that begins with a bulleted list character to change the indent level.

If that's too difficult to support practically, perhaps a good alternative would be dedicated keyboard shortcuts for increasing and decreasing the indent level for the current line.

(Update: It appears as though shift-tab already performs de-indentation as expected, it's just tab-to-indent that's not working)

**Comment by ylian** [comment]
I'm aware of the issues. Ace improvements will come a bit later.

**Comment by ylian** [comment]
Merged with #314.
