### ISSUE TITLE
[MultiMarkdown] Span cells across column doesn't work

### ISSUE THREAD

**Issue by DamienPetrilli** [HappenApps/Quiver#431]
Hi,

seems the syntax to span cell accross multiple column doesn't work

Quilver
![Quilver](https://cloud.githubusercontent.com/assets/7512468/12886341/7b369eba-ce3a-11e5-8ed6-bdf037837941.png)

MultiMarkdown
![MultiMarkdown](https://cloud.githubusercontent.com/assets/7512468/12886314/5371df8e-ce3a-11e5-954b-b9a588629a34.png)

```
|Header||
|:---:|---|
|Column1||
|Column1|Column2|
```

**Comment by ylian** [comment]
Quiver doesn't support multi-Markdown. The table support comes from GFM (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables)

**Comment by DamienPetrilli** [comment]
ok, make sense then ;)

Thanks
