### ISSUE TITLE
Filtering or searching for string "markdown" returns notes with markdown cells

### ISSUE THREAD

**Issue by craighurley** [HappenApps/Quiver#436]
Quiver: 3.0.1

I filter or search for notes using the string "markdown".

Expected behaviour: Notes containing "markdown" in a keyword, in the title or in a tag get displayed.

Actual behaviour: Notes containing "markdown" in a keyword, in the title or in a tag get displayed _and_ any note containing a cell of type markdown also get displayed.

**Comment by ylian** [comment]
Yep, it's due to how search indexing is done. Will fix.
