### ISSUE TITLE
Notes won't reorder after changing titles

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#44]
Steps: 
- select "Sort by Title" at the top of the sidebar
- Change any notes title

Expected: 
The notes should be reordered taking into account the changed title

Result:
The notes won't reorder. It works only manually by changing sort criteria and then selecting again the original criteria.

**Comment by ylian** [comment]
Thanks. Will fix together with #41. Probably in 2.2.

**Comment by LeonardoGentile** [comment]
This is still happening in quiver `3.0b1 (48)` and it also applies to new notes. If I create a new note, say with title `00AA` and the default order is by title then it won't be moved automatically to the first row of the note list. 

Either I have to change notebook and come back or I have to chenge sort order and then change it again to the previous one.

**Comment by ylian** [comment]
Will fix.

**Comment by ylian** [comment]
Fixed in beta 4: https://github.com/HappenApps/Quiver/issues/162#issuecomment-142169924

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.
