### ISSUE TITLE
Import Evernote doesn't show new notebook in 1st pane

### ISSUE THREAD

**Issue by bdillahu** [HappenApps/Quiver#443]
Imported a (pretty large) Evernote *.enex file - I think that went OK, but once the import dialog closed, it didn't look like anything had happened. I noticed the "All Notes" count had increased, but no new notebook had appeared.

The new items were members of the "Imported (<DATE>)" notebook, but it didn't appear in the list in the left pane.

Quit and restart and it appeared.

**Comment by ylian** [comment]
It sounds like the importer failed to import some notes. If you compare the number of notes in the .enex file, and the number of notes imported, they are probably different.

If you are not using 3.0.1, please update to 3.0.1. I fixed a bug with the importer in 3.0.1.

If you are already using 3.0.1, and indeed some notes are not imported, it would be great if you could import notebook by notebook, and send me the notebook (.enex) that couldn't be imported. I will fix right away.

**Comment by bdillahu** [comment]
Right you are… 3.0.1 seemed to fix it and does a complete import.

I actually had access to three different (large) .enex files that I cross checked the item/note count between Evernote and Quiver’s import and you got them all. Seems the fix is good :-)

My congrats! I think you are the first non-Evernote tool I’ve ever tried to use to import a *.enex file that could import them all!

## 

Bruce Dillahunty
http://brucedillahunty.xyz

**Comment by ylian** [comment]
That's great to know.
