### ISSUE TITLE
When exporting Code Cells to Markdown, tag the fenced code block with the set language.

### ISSUE THREAD

**Issue by arrayjam** [HappenApps/Quiver#444]
If I'm exporting a Code Cell of type jsx to markdown, it would be nice if the exported markdown contained something like this:

``````
```jsx
<Stuff>here</Stuff>
```
``````

**Comment by ylian** [comment]
Good catch. Actually this already works for most languages, but somehow I missed JSX. Will fix in 3.0.2.

**Comment by arrayjam** [comment]
Great! On a related note, would that explain why there is no syntax highlighting for jsx fenced code blocks in Markdown Cells?

**Comment by ylian** [comment]
@arrayjam Yes, indeed.

**Comment by ylian** [comment]
Fix coming in 3.0.2.

**Comment by ylian** [comment]
Fixed in 3.0.2. Released today.
