### ISSUE TITLE
Is there a way to add a black bar? (or any other color, or color-customizable)

### ISSUE THREAD

**Issue by khlj** [HappenApps/Quiver#445]
Is there a way to add a black bar as a field?
I have bunch of different notes during lectures, (code/text editting/etc)
and it's hard to differentiate the different sections of the notes I'm taking.

**Comment by khlj** [comment]
Or maybe try to link the color-coded bars to the tags, and it basically picks same color of the portion of the note proceeding the bar and labels the portion until the next bar as the specific tag?

**Comment by ylian** [comment]
Not sure. I don't really get the use of these color-coded bars.
