### ISSUE TITLE
[Minor Bug] Quiver adds space before VimL code comments on preview

### ISSUE THREAD

**Issue by dkarter** [HappenApps/Quiver#447]
Not a huge deal but it seems like Quiver is adding space before comments:
![image](https://cloud.githubusercontent.com/assets/551858/12968546/1c29322e-d039-11e5-9c7a-c162afb62c2c.png)

This is using the VimL syntax on a code cell surrounded by markdown cells.

This is not happening for ruby:
![image](https://cloud.githubusercontent.com/assets/551858/12968583/79534e30-d039-11e5-8a9e-5aecc1ea4e24.png)

**Comment by ylian** [comment]
Fixed in 3.0.2 Build 83: https://dl.dropboxusercontent.com/u/3445731/Quiver%203.0.2%20Build%2083.zip

**Comment by dkarter** [comment]
Fix confirmed. Thank you!

**Comment by ylian** [comment]
Fixed in 3.0.2.
