### ISSUE TITLE
Support HTML entities in Markdown

### ISSUE THREAD

**Issue by rasbt** [HappenApps/Quiver#449]
Thanks for all the great development so far! If you don't mind, I'd like to add another feature to the to-do list: Supporting HTML entities. 

Typically, I write most of my notes in LaTeX since they are quite math heavy. However, I am big fan of Markdown to get things done (/written), and it would be nice if I could throw in a special character here and there (e.g., a Greek letter or so). So, it would be nice if Quiver would convert HTML entities correctly, e.g., if I write `&phi;`, it would just leave it as is instead of showing the correct letter in the markdown preview or exported HTML file. 

PS: Here's one of the many HTML entity lists if it helps: http://www.htmlhelp.com/reference/html40/entities/symbols.html

**Comment by rasbt** [comment]
Sorry, never mind, it was a technical issue on my side ...

**Comment by ylian** [comment]
Just want to mention that you can write all the LaTeX inside Markdown cells. Both inline and display math are supported in Markdown cells.

**Comment by rasbt** [comment]
That's good to know, thanks! And sorry again for bothering with this issue earlier, was really a mistake on my side! Btw. I really appreciate your responsiveness towards issues and feature requests! I've probably never seen any other project where the developer(s) cared so much about the users! Thanks!
