### ISSUE TITLE
[Suggestion] Set different sorting criteria per notebook

### ISSUE THREAD

**Issue by ylian** [HappenApps/Quiver#45]
So one notebook might be sorted by title, another by updated date. Or another manually sorted.

I think this makes sense and should be the default behavior. Since it's a change from the current design, let me know your opinions.

**Comment by ghost** [comment]
:+1:

**Comment by LeonardoGentile** [comment]
I would suggest a sort of switch button at the top of the notebook that let us use the per-notebook criteria or the default one applied application-wide.

Also having access to this option with keyboard shortcuts would make this really useful

:+1:

**Comment by ylian** [comment]
How about moving the global sorting settings to Preferences? When you open a notebook, it defaults to the global sorting order, but if you change it, it will remember the new sorting order for that notebook.

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
