### ISSUE TITLE
Is it safe to operate on the files outside of Quiver?

### ISSUE THREAD

**Issue by bdillahu** [HappenApps/Quiver#451]
I assume it is (given the file format information).

What I have is several imports from Evernote (worked great!) that have duplicates in the imported data. Quiver doesn't seen these as dupes since they came from different places at different times, but the data is the same.

Can I run an external file de-dupe tool against the filesystem, clean it up, and Quiver deal with it?

I'll test, but thought I would ask if there was something I was obviously missing.

(also, if there is a better place for something like this, sorry, please point me that way)

Thanks,
Bruce

**Comment by ylian** [comment]
It's safe. You might want to close the app while doing this. If the app is open, the only thing is that if the note currently open in the editor/preview/presentation is deleted from the disk, the app might show a blank note.
