### ISSUE TITLE
Cmd+click support for Notebooks and Library items or saving selection focus

### ISSUE THREAD

**Issue by 140am** [HappenApps/Quiver#456]
I switch between different projects throughout the day and currently it does not seem to be possible to have different Quiver windows opens in different spaces or I have not figured it out yet. I noticed the recent support for cmd+click on notes and think it would be great to have the same for notebooks or the Inbox/Favorites. Saving the last selected note within a notebook and sharing one Quiver window between different spaces would make switching between different projects/notebooks  probably as easy.

Moved 600+ notes from evernote into it after trying it for two days - great app!

**Comment by ylian** [comment]
I intend to keep the single-window design for its simplicity. But I could add a setting to show the last selected note in a notebook when it's opened. Would that be good enough for your use case?

**Comment by 140am** [comment]
Thanks for the prompt response! I very much like the simplicity of the current UI and focus on keeping that. Showing the last selected note when switching notebooks would solve the described issue great for me. Switching between different notebooks quickly would then have much less overhead.
