### ISSUE TITLE
Paste format broken again in 2.1 App Store Version (Was good in 2.1 beta)

### ISSUE THREAD

**Issue by x-ji** [HappenApps/Quiver#46]
Previously in 2.0 when I paste a text paragraph from web line breaks occur unnaturally throughout the paragraph. It seemed to have been fixed in 2.1 Beta you sent me. But now in the formal release it seems to be broken again.

i.e. I'll get

> There is no need (and it is error prone) to deploy a new instance of an app by replaying the entire migration history. It is much simpler and faster to just load into the database a description of the current schema.

in 2.1 Beta but

> There is no need (and it is error prone) to deploy a new instance of an app by
> replaying the entire migration history. It is much simpler and faster to just
> load into the database a description of the current schema.

in both 2.0 and 2.1 App Store Releases, which break the paragraph into three lines.

**Comment by ylian** [comment]
Seems to be reverted in a last-minute change. I will fix it again in 2.1.1.

In the meantime, you can fix this by adding the following to the editor CSS (in preferences):

``` css
.text-cell {
  white-space: normal;
}
```

Let me know if it works.

**Comment by x-ji** [comment]
Yeah that works in editor view. However the same problem persists in preview view.

**Comment by ylian** [comment]
You can do the same in the preview CSS and presentation CSS. Note that in the editor, you may have issues with moving cursor between cells with up and down arrows. This was the reason the white-space setting was reversed in the last minute.

I already submitted Quiver 2.1.1, which fixed this issue without breaking keyboard navigation.

**Comment by ylian** [comment]
Fixed in 2.1.1.

**Comment by ylian** [comment]
Note that I had to retract 2.1.1 due to a separate issue. Please wait for 2.1.2 to verify this fix.

**Comment by ylian** [comment]
Unfortunately this change creates more issues than it solves. I have got a few user reports that they are surprised to see whitespaces not being kept. This happens when copying some Markdown text to a text cell. Most users would expect to see linebreaks `\n` actually breaking lines, or 4 spaces actually taking up 4 spaces. I think I have to revert this change.

**Comment by ylian** [comment]
This is still the correct behavior. Most webpages use `white-space: normal;`. It's a huge surprise to see whitespaces between html tags rendered.
