### ISSUE TITLE
Markdown renderer does not recover from crash unless the app is restarted

### ISSUE THREAD

**Issue by charignon** [HappenApps/Quiver#460]
I was trying to display new kind of graphs than what is supported so I tried to include some javascript library in a markdown cell and display the graph. I believe that the markdown renderer crashed as no markdown cell was rendering anywhere. I had to restart the app to get it working again.

**Comment by ylian** [comment]
This is expected. The editor/preview are just webviews, and they only get reloaded on app restart. So if you inject some JavaScript that causes errors, you would need to restart the app.

**Comment by charignon** [comment]
Ok, that's expected but I wouldn't expect every markdown render to crash if one cell is wrong. Feel free to close that for now if you think it isn't very important.
