### ISSUE TITLE
[Suggestion] A programmable cell type

### ISSUE THREAD

**Issue by hlissner** [HappenApps/Quiver#466]
(I posted this in another issue, but it was a bit out of place there so I moved it here)

Because this is a note-taking app for programmers, why not have a "script" cell-type? You'd specify a path to a script, pass some metadata (note data, id, etc.) as input and use its output to replace the cell in preview/presentation/export mode.

For instance, 

``` js
{
  "title": "Taskpaper todo list",
  "cells": [
    {
      "type": "script",

      // Could be written in any language, so long as it has a valid shebang line
      "path": "~/bin/get_todos.sh",

      // Determines how the rendered cell is treated in preview mode. Should accept 
      // any cell type, as well as "html" for raw markup for the WebView to render.
      "preview": "markdown",

      "data": "..."
    }
  ]
}
```

This could address #383, #266, #298, #462, #433 and others by lending the community the power to implement other alternative rendering engines (e.g. plantuml, opml, org-mode, other markdown engines, viz.js, html, etc), data aggregation scripts, and even bind cells to external services/apps. This would shift some of the burden off your shoulders.

Another idea: perhaps scripts could optionally output JSON for Quiver to interpret, similar to Launchbar's approach to custom actions?

**Comment by ylian** [comment]
Thanks, but I don't want to add dynamic script execution to Quiver. Main reason: that's not where I want to take Quiver. I think of Quiver as a notebook for static contents, not an IDE, or a scripting environment. What you want is very much like iPython Notebook, or Mathematica Notebook. Those are powerful tools, but that's a very different direction from where Quiver is heading.

Practical reasons:
1. Quiver is sandboxed, so it can't access arbitrary script files unless it's opened with a open file panel or the script is dragged in.
2. Quiver's key strength is its speed. If these scripts are executed synchronously, a single slow script can bring the app to a halt. If they are executed asynchronously, the preview will flash as contents are rendered.
3. Other rendering engines need to support a common output format.

I honestly think this should be a new app. A generic version of iPython.

**Comment by hlissner** [comment]
Understood. A part of me would like a little bit of iPython notebook in Quiver, but I am perfectly happy with it as it is. Thanks for hearing me out!
