### ISSUE TITLE
Vim ce motion doesn't work properly

### ISSUE THREAD

**Issue by prurph** [HappenApps/Quiver#467]
In Vim, `ce` (for change to end) is supposed to delete to the end of a word, including the last character, and go into insert mode. In Quiver it doesn't delete the last character.

Repro: type `foobar`, hit escape to enter normal mode, move to the beginning of the word and type `ce`. Expected behavior: the entire word is deleted and you are insert mode. Actual behavior: the `r` is not deleted and you are left in insert mode with the cursor to the left of this character.

**Comment by dkarter** [comment]
I'm using a beta version: 3.0.2 (82) and it seems to be working great.
![screencap](http://g.recordit.co/LwlWcgoo2e.gif)

**Comment by ylian** [comment]
Fixed in 3.0.2.
