### ISSUE TITLE
[Feature Request] Kotlin language support

### ISSUE THREAD

**Issue by imallan** [HappenApps/Quiver#476]
JetBrains has just released version 1.0 of [Kotlin](http://kotlinlang.org). The language seems to be getting more popularity recently. It would be great to have Kotlin support in code/markdown cells. Thanks!

**Comment by ylian** [comment]
Yes, I have already added in a dev build. This is coming out in 3.0.2.

You can try the dev build here: https://dl.dropboxusercontent.com/u/3445731/Quiver%203.0.2%20Build%2084.zip

**Comment by imallan** [comment]
Cool! Thanks a lot!

**Comment by ylian** [comment]
Added in 3.0.2. Released today.
