### ISSUE TITLE
Korean Input Issue without 

### ISSUE THREAD

**Issue by lyuha** [HappenApps/Quiver#477]
I use OSX 10.11.3 and Quiver Version 3.0.1 (78)
This issue is similar to #334. When typing korean, it is broken all cell mode except Text Cell(like under image). However, once typed characters is not broken, typing korean is correct. If relaunch app, fixed. After reboot, this situation repeat.
<img width="177" alt="quiver 2016-02-25 03-38-48" src="https://cloud.githubusercontent.com/assets/4014016/13296523/4ba9a5ea-db71-11e5-8985-333f2e834895.png">

**Comment by ylian** [comment]
It's a bug with the Ace editor. I just started looking into the internals of the Ace editor, but it may take a while before I understand the code well enough to fix issues like this.

**Comment by chulkilee** [comment]
I don't know which version of [Ace Editor](https://ace.c9.io/) Quiver is using, but the web demo of Ace Editor handles it properly from Mac Firefox. @ylian could you test with the latest version of ace editor?

I still see the problem on Quiver 3.0.1 (78), Mac 10.11.4.

---

FYI

[Keyboard layout: East Asian languages](https://en.wikipedia.org/wiki/Keyboard_layout#East_Asian_languages)

> ...Korean is typed similarly to Western languages. There exist two major forms of keyboard layouts: Dubeolsik (두벌식), and Sebeolsik (세벌식). Dubeolsik, which shares its symbol layout with the QWERTY keyboard, is much more commonly used. While Korean consonants and vowels (jamo) are grouped together into syllabic grids when written, the script is essentially alphabetical, and therefore typing in Korean is quite simple for those who understand the Korean alphabet Hangul. Each jamo is assigned to a single key. As the user types letters, the computer automatically groups them into syllabic characters. Given a sequence of jamo, there is only one unambiguous way letters can be validly grouped into syllables, so the computer groups them together as the user types.

Example: to enter `가나다`, you need to type `ㄱ`, `ㅏ`, `ㄴ`, `ㅏ`, `ㄷ`, and `ㅏ`. After you enter `ㄱ` and `ㅏ`, it must be transformed to `가`.

HTML excerpts from "Inspect Element"

``` html
<!-- typing in Quiver 3.0.1 (78) -->
<!-- output: ㄱㅏㄴㅏㄷㅏ -->
<div class="ace_line_group" style="height:27px">
  <div class="ace_line" style="height:27px">
    <span class="ace_text ace_xml">
      <span class="ace_cjk" style="width:21.674375px">ㄱ</span>
      <span class="ace_cjk" style="width:21.674375px">ㅏ</span>
      <span class="ace_cjk" style="width:21.674375px">ㄴ</span>
      <span class="ace_cjk" style="width:21.674375px">ㅏ</span>
      <span class="ace_cjk" style="width:21.674375px">ㄷ</span>
      <span class="ace_cjk" style="width:21.674375px">ㅏ</span>
    </span>
  </div>
</div>

<!-- pasting into Quiver 3.0.1 (78) -->
<!-- output: 가나다 -->
<div class="ace_line_group" style="height:27px">
  <div class="ace_line" style="height:27px">
    <span class="ace_text ace_xml">
      <span class="ace_cjk" style="width:21.674375px">가</span>
      <span class="ace_cjk" style="width:21.674375px">나</span>
      <span class="ace_cjk" style="width:21.674375px">다</span>
    </span>
  </div>
</div>
```

**Comment by ylian** [comment]
@chulkilee Just pushed out 3.0.2, which includes the latest Ace editor. Can you test again? Hopefully it's fixed.

**Comment by chulkilee** [comment]
@ylian 3.0.2 (86) works for me. It had the problem at first, but when I closed all windows and reopened the note, then it worked.

Thanks for the quick response!

**Comment by ylian** [comment]
Closing this since it seems to be fixed with the Ace update.
