### ISSUE TITLE
Indent text in markdown cell

### ISSUE THREAD

**Issue by doginthehat** [HappenApps/Quiver#478]
Enjoying my use of Quiver so far, nice little app.

Would it be possible to add a feature to the markdown cells to indent text in a the cell?

Indented text would display like a code block.

Mou has a good implementation of this behaviour, for reference.

**Comment by ylian** [comment]
Indented text is already treated like a code block. Use 4 spaces for indentation.

![image](https://cloud.githubusercontent.com/assets/984895/13305888/da9a37aa-db2c-11e5-8823-f4be861fd14f.png)

**Comment by doginthehat** [comment]
@ylian 

Thanks for the quick reply. 

I wasn't very clear on my feedback, sorry. 

What would be nice is a keyboard shortcut that would indent a whole block of text at once.

In Mou (and some other editors), it's CMD+].

Here's a screenshot of what it does

<img width="1044" alt="screen shot 2016-02-25 at 11 34 21" src="https://cloud.githubusercontent.com/assets/843366/13305986/c5fb5ae0-dbb3-11e5-8ad1-7aa3c17dc417.png">

With the 4 spaces example you've given, that also creates a numbered list, which isn't ideal.

**Comment by ylian** [comment]
Oh I see. The Ace editor uses Tab and Shift+Tab for that. I might change the shortcut someday but I would rather leave that until I get a better understanding of the Ace editor's code.

**Comment by doginthehat** [comment]
I see, so there's is an indent shortcut, thanks.

Now the next trick would be to do something with that indent. 

A single shift doesn't put the result in a different code format block.

Double shift results in the same output as 4 tabs.

**Comment by ylian** [comment]
Oh I see. No, the 4 spaces create a code block. It just has the line number turned on. You can turn off the line number if you like: Preferences > Cells > Code Cell (a bit confusing here, but code blocks are styled the same way as code cells):

And you can change the code cell theme if you want a dark background color.

![image](https://cloud.githubusercontent.com/assets/984895/13306225/dd44d688-db2f-11e5-8a4d-92ac857c51d4.png)

And it will look like this:

![image](https://cloud.githubusercontent.com/assets/984895/13306231/ed4321ac-db2f-11e5-8b64-f81c6986b582.png)

**Comment by doginthehat** [comment]
Ah, yes!

Line numbers, off course.

That's awesome, thanks for your input.

**Comment by ylian** [comment]
You are welcome. Close this now.
