### ISSUE TITLE
Keyboard shortcut to access filter

### ISSUE THREAD

**Issue by craighurley** [HappenApps/Quiver#479]
Quiver: 3.0.1
OSX: 10.11.3

I know I can use OPTION+CMD+F to find notes containing a string, but I find most of the time I use the filter functionality located in the bottom left.  It would be great to have a shortcut to select the filter box, or even a method to assign or override shortcuts.

-- subjective comment --
On a related note, I find the location of the filter box quite clumsy to select -- it often happens that I try to click it and the OS X dock will go from being hidden to popping up and getting in the way.  I think it would be better placed somewhere at the top of the UI.
-- subjective comment --

**Comment by ylian** [comment]
I agree a shortcut would be nice.

**Comment by ijoseph** [comment]
I like the location of the filter, which I find elegant; however, I dislike the lack of keyboard shortcut for it, which renders it of not much use to me.

**Comment by jkryanchou** [comment]
@ylian Is the latest version support? I'd like to locate it through keyboard shortcuts.
