### ISSUE TITLE
Spelling and grammar check do not work

### ISSUE THREAD

**Issue by xiaohk** [HappenApps/Quiver#480]
I have checked all these options, but Quiver still does not show where I spelled wrong.
![image](https://cloud.githubusercontent.com/assets/15007159/13321485/dc527b12-db94-11e5-94ec-c0198510f379.png)

**Comment by ylian** [comment]
Is it in a text cell or a Markdown cell? Spellcheck doesn't work in Markdown cells, due to limitation of the Ace editor.

**Comment by xiaohk** [comment]
Oh, I see. It is in the Markdown cell, thank you!

**Comment by ylian** [comment]
Yeah, there is a ticket for that (https://github.com/HappenApps/Quiver/issues/89). I will eventually fix it, but it's a challenge. Ace doesn't really support spellchecking, and it's not possible to use browser's built-in spellchecker with Ace.

**Comment by xiaohk** [comment]
That definitely will be awesome! I also use another Markdown Editor, named "MarkEditor". It supports spellchecking in the version 1.0.9.9. Maybe it could be helpful!

Here is [updating track](http://zrey.com/docs/markeditor-updates.txt) for that app (sorry it is in Chinese, the app supports English tho)

**Comment by ylian** [comment]
Great reference. Thanks. It seems to be a webapp built with Flask, then wrapped in either Electron or Qt. I haven't figured out what library the editor uses.

**Comment by ylian** [comment]
Actually MarkEditor is a Qt app written mostly in Python. The editor seems to be written in Python, while the preview uses a Qt webview. Interesting design.

**Comment by xiaohk** [comment]
Wow! How did you find out how the program had been written? It is impressive!
Yeah, I do believe the programmer wrote in Python for most parts, because he is a huge Python fan XD

**Comment by ylian** [comment]
Just right click on the application, show package contents, and look at the resource files. Lots of Qt libraries, then main part is all Python. Of course I can't really see the code for the editor because it's complied Python. But knowing the technology stack was enough for my curiosity.

**Comment by xiaohk** [comment]
Oh I see, thanks for telling me that! 
Good luck on the further updating of both Quiver for Mac and for iOS, I really enjoy it~

**Comment by jryio** [comment]
Any word/update on the limitations or status of spell checking in the Ace Editor?

It's very difficult not to have spell checking in Markdown syntax when many other Markdown editors have it as well.

My personal use of Quiver is Markdown and Code cells exclusively and I love - however I make many spelling mistakes!

**Comment by vanDeventer** [comment]
It seems to still be the case en version 3.1.3.
