### ISSUE TITLE
[Markdown] add links end with parentheses 

### ISSUE THREAD

**Issue by ruijianw** [HappenApps/Quiver#484]
I am trying to add the link: [L1 (Lasso)](https://en.wikipedia.org/wiki/Lasso_%28statistics%29) to a markdown cell, but it seems the parser does not work correctly, parsed as `L1 (Lasso))` I also tried to add back slash to the parentheses surrounding the `statistics`, it still dosen't work, and result became more weird as `statistics">L1 (Lasso)`.

I tried another markdown editor, [Mou](http://25.io/mou/), it has the same issue without back slash but works well after adding back slash. And it seems github can parse it well without backslash.

**Comment by ylian** [comment]
Fixed in 3.0.4.
