### ISSUE TITLE
[Feature Request] copy selected as HTML Source.

### ISSUE THREAD

**Issue by fomotoshi** [HappenApps/Quiver#486]
I use parts of quiver's notes to make ANKI cards and I don't want to do same work with formatting cards in ANKI. I will be able to copy markdown from part of quiver's note as HTML Source.

or if this difficult for you, will you able to make export as HTML without title? or if title is clear, HTML Source will be without `<div id="title area"> Title Here</div>`. Because I need to delete this code every time, when I make cards.

**Comment by gandalfsaxe** [comment]
I'm also interested in generating Anki cards from Quiver notes. What is your current workflow?

**Comment by brettz9** [comment]
This would also be very handy for Issue #452 when one wishes to copy the formatted result of Markdown or code, etc. into an email instead of the source.
