### ISSUE TITLE
Enhancement: Render blueprint markdown using aglio

### ISSUE THREAD

**Issue by catesandrew** [HappenApps/Quiver#49]
Add cell type for blueprint markdown files that render web apis. Currently [aglio](https://github.com/danielgtaylor/aglio) seems to offer the best support. The only issue is the snowparser that protagonist relies on uses node-gyp bindings and might not be easy to target on multiple machines as an all in one package, but not sure (limited knowledge of mac apps).

**Comment by ylian** [comment]
Closing this. Not a good fit for Quiver. Quiver should provide generic cell types that most users will use.
