### ISSUE TITLE
Clicking "Replace" after prompted to overwrite existing Synced Quiver library doesn't do anything 

### ISSUE THREAD

**Issue by welps** [HappenApps/Quiver#493]
I have a copy of Quiver on two computers. Let's call them Quiver 1 and Quiver 2.

Quiver 1's library is already synced to my dropbox, but Quiver 2 is not. Quiver 2 has newer content and should replace Quiver 1's entirely. 

If I click "Replace" after prompted to overwrite the existing Quiver 1 library on Dropbox, nothing happens.

![screen shot 2016-03-02 at 7 57 04 pm 1](https://cloud.githubusercontent.com/assets/677680/13481157/3ade2138-e0b1-11e5-8311-09ab3159af20.png)

The workaround is easy (just remove the existing library and then try to move the Quiver 2 library), but thought I'd let you know. Thanks!

**Comment by ylian** [comment]
Good catch. Thanks.

**Comment by ylian** [comment]
Already fixed in 3.0.2.
