### ISSUE TITLE
Improving vim mode

### ISSUE THREAD

**Issue by jimzenn** [HappenApps/Quiver#504]
**Including vim mode is really great and I'm surprised that it's so complete.** However, there's still some small functions I think can be improved:
in vim mode:
- Can "/" be mapped to command + F, i.e. search, and "n" & "N" also be mapped correspondingly?
- Can there be a simple indicator (a basic one will do, with current mode and instruction inputted)?
- Line number is important in vim when you want to jump from line to line, can there be an option to show line number?

**Comment by dkarter** [comment]
In 3.0.2 (82) (beta that can be found somewhere here in the issues and is scheduled to be released) the following works:
- Can search with `/` and jump between results with `n`:
  ![search](http://g.recordit.co/w2zfCMmcl6.gif)
- Can run some commands (like replace):
  ![replace](http://g.recordit.co/2SxMXzkhUC.gif)
- Jump to a specific line number:
  ![jump](http://g.recordit.co/iohTMAs1O3.gif)
- You can get line numbers by switching to a code cell and setting the language to text (no highlighting - as in above gif)
- For indication of current mode 
  - normal mode: cursor is a red block
  - visual mode: selection appears
  - insert mode: cursor turns into a pipe instead of block

**Comment by dkarter** [comment]
For instruction inputted you can use something like Keycastr (as in above gifs):
https://github.com/keycastr/keycastr

**Comment by Jim-Zenn** [comment]
Great job! Can’t wait to see it.
On Tue, Mar 8, 2016 at 18:14, Dorian Karter <notifications@github.com> wrote:
In 3.0.2 (82) (beta that can be found somewhere here in the issues and is
scheduled to be released) the following works:

 * Can search with / and jump between results with n : search
   [https://camo.githubusercontent.com/c8ec32164a690c4e183e44be279388c87b0cc285/687474703a2f2f672e7265636f726469742e636f2f77327a66434d6d636c362e676966]
   [https://camo.githubusercontent.com/c8ec32164a690c4e183e44be279388c87b0cc285/687474703a2f2f672e7265636f726469742e636f2f77327a66434d6d636c362e676966]
 * Can run some commands (like replace): replace
   [https://camo.githubusercontent.com/b22220044c782a9d9096039892472925e178e3e9/687474703a2f2f672e7265636f726469742e636f2f3253784d587a6b6855432e676966]
   [https://camo.githubusercontent.com/b22220044c782a9d9096039892472925e178e3e9/687474703a2f2f672e7265636f726469742e636f2f3253784d587a6b6855432e676966]
 * Jump to a specific line number: jump
   [https://camo.githubusercontent.com/af23f5f65123926d9e88e5e589f9956399949723/687474703a2f2f672e7265636f726469742e636f2f696f68544d4173314f332e676966]
   [https://camo.githubusercontent.com/af23f5f65123926d9e88e5e589f9956399949723/687474703a2f2f672e7265636f726469742e636f2f696f68544d4173314f332e676966]
 * You can get line numbers by switching to a code cell and setting the language
   to text (no highlighting - as in above gif)
 * For indication of current mode * normal mode: cursor is a red block
    * visual mode: selection appears
    * insert mode: cursor turns into a pipe instead of block
   
   

—
Reply to this email directly or view it on GitHub
[https://github.com/HappenApps/Quiver/issues/504#issuecomment-194072102] .[https://github.com/notifications/beacon/AG8SG1YW-uSpvK0D3MFp17LhbVW8AAu9ks5priztgaJpZM4Hrc-a.gif]

**Comment by dkarter** [comment]
All credits are due to @ylian and the Ace editor team.  Feel free to close the issue if all the above satisfy your requirements.

**Comment by jimzenn** [comment]
Great job. Glad to hear that!
