### ISSUE TITLE
Not fixed UUID!

### ISSUE THREAD

**Issue by amirmasoudabdol** [HappenApps/Quiver#507]
Hi,

I am using UUID to link notes to each other or link to a note from other app. But I realized that the UUID it could change. Is this a possibility? It happened several times for me, I created a note, use Cmd+Opt+Ctrl+C to get the link and paste it somewhere else; and after few days when I clicked on it, nothing shows up in Quiver. 

For instance these are two links to one note, most part are the same but the last part added (I don't know when) and that breaks the link.

```
quiver:///notes/E6767BE2-1AA6-4D46-9C1B-B82F94
quiver:///notes/E6767BE2-1AA6-4D46-9C1B-B82F94A09
```

Do you have any idea why is this happening? and what should I do to prevent it?

Thanks,
Amir.

**Comment by ylian** [comment]
That's weird. UUID should never change. Also, UUID has a fixed length, so the second link isn't right. The "A09" at the end of the second link must have been added in some other way. Are the links in a Markdown cell or a text cell?

**Comment by amirmasoudabdol** [comment]
As you said this is really weird and I'm confused! I tried to get the notes UUID again and I ended up with this. Two more digits added!

```
quiver:///notes/E6767BE2-1AA6-4D46-9C1B-B82F94A09A96
```

I don't understand what's going on! I usually get the code and make a link in different app; so, I didn't copy it in a Markdown or text cell. I also checked the database, and here is the file `E6767BE2-1AA6-4D46-9C1B-B82F94A09A96.qvnote`!

**Comment by ylian** [comment]
Can you give me detailed steps to reproduce this?

**Comment by ylian** [comment]
Actually the UUID should be 36 letters (including dashes and numbers). So the first two links you posted were wrong. The last one is right.

I just checked one of mine:

```
quiver:///notes/B3D339CB-D3E8-4CDF-80FB-8FABF9A162D8
```

So the first two links actually missed a few letters from the end.

**Comment by amirmasoudabdol** [comment]
Oh, ok, I think I've an idea why this is happening. Probably somewhere in my copy/paste workflow (Snippet that I wrote in TextExpander) I tend to miss few characters at the end of the UUID. 

Ps. Now that we are talking about this. I have to do this transformation because I need to paste the copied link to an editor which is a rich text editor but it does not support link. So, if I paste the link directly from Quiver then I only get the title. So, I have to copy it somewhere else, get the "actual" link and then processed. Is there a way around this? Maybe having another copy command for only copying UUID would be a solution? 

Thanks a lot for help :smile:

**Comment by ylian** [comment]
I see. Make sure you are using Quiver 3.0.1.

In 3.0.1, when you copy a note link, it will copy two things into the pasteboard, a plain-text version like `quiver:///notes/B3D339CB-D3E8-4CDF-80FB-8FABF9A162D8`, and a rich text version. So in your snippet, maybe you could examine the pasteboard and find the plain-text version. I don't know much about TextExpander, so I can't be of more help here. :)
