### ISSUE TITLE
How can I type the degree symbol in inline LaTeX syntax?

### ISSUE THREAD

**Issue by birkhofflee** [HappenApps/Quiver#508]
After a couple of searching on Google, I cannot find the way to type the degree symbol in inline LaTeX syntax.

**Comment by ylian** [comment]
MathJax probably doesn't support `\degree`. You can use this to fake it: `$^{\circ}$`. I don't know LaTeX so well so there might be other ways.

**Comment by quark67** [comment]
@BirkhoffLee  You can probably use the `°` key on your keyboard if you have it. See the answer here: http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference#answer-19678

**Comment by birkhofflee** [comment]
Thanks bro.

**Comment by erickzind** [comment]
**gensymb**
```
\usepackage{gensymb}
\begin{document}
The right angle is 90\si{\degree}.
\end{document}
```

**textcomp**
```
\usepackage{textcomp}
\begin{document}
The round angle is 360\si{\textdegree}.
\end{document}
```

**siunitx**
```
\usepackage{siunitx}
\begin{document}
Degree symbol: 45\si{\degree}.
\end{document}
```
**circ**
`[^{\circ}](url)`

You can do it in 4 different ways above.

For more detailed explanation: https://www.degree-symbol.com/article/degree-symbol-on-latex

**Comment by quark67** [comment]
No, @erickzind, here the question is about the MathJax syntax used by Quiver, it's not a pure LaTeX syntax. You cannot use `\usepackage` with MathJax.
