### ISSUE TITLE
Add hotkey to assign a notebook in 'Quick Note'  menu

### ISSUE THREAD

**Issue by nikivdev** [HappenApps/Quiver#525]
![2016-03-20 at 13 19](https://cloud.githubusercontent.com/assets/6391776/13904364/748d86ee-ee9e-11e5-8a9f-acf6b2a1f43a.png)

I can't seem to find it, perhaps it exists. If not I really wish there was such a hotkey, would make the workflow much faster.

Thank you.

**Comment by ylian** [comment]
It's in the menu, so you can map a keyboard shortcut to it. See https://support.apple.com/kb/PH18418?locale=en_US

**Comment by nikivdev** [comment]
thank you :)
