### ISSUE TITLE
Is it possible to add new cells on top?

### ISSUE THREAD

**Issue by manuelescamilla** [HappenApps/Quiver#529]
When I add a new cell it gets inserted below the current selected cell. But is it possible to insert the new cell above the current selected cell?

If not, is it possible to move and reorder the cells?

Right now I leave a blank cell on the top, so i can alway have my latest notes on the top.

Thanks.
Quiver Version 3.0 (66)

**Comment by ylian** [comment]
Yes you can. First make sure you update to 3.0.1.

cmd+shift+enter inserts a new cell above the current cell. You can move the cells as well. Look under the Cell menu.
