### ISSUE TITLE
[Feature Request] Option to allow nested Notebooks

### ISSUE THREAD

**Issue by justnealpatel** [HappenApps/Quiver#530]
Although the app is very concise with organization, it would be helpful to better organize notebooks within other notebooks.

Programming Languages (notebook)
      C++ (notebook)
      Java (notebook)
      other notebooks

**Comment by nikivdev** [comment]
It has been said that such a feature is coming. I am also really waiting for it but I suppose Lian is focusing on the iOS app currently.

**Comment by ylian** [comment]
Duplicate of #2.
