### ISSUE TITLE
Chinese characters letter spacing larger than expected in code cell

### ISSUE THREAD

**Issue by MasonPanHB** [HappenApps/Quiver#535]
**In the editor mode:**
<img width="604" alt="2016-03-26 11 01 07" src="https://cloud.githubusercontent.com/assets/6447075/14057663/514b0640-f342-11e5-8677-55031c2d6c68.png">

**Same content in preview mode.** Check line 5 and line 9 of some code cell block. Those chinese characters have a overlarge spacing between each other. That is particularly annoying for users who wrote chinese.
<img width="584" alt="2016-03-26 11 01 22" src="https://cloud.githubusercontent.com/assets/6447075/14057664/566a310a-f342-11e5-82cc-690ee76e85a7.png">

**Comment by ylian** [comment]
Fixed in 3.0.2.
