### ISSUE TITLE
Request: shortcuts for common symbols

### ISSUE THREAD

**Issue by zachkirsch** [HappenApps/Quiver#539]
I'm trying to find a way to use Latex-like shortcuts to use common symbols (e.g. \Alpha) in a Text Cell. Is there a way of doing this already / could this be included in the future?

**Comment by ylian** [comment]
That would require on-the-fly parsing of text input. I don't know if I want to support that. It's certainly powerful but also can open the door to a lot of complexities, such as: should the app support all the LaTeX symbols? how about many other shorthands? how about Markdown syntaxes? how about subscript and superscript? how about text expansion?

**Comment by JMichaelTX** [comment]
> I'm trying to find a way to use Latex-like shortcuts to use common symbols (e.g. \Alpha) in a Text Cell.

Have you tried [TextExpander](https://smilesoftware.com/textexpander)?

It works great for this and many, many other purposes.  I use it many times a day.

**Comment by zachkirsch** [comment]
Thank you!
