### ISSUE TITLE
When opening a note in separate window, and then closing main window, I can't open main window + can't create new Note

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#54]
Open note in separate window (double click it)
Close main window, leave the note window open
How to get back to main window?
Plus Create New note is disabled

Only solution I found: Close note window, open Quiver again

**Comment by ylian** [comment]
That's true. I guess I can add a menu item to show the main window.

**Comment by Strajk** [comment]
Even not disabling creating New note would be great :+1:

**Comment by Strajk** [comment]
Inbox sounds good to me (like in Things app), or setable default notebook (like in Evernote)

![image](https://cloud.githubusercontent.com/assets/697301/6426536/5977cb58-bf60-11e4-82d2-b0410dd0a4f0.png)

**Comment by ylian** [comment]
Added a menu item "Show Main Window" under the Window menu.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b15.zip

**Comment by ylian** [comment]
Enabled the "New Note" menu item when the main window is closed.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b31.zip

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
