### ISSUE TITLE
How can I manage my notebooks

### ISSUE THREAD

**Issue by xiaohk** [HappenApps/Quiver#544]
Hi, I wonder how to delete or rename my notebooks?

**Comment by ylian** [comment]
In the sidebar, click on the notebook name to rename, or right click and "Rename notebook". To delete a notebook, right click on the notebook name and "Delete notebook".

**Comment by HazelHik** [comment]
Hi your reply doesn't solve my problem, in the sidebar I can't even arrange them in the form of "notebooks", it's that I've already entered a notebook and the sidebar shows the list of notes in that notebook.

**Comment by ylian** [comment]
@HazelHik Press cmd+3 to show the sidebar (what you saw was the middle column, not the sidebar).

**Comment by HazelHik** [comment]
Thank you @ylian, I hardly noticed that I was in the two column mode, and cmd+3 worked!
