### ISSUE TITLE
When searching, cannot create new note

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#55]
Common use case: Searching for some term to check if I already have a note for that, if not, I want to create a note :)

![image](https://cloud.githubusercontent.com/assets/697301/6426429/acc44b34-bf5a-11e4-99cb-0fdaf5813ca9.png)

**Comment by ylian** [comment]
That makes sense. There is one little technical issue: during the search, no notebook is selected, so which notebook should the new note be created in?

I am actually thinking about adding a generic "Inbox" notebook for quickly creating a note. But not sure yet. This also applies to #54.

**Comment by Strajk** [comment]
Inbox sounds good to me (like in Things app), or setable default notebook (like in Evernote)

![image](https://cloud.githubusercontent.com/assets/697301/6426538/71bb577a-bf60-11e4-8116-75d546eb71a0.png)

btw: keep up great work! :)

**Comment by ylian** [comment]
Sounds good. Thanks.

**Comment by ylian** [comment]
Implemented "Inbox". It's just a special notebook that you can't delete.

If no notebook is selected, you can create a new note and it will go into Inbox.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b31.zip

**Comment by Strajk** [comment]
Awesome!!!

Just a small note, when searching, I can create a new note, it will open in a new window - so far so good, but there is no indication where the note was created...
![untitled note 2015-05-05 09-15-16](https://cloud.githubusercontent.com/assets/697301/7468350/8ec08a7c-f307-11e4-842e-66799800adc8.png)

![untitled note 2015-05-05 09-15-16](https://cloud.githubusercontent.com/assets/697301/7468319/427e01bc-f307-11e4-83fe-4d2b1d7d1411.png)

**Comment by Strajk** [comment]
How evernote handles it
![jade evernote 2015-05-05 09-18-10](https://cloud.githubusercontent.com/assets/697301/7468355/b3c3e65c-f307-11e4-80e2-e231e6418f17.png)

**Comment by ylian** [comment]
Good idea.

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
