### ISSUE TITLE
Images in Markdown cells

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#56]
Why not allowing images in markdown notes?

I know I can easily make another text cell just for image and then another cell back to markdown... but why to make it harder? :)

This would be a killer feature for me :)

How I doing that in Evernote at the moment:

![image](https://cloud.githubusercontent.com/assets/697301/6427618/fadf91ae-bf85-11e4-95fc-b7f6e131d9cf.png)

**Comment by ylian** [comment]
Yeah, I had this in mind already. Not just images. Markdown cells should have pretty much all the formatting options as text cells.

**Comment by ghost** [comment]
+1

**Comment by Strajk** [comment]
Any update on this pls? @ylian

**Comment by ylian** [comment]
Working on it right now. Should have a build tonight or tomorrow.

**Comment by ylian** [comment]
Implemented in 2.2b28, together with other formatting controls and keyboard shortcuts.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b28.zip

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.

**Comment by birkhofflee** [comment]
But I still cannot drag images into the markdown cell. Is clicking the button on the toolbar the only way to add a picture into it?
