### ISSUE TITLE
All of my notes were randomly wiped

### ISSUE THREAD

**Issue by sangheraio** [HappenApps/Quiver#569]
Hi,

I've been using Quiver (v3.0.1) for the past 6 months or so and had quite a bit of very critical information stored in there. After restarting my laptop (OSX El Captain v10.11.2), my entire notebook went blank and I can't find my notebooks anywhere so basically all of my notes appear to have been deleted.

Previously it always seemed to be auto saving and never was an issue when I restarted or anything. I can't remember ever clicking to back it up because I assumed it was storing it automatically. I really need that information back. Is there any way to recover it?

Thanks

**Comment by ylian** [comment]
I can help you with that.

First, reboot your computer again and see if Quiver can load your notes. There was a bug in Quiver 3.0 that was fixed, but it might have some residue effect if you upgraded to 3.0.1 only recently.

If that doesn't work, it's important to find out where your Quiver library was.

If you never moved your Quiver library to another location, it would be here: `~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/Quiver.qvlibrary`. 

If you moved the library to Dropbox/Google Drive/iCloud Drive, etc, check those places for Quiver.qvlibrary. Check the size of the library file and see if it's reasonable (the default size with the tutorial notes is only a couple MB).

If you could find your library file that is of reasonable size, your notes would be there. Just double click on the library to open it in Quiver, in case somehow Quiver can't resolve the library location.

If you couldn't find your library file or it only contains the default tutorial notes, you would need to restore the file from a backup. If you had it backed up to Dropbox or Time Machine, it's easy to restore.

Let me know and I can help guide you if needed.

**Comment by sangheraio** [comment]
Ok great, I tried restarting but it didn't work. The library file is in the default location still and is 1.1MB, I tried double clicking on it and it opens Quiver, but the screen still remains blank. It also says it was last modified March 19th, which can't be true because I was updating notes just yesterday...

**Comment by sangheraio** [comment]
Ok very odd, I just quit and restarted quiver and all the notes came back. I'll definitely be backing up frequently now though, thanks!

**Comment by ylian** [comment]
Hmm. Can you do me a favor and open Preferences > Sync. And send me the library location.

**Comment by Everhusk** [comment]
/Users/SS/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver/Quiver.qvlibrary

**Comment by ylian** [comment]
That's weird. That's the default location. But your library at the default location is only 1.1MB, too small to contain your notes.

**Comment by ylian** [comment]
Quit Quiver and reopen, check the library location again. Thanks.

**Comment by ylian** [comment]
Or maybe your notes are really only 1.1MB?

**Comment by sangheraio** [comment]
Yeah everything looks fine, it's still the same location. Also, I backed it up to new location and it was the same size, so my notes are only 1.1MB.

**Comment by sangheraio** [comment]
Thanks for the quick response!

**Comment by ylian** [comment]
I see. Just one more thing before I let you go. When you couldn't see your notes, were you seeing just an empty app window, or the app UI was there but no notebooks?

**Comment by sangheraio** [comment]
It looked like this:

https://cloud.githubusercontent.com/assets/6391776/14082670/9b8348dc-f511-11e5-8299-fbaa05bbeef5.png

**Comment by ylian** [comment]
I see. That's actually a reported bug that I haven't hunted down yet: https://github.com/HappenApps/Quiver/issues/538

Right now just reopen Quiver if it happens. I will try to fix this.

**Comment by ylian** [comment]
It's an issue with app loading, but the notes are safe.

**Comment by JMichaelTX** [comment]
@Everhusk , sorry for your loss/troubles.

This won't help you now, but for the future, and for others, this may be a good backup for Quiver.

#### If you sync Quiver using DropBox, then you can restore the Quiver files in Dropbox to a prior version.

**Comment by Michaela-Davis** [comment]
@ylian Thank you!!!! I also lost my entire Quiver library with critical information after restarting my computer. Your advice save me, and my Quiver library!

**Comment by crabdul** [comment]
I had this issue as well. I looked in  `~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/Quiver.qvlibrary` but the library in there was a very old one. I haven't deleted any libraries

Any update on this issue?
