### ISSUE TITLE
Bug: Clicking Replace does not overwrite existing library

### ISSUE THREAD

**Issue by neo-anderson** [HappenApps/Quiver#572]
I had created a backup of the notebooks into a library file "Backup.qvlibrary" in the Documents folder. After a few days, I tried to create another backup, with the same name. Quiver opened a message box alerting me of an existing file with the same name. I clicked "Replace" button. But, Quiver did NOT backup the library.
Unfortunately, I assumed that a backup would have been created and opened another library to work on. Afterwards, when I opened "Backup.qvlibrary", all the changes I made since the first backup were gone. :(

**Comment by ylian** [comment]
Fixed in 3.0.2.
