### ISSUE TITLE
note disappear when changing the notebook it belongs to

### ISSUE THREAD

**Issue by LeonardoGentile** [HappenApps/Quiver#580]
STEPS:  
- search by tag, for example `node`
- in the search result there are 3 notes. The side left panel is focused on tags. The tag marked `node` on the sidebar marks `3`
- change one of the note notebook by editing the top left select on the main window (`Move to Notebook`)

RESULT:
The note disappears from the search result. 

To let it reappear: change selected tag (form left sidebar) and go back to previous one. Now the note reappears in the search result (the search having the tag selected)

**Comment by ylian** [comment]
Fixed in 3.0.7.
