### ISSUE TITLE
Can't paste URL from address bar

### ISSUE THREAD

**Issue by preflight** [HappenApps/Quiver#594]
For the past few months in Chrome Canary (currently version 53), it's not possible to copy a URL from the browser address bar and paste it into a text cell in Quiver. The cursor remains in position and nothing is pasted.

Other browsers work fine, including stable Chrome (version 50), Safari, etc.

Pasting the URL into a code cell or a markdown cell works fine.

If you paste the URL into a text cell and then convert it to a markdown cell, the cell contents become an empty set of link brackets with the pasted address in parentheses. This occurs without re-pasting after switching to markdown. Switching back to text cell hides the content again.

Here's what you see if you:
1) copy the URL from Chrome Canary address bar
2) paste the URL into a text cell in Quiver
3) convert the text cell to a markdown cell

```
[](https://github.com/HappenApps/Quiver/issues/new)
```

**Comment by ChiefWooster** [comment]
Ran into the same issue for Chrome: Version 51.0.2704.84 (64-bit)

**Comment by ylian** [comment]
Fix coming shortly.

**Comment by mugshepherd** [comment]
I have this same issue.  Copy and Pasting does not work, although it does successfully paste if I "Paste and Match Style".

Chrome Version 51.0.2704.103 (64-bit)

**Comment by ylian** [comment]
Fixed in 3.0.3.

**Comment by preflight** [comment]
Working great after update - thanks for fixing it!

**Comment by mugshepherd** [comment]
I updated my app, but the version coming up when i open it on my desktop is
still v. 3.0.2.  Finding the App on the App store and clicking Open opens
up v3.0.2. I have restarted my computer since updating.  Any suggestions?

Thank you - great product!

On Mon, Jul 11, 2016 at 9:07 AM, preflight notifications@github.com wrote:

> Working great after update - thanks for fixing it!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/HappenApps/Quiver/issues/594#issuecomment-231649473,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHbI_BXTzmkgfcIPb2VBWQRwzMxjUCQ_ks5qUd24gaJpZM4IkzVj
> .

##

**Comment by ylian** [comment]
@mugshepherd Please delete the app on the desktop. Use the one in /Applications instead (that's the one installed by the Mac AppStore). If still not working, delete the one in /Applications as well, and install from the AppStore again. (This won't affect your data.)
