### ISSUE TITLE
[Feature Request] Hotkey for "Move to Notebook"

### ISSUE THREAD

**Issue by cppcho** [HappenApps/Quiver#597]
Hi thanks for your awesome app! @ylian 

Would you please consider adding a shortcut (such as ctrl+cmd+m like evernote) to move a note to chosen notebook? Thanks!

**Comment by ylian** [comment]
You can do that already. Just create a custom hotkey for the menu item "Move to Notebook". 

https://support.apple.com/kb/PH18418?locale=en_US

**Comment by cppcho** [comment]
Oh didn't know that. Thanks.
