### ISSUE TITLE
[Bug] Cannot edit after changing to side-by-side preview from preview only

### ISSUE THREAD

**Issue by xiaohk** [HappenApps/Quiver#600]
![image](https://cloud.githubusercontent.com/assets/15007159/15721883/9fcc3bde-2800-11e6-87db-3c2d79757325.png)
I found I can't type after changing note view from the Preview Only to Side-by-side Preview.

One current solution is to convert to Edit Only mode then convert back. It looks like a bug 😄

**Comment by ylian** [comment]
Good catch. Thanks.

**Comment by ylian** [comment]
Fixed in 3.0.6.
