### ISSUE TITLE
Search failure

### ISSUE THREAD

**Issue by lunelson** [HappenApps/Quiver#602]
I remember having this issue earlier, but I thought it was solved. 
See in the screenshot, how search fails to find the text that is in the note:

![screen shot 2016-06-03 at 13 03 27](https://cloud.githubusercontent.com/assets/1242864/15776963/fad602ee-298b-11e6-8088-6efce9750aba.png)

**Comment by m-thomson** [comment]
+1 

I've just experienced this exact bug.

**Comment by umiyosh** [comment]
I also have faced the mismatch problem of search results as well.

**Comment by osdouglas** [comment]
This also happened to me. I had to stop using the app because of it.
