### ISSUE TITLE
Tabs vs Spaces issue when copy/pasting

### ISSUE THREAD

**Issue by pentool** [HappenApps/Quiver#61]
Hello,

When pasting code from a document that uses tabs for indentation (as opposed to spaces), Quiver displays these tabs with the tab character (small right arrows). Which is good. However, when I start adding/changing the pasted code, and use the tab key to insert tabs (for indentation), these are going to be converted to spaces and not tabs.

**Example:**

As a preparation, set the 'Code Cell' tab size to 4 spaces in the preferences.
1. Create a code document in another app. Eg, use Sublime Text to create PHP, C++, Objective-C, PHP etc code. Can be gibberish too. Make sure the application uses TAB characters for indentation and not spaces. Insert a few tabs into the document, and notice they are correctly inserted.
2. Copy the entered code and paste it into a code block into Quiver. (Make sure you are showing the invisible characters.) Notice that the TAB characters (that you have inserted in the other app) are indicated in Quiver as small, right pointing arrows. These are correct, since they are actual TABs.
3. Try to delete one of these TAB characters that you have pasted from the other app. Notice you only have to press the delete/backspace key once, and the TAB character will be deleted.
4. Now, press the TAB key a few times to insert TAB characters into this same code cell via Quiver. Notice the TAB characters are indicated by dots not the small, right pointing arrows! This is because you are actually inserting spaces and not TABs! To prove that...
5. Press the delete/backspace key to delete the 'fake' TAB characters you entered. Notice these are spaces (indicated by dots)! You have to press the delete/backspace key 4 times to delete a single TAB.

**Conclusion:**

When I press the TAB key in a code cell in Quiver, it should insert TAB characters (indicated by the small right arrows) and NOT spaces (indicated by dots). Otherwise the code you paste from another app (and later edit in Quiver) will have mixed TABs. Some tabs will be real tabs (the ones that were pasted from the other app) and some tabs will be just spaces (the ones you inserted via Quiver).

(...unless I'm doing something wrong. Sorry for the lengthy explanation, hope it makes sense.)

Currently I don't see a preference whether you want your tabs to be actual TAB characters or spaces. The only preference I see is to declare that 1 TAB = X spaces.

Quiver 2.1.2 (10)
OS X 10.9.5 Mavericks

**Comment by ylian** [comment]
Appreciate the detailed report. I will add a setting "Use Soft Tabs". This is something that Ace supports.

**Comment by ylian** [comment]
Added a setting "Use soft tabs". Also tab width options are now from 1 to 8, consistent with Sublime Text.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b17.zip

**Comment by pentool** [comment]
Thanks very much!!! Looks good!

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
