### ISSUE TITLE
How do I get Solarized?

### ISSUE THREAD

**Issue by lifyd** [HappenApps/Quiver#615]
The https://github.com/HappenApps/Quiver/wiki/Supported-Themes page says that Solarized Dark is a supported theme, but I can't seem to find the link.

Where can I get access to the theme?

**Comment by ylian** [comment]
That page refers to the code cell's theme (Preferences > Cells > Code Cell > Theme), not the overall app theme.

**Comment by kyanny** [comment]
Hi @lifyd and @ylian !
Just want to let you know that I made Solarized Light / Dark themes for Quiver.
See https://github.com/kyanny/Quiver-Theme-Solarized to get theme json files.
(I've updated [wiki page](https://github.com/HappenApps/Quiver/wiki/Themes) too)
