### ISSUE TITLE
a bug maybe, can't copy the url address in the text cell

### ISSUE THREAD

**Issue by fhefh2015** [HappenApps/Quiver#623]
quiver version :
Version 3.0.2 (86)

description：
To copy a url address in the text cell, the cell doesn't have the url text.

the previous version is not the problem.

![untitled](https://cloud.githubusercontent.com/assets/14891797/16368116/175e997e-3c5d-11e6-9a2d-ceec927036b4.gif)

**Comment by mattgibson** [comment]
Also getting this. Chrome 51.0.2704.84 (64-bit)

**Comment by fhefh2015** [comment]
@mattgibson 
i update chrome to the newest version(51.0.2704.106 (64-bit)),  the problem is still unsolved.
safari is ok

**Comment by ylian** [comment]
Yeah, a fix is coming shortly.

**Comment by ylian** [comment]
Fixed in 3.0.3.
