### ISSUE TITLE
How can I inspect the DOM of the interface if I want to write a new theme?

### ISSUE THREAD

**Issue by jimzenn** [HappenApps/Quiver#624]
I also want to know the structure of editor, so that I can write new themes

**Comment by ylian** [comment]
Turn on webview inspector: http://stackoverflow.com/questions/695038/is-there-a-way-to-use-the-webkit-web-inspector-from-a-cocoa-webview-object

**Comment by jimzenn** [comment]
Cool

**Comment by jimzenn** [comment]
@ylian but I still cannot inspect the elements in editor. Is there a way?

**Comment by ylian** [comment]
Once you follow the link above to turn on the web inspector, you can right click in the editor area and choose "Inspect Element", and you will see the web inspector.

![screen shot 2016-06-30 at 8 57 26 pm](https://cloud.githubusercontent.com/assets/984895/16500524/4819ed48-3f05-11e6-89a2-3e78a07dfb0b.png)
