### ISSUE TITLE
Bug when deleting note

### ISSUE THREAD

**Issue by cppcho** [HappenApps/Quiver#625]
Quiver Version 3.0.2 (86)

Step to reproduce:
1. Create notes with title 1,2,3,4,5,6 in Inbox
2. Tag these notes with tag "test"
3. Switch to tag listing view and select the tag "test", such that all notes tagged with "test" are shown in the listing
4. Delete 3 notes one by one with Command+Delete
5. You will see the remaining notes will display wrongly

Illustration video: [quiver_delete_bug.mov](https://dl.dropboxusercontent.com/u/9208769/quiver_delete_bug.mov)

Edit: Just realized same bug occured without using keyboard shortcut too

**Comment by ylian** [comment]
Fixed in 3.0.7.
