### ISSUE TITLE
[Feature Request] Configurable Title Text Sizing

### ISSUE THREAD

**Issue by runrunrirun** [HappenApps/Quiver#632]
It would be nice if the font size used for the Note Title text were configurable to make it larger/smaller.

**Comment by visini** [comment]
This is currently possible, check out Settings > Styles > Editor (or Preview or any other area), then add:

```
#titlearea{
  font-weight: bold;
  font-size: 18px;
}
```

**Comment by ylian** [comment]
Indeed, it can be configured in CSS. Thanks, @visini .
