### ISSUE TITLE
Suggestion: View and Edit Modes

### ISSUE THREAD

**Issue by gabriellebadie** [HappenApps/Quiver#64]
It would be fantastic to have a 'view' mode and 'edit' mode.  As it looks to me (right now) I must use either the preview or presentation button to view rendered markdown.  It would be far preferred if I could be in either a 'view' or 'edit' mode so I don't have to open an extra window just to see the rendered markdown.  Most of the time I am viewing my notes, _not_ editing them, and viewing notes still doesn't provide a great experience for me as I have to have two windows open to browse and view.

**Comment by ylian** [comment]
Thanks for the suggestion. The preview is being redesigned in v2.2.

https://github.com/HappenApps/Quiver/issues/59#issuecomment-77149364

**Comment by gabriellebadie** [comment]
Sweet! I'll follow that comment.
