### ISSUE TITLE
Bug when moving notes in "All Notes" view

### ISSUE THREAD

**Issue by mpbarras** [HappenApps/Quiver#640]
Quiver 3.0.2
1. View notes 1,2,3 in "All Notes" list view
2. Select note 2 and move it to a [different] folder
3. Note 2 disappears from the list (note 3 is now highlighted), but detail pane still shows contents of note 2. 
4. Select note 1 - detail pane shows note 1 contents. Select note 3 - detail pane shows note 2 contents.
5. Change view to another notebook and then back to "All Notes" and note 2 is now listed properly again.

**Comment by the-c0d3r** [comment]
Quiver 3.0.3

This bug is also in "Recents View", and most likely, all of them. And it is not supposed to disappear when you move note to notebook in "Recents View", it just didn't make any sense.

I was about to create a new issue for this.

**Comment by ylian** [comment]
Fixed in 3.0.7.
