### ISSUE TITLE
Application wide macros require manually reload of document

### ISSUE THREAD

**Issue by notmgsk** [HappenApps/Quiver#646]
Application wide macros are not applied immediately to a document that is currently being edited, meaning that one must leave and re-open the current document.

I don't know if this is intended behaviour or not, but I thought it was worth mentioning. A preferred behaviour (IMO) would be that the current document is refreshed with these changes to macros in mind.

**Comment by ylian** [comment]
Yes it's a bug. The equation cache needs to be cleared.

**Comment by ylian** [comment]
Fixed in 3.0.4.
