### ISSUE TITLE
Enable Formatting via menu (and keyboard shortcuts) in Markdown cells

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#65]
Would be really great to be able to format the markdown text with keyboard shortcut

You can check http://25.io/mou/ for inspiration

**Comment by ylian** [comment]
Thanks. Working on it.

**Comment by ylian** [comment]
Implemente in 2.2b28.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b28.zip

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
