### ISSUE TITLE
[Feature Request] - Fence around code in markdown

### ISSUE THREAD

**Issue by BrendanThompson** [HappenApps/Quiver#650]
It would be ideal if there was the ability to have a fence around the code blocks in markdown.

**Comment by ylian** [comment]
Fenced code blocks is already supported in Markdown.

**Comment by BrendanThompson** [comment]
Hey @ylian when I do a code block, it doesn't fence it. It only shows the syntax highlighting which most of the time isn't enough to differentiate it from the rest of the text. I was thinking more like the GH style where it changes the background colour slightly so you can obviously see that there is a block of code.

**Comment by ylian** [comment]
Are we talking about the same thing? The background color depends on the code cell theme you have chosen.

![image](https://cloud.githubusercontent.com/assets/984895/17164604/2870701e-53ca-11e6-832c-9cf7c76a2e1d.png)

**Comment by BrendanThompson** [comment]
I don't have the line numbers turned on for my code blocks, even there you can see that background of the block is still white like the rest of the document. I am more talking like the below:

![github-code-fence](https://cloud.githubusercontent.com/assets/2595712/17164700/1c9271f4-540e-11e6-85b4-b37974643baf.png)

As you can see the code fence is more of a browny-grey colour, and is very easily distinguishable from the remainder of the other content. I don't want any of the other background colours to change, just the code fence.

**Comment by ylian** [comment]
I see. You can change the code cell theme:

![image](https://cloud.githubusercontent.com/assets/984895/17164997/441132e2-53cd-11e6-9c8c-5070cae3ad5e.png)

This is how it looks when using the "Dawn" theme. I also turned off the line number.

![image](https://cloud.githubusercontent.com/assets/984895/17165006/54187402-53cd-11e6-82c0-b16db82b7220.png)

**Comment by BrendanThompson** [comment]
Ahh excellent! Is it possible to customise the colourings at all?

**Comment by ylian** [comment]
To do that, you need to create a new Ace theme (https://ace.c9.io/). No convenient way to do it in Quiver.
