### ISSUE TITLE
Default Cell Type

### ISSUE THREAD

**Issue by adamshand** [HappenApps/Quiver#657]
There doesn't seem to be a way to set the default cell type when you create a new document.  It always starts as a text cell.

I'd quite like to have Markdown be my default and I can imagine others might like code to be the default.

**Comment by jeffkimbrel** [comment]
The first page of the preferences has a selector for "Default Cell Type". Any of the 5 types can be selected here.

**Comment by adamshand** [comment]
Whoops, missed the obvious!  Thanks.
