### ISSUE TITLE
[Bug] Notes with no tags display blue line under note title

### ISSUE THREAD

**Issue by maddiemort** [HappenApps/Quiver#664]
## Description

When notes with no tags are viewed in the Preview view, or exported to a PDF, a blue line appears where the tags would normally appear. I only noticed this behaviour after updating to macOS 10.12. This does _not_ happen when exporting to HTML.
## Version Info

macOS version: 10.12 Sierra
Quiver version: 3.0.3 (88)
## Screenshots

A note called **Getting Set Up on Mac for Swift Development** in Editor view: (Note the lack of tags)

![screen shot 2016-08-08 at 16 13 01](https://cloud.githubusercontent.com/assets/13041332/17494892/afcea332-5d84-11e6-8796-7590e6764cff.png)
### In Preview View

_There is a blue line under the title where the tags would normally appear_

![screen shot 2016-08-08 at 16 13 14](https://cloud.githubusercontent.com/assets/13041332/17494894/b1206446-5d84-11e6-8e05-f610900a9bc8.png)
### Exported to PDF

_The line appears_

![screen shot 2016-08-08 at 16 28 38](https://cloud.githubusercontent.com/assets/13041332/17494994/3354ba7a-5d85-11e6-9c5e-fe7cc149c06a.png)
#### Viewed in Safari

_The line does not appear_

![screen shot 2016-08-08 at 16 28 43](https://cloud.githubusercontent.com/assets/13041332/17495002/3a6c1a10-5d85-11e6-9f54-8d767c234ed8.png)
#### Viewed in Chrome

_The line does not appear_

![screen shot 2016-08-08 at 16 29 56](https://cloud.githubusercontent.com/assets/13041332/17495087/a415013e-5d85-11e6-8a78-48a47d1ae8cf.png)

**Comment by ylian** [comment]
Thanks. Will fix before 10.12 is released.

**Comment by ylian** [comment]
Fixed in 3.0.4. Apologize for taking so long.
