### ISSUE TITLE
LaTeX text not rendering correctly

### ISSUE THREAD

**Issue by nschneid** [HappenApps/Quiver#67]
I have a LaTeX cell with:

``` latex
\footnote{Cohen's $\kappa$, limited to tokens for which both annotators assigned a supersense, is very similar: 76\%, 93\%, and 90\%, respectively.}
```

It displays in Preview and Presentation modes as:

> \footnote{Cohen's κ, limited to tokens for which both annotators assigned a supersense, is very similar: 76\%, 93\%, and 90\%, respectively.}

i.e. it handles the markup for math, but not text.

**Comment by ylian** [comment]
This is a limitation of MathJax, which Quiver uses to render LaTeX cells. MathJax is not a full LaTeX renderer: it only supports math-mode macros, not text-mode or general processing macros. And in Quiver, the LaTeX cell is only meant to typeset math equations.
