### ISSUE TITLE
[Request] Support Notebook within notebook

### ISSUE THREAD

**Issue by xnxky** [HappenApps/Quiver#679]
Currently, Notebook is like a folder, which can only hold notes, which are like files; However, many times, I need a deeper hierarchy, having Notebook within in Notebook, just like in a filesystem, a folder can have folders in it for better management of different categories:
- Notebook1
  - Notebook11
    - Note 1
    - Note 2
    - ....
  - Notebook12
    - Notebook123
      - Note 4
      - Note 5
  -  .....
- Notebook2
  .....

**Comment by ylian** [comment]
Merged with #2.
