### ISSUE TITLE
Performance Issue: Too slow to render complicated LaTeX document.

### ISSUE THREAD

**Issue by huntzhan** [HappenApps/Quiver#681]
It takes nearly 20 seconds to render a page with **a lot of** LaTeX elements, during the rending process Quiver is stuck and giving no response to user operations. Example of document: http://huntzhan.org/suffix-automaton-tutorial/

**Comment by ylian** [comment]
Yes, MathJax is too slow. I am testing KaTeX which renders 20 times faster.

**Comment by huntzhan** [comment]
Rendering speed is one problem, but the major issue annoys me is that Quiver doesn't response to user operation during rendering. I think it would be great to parallelize the rendering process so that it would not hurt the user experience.

**Comment by ylian** [comment]
Yes, both issues need to be resolved. Switching to KaTeX and markdownit improves the rendering speed significantly. Another step is to use web worker and do the rendering in a different thread.

**Comment by huntzhan** [comment]
Cool, thanks for response.
