### ISSUE TITLE
Markdown Bug: Links with parentheses not working properly

### ISSUE THREAD

**Issue by allisonlphillips** [HappenApps/Quiver#685]
This markdown:
`[Recursion](https://en.wikipedia.org/wiki/Recursion_(computer_science))`

Is displayed with an extra `)`:
![screen shot 2016-08-29 at 4 24 58 pm](https://cloud.githubusercontent.com/assets/16893869/18070792/2d10907c-6e05-11e6-86d7-d1428f5642d9.png)

When you click on the link, it's also not taking you to the full URL; it takes you to `https://en.wikipedia.org/wiki/Recursion_(computer_science` instead of `https://en.wikipedia.org/wiki/Recursion_(computer_science)`.

**Comment by tomibennett** [comment]
From issue #155

> I fixed this by replacing my parenthesis by %29 code, but maybe there's better solution that can be found.

**Comment by ylian** [comment]
This will be fixed in the next update. I am switching to a better Markdown parser.

**Comment by tomibennett** [comment]
Great news!

**Comment by ylian** [comment]
Fixed in 3.0.4.
