### ISSUE TITLE
Impossible to add a link

### ISSUE THREAD

**Issue by benjbaron** [HappenApps/Quiver#69]
As of version 2.1.2, it is impossible to add links to the text. It would also be cool to have a fast access button on the toolbar.

**Comment by ylian** [comment]
There are a few ways to add a link in 2.1.2:
1. Copy a link from the address bar or a webpage, and paste it in a text cell.
2. Drag a link from a webpage directly into a text cell.
3. Enter the url manually, then select it and hit "cmd+k" to turn it into a hyperlink.

I agree that Method 3 is confusing and needs improvement. Hitting "cmd+k" without selecting any text should open a dialog box so the user can enter the link and title.

**Comment by dperetti** [comment]
One should be able to enter any kind of link, not just http://. I'm using private URL schemes, such as: dpl:ma-ujZcJO7n.py and usually it works in text editors.

**Comment by lahtikarri** [comment]
I agree that `cmd + k` should bring up a dialog box for entering the directly there. That's what I think most users are expecting.

**Comment by user-don** [comment]
As a developer, I love using Quiver for keeping track of projects and useful notes. However, not being able to embed hyperlinks is a huge pain point. Extremely long URLs can totally disrupt the flow of my notes. It would be great to have something like cmd-K (insert link) in Google Docs to eliminate long URLs  and improve readability.

**Comment by ylian** [comment]
Absolutely, this is one of the remaining things I am working on for the next update.

**Comment by JMichaelTX** [comment]
ylian commented on Mar 17:

> Hitting "cmd+k" without selecting any text should open a dialog box so the user can enter the link and title.

This does NOT work.  Just tried it.

**Comment by ylian** [comment]
Improved in Quiver 3.0 beta: https://github.com/HappenApps/Quiver/issues/162

**Comment by JamesHaskell** [comment]
This is a big problem for me.  When will this be fixed???  Cmd-K is completely broken on my 2.1.2 version.

**Comment by ylian** [comment]
@JamesHaskell Try Quiver 3 beta: https://github.com/HappenApps/Quiver/issues/162

**Comment by JamesHaskell** [comment]
How do install this?  Please give me detailed instructions.

**Comment by JamesHaskell** [comment]
Never mind.  I’m not comfortable installing an app that is not on the App Store.  When are you going to release a fix for this serious issue to the App Store???

**Comment by ylian** [comment]
@JamesHaskell Will be released in Quiver 3.0. I'm fixing the last couple bugs.

**Comment by lahtikarri** [comment]
@JamesHaskell I decided to write to you a little more detailed instructions: 
1. First, it might help if you cmd+z your head from your a55.
2. Instead of choosing to whine like a 11-year old developer, [download the beta version](https://github.com/HappenApps/Quiver/issues/162) (yes, adding a link works with cmd+k, including outside of the Mac App Store - see attached photo).
3. Feel the immediate satisfaction of getting on with your life.
   <img width="912" alt="oh-a-third-link" src="https://cloud.githubusercontent.com/assets/10692193/10708317/80a4daf6-79da-11e5-840f-ae7eba67e137.png">

Sorry to others about the extra messages.

**Comment by JamesHaskell** [comment]
Expectations change when you charge money for an app.  If this was Open
Source, I would be happy to help, and OK with a terse tech support reply of
"Try Quiver 3 beta: #162 https://github.com/HappenApps/Quiver/issues/162".

**Comment by ylian** [comment]
Let's drop this. Quiver 3 will be out in a few days.

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.
