### ISSUE TITLE
Don't you think  quiver  support outline-article is a good idea?

### ISSUE THREAD

**Issue by karterotte** [HappenApps/Quiver#699]
I hope quiver articles could support folding and unfolding paragraph. And it could apply certain theme to different levels.Just like omnioutliner(it just lacks markdown support)

**Comment by ylian** [comment]
Unfortunately I don't think Quiver should support outliner functions. Outliners provide a quite different way of organizing information --- hierarchical. I think Quiver should stick to a linear structure in the note.
