### ISSUE TITLE
Enable Scroll Past End

### ISSUE THREAD

**Issue by michael-jarosik** [HappenApps/Quiver#7]
Quiver is amazing -- truly remarkable work.

One feature I'd like to see added is the ability to scroll note content higher when you reach the bottom of the screen. Currently, once a note reaches the height of the screen, the cursor position is always at the bottom as you add more content to the note. Adding extra line breaks to create space isn't really practical because you would then need to remove them when creating a new cell. In case it helps, in Sublime Text, this setting is named "scroll_past_end".

**Comment by ylian** [comment]
Implemented in Quiver 2.1. There is a setting "Scroll Past End" in preferences.
