### ISSUE TITLE
big space gap in markdown cell if create a table using HTML syntax

### ISSUE THREAD

**Issue by miyakido** [HappenApps/Quiver#707]
<img width="1064" alt="screen shot 2016-10-04 at 3 59 56 pm" src="https://cloud.githubusercontent.com/assets/11013069/19092341/d0b3a194-8a4b-11e6-983e-8b01a176db4e.png">

This is in the side-by-side view.

so as you can see, there is a very big gap before the table.

I use this syntax because I want to create a table without table header.

**Comment by ylian** [comment]
This will be fixed in the next update. It's a bug with the Markdown renderer.

**Comment by ylian** [comment]
Fixed in 3.0.4.
