### ISSUE TITLE
Data lost after switching notes

### ISSUE THREAD

**Issue by RobinQu** [HappenApps/Quiver#709]
System Info:
Version 3.0.3 (88)
OSX 10.12 (16A323)

How to reproduce:
1. Edit current note for a while 
2. Click on another item on the left panel to show another note
3. Switch back to the first note
4. Data in the first note will be partially lost; Export or save won't find the lost data neither.

This is considerately dangerous for a note keeping software. 
Happened twice on me. 😭

**Comment by ylian** [comment]
Good find. Will fix. Thanks.

**Comment by lemonade512** [comment]
Just want to mention that this is happening to me as well. I have found that it is most likely to happen if I write something and then quickly switch to a new note. In fact, I can get it to happen pretty consistently if I switch notes quickly enough.

Quiver Version 3.2.2 (181)
OSX 10.14

Basically the same steps to reproduce as @RobinQu, but make sure you switch quickly after you edit the first note.

**Comment by ylian** [comment]
@lemonade512 Yes, this is a regression. Will fix in 3.2.3.

**Comment by ylian** [comment]
Fixed in 3.2.3.

**Comment by hollisimo** [comment]
This is happening consistently for me in 3.2.4 on OSX 10.14.4, and has made Quiver totally unusable for me.
