### ISSUE TITLE
2.1.2: Undo (cmd+z) does not work when editing title of note

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#71]
On text of note working fine

**Comment by ylian** [comment]
Indeed. Thanks for reporting.

**Comment by ylian** [comment]
Fixed in 2.2b21. Also fixed another issue that a long title would be cutoff.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b21.zip

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
