### ISSUE TITLE
[question] how to delete line number on markdown cell

### ISSUE THREAD

**Issue by ynqa** [HappenApps/Quiver#713]
as of title, I hope not to display without line number on markdown cell.
so I try using three or more back-quotes or four spaces.

```
<- like this, no line number is here. 
```

and also, if you can, NOT using code cell set no line number.

**Comment by ynqa** [comment]
hmm, I want to use code cell with line numbers, and also not to use markdown without line numbers...

**Comment by ylian** [comment]
If you just want a code block without line numbers, use the standard indented code blocks in Markdown (4 spaces indentation).

```
Here is an example of AppleScript:
    tell application "Foo"
        beep
    end tell
```

But you won't get syntax highlighting this way.
