### ISSUE TITLE
Down key doesn't work when navigating a cell ended with empty lines

### ISSUE THREAD

**Issue by MauriceZ** [HappenApps/Quiver#72]
If a cell ends with 1 or multiple empty lines and the cursor is placed in any one of those lines, the down arrow moves the cursor directly to the cell below it, or does nothing if there are no cells below it.

Same thing for the up arrow when the empty lines are at the beginning of the file.

As in this case, the down key doesn't do anything:
![screen shot 2015-03-19 at 9 08 07 pm](https://cloud.githubusercontent.com/assets/6665594/6744183/1a6e9f38-ce7c-11e4-8090-59f45c7bc912.png)

I think it has something to do with the new feature of navigating through different cells with the arrow keys.

**Comment by ylian** [comment]
Thanks for reporting the issue. Will fix.

**Comment by ylian** [comment]
Fixed in 2.1.3b14.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b14.zip

**Comment by MauriceZ** [comment]
Hey, in this version, the down key doesn't work if the last line is empty and the cursor is set at the very end of the 2nd to last line. Like this:

![example](https://cloud.githubusercontent.com/assets/6665594/7152253/3edaef90-e306-11e4-9aeb-51562ed10994.png)
Thanks!

**Comment by ylian** [comment]
Thanks. Fixed again in 2.2b33. Let me know if you find other edge cases.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b33.zip

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.
