### ISSUE TITLE
Text input eventually slow

### ISSUE THREAD

**Issue by jpuritz** [HappenApps/Quiver#720]
After a while, a build up develops between keyboard input and text entry.  It seems to happen after rendering markdown cells.  It goes away after a restart, but gets annoying.

**Comment by ylian** [comment]
Aware of the issue. This happens if a Markdown cell gets long, esp. with equations. I have already significantly improved the Markdown cell performance in my dev build, so this will get better in the next release.

**Comment by ylian** [comment]
This is significantly improved in 3.0.4.
