### ISSUE TITLE
Request for enhancement: support for restructured text

### ISSUE THREAD

**Issue by KarstenSchulz** [HappenApps/Quiver#723]
RFE: Hi there! Are there any plans to support Restructured Text format (big parts of the python world rely on it: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html).

It would be nice, if the editor could support the syntax. It would be absolutely superior, if we got a restructured text cell like the markdown cell. Thanks!

**Comment by ylian** [comment]
Maybe I will add support for custom parser for the Markdown cell.

**Comment by dnng** [comment]
Any news about this issue?

**Comment by jkryanchou** [comment]
:+1: Looking forward to add the feature to support reStructuredText. And I have searched for a while found that the repo could do helpful on converting from Markdown to reST.
