### ISSUE TITLE
After note deletion, note highlighted in notes list and contents of note editor are out of sync

### ISSUE THREAD

**Issue by tomleim** [HappenApps/Quiver#738]
I'm using v3.0.3 under OS X 10.10.5. 

Create a note with title "note 1" and contents "note 1 blah blah blah". Create a second note with title "note 2" and contents "note 2 blah blah blah". 
Now delete note 2 by pressing command-delete. Note 1 will be highlighted in notes list but note 2's contents will appear in note editor. Scroll down one note using down arrow in notes list. You'll see the content of note 1 in the note editor and not that of the currently highlighted note. 

Thanks. I love what you've done with Quiver and I look forward to it being free of little bugs like this.

**Comment by ylian** [comment]
Fixed in 3.0.7.
