### ISSUE TITLE
Multiple Cursors?

### ISSUE THREAD

**Issue by praveenperera** [HappenApps/Quiver#743]
Is it possible to edit multiple instances at once for example CMD+D in Sublime

**Comment by ghost** [comment]
You can add multiple cursors in a couple of ways. Command + Click to add cursors wherever you want and Control+Option+Arrow Key. Arrow up and down add a cursor above or below, Left and Right selects instances of the same word.

**Comment by praveenperera** [comment]
@Poolenc awesome thanks, just realized it works everywhere except the text cell, which makes sense. Thanks

@ylian It would be great to have CMD+D functionality as well, where it selects the next instance and creates a cursor like in sublime.

**Comment by levelont** [comment]
I know this is closed, but I am failing to understand the following statement:

> it works everywhere except the text cell, which makes sense.
[Source](https://github.com/HappenApps/Quiver/issues/743#issuecomment-264536909)

Why does it make sense to not offer multiple cursors on the text cell, may I ask?
I'm afraid that's exactly the use case that I have now, and I can confirm that it does not work.

Edit: I'm on version `Version 3.2.7 (201)`
