### ISSUE TITLE
Request: Nested Notebooks

### ISSUE THREAD

**Issue by lahtikarri** [HappenApps/Quiver#749]
Any chance of getting nested notebooks? 

I have different areas/projects which require multiple notebooks and it would be great if I'd be able to group those together. I know search in Quiver is good, and tagging is a possibility (although not something I'd prefer).

If not, what would you propose as an alternative solution? 

Thanks and thanks so much for this great app!

**Comment by LeonardoGentile** [comment]
Duplicated of #2 a very old and well discussed topic, unfortunately still not implemented..

**Comment by ylian** [comment]
Implemented in 3.1.1.
