### ISSUE TITLE
[Suggest] Export styles to cloud

### ISSUE THREAD

**Issue by ahmadmayahi** [HappenApps/Quiver#750]
I'd like you to add exporting styles to Cloud alongside with the library.

**Comment by ylian** [comment]
You can export your settings as a json file. Put that json file in the cloud and you can load it on another computer.

![image](https://cloud.githubusercontent.com/assets/984895/24313769/a463c208-10de-11e7-8af3-a0731c742175.png)

**Comment by preflight** [comment]
In case it helps anyone (for symlinks, etc.), Quiver's `settings.json` file on OSX 10.11 is located at:

```
/Users/<USERNAME>/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/settings.json
```
