### ISSUE TITLE
Export as Markdown cannot finish.

### ISSUE THREAD

**Issue by Chen-tao** [HappenApps/Quiver#757]
![wechatimg3](https://cloud.githubusercontent.com/assets/1845119/21450188/780d409a-c92f-11e6-8298-85f6f0997794.jpeg)
when i use export as markdown , it just cannot finish , whenever i restart quiver.
please check it.

**Comment by ylian** [comment]
It seems that one of the notes (likely the fifth one in your list) triggered an exception. Can you try to export the fifth note to Markdown? If it fails, please send that note (zip the .qvnote) to me (ylian@happenapps.com) so I can fix. Thanks.

**Comment by ylian** [comment]
Thanks a lot for sending me the note. Fixed in 3.0.4.

**Comment by Chen-tao** [comment]
Thanks a lot, it works.
