### ISSUE TITLE
preview of markdown no code color

### ISSUE THREAD

**Issue by bbxytl** [HappenApps/Quiver#762]
No code color 
![image](https://cloud.githubusercontent.com/assets/6448073/21604818/41de5fd6-d1e0-11e6-87ef-d135b824388d.png)

How do I set up?

**Comment by ylian** [comment]
Specify the language in the code block:

<pre>
```c
char *strncpy( char *dest, const char *src, size_t count);
```
</pre>
![image](https://cloud.githubusercontent.com/assets/984895/21605995/d9bc52ce-d1ac-11e6-828b-00ae0235a5cd.png)
