### ISSUE TITLE
customer preview CSS

### ISSUE THREAD

**Issue by superchun** [HappenApps/Quiver#769]
How can I customer the preview CSS, include h1, h2 ,img, like [github-markdown-css](https://github.com/sindresorhus/github-markdown-css).

**Comment by grstreten** [comment]
Click **Quiver** in the menu bar, go to **Preferences**, then click the **Styles** tab. From there you can edit the CSS for each of the customisable areas :)

**Comment by fabianmarz** [comment]
To see all available default selectors you can right click the quiver app and select "Show Package Contents" then navigate to "Content -> Resources -> html-build -> css". There you'll find all css with the available selectors. Those selectors can be overridden via your custom css from the styles tab.

**Comment by likaiguo** [comment]
Click **Quiver** in the menu bar, go to **Preferences**, then click the **Styles** tab. From there you can edit the CSS for each of the customisable areas :)

for example
Click  Preview:  **Edit CSS**, paste the code below

```
.markdown-cell strong{
  font-size: 14px;
  color: red;
}
```

add the code in editor:
```
**Quiver**
```
you will see:
in preview the text Quiver become red.

**Comment by libratiger** [comment]
> Click **Quiver** in the menu bar, go to **Preferences**, then click the **Styles** tab. From there you can edit the CSS for each of the customisable areas :)
> 
> for example
> Click Preview: **Edit CSS**, paste the code below
> 
> ```
> .markdown-cell strong{
>   font-size: 14px;
>   color: red;
> }
> ```
> add the code in editor:
> 
> ```
> **Quiver**
> ```
> you will see:
> in preview the text Quiver become red.

But How can I find the the available selectors, such as you list as `strong`. the method referenced by @fabianmarz is not work now. 

If I want to increase the font size of code block , the following is not working,

```
.markdown-cell code{
font-size: 14px;
 color: red;
}
```

it only works for the code line.

**Comment by ylian** [comment]
The best way to see the selectors is to turn on the web inspector: https://stackoverflow.com/questions/695038/is-there-a-way-to-use-the-webkit-web-inspector-from-a-cocoa-webview-object

```
defaults write com.happenapps.Quiver WebKitDeveloperExtras -bool true
```

**Comment by libratiger** [comment]
@ylian Thanks for you suggestion, I will try it.

The default code size is a little small under preview mode, maybe some other users also need the ```css``` cheatsheet, can you offer this in the wiki?

**Comment by libratiger** [comment]
After enable the web inspector, I found the following selector can work for the code block

```
.markdown-cell pre div{
  font-size: 14px;
  font-family: "Source Code Pro";
}
```

**Comment by ylian** [comment]
The default css files can be found in the application bundle. Right click on Quiver.app, show package contents, Contents/Resources/dist/css/.

**Comment by libratiger** [comment]
Yes, it works but not obvious enough, maybe the best way is turn on the web inspector.
