### ISSUE TITLE
[Cannot Wait]When is the expected date to release 3.1?

### ISSUE THREAD

**Issue by rockyzhang24** [HappenApps/Quiver#773]

**Comment by kimaldis** [comment]
+1

**Comment by kimaldis** [comment]
Quiver is great for me in almost every respect other than organisation now that my library has become too large for the current flat notebook arrangement to work well. I really hate to appear pushy but there was a post suggesting 3.1 by the end of last year in Nov 16 and now it's all gone rather quiet here in terms of response. Unless there really is going to be something on the horizon I'm going to have to look for an alternative.

Some kind of indication that it hasn't been dropped and maybe even a loose idea of when would be very helpful right now.

thanks.

**Comment by medifle** [comment]
@kimaldis Now what's your alternative?

**Comment by kimaldis** [comment]
I'm toying with Mweb and Bear. There's a lot of developer enthusiasm at Bear right now, it looks to be going interesting places. Mweb is also very good; like Quiver it's well considered but it's also a one person dev which, as with Quiver, makes me a touch nervous about where its future lies.

**Comment by rockyzhang24** [comment]
@kimaldis But Quiver has most powerful support of code block (code cell) which is so attractive. I choose to stay with Quiver and wait for its update. However so far no nested notebooks is so annoying and troublesome. I hope he can release a new version at least just supporting nested notebooks. Sigh...

**Comment by kimaldis** [comment]
I agree but like I said, the erratic nature the lead up to next release troubles me.  If I'm going to invest time and effort I'm going to need a great deal more reassurance about the future.
