### ISSUE TITLE
straight (double or single) quotes in plain text or inline code

### ISSUE THREAD

**Issue by FullStackAlex** [HappenApps/Quiver#774]
Hi, is it possible to write straight (double or single) quotes in plain text or inline code? Right now the quotes are always turned into curly quotes automatically. Is it possible to change this behaviour or to insert somehow straight quotes by a shortcut?

**Comment by ylian** [comment]
In a text cell, the "smart quote" conversion is a system feature, which you can turn off.

![image](https://cloud.githubusercontent.com/assets/984895/24313680/3ab5e62e-10de-11e7-8b63-7bedac061274.png)

In other cell types, only straight quotes are used.

**Comment by FullStackAlex** [comment]
great! thanx!
