### ISSUE TITLE
Move to not found Notebook Moves to Trash

### ISSUE THREAD

**Issue by allisonlphillips** [HappenApps/Quiver#778]
When you do **Move to Notebook** and search a notebook name that does not exist in *Find notebook*, it says *No Matches* and has active **Move** and **Cancel** buttons. If you hit enter/**Move** at this point, it moves it to the trash without even notifying the user that the file was moved to the trash. This is not ideal because it leads to accidental deletions. 

Please change this behavior so that it creates a new notebook with the searched name.

**Comment by ylian** [comment]
Fixed in 3.0.7.
