### ISSUE TITLE
Notebooks menu not visible after closing window unless application is reopened

### ISSUE THREAD

**Issue by allisonlphillips** [HappenApps/Quiver#779]
- Close window in 2-pane mode (haven't checked other modes) but do not exit application
- Command-N to open window. The pane menu (three horizontal lines) icon is not visible in the newly-opened window.  Menu options related to Notebooks/Tags and Document List are greyed out. There seems to be no apparent way to get the pane menu with document list back unless you quit the application and reopen it.

**Comment by ylian** [comment]
In this case the new note is opened in a separate window. That's why you don't see the pane menu and some options are greyed out. You can show the main window from the Window menu > Show main window.
