### ISSUE TITLE
Feature Request: Tag links in HTML export

### ISSUE THREAD

**Issue by Tekl** [HappenApps/Quiver#78]
Exporting a whole Notebook adds navigation links to the upper left and an index file to the exported folder. That's great. How about doing this for Tags (optionally)? They could be placed on the upper right and link to tag pages with a link-list of all tagged notes.

**Comment by ylian** [comment]
Tag links would require extra tag pages. I don't think I would add that.
In 3.0.1, tags are added to the index page, after note titles. Hope that helps a bit.
