### ISSUE TITLE
Multi-touch bar bug in some modes

### ISSUE THREAD

**Issue by yzld2002** [HappenApps/Quiver#788]
I'm using a NMBP with multi-touch bar.
When I input in Markdown cell, the bar keeps flashing.
Need update to adapt this feature.

**Comment by blakfeld** [comment]
I'm also having this problem.

**Comment by cssaus** [comment]
I too suffer this on 13" touch bar Pro (2016). I'm afraid to continue using the app in case something blows!

**Comment by eric-kwon** [comment]
Is there any update on this?

**Comment by cssaus** [comment]
I found quite a weird "solution" to this today.

Try opening Apple's Notes app; then via "View" on the menubar go to "Customise Touch Bar..." and within that beautiful thing that pops up, unselect "Show typing suggestions"; then press "Done".

This for some reason seems to be disabling spelling suggestions being offered through the touchbar to apps that use ace editor (which I'm guessing is the source of the flashing problem). At least it has for me in both Quiver and RStudio.

Hope this works for others, and leads someone to figuring out what's really happening. Cheers

**Comment by ylian** [comment]
Fixed in 3.1.1.
