### ISSUE TITLE
Up-arrow jumps over newlines

### ISSUE THREAD

**Issue by Bouke** [HappenApps/Quiver#79]
Say I have the following text cell (2 newlines, the cursor is on the third line)

```
⏎
⏎
| ← cursor is here
```

If I now press the up-arrow, the cursor jumps to the title field. I would expect the cursor to move to the 2nd line of the text cell.

**Comment by ylian** [comment]
Fixed in 2.1.3b14.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b14.zip

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.
