### ISSUE TITLE
Markdown link not parse right if link contains parenthesis

### ISSUE THREAD

**Issue by tankywoo** [HappenApps/Quiver#791]
E.g:

```
[hop](https://en.wikipedia.org/wiki/Hop_(networking))
```

The url is `https://en.wikipedia.org/wiki/Hop_(networking)`, which include **parenthesis**， and the parsed text is `hop)`, with a close parenthesis in the end.

Below is parsed by Github GFM，and is ok:

[hop](https://en.wikipedia.org/wiki/Hop_(networking))

**Comment by ylian** [comment]
Fixed in 3.0.4.
