### ISSUE TITLE
Cursor Disappears Within Code Cell

### ISSUE THREAD

**Issue by justnealpatel** [HappenApps/Quiver#798]
For some odd reason, my cursor keeps disappearing within my code cell.
Reference: http://imgur.com/a/A6n8I
As I go down you can see the line being darkened. Not sure as to why this happens.

**Comment by ylian** [comment]
Most likely an issue with the variable-width font you're using. Try to switch to the default settings. The Ace editor doesn't support variable-width font.

**Comment by justnealpatel** [comment]
The strange thing is that it was a one-time thing. It hasn't happened since. I'll update this issue if it happens again. Without switching to the default settings, the cursor doesn't disappear anymore.

**Comment by ylian** [comment]
Interesting. Anyway the Ace editor is being revamped. Closing this for now.
