### ISSUE TITLE
Make Period a Word Separator in Text Cells

### ISSUE THREAD

**Issue by michael-jarosik** [HappenApps/Quiver#8]
When selecting a word by double-clicking, consider a period to be a word separator even if there are no spaces on either side of it. Use case: when referring to a JS method name like `Module.init`, double-clicking `init` should select `init` only so you can change the method name in the text cell, ala `Method.load`. This feature is already implemented for both code cells and markdown cells.

**Comment by ylian** [comment]
Just spent some more time on this. This seems to be the standard selection behavior in Safari. You can use Safari to open a webpage with such text, and try double clicking to select. It will select "module.init" as one word.

Quiver uses a WebView in the editor area, which is just a stripped-down version of Safari. So I will mark this as "Won't fix". If you find a workaround in Safari, let me know.
