### ISSUE TITLE
Future Feature

### ISSUE THREAD

**Issue by rockyzhang24** [HappenApps/Quiver#803]
This new version is awesome and what I am understanding is that these improvement and modification internally will be the foundation for future functions, right? So what are the future features that we all should look forward? Is there a timeline for them? Thank you again for your hardworking and making Quiver better.

**Comment by ylian** [comment]
Certainly, JS refactoring is important for future development of the editor and preview.

Coming next will be a few more small updates to do the following:
* Catch up with the bugs reported here
* Underlying data modeling changes (mostly caching, search indexing). Won't change persistence just yet.
* It's likely that I will implement a UI-only "nested notebooks" feature as a stop-gap measure, as well as to collect feedbacks.

These updates will come out in the next few weeks.

Once these small updates are done, a few major changes may happen:
* Persistence changes (solve many issues, such as native support of .md format, Spotlight indexing, external folder support)
* Markdown editor revamp (the current one has many issues with Chinese input, lack of spellchecking, lack of support for variable-width fonts)
* Code editor revamp

Of course, in the meantime, the iOS version. And the work there is mostly:
* Finish up syncing support (update Dropbox API to v2, add iCloud syncing support)
* Add note editing support (requires code editor revamp, as Ace doesn't really work on mobile devices)

**Comment by rmrnc** [comment]
Sorry to bring this up here, but is there any progress in regards to the web clipper (see #100); reported to be "About 80% complete" (@ylian) a year ago?

**Comment by ylian** [comment]
@rmrnc Haven't worked on the web clipper for a while. But it's a much smaller project. I will give it a try this weekend.

**Comment by rmrnc** [comment]
Thank you!!! I'd really appreciate it. 

Being able to capture and store an entire (or optionally parts of) a web page in Quiver, ideally uncluttered from ads and navigation items, is all it takes to finally get rid of Evernote.

**Comment by rmrnc** [comment]
Hope you don't mind me asking: would it be possible to clip in "Safari's Read View" format? (I.e., https://support.apple.com/kb/PH21467?locale=en_US)

**Comment by ylian** [comment]
@rmrnc I already wrote two libraries (declutter and unmarked) years ago for this purpose. "unmarked" is already used in Quiver to convert HTML back to Markdown, but "declutter" was meant for the reader view and it's not yet production ready. https://github.com/ylian/declutter

So what's left for the web clipper is:
* Some UI work (a popup with some buttons)
* Improve declutter to production quality

**Comment by LeonardoGentile** [comment]
@ylian 👍 
Where have you been mate?? 😄
