### ISSUE TITLE
Deleted notes with tags remain in tag view after trash emptied, app unresponsive.

### ISSUE THREAD

**Issue by JonathanPerkins** [HappenApps/Quiver#81]
Quiver 2.1.2: 
1. Create a new note with a new tag.
   2.Delete the note, empty the trash and then switch to the tags view. The deleted note still appears in the tag listing but with no body.
2. Restart the application and switch to tag view. The new tag is still visible with a count of 1. Select that tag and the app becomes unresponsive, not showing the correct note when clicking on other tags.
3. Restart the app again and now the new tag category has finally gone and the app is working as expected.

Thanks,
Jonathan

**Comment by ylian** [comment]
Great catch. Thanks. Fixed in 2.1.3b8.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b8.zip

**Comment by JonathanPerkins** [comment]
Thanks, that was quick! Confirmed fixed in 2.1.3b8

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.
