### ISSUE TITLE
Does not print anything.

### ISSUE THREAD

**Issue by ghost** [HappenApps/Quiver#813]
I can't print anything but text.  Any note with any content other than text just gives me a page with nothing but the note title at the top.  Same results if i try to export.

**Comment by ylian** [comment]
Could you try a few things?
1. Quit and reopen Quiver, try to print again.
2. If it still doesn't work, please send me the note (.qvnote). That will help me reproduce the issue. Thanks. (Email: ylian@happenapps.com)

**Comment by ghost** [comment]
Problem solved.  Can't believe i didn't bother to try that... I had the same issue in the trial version and just assumed that it was due to being a trial.  I have quite and reopened Quiver a few times since installing the paid version so I didn't even consider it.  Thanks for quick feedback!

**Comment by ylian** [comment]
I see. But there is still a problem. Basically one of your notes have triggered some JavaScript error, and the webview couldn't recover. If you figure out how to reproduce this (click around some notes of yours), let me know. It would be super helpful. I have been trying to hunt down this one for a while.

**Comment by ghost** [comment]
Will do.  I just tried to print every note i have and that worked fine.  I then started to edit a couple of notes, changing the cell type, creating new notebooks, moving the notes into and back out of the notebooks and editing them in between...still works.  Ill let you know if i can reproduce.

Thanks

**Comment by ylian** [comment]
Close for now.
