### ISSUE TITLE
typed chinese bugs in Markdown cells on 3.0.4 under OS X 10.12.4

### ISSUE THREAD

**Issue by luyuqiang** [HappenApps/Quiver#816]
When i typed chinese  like '中文' by sogou input method ,firstly i got 'zhong'wen'  ,then i need to type space again ,finally i got 'zhong'wen中文'.
I don't konw it is bugs of Quiver or  sogou input method.

**Comment by duskalbatross** [comment]
I have the same issue. I cannot use Markdown cell now. Hope to fix this issue ASAP.

**Comment by nodewee** [comment]
use system default input method, same issue

**Comment by zxdposter** [comment]
same issue too.

**Comment by ylian** [comment]
Looking into it. Thanks for reporting the issue.

**Comment by WanChengCheng** [comment]
The issue is that characters pressed in IME will also be dumped to the MarkDown cell.
This happens on **Sierra 10.12.4**, on my another mac which is **10.12.3** it works fine.

**Comment by KiwiShow** [comment]
Same issue too.My mac is on Sierra 10.12.4.

**Comment by ylian** [comment]
Thanks. Yes, it seems to be broken on 10.12.4. I am working on a fix.

**Comment by junnplus** [comment]
Me too. qwq

**Comment by ylian** [comment]
I have a fix. Doing more testing right now. I should be able to submit the fix tonight and it will be available for download tomorrow.

**Comment by ylian** [comment]
Submitted 3.0.5 with the fix. It should be ready for download tomorrow.

**Comment by sunningQD** [comment]
same issue
