### ISSUE TITLE
Why can't I find how to auto-completion on quiver 3.0.4?

### ISSUE THREAD

**Issue by phonzia** [HappenApps/Quiver#817]

**Comment by ylian** [comment]
Auto completion in code cells was removed. It only had very limited snippet support anyway, and wasn't customizable.

**Comment by phonzia** [comment]
Will basic autocompletion(completion in current buffer) be added in future?

**Comment by ylian** [comment]
Yeah, that would actually be more useful than the old autocompletion behavior.
