### ISSUE TITLE
Simplified Chinese input is broken in macOS 10.12.4

### ISSUE THREAD

**Issue by DannySu09** [HappenApps/Quiver#819]
When I input "家族", It looks like the picture:
<img width="99" alt="screen shot 2017-03-30 at 17 00 59" src="https://cloud.githubusercontent.com/assets/3401641/24496465/e7a3b092-156a-11e7-9aca-aa4fd35a9b05.png">

And when I hit Enter key, it becomes:
<img width="106" alt="screen shot 2017-03-30 at 17 01 03" src="https://cloud.githubusercontent.com/assets/3401641/24496470/ea9f125a-156a-11e7-98ac-4f2d29818609.png">

And when I type quickly, it becomes:
![image](https://cloud.githubusercontent.com/assets/3401641/24496539/1937ed08-156b-11e7-8520-89581fe217de.png)

First I type "suibiandayixiezi", and the expected result is "我想打一些字", but it comes out `sui bian da yi xie wen zi`. Then I type "s", "我想打一些字" comes out.

**Comment by ylian** [comment]
Just pushed out a fix today. Please download 3.0.5.
