### ISSUE TITLE
Feature Request: Automatic or 1-click export

### ISSUE THREAD

**Issue by Tekl** [HappenApps/Quiver#82]
What about automatically exporting the changes to a specified destination? So I can place it on my Dropbox and everyone could browse it. Maybe if auto export is a problem I would like to see 1-click export which remembers the destination and just refreshes the files.

**Comment by ylian** [comment]
1-click export is probably better. I don't think you want people to see all your changes as you edit the notes, and it slows down the app.

But then it's not too different from the current setup. You could save some time from not having to look up the destination. Maybe in a future update.

**Comment by Tekl** [comment]
Oh, that's a good point. Auto export also would produce unnecessary traffic.

**Comment by ylian** [comment]
I will close this but will keep in mind designing a more seamless publishing process in the future.
