### ISSUE TITLE
Raw web links in Markdown not clickable

### ISSUE THREAD

**Issue by quark67** [HappenApps/Quiver#826]
In previous version (3.0.3), raw web links in markdown cell are displayed in preview as clickable. But now, with version 3.0.5, raw links in markdown cell are displayed as simple text.

Since you have replaced previous markdown parser by **markdown-it** in 3.0.4, it seems that you don't have enabled **linkify** (see at end of https://github.com/markdown-it/markdown-it#usage-examples, before API section). You can see this at https://markdown-it.github.io in the Link section and compare with **linkify** button checked/unchecked at top of the page.

Can you correct this? Thanks.

**Comment by ylian** [comment]
Sure. Will push out a fix this week.

**Comment by ylian** [comment]
Fixed in 3.0.6.
