### ISSUE TITLE
Side by Side preview

### ISSUE THREAD

**Issue by NytFox** [HappenApps/Quiver#827]
Hi, the new side by side preview idea is awesome. However, the alignment of the preview with the text is not that ideal, I think just give the preview part itself a scroll bar and leave it unlocked will be awesome for people to use.

**Comment by ylian** [comment]
You can turn off "Scroll Sync": View Menu > Note View > Uncheck "Scroll Sync".

**Comment by NytFox** [comment]
Thanks
