### ISSUE TITLE
Quiver crashes when opening existing library from Finder

### ISSUE THREAD

**Issue by MikeChristianson** [HappenApps/Quiver#833]
Opening my existing 8MB Quiver library from the Finder causes a crash. 

![image](https://cloud.githubusercontent.com/assets/1694387/24730837/f6cc9818-1a1a-11e7-8afa-e0f1c4d26069.png)

Opening it as an Existing Library results in an empty library in the UI.

![image](https://cloud.githubusercontent.com/assets/1694387/24730916/6ff9602c-1a1b-11e7-87d0-fc1a73caf7ff.png)

**Comment by ylian** [comment]
Aware of the issue. I have already found a fix. Will push out an update this week.

**Comment by MikeChristianson** [comment]
@ylian Great. Looking forward to it.

**Comment by ylian** [comment]
Fixed in 3.0.6.
