### ISSUE TITLE
Quiver don't add word by using chinese input method on vim mode

### ISSUE THREAD

**Issue by JackDrogon** [HappenApps/Quiver#834]
When I use chinese input method to add word on vim mode, quiver only add the chars not chinese.
After that,  I type other chars, It insert a lot of other word. For example, I insert `你好`， quiver add `nihao`， after that I typed `s`, quiver add `你好nihaos`。

**Comment by ylian** [comment]
Please make sure to update to 3.0.5. This should be working in 3.0.5.
