### ISSUE TITLE
10.12 系统下编写 md 中文输入法的问题

### ISSUE THREAD

**Issue by icyleaf** [HappenApps/Quiver#836]
在 macOS 未升级到 10.12 之前使用一切正常，在升级 10.12 之后发现只有在编写 markdown 的时候使用我目前测到的中文输入法都存在敲入之后会首先显示敲入的字母，在按空格之后在后面追加选择的中文，如果连续输入，之前的输入显示出来的也会再不断重复输出。

这里还录了一个视频：http://v.youku.com/v_show/id_XMjcwMzc3MjY3Ng==.html?spm=a2h3j.8428770.3416059.1

本机系统信息：
![screen shot 2017-04-12 at 15 32 52](https://cloud.githubusercontent.com/assets/17814/24946397/5912ed9a-1f95-11e7-823d-2444a6275746.png)

软件版本：Version 3.0.4 (96)

**Comment by icyleaf** [comment]
貌似和 #819 类似，我先关闭

**Comment by icyleaf** [comment]
升级 3.0.5 已解决，之前 app store 账户除了问题没有显示出来更新提醒。

**Comment by yuanxiangxie** [comment]
同遇到这个问题，楼主咋解决的？
