### ISSUE TITLE
[bug]Quiver has some problem when use "Copy note link"

### ISSUE THREAD

**Issue by crhan** [HappenApps/Quiver#839]
When I use the "Copy note link" function for notes in CHINESE title. The link copied is some kind of messy code.

For Example, I have a note like this:
![image](https://cloud.githubusercontent.com/assets/532040/25034979/2ba25dda-211d-11e7-8c8f-11ec2f241e66.png)

When I copy the link and paste at OmniFocus:

![image](https://cloud.githubusercontent.com/assets/532040/25034998/4ca21b6a-211d-11e7-9827-ada7b3c7cee1.png)
![image](https://cloud.githubusercontent.com/assets/532040/25035005/5a7fbee0-211d-11e7-9703-aa0fdc4d4762.png)

Mac's TextEditor just act the same:

![image](https://cloud.githubusercontent.com/assets/532040/25035028/7f2892da-211d-11e7-8207-0f6bfddf1af9.png)

This link title is a mess, but link function well.

**Comment by ylian** [comment]
Good catch. I can reproduce the issue. Will fix.

**Comment by ylian** [comment]
Fixed in 3.0.6.
