### ISSUE TITLE
mac version 3.0.3, weird backup behavior

### ISSUE THREAD

**Issue by yunuli** [HappenApps/Quiver#842]
when i use the Backup Panel  to backup, the Quiver.qvlibrary file's modified date shows as a weeks ago. shouldn't the modified date be the current time?  is the backup up to date? i am confused.

**Comment by ylian** [comment]
The backup should be fine. The code actually deletes the existing backup with the same name, so the overwrite is always clean.

There is a separate issue with the modified date. Basically the modified date of the library may not reflect the last note change date.
