### ISSUE TITLE
Horizontal line rendering doesn't work right with manual line breaks

### ISSUE THREAD

**Issue by icopp** [HappenApps/Quiver#846]
To duplicate:

```
This should be a header
---

This should not be a header  
---
```

Note the two spaces at the end of the "This should not be a header" line, to indicate a single line break. That turns into a header, but it should be a line break and then a horizontal line.

**Comment by ylian** [comment]
I don't think this is the standard Markdown behaviour. You can try it with the CommonMark demo: http://spec.commonmark.org/dingus/

Since Markdown syntax has a lot of ambiguities, it's best to stick to the CommonMark spec whenever possible (except adding feature extensions).

**Comment by icopp** [comment]
Interesting. It seems like there's no way with CommonMark to put a horizontal line in between other lines without using HTML.

**Comment by ylian** [comment]
Just enter another line break.

```
This should be a horizontal line

---
```

**Comment by ylian** [comment]
Also note that in Quiver's Markdown cell, GFM linebreaks are enabled by default.

**Comment by ylian** [comment]
You can also use asterisks or underscores for the horizontal line.

https://daringfireball.net/projects/markdown/syntax#hr
