### ISSUE TITLE
[BUG] Move to Notebook feature either won't work or causes data loss

### ISSUE THREAD

**Issue by alayliercan** [HappenApps/Quiver#847]
**Steps to reproduce the bug:**

1. Create two notebooks named `Notebook-A` and `Notebook-B`.
2. Create a few notes in `Notebook-A` and assign a specific tag to each note as you create them. Such as `TestTag`.
3. Switch to _Tags View_ by heading over to _View_ > _Sidebar_ > _Show Tags_ menu.
4. Select the tag called `TestTag` to see the notes that you created earlier in _Note List_ section.
5. Select a note from the list by right clicking on it, and then choose _Move to Notebook_ from the pop-up menu.
6. Try to move the note by clicking on the notebook called `Notebook-B` from the _Move to Notebook_ panel.

**The result will be either:**
- `Often`: the note will disappear from Note List and nothing will change
- `Less often`: the note will disappear from Note List and be actually moved into Notebook-B
- `Rarely`: the note will remain in Note List section but it will be duplicated and will lose its content
Plus, attempting to delete the duplicated notes will result crashing the _Quiver_, and if you try and reopen the Quiver after the crash, you will find that another one of the notes with the same tag (TestTag) is now duplicated. I believe this means that the data integrity of the entire Quiver Library is damaged now.

**What was expected:**
- It's not a must-have but as we move a note filtered by a tag, perhaps it should remain in _Note List_ after moving it. We haven't changed its tag, and currently active filter for the Note List section is still accurate after all.
- It goes without saying but, the note is supposed to be moved into target _Note Book_ by using _Move to Notebook_ feature.
- _Under no circumstances_ should a note lose the data that it contains.

**Comment by ylian** [comment]
Fixed in 3.0.7.
