### ISSUE TITLE
Paste and Match Style Shortcut

### ISSUE THREAD

**Issue by beetahnator** [HappenApps/Quiver#851]
Is there a reason the shortcut is `Command+Alt+Shift+V`?

Its a very uncomfortable shortcut to use and it would be better if the shortcut was just `Command+Shift+V`, which is the way a lot of other apps have it set.

**Comment by ylian** [comment]
It's the same shortcut as in Apple Mail, Apple Notes, etc.

You can always remap the keyboard shortcuts:

![image](https://cloud.githubusercontent.com/assets/984895/25455324/a92efd60-2acf-11e7-9b81-dad0faf1c77e.png)
