### ISSUE TITLE
Diagram cell shows duplicated participants when arrows of participant indicate itself

### ISSUE THREAD

**Issue by kadoyau** [HappenApps/Quiver#874]
[js\-sequence\-diagrams by bramp](https://bramp.github.io/js-sequence-diagrams/) shows this diagram.
![image](https://cloud.githubusercontent.com/assets/11990327/26058731/191e759e-39ba-11e7-86af-4fee7a4e0b8b.png)

However, diagram cell shows this diagram. "A" is duplicated.
![image](https://cloud.githubusercontent.com/assets/11990327/26058685/d9c8e97e-39b9-11e7-9b23-52f0b738ca14.png)

- Quiver v3.0.6
- OSX 10.11.5

**Comment by ylian** [comment]
I will update the js-sequence-diagram library.

**Comment by kadoyau** [comment]
Thank you for your support!

**Comment by ylian** [comment]
Fixed in 3.0.7.
