### ISSUE TITLE
[Feature Request]Web Clipper

### ISSUE THREAD

**Issue by rockyzhang24** [HappenApps/Quiver#878]
Hi,

How is the progress of developing the web clipper? 

A couple of weeks ago, you said you almost finished the web clipper plugin for web browsers. Is is possible for you to release it even though probably it is just a raw version? 

I am so looking forwarding to it. Thank you so much.

**Comment by ylian** [comment]
One thing at a time. I am still doing testing for 3.0.7. Web clipper is mostly there, but have to push out other things first.

**Comment by rockyzhang24** [comment]
@ylian I got it. Many thanks and appreciate your hard working. 

By the way, are there opportunities for our users to get a beta version prior to the official release of each version so that we can help you test it and save your time?

Also, I think you can change the charging mode of Quiver to subscription like Bear Note. Actually, I don't which way is better to you, just my suggestion. :)

**Comment by ylian** [comment]
@yanzhang0219 Thanks for understanding. :)

User testing is useful, but not comprehensive. 3.0.7 changes the note list quite a bit (there are actually lots of edge cases with the note list that I didn't handle properly, try enter something in the search field below the note list then move or delete notes), so I want to test a bit more carefully. Should be done tonight.

My time constraint is only temporary. As you have seen, Quiver development is already much better than last year, and many things are still in the pipeline. All these are despite that I only have time to work on Quiver at night and on weekends. I am sure I can manage all these until the day my time constraint is fully removed. As for the business model, I am sure the current business model works well enough. I dislike the subscription model and won't put my users through that.

**Comment by kimaldis** [comment]
If it helps, there's a script in the Wiki under the Import Scripts section that uses Instapaper to strip the junk from web pages and adds the result to a Quiver notebook. There was a login issue with it, which I've looked at and I figured we could improve it a touch by having it fetch a URL from Firefox's current page. It's not perfect but it works. See comments for the mods needed. And thanks to @kspeeckaert for the script.

https://gist.github.com/kspeeckaert/934a8308a4ec09e2e0756a313a915622

**Comment by superxp1412** [comment]
I dislike the subscription model as well. Thank you.

**Comment by fharper** [comment]
+1 on the Web Clipper too, thanks for the great software by the way

**Comment by kimaldis** [comment]
FWIW: While we wait for something more official, I've found the most reliable way to clip from web to Quiver is to use the Evernote web clipper, export the clipped note to .enex then import this into Quiver. It nicely brings everything, including images. When I get a moment I'll have a crack at making it more automatic.

**Comment by kimaldis** [comment]
I made some changes to Kristof's python web clipper, if anyone's interested. I hope it's a bit easier to use. see my last post to his gist: https://gist.github.com/kspeeckaert/934a8308a4ec09e2e0756a313a915622

**Comment by ylian** [comment]
Quiver Web Clipper 1.0 is released: https://chrome.google.com/webstore/detail/quiver-web-clipper/hcnffmpopoelpggikahccdfenoobjigj

Please make sure to update Quiver to 3.2.4.
