### ISSUE TITLE
Image size problem with preview

### ISSUE THREAD

**Issue by tankywoo** [HappenApps/Quiver#880]
I inserted a image with the toolbar button, and generated like this:

```
![abc.jpg](quiver-image-url/DD8BA8D5EB58672830575D9C9AEDF803.jpg =959.7519561957083x790)
```

But image not show in preview pane, only the raw text.

I tried to change the image size manually to `=959x790`，it works ok。

**Comment by ylian** [comment]
Fixed in 3.0.7.
