### ISSUE TITLE
Nested notebooks, when

### ISSUE THREAD

**Issue by kimaldis** [HappenApps/Quiver#883]
Would it be possible to give an idea of when, or even if, we might see nested notebooks appearing in Quiver.  If I could be sure hierarchies are on the horizon I could stick with Quiver but if it's going to be, like, 6-12 months then the organisational overhead with so many notes is probably going to be too much and I might have to make a difficutl decsion.

I appreciate the difficulty of releasing development road maps and I really don't want this to be seen as a threat  but anything you can offer up would be appreciated.

Thanks.

**Comment by ylian** [comment]
This weekend.

**Comment by kimaldis** [comment]
Awesome. Thanks Ylian.

**Comment by kimaldis** [comment]
It's this weekend. Any news?

**Comment by ylian** [comment]
@kimaldis Give me two more days.

**Comment by kimaldis** [comment]
:-)

**Comment by ylian** [comment]
UI:

![image](https://cloud.githubusercontent.com/assets/984895/26790489/2e4f8ede-4a14-11e7-852a-27011f7463fc.png)

Will post a working build here tonight.

**Comment by ylian** [comment]
@kimaldis  Couldn't get a working build tonight. Drag and drop in an NSOutlineView is quite complicated. Will keep working on it tomorrow.

**Comment by kimaldis** [comment]
They're a bugger, aren't they. I spent a week on it first time I tried one.

**Comment by ylian** [comment]
@kimaldis They are. I am gonna push out the iOS release first, since it is closer to completion. This nested notebooks feature will likely take another week to implement.

**Comment by kimaldis** [comment]
Ok. I'll just have to be patient.

**Comment by n8gray** [comment]
Wait, iOS release?

:derailed:

**Comment by albytseng** [comment]
@ylian Really excited for nested notebooks -- thanks so much!

**Comment by rockyzhang24** [comment]
Any good news?

**Comment by kimaldis** [comment]
Sorry, couldn't wait any longer, moved over to another solution. Good luck with it, whichever way it goes.

**Comment by ylian** [comment]
@kimaldis No worries. :)
