### ISSUE TITLE
incorrect display of \tilde in mathmode

### ISSUE THREAD

**Issue by coderaka** [HappenApps/Quiver#884]
It seems that in the recent version (3.0.7), quiver incorrectly displays math symbol like $\tilde x$, $\vec x$. The cap above the letter offsets a bit. There is no such issue before updating...

Code:
`The one-form $\tilde x$ and the vector $\vec y$  are not properly rendered`

Quiver renders the above code as

<img width="377" alt="screen shot 2017-05-31 at 18 35 16" src="https://cloud.githubusercontent.com/assets/6745860/26628277/07b2efa6-4630-11e7-9b15-38fce632667c.png">

**Comment by coderaka** [comment]
Is this a confirmed bug?

**Comment by ylian** [comment]
Yes it is.

**Comment by coderaka** [comment]
The bug is still there after today's (19 Oct) update.

**Comment by gandalfsaxe** [comment]
It's also a problem with \hat{x}.

**Comment by ylian** [comment]
Fixed in 3.1.2.
