### ISSUE TITLE
请问覆盖安装，原笔迹内容是否被替换了？

### ISSUE THREAD

**Issue by salmanchan** [HappenApps/Quiver#892]
请问旧版本新建了一个笔记本，使用新版本直接覆盖安装了，原笔记本不见了，是不是被删掉了，可以恢复吗？

**Comment by ylian** [comment]
覆盖安装不会影响数据。请查看是否打开了正确的 Quiver library。

**Comment by ylian** [comment]
Please email me (ylian@happenapps.com) for further questions.
