### ISSUE TITLE
How to use highlight in Markdown cells?

### ISSUE THREAD

**Issue by zyyedi** [HappenApps/Quiver#893]
我想通过更改css来达到，比如`==text==` 和 `<mark>text</mark>` 一样的效果

**Comment by ylian** [comment]
Markdown supports inline HTML, so use it directly in Markdown:

```
<mark>highlight</mark>
```

**Comment by zyyedi** [comment]
<img width="1307" alt="screen shot 2017-06-09 at 1 31 31 am" src="https://user-images.githubusercontent.com/26909419/26942165-9b6f77ee-4cb3-11e7-9919-95d942764813.png">
bug?

**Comment by zyyedi** [comment]
Moreover i wanna ask how to change the background color of select text for specific cell, i've tried `::selection` but it seems only change the background color for text cell.

**Comment by ylian** [comment]
For ```<mark>For **Pop**</mark>```, you can't use Markdown inside HTML then inside Markdown. It's not supported. You can use ```<mark>For <b>Pop**</mark>```.

If by 'selection' you meant highlight, you can set css as follows:

```css
mark {
  background-color: red;
}
```

**Comment by zyyedi** [comment]
no, for selection i mean 
![screen shot 2017-06-09 at 5 16 49 pm](https://user-images.githubusercontent.com/26909419/26969197-765ec908-4d37-11e7-99d0-9edb3123195f.png)
the background color for selected text.

**Comment by ylian** [comment]
I see. Indeed `::selection` will only work for text cells. Markdown and code cells use the Ace editor, and there is no way to change the selection color.

**Comment by zyyedi** [comment]
is it hard to add such function ?

**Comment by zyyedi** [comment]
I mean, in the preference

**Comment by ylian** [comment]
The underlying Ace editor doesn't have such options, so unfortunately this can't be done.

**Comment by zyyedi** [comment]
sad

**Comment by zyyedi** [comment]
i think i found a way to do so, i just change the editor.css file under ~/Applications/Quiver.app/Contents/Resources/dist/css
