### ISSUE TITLE
Nested folder support

### ISSUE THREAD

**Issue by superxp1412** [HappenApps/Quiver#898]
Please add feature of nested folders for notebooks

**Comment by rockyzhang24** [comment]
@superxp1412 Many users have been requiring this must-have feature and based on what the developer said before, this feature should have been released last month already. I don't know why it is still in pending status. So sad.

**Comment by FBeccaria** [comment]
Some kind of hierarchical notebook structure would make Q a truly great utility...   👀

**Comment by e1782753** [comment]
The other thread about this with 15 comments was closed a week ago without any result. I think it's mind-boggling that this feature has not been added yet. Hopefully the developer knows we all cherish Quiver and don't want to give up on it. But for now, I stopped recommending it to others.

**Comment by KwrKy** [comment]
Just wanted to bump this. It's the only thing that frustrates me about this app — everything else is stellar.
Are nested folders going to be a thing soon? Please please? 👀

**Comment by ylian** [comment]
Implemented in 3.1.1.
