### ISSUE TITLE
Any plan about Android version ?

### ISSUE THREAD

**Issue by dukkha-s** [HappenApps/Quiver#908]
Is there any plan to develop Android version?

**Comment by ylian** [comment]
There is an unofficial app built by a community member.
https://play.google.com/store/apps/details?id=net.andrewt.quaver&hl=en

**Comment by yaoxinghuo** [comment]
Hi, I wrote a simple read-only android app [Quview](https://github.com/yaoxinghuo/Quview) (OpenSource) in case someone need it. Since Quaver's search function is broken (Which is I really care) and there is no update for years, I have to create one for my own use.
