### ISSUE TITLE
It's not an issue or bug!

### ISSUE THREAD

**Issue by gavin971** [HappenApps/Quiver#909]
Quiver just has three layer: Notebook->Note->Note details. So, we still cannot classify the Notebook. Can you add new collapsible items.  i.e. Item->Notebook->Note->Note detailed. Then the UI of Quiver can be more succinct. Hope to hear from you！

**Comment by gavin971** [comment]
@ylian ylian

**Comment by ylian** [comment]
I am focusing on the nested notebook feature right now. I am closing this one since there are several tickets open for this feature request already.
