### ISSUE TITLE
Global note search not working

### ISSUE THREAD

**Issue by RajeshThallam** [HappenApps/Quiver#921]
I installed new version of Quiver (v3.0.7) on my macbook pro running OS X El Capitan. I do not see global text search working even though with-in note search works perfectly. Any reason or am I missing something?

![quiver-full-text](https://user-images.githubusercontent.com/10550846/28502472-ffad3b9e-6fa7-11e7-99cb-3b9c0d4bb4fa.png)

**Comment by ylian** [comment]
Looks like the search index is corrupted. (This could happen if you ran two Quiver versions such as trial and paid at the same time.) Restart the app and the search index will fix itself.

**Comment by RajeshThallam** [comment]
Thanks @ylian . Restarting the app worked. You were right about running trial and paid versions together. Closing the issue.
