### ISSUE TITLE
Editing text cell inline code css

### ISSUE THREAD

**Issue by KwrKy** [HappenApps/Quiver#922]
Hi there.

Firstly, awesome app. I freaking love it!

Secondly, is there a way to edit the css of the inline code in text cells? I just want to change the color and background color to make it stand out a little more. I've tried a few combinations using 
`.text-cell .* {code}`, but nothing has worked so far. What is the magic selector to make this happen?

Peace

**Comment by justnealpatel** [comment]
The selector for changing the inline code is simply `code`. Use the `color` property to change the color of the text. In order for it to blend in nicely, you should also use the `background-color` property to be the same as the background color for the theme you're using. For some odd reason, the background color of the inline code isn't the same as the theme (this was the situation for me). Let me know if that works for you. In the future, you should probably enable the web inspector (Run `defaults write com.happenapps.Quiver WebKitDeveloperExtras -bool true` inside your Terminal and now if you right click anywhere you should be able to grab the CSS selectors easily). I would also add the `!important` property to this selector as well as it made the experience more stable for me.

**Comment by KwrKy** [comment]
Now I feel really silly — `.text cell code {...}` works perfectly now. I thought I tried that yesterday, but I must have forgotten the `.` before it. 

Thanks for your time (also for the inspector tip 👍 ).

**Comment by ylian** [comment]
@justnealpatel Thanks for helping. ;)
