### ISSUE TITLE
Dragging PDFs into text cells is broken

### ISSUE THREAD

**Issue by bobtheguitar** [HappenApps/Quiver#928]
Dragging PDFs into text cells doesn't open a dialog box to choose link vs. copy. Automatically copies, but with a broken thumbnail/preview. And so cannot link to local PDF files. (Which is what I want to do at this moment.) Dragging any other file type opens the dialog box and works as expected. Example:

<img width="1133" alt="screen shot 2017-08-06 at 22 49 08" src="https://user-images.githubusercontent.com/30782578/29007425-f3e70c00-7afa-11e7-8ae5-d276c1bd6813.png">

**Comment by ylian** [comment]
Fixed in 3.1.1.
