### ISSUE TITLE
It Seems Quiver Is Dead.....

### ISSUE THREAD

**Issue by rockyzhang24** [HappenApps/Quiver#939]
As the title.
And within this half year, many customers request some new features, especially the Nested Notebook. And the developer said many times like "It will be released soon" or "It will be released next week/month". During such these replies, the time has been passing almost half a year but still, disappointedly, we don't get such a release. 

Then many ppl were planning to switch to another note app. But with the love of Quiver, we so hesitate that we are still hanging in there and accompanying with Quiver. On the other hand, switching to another note app is very time consuming and troublesome because we have to migrate all our notes to another. 

I understand probably the developer is busy with their own stuff. But most importantly, he should keep in touch with us and try to update the progress of developing Quiver. For example, he could write a blog, or update some tweets to tell us that "All right, even though the development of Quiver is very slow, I'm still immersed in it". If so, I think our customers would continue to use Quiver because we could know that Quiver is alive and we do not have to switch to another app with that annoying notes migrating and we could believe that some bugs or missing feature will be added at the end. 

But so far, I don't know how Quiver is going and it seems to be dead.

**Comment by ylian** [comment]
There is a beta version with nested notebook support in this thread: https://github.com/happenapps/Quiver/issues/2#issuecomment-320806722

The only thing I want to say is that Quiver is alive and I am committed to it.

Closing this because a post like this doesn't help anything.
