### ISSUE TITLE
iCloud Drive Sync

### ISSUE THREAD

**Issue by ejwolfe** [HappenApps/Quiver#944]
I've been using Quiver recently for school and have noticed that my notes don't sync or revert back to a previous version. I will hit save multiple times but it still won't sync all the time. Does iCloud have problems with syncing or is this a random issue? I've attached a pdf that I exported after finishing the note and the version that was reverted (the old one). 
[Homework #2 old.pdf](https://github.com/HappenApps/Quiver/files/1275695/Homework.2.old.pdf)
[Homework #2.pdf](https://github.com/HappenApps/Quiver/files/1275696/Homework.2.pdf)

**Comment by loriculberson** [comment]
@erwolfe Did you ever get this issue resolved because I am experiencing it now between my two computers.

**Comment by loriculberson** [comment]
So I quit the application, reopened it and the notes are now up to date!
