### ISSUE TITLE
Unable to locate backup

### ISSUE THREAD

**Issue by lrdegeest** [HappenApps/Quiver#947]
I installed Quiver on a new computer and tried to restore my notes from a Time Machine backup. From previous answers it seems backups are supposed to be in:

~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/Quiver.qvlibrary/

but I don't see any such directory in my Time Machine backup or on my old machine. 

Any ideas? How can I transfer my notes?

**Comment by ylian** [comment]
Time Machine does back up this directory. The library folder might be hidden.

**Comment by lrdegeest** [comment]
Bingo! Many thanks.
