### ISSUE TITLE
Latex problem in Markdown mode

### ISSUE THREAD

**Issue by shagru** [HappenApps/Quiver#96]
In markdown mode, this cannot be displayed correctly.
$\frac{1}{2} + f_2 + \left[ q_f \right]$

And ${ }$ cannot be displayed as well.

**Comment by shagru** [comment]
In latex mode it is OK. But in latex mode I cannot do any text macro like \emph and etc...

**Comment by ylian** [comment]
This is working fine for me in Markdown cells. Can you check it again? Thanks.

The LaTeX uses MathJax, which only supports math macros. Text macros are not supported.

**Comment by shagru** [comment]
Can you try this two again? It doesn't work for me in markdown...

$\mathbf{q} = \left [ q_f \right]_{f=1}^m$.

${1,\cdots,n}$

**Comment by shagru** [comment]
$\mathbf{q} = \left [ q_f \right]_{f=1}^m$.

${1,\cdots,n}$

It works in Latex mode but doesn't in Markdown mode. It is strange since I guess in either mode it is processed by MathJax?

**Comment by ylian** [comment]
Hmm. You're right. It seems that `\left` and `\right` work in LaTeX cells, but not Markdown cells. I will fix it.

**Comment by shagru** [comment]
\left and \right works sometimes in markdown. 

If you simplify the formula a bit like this $\mathbf{q} = \left [ q \right]$ it would work.

Please fix this as I absolutely love this app : )!
Thanks!

**Comment by ylian** [comment]
Thanks. I think I know why. It's `q_f`. The text is first sent through the Markdown renderer, which converted the underscore to a HTML tag. So when it goes through MathJax, it fails to parse correctly.

**Comment by ylian** [comment]
Fixed in v2.2b22. Let me know if you find issues. Thanks.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b22.zip

**Comment by shagru** [comment]
It works! Thanks!

**Comment by ylian** [comment]
This is fixed in Quiver 3.0, released today.
