### ISSUE TITLE
How to import many Evernote notebooks?

### ISSUE THREAD

**Issue by nyammy** [HappenApps/Quiver#976]
I'm trying to move from Evernote to Quiver.
There are many notebooks in Evernote library. Is there any way to import them at once?

I wrote the script which export all notebooks to individual enex files, but Quiver's importer accepts single enex file only at once...

**Comment by JMichaelTX** [comment]
> I'm trying to move from Evernote to Quiver.

@nyammy , before you do that make sure you have tested Quiver thoroughly.

Clearly, Quiver is a much better snippet manager, but the Evernote Search and Sync are far better than Quiver's.  I find it hard to find specific stuff in Quiver.

**Comment by nyammy** [comment]
@JMichaelTX , Yeah I know about them. I don't need powerful search and Dropbox sync is enough for me. Instead of powerful search, I need hierarchical notebook structure and Quiver don't have it now, but I believe it will be implemented near future.

Anyway, I'm testing Quiver and feeling great, so I want to continue evaluating with some of actual notebooks (approx. 30 notebooks - a group don't require hierarchical structure) in actual work.
Importer is working good for me except that it accepts only 1 file at once. I just want to import them at once. (Otherwise I need to import all notebooks individually after evaluation)

**Comment by ylian** [comment]
It's possible to export all notebooks from Evernote to a single .enex file. But that file unfortunately doesn't contain any notebook information, so when imported into Quiver, you will see all notes inside one notebook. It's probably not what you want either. So I don't really have a good solution for you.

I have a 3.1.0 build that seems to work quite well. Have been testing it for a week or so, and if I don't find new bugs, I will submit it tonight. The main feature of 3.1.0 is of course the nested notebook functionality.

**Comment by nyammy** [comment]
@ylian Thank you for your reply. As you mentioned, one notebook is not the desired result.
OK, now it's clear that there are no good ways. I think I need to try to write the import script.
If you can provide standalone convert script, I want to modify it. (If not, I just write some thing from scratch.)

> I have a 3.1.0 build that seems to work quite well. Have been testing it for a week or so, and if I don't find new bugs, I will submit it tonight. The main feature of 3.1.0 is of course the nested notebook functionality.

It's a good news!

**Comment by nyammy** [comment]
I wrote mover script (from Finder-organized notebooks to nested Quiver notebooks).
Thanks.

**Comment by ylian** [comment]
@nyammy That's nice. :)

**Comment by JMichaelTX** [comment]
> I wrote mover script (from Finder-organized notebooks to nested Quiver notebooks).

@nyammy ,

Would you mind sharing your script?  Also, what do you mean by "Finder-organized notebooks", since the Finder does NOT have notebooks, but does have folders.  Did you mean folders?

**Comment by PatrickF1** [comment]
Sorry I know this thread is almost a year old but I'm in the same boat, a long time Evernote user with 50+ notebooks hoping to migrate to Quiver. Would really appreciate it if @nyammy could share his script! Thanks!

**Comment by JMichaelTX** [comment]
> a long time Evernote user with 50+ notebooks hoping to migrate to Quiver.

@patrickf3139 , if the Evernote Notes that you want to migrate are code snippets, **then I would suggest exporting Evernote to the macOS file system**, where each EN NB is a Folder, and each EN Note is a file in that folder.  Then assign Finder Tags (could be from your EN Tags) to each file.

I have now been using a very extensive "snippet library" by using the macOS, folders, files and Finder Tags.  I have found this works much better than either Evernote or Quiver, because the macOS Spotlight is so powerful and easy to use.  I mostly use Spotlight Search in the Finder.  Please let me know if you'd like any more details.

I have to say that I have tried just about every snippet library there is, and all have fallen short.
Oh, I forget to mention that I also make good use of [Typinator](https://www.ergonis.com/products/typinator/) for my very short snippets.  Highly recommended.

**Comment by PatrickF1** [comment]
@JMichaelTX Only about 10% of them contain code snippets. I am fairly certain I want to use Quiver. Thank you for your suggestion though!

**Comment by nyammy** [comment]
Oh, I hadn't watched this thread.

@JMichaelTX Yes, it means folder-organized. It was typo.
And,
@patrickf3139 My scripts are just for one-time use so I'm embarrassed to show them, but now I share them. I hope it will be the HINT for you.
[Download from Dropbox](https://www.dropbox.com/sh/92rf224vxge87ky/AABMHRBcWm6fwNV6lOcDsUT9a?dl=1)

Please note:
- I'm not sure the scripts are compatible with latest Evernote and Quiver.
- I tried them with Evernote app which is directly downloaded from Evernote website. Not tested with AppStore (sandboxed) version.
- They may contain some bugs. Backup notebooks and libraries before you try. And use them at your own risk.
- The name of some notebooks and notes can be changed. (For example, "/" will be changed to "_".)
- There is the problem in handling modified time. After the notes has been imported into Quiver, when you touch the imported notes, modified date will be updated (first time only).
- The contents in each notes will be put into single text cell.

Usage:
- Open "BackUpEvernote.scpt" with Apple Script Editor, and tailor exportPath to your environment.
- Execute the script. (Use the button in toolbar)
- The folder contains notebooks are created in Desktop. (You can close Script Editor after It finishes exporting.)
- Open Terminal.app and execute enhtml2quiver.pl.
`$ enhtml2quiver.pl [Exported Folder]`
- Copy converted *.qvnotebook packages to Quiver's library folder, and add the content of meta_test.txt into Quiver library's meta.json.

Good luck!

* I will not delete the files soon, but it will be deactivated someday...

**Comment by PatrickF1** [comment]
Thanks so much @nyammy . Really appreciate it. Unfortunately, I've already hand-imported all my notebooks (took me almost an hour), but if I ever go to Evernote and then back again (I'm now undecided about Quiver), they will be super useful. Thanks!
