### ISSUE TITLE
All notes gone since new update

### ISSUE THREAD

**Issue by bureaunoir** [HappenApps/Quiver#979]
Hi,

since the last update today, all my notes are gone and i can't load the old library or even a backup. Any idea how to get my notes back? When i restore from a backup, quiver crashes immediatly.

**Comment by ylian** [comment]
Your notes should be safe.

You can download the previous version (v3.0.7) from here: https://www.dropbox.com/s/3t4yfkgarohjo4k/Quiver%203.0.7.zip?dl=0

Please let me know if the previous version works. Also, if you could find the crash log in the console, please send it to me (ylian@happenapps.com). This crash seems to happen to some users, and I'm trying to fix it right away.

**Comment by ylian** [comment]
Figured it out. Please try this build:

https://www.dropbox.com/s/lm9o9rrwy2dgh2i/Quiver%203.1.1%20Build%20123.zip?dl=0

**Comment by ejb** [comment]
This has also affected my notes too. I can see the data in the library, but it seems they're not being read. Trying the new build now.

**Comment by ejb** [comment]
The new build works! I can see my notes again. And the nesting works great too :)

**Comment by ylian** [comment]
@ejb Great! I will push out the fix tonight.

**Comment by ylian** [comment]
Submitted 3.1.1 with the fix. Should be available on the App Store in a few hours.

**Comment by ylian** [comment]
3.1.1 is out. Please remove the beta builds and download 3.1.1 from the app store.

**Comment by ejb** [comment]
3.1.1 is working great! Thanks for being so responsive and fixing this so quickly!

![giphy](https://user-images.githubusercontent.com/1442752/31797069-50aa5404-b4fa-11e7-95a4-59d981c4f351.gif)
