### ISSUE TITLE
iCloud syncing sometimes corrupts the Quiver library

### ISSUE THREAD

**Issue by ylian** [HappenApps/Quiver#98]
Received one user's email that his Quiver library on iCloud fails to load (so he thought all the notes are gone). It turns out iCloud renamed `Quiver.qvlibary` to `Quiver.qvlibrary.folder`. Some of the .qvnotebook files inside the library are also renamed.

I suspect that the issue is caused by accidentally clicking on the Quiver.qvlibrary file from an iOS device. Since Quiver for iOS is not yet available, the iOS device doesn't recognize the .qvlibrary file package format, and gets confused. It might have opened it as a folder, then when synced to the Mac version, iCloud thinks it's a conflict (one is a file package, the other is a folder).

![2015-04-15 4 21 54](https://cloud.githubusercontent.com/assets/984895/7173136/cc08a4c4-e3c0-11e4-85a6-e347551b193b.png)

![2015-04-15 4 21 59](https://cloud.githubusercontent.com/assets/984895/7173143/e083e97c-e3c0-11e4-8eca-2f9f09655f62.png)

A pretty tricky issue. I will look into ways to resolve this. In the meantime, I suggest users should avoid putting their Quiver libraries on iCloud Drive.

**Comment by taiidani** [comment]
The same thing happened to me, but I didn't access the notebook over any mobile devices. I just upgraded to El Capitan so I assume my .qvlibrary was corrupted when iCloud Drive reinitialized.

For anyone else with the problem, take note that you need to rename _all_ of your `.qvlibrary`, `.qvnotebook` and `.qvnote` files so they don't have the `.folder` extension.

**Comment by ylian** [comment]
This issue seems to happen more often recently. I received 4 reports in the last two weeks.

I did some searches and apparently this is an iCloud Drive bug. It's happening to many other apps, including:
- GoodNotes: https://goodnotes.zendesk.com/hc/en-us/articles/202168045-All-my-documents-are-missing-
- MindNode: https://gist.github.com/aquarius/ff2328a0dad34cbcfc6a, https://twitter.com/mindnode/status/589009501501726720
- Notability: https://www.facebook.com/Notabilityapp/posts/1016976144998539

Since I can't fix iCloud Drive and my bug reports to Apple never get any response, I am trying to fix this on my end. With a few code changes, Quiver now works with the ".folder" extension as well. Here is a build with the fix: https://dl.dropboxusercontent.com/u/3445731/Quiver%203.0-icloud-fix.zip

Here is what you should expect: iCloud Drive can still mess up the Quiver library, notebooks, and notes. But when this happens, you should still be able to use Quiver as usual. You shouldn't notice anything different inside Quiver: all your notebooks, notes should still be there, and you shouldn't need to manually set the library location either (Quiver can find the library automatically even if the library is renamed or moved).

Please let me know if you find any issues.

**Comment by ylian** [comment]
I have implemented a workaround in Quiver 3.0, so even if iCloud Drive messes up your Quiver library, Quiver will still be able to load the library and its contents. As a user, you shouldn't notice anything different.

**Comment by freddy311082** [comment]
Hey guys, sorry for my newbie question: I have my file in iCloud and I want to load it from iOS. I haven't found how to do it because the only option I see there is Dropbox and WebDAV. Can you help me please?
