### ISSUE TITLE
Unable to open existing Quiver library

### ISSUE THREAD

**Issue by globalflea** [HappenApps/Quiver#981]
For sharing across computers, i put my Quiver.library file in my OneDrive.  After a recent upgrade to 3.1.0 (122), it crashed when i pointed it to the library file (via preferences->sync->Library Location) and subsequently on further attempts, it refuse to open up the library - i.e none of my earlier notes shows up.

**Comment by ylian** [comment]
I pushed out 3.1.1 last night with the fix. Please update.
