### ISSUE TITLE
Subscript and superscript should have keyboard shortcuts

### ISSUE THREAD

**Issue by filiptdz** [HappenApps/Quiver#987]
Exactly like in Pages, it would help immensely people who use Quiver to write chemical formulas.

**Comment by justnealpatel** [comment]
I've actually found somewhat of a hack for this (for any menu shortcuts, actually). If you go to System Preferences -> Keyboard -> Shortcuts -> App Shortcuts, then just add Quiver as the application then type the shortcut exactly how it appears in the menu, then just add your custom shortcut. This is actually how I keep up with shortcuts for almost all applications since many applications don't deal with customizing shortcuts. In my opinion, I consider this way to be better than a fix since the shortcuts are easily customizable, whereas if an application was in charge of shortcuts, they might not be.

<img width="780" alt="screen shot 2017-10-26 at 12 02 45 am" src="https://user-images.githubusercontent.com/12269792/32035790-0cdb52dc-b9e1-11e7-9d43-774cea9bb468.png">

**Comment by filiptdz** [comment]
@justnealpatel thanks a lot! Since I still believe that this should be included natively, I won't close the issue, but that's a really good fix, that I'll be most likely using again.

**Comment by olibclarke** [comment]
Totally agree on this - native shortcuts for super and subscript would be great! Using Quiver as an electronic lab notebook, so both are used a lot (measurement units, chem formulae etc)

**Comment by olibclarke** [comment]
@ylian would it be possible to add shortcuts for super/subscript during the editor rewrite? It is a small thing, but it would make Quiver much nicer to use for laboratory notes (my primary use case) and for writing simple mathematical and chemical forumulae without needing to use Markdown/LaTEX - thanks!

**Comment by ylian** [comment]
@olibclarke The app shortcut as mentioned above works fine. That is not a hack and it's no different from setting a shortcut for the menu item in the app.

**Comment by filiptdz** [comment]
I'd say this solution works fine, but only for someone willing to dig deeper to find it. Many people will see there is no keyboard shortcut, and resign themselves to opening the menus manually. I don't see why not to add this shortcut.

**Comment by olibclarke** [comment]
Seems inconsistent to me that you have native shortcuts for strikethrough, underline, and various heading styles, but not for sub/superscript. As mentioned, I would never have found this shortcut without looking on Github. I think there should be an icon for it in the formatting toolbar and native shortcuts - to me it seems like an odd omission that would be straightforward to fix.

**Comment by olibclarke** [comment]
Also, having tried this fix @ylian, it is not ideal. A shortcut for a style should act as a toggle - press once, and the style is on, press again and it is off. This doesn't work that way - I can press the custom shortcut for subscript multiple times, and it remains in the subscript style. This substantially reduces its utility vs a native shortcut IMO.

**Comment by ylian** [comment]
@olibclarke Okay, I will add a shortcut. Any suggestion for the particular key combination I should use?

**Comment by filiptdz** [comment]
[Pages](https://support.apple.com/kb/PH23626?locale=en_US&viewlocale=en_US) uses Ctrl+Shift+Command+Plus Sign (+) for Superscript and Ctrl+Command+Minus Sign (-) for Subscript. I guess that's the closest we can get to an Apple standard. However, I don't love this Shift difference between the two.

**Comment by ylian** [comment]
@filiptdz Sounds good. Will try to add this in 3.2.4.

**Comment by olibclarke** [comment]
I would prefer Cmd-(-) for subscript and Shift-Cmd-(+) for superscript for compatibility with MS Word, but either is fine - thanks @ylian!

**Comment by justnealpatel** [comment]
You could try to do it how the Magnet app does it, to where the shortcuts are re-mappable.
