### ISSUE TITLE
[Feature Request] Duplicate nested folder

### ISSUE THREAD

**Issue by juststevede** [HappenApps/Quiver#997]
After working with the nested folders I am looking for a way to duplicate a nested folder with its subfolders and including notes. As I have several nested folders for use like a template, it would be very nice to be able to just duplicate them.

Is there any way to do this? Thx in advance!

**Comment by ylian** [comment]
Unfortunately not. The nested structure is only a UI feature. Notebooks are still saved in a flat structure on the disk.

Close as "won't fix".
