### ISSUE TITLE
Blanked-out Look with Dark theme

### ISSUE THREAD

**Issue by NortGit12** [HappenApps/Quiver#998]
I have the Dark theme selected.  Whenever I shut my Mac down I always select to reopen programs the next time I restart.  When Quiver starts, its look is blanked out.  I have to quit the app then restart for the regular Dark theme to work.

![screen shot 2017-11-14 at 10 22 09 am](https://user-images.githubusercontent.com/1799654/32794437-18f8c41a-c926-11e7-91e0-361b976c0062.png)

**Comment by mike-kelly** [comment]
Same issue here

**Comment by ylian** [comment]
Fixed in 3.1.3. In previous versions an exception might be thrown during app launch which caused the the app to display no notes like in the screenshot.
